import { useState } from 'react'
import { Map, RefreshCw, SkipForward, Target } from 'lucide-react'
import { Button, Card, GameTooltip } from '../../components/ui'
import type { GameState, MonsterId } from '../../game/types'
import { MONSTERS } from '../../game/content/monsters'
import { getHunterBlockSlotCount, getHunterRerollMarkCost, getHunterSkipMarkCost, isHunterContractBoardUnlocked } from '../../game/systems/huntersOrder/huntersOrderRuntime'
import { useGameStore } from '../../store/gameStore'
import { setNavigationIntent } from '../../ui/navigation/navigationIntent'
import { HunterBlockManager } from './HunterBlockManager'
import { getHunterContractPresentation } from '../../game/presentation/huntersOrder/hunterPresentation'

export function HunterContractsTab({ state }: { state: GameState }) {
  const [manageBlocks, setManageBlocks] = useState(false)
  const order = state.progress.huntersOrder
  const active = order.activeContract
  const offers = order.availableContracts
  const methods = useGameStore.getState()
  const boardUnlocked = isHunterContractBoardUnlocked(state)
  const blockSlots = getHunterBlockSlotCount(state)
  const refreshCost = getHunterRerollMarkCost(state)
  const activePresentation = active ? getHunterContractPresentation(active) : null
  const openGround = (monsterId?: MonsterId) => { setNavigationIntent({ combatDungeonId: 'hunters-ground', combatMonsterId: monsterId ?? null }); methods.setScreen('combat') }
  return <><section className="hunter-contract-layout"><div className="hunter-contract-main">
    <div className="hunter-board-heading"><div><span className="hunter-card-kicker">{boardUnlocked ? 'CONTRACT BOARD' : 'ORDER DISPATCH'}</span><h2>{active ? (order.totalContractsCompleted === 0 ? 'First assignment' : 'Current assignment') : boardUnlocked ? 'Choose a contract' : 'Tracker dispatch'}</h2><p>{active ? 'The marked assignment authorizes matching quarry in Gloamridge.' : boardUnlocked ? 'Choose one assignment. Other offers stay on the board until accepted.' : 'Tracker assignments arrive one at a time until you earn Scout standing.'}</p></div><GameTooltip content="Contracts authorize matching quarry in Gloamridge; a matching assignment is required to hunt Order quarry."><span className="hunter-contract-help">FIELD GUIDE</span></GameTooltip></div>
    {active && <Card className="hunter-active-contract"><div className="hunter-contract-emblem"><Target size={22} /></div><div className="hunter-contract-copy"><div className="hunter-card-kicker">{order.totalContractsCompleted === 0 ? 'FIRST ASSIGNMENT' : `${active.tier.toUpperCase()} · ACTIVE`}</div><h3>{activePresentation?.objective}</h3><div className="hunter-active-objective"><strong>{active.target.toLocaleString()} required</strong><span>{activePresentation?.action}</span></div><div className="hunter-progress-track" role="progressbar" aria-label="Contract progress" aria-valuenow={active.progress} aria-valuemin={0} aria-valuemax={active.target}><span style={{ width: `${Math.min(100, active.progress / active.target * 100)}%` }} /></div><div className="hunter-active-details"><strong>{active.progress.toLocaleString()} / {active.target.toLocaleString()} complete</strong><span>{activePresentation?.remaining.toLocaleString()} remaining</span></div><div className="hunter-reward-line"><span>+{active.reputationReward.toLocaleString()} Reputation</span><strong>+{active.marksReward} Hunter Marks</strong></div><GameTooltip content="Open Combat with Gloamridge selected and this quarry targeted where supported."><Button variant="primary" onClick={() => openGround(active.targetSpec.type === 'monster' ? active.targetSpec.monsterId : undefined)}><Map size={14} /> OPEN GLOAMRIDGE</Button></GameTooltip></div>{boardUnlocked && <GameTooltip content={`Skip this assignment for ${getHunterSkipMarkCost(state)} Hunter Marks; current progress is forfeited.`}><Button variant="ghost" disabled={order.hunterMarks < getHunterSkipMarkCost(state)} onClick={() => methods.skipHunterContract()}><SkipForward size={15} /> Skip</Button></GameTooltip>}</Card>}
    {!active && !boardUnlocked && <Card className="hunter-empty-state hunter-first-assignment"><div className="hunter-card-kicker">TRACKER DISPATCH</div><h3>{order.totalContractsAccepted === 0 ? 'Your first Hunt Assignment is ready.' : 'Ready for another hunt?'}</h3><p>{order.totalContractsAccepted === 0 ? 'The Order issues this routine assignment at no cost. It authorizes its quarry in Gloamridge.' : 'Request another free Routine assignment. A choice board unlocks at Scout.'}</p><GameTooltip content="Receive one free Routine monster assignment from the Order."><Button variant="primary" onClick={() => order.totalContractsAccepted === 0 ? methods.issueFirstHunterContract() : methods.requestHunterAssignment()}>{order.totalContractsAccepted === 0 ? 'REQUEST FIRST ASSIGNMENT' : 'REQUEST RANDOM ASSIGNMENT'}</Button></GameTooltip></Card>}
    {boardUnlocked && <><div className="hunter-offer-heading"><h3>{active ? 'Other board choices' : 'Available contracts'}</h3><span>{offers.length} offers</span></div>{offers.length ? <div className="hunter-offer-grid">{offers.map((contract) => { const presentation = getHunterContractPresentation(contract); const verb = presentation.action; return <Card key={contract.id} className={`hunter-offer-card hunter-offer-${contract.tier}`}><div className="hunter-offer-labels"><span className={`hunter-tier-mark hunter-tier-${contract.tier}`}>{contract.tier}</span><span>{verb}</span></div><span className="hunter-offer-icon"><Target size={20} /></span><h3>{presentation.objective}</h3><p>{contract.targetSpec.type === 'monster' || contract.targetSpec.type === 'boss' ? MONSTERS[contract.targetSpec.monsterId]?.subtitle : 'Eligible quarry matching this Order assignment.'}</p><div className="hunter-offer-target">Defeat {contract.target.toLocaleString()} {contract.targetSpec.type === 'region' ? 'eligible quarry' : contract.targetSpec.type === 'family' ? 'family members' : 'targets'}</div><div className="hunter-reward-line"><span>+{contract.reputationReward.toLocaleString()} REP</span><strong>+{contract.marksReward} MARKS</strong></div><GameTooltip content={`Accept this ${contract.tier} assignment. It requires ${contract.target.toLocaleString()} tracked kills.`}><Button variant="primary" disabled={Boolean(active)} onClick={() => methods.acceptHunterContract(contract.id)}>ACCEPT CONTRACT</Button></GameTooltip></Card> })}</div> : <Card className="hunter-empty-state"><h3>No contracts available</h3><p>{order.blockedTargets.length ? 'Target Blocks are excluding quarry from new assignments.' : 'Request fresh assignment choices from the board services.'}</p><Button variant="primary" onClick={() => order.blockedTargets.length ? setManageBlocks(true) : methods.requestHunterContractBoard()}>{order.blockedTargets.length ? 'MANAGE TARGET BLOCKS' : 'PREPARE CONTRACT BOARD'}</Button></Card>}</>}
  </div><aside className="hunter-contract-sidebar" aria-label="Order contract services">{boardUnlocked && <Card className="hunter-order-resource"><div className="hunter-card-kicker">BOARD SERVICES</div><strong className="hunter-mark-balance">{order.hunterMarks.toLocaleString()} <small>HUNTER MARKS</small></strong><div className="hunter-refresh-cost"><span>Refresh cost</span><strong>{refreshCost} Marks</strong></div><GameTooltip content={`Spend ${refreshCost} Hunter Marks to replace board offers. Active progress is preserved.`}><Button variant="secondary" disabled={order.hunterMarks < refreshCost} onClick={() => methods.rerollHunterContracts()}><RefreshCw size={14} /> REFRESH BOARD</Button></GameTooltip></Card>}{blockSlots > 0 && <Card className="hunter-block-summary"><div className="hunter-card-kicker">TARGET BLOCKS</div><strong>{order.blockedTargets.length} / {blockSlots} slots used</strong><p>Blocked quarry stay visible here but will not appear in future offers.</p><GameTooltip content="Manage quarry excluded from future board choices. Current active targets cannot be blocked."><Button variant="ghost" onClick={() => setManageBlocks(true)}>MANAGE BLOCKS</Button></GameTooltip></Card>}<Card className="hunter-contract-guidance"><div className="hunter-card-kicker">FIELD NOTE</div><p>Only quarry matching your active assignment are authorized in Gloamridge.</p></Card></aside></section>
    <HunterBlockManager state={state} open={manageBlocks} onClose={() => setManageBlocks(false)} />
  </>
}

