import { Crown, Map, Target } from 'lucide-react'
import { Button, Card, GameTooltip, Status } from '../../components/ui'
import { HUNTER_EXCLUSIVE_MONSTER_IDS } from '../../game/content/monsters/huntersOrder'
import { MONSTERS } from '../../game/content/monsters'
import { DUNGEONS } from '../../game/content/dungeons/dungeons'
import { doesMonsterMatchHunterContract, getHunterAuthorization } from '../../game/systems/huntersOrder/huntersOrderRuntime'
import { useGameStore } from '../../store/gameStore'
import type { GameState, MonsterId } from '../../game/types'
import { setNavigationIntent } from '../../ui/navigation/navigationIntent'

export function HunterGroundsTab({ state }: { state: GameState }) {
  const active = state.progress.huntersOrder.activeContract
  const regular = HUNTER_EXCLUSIVE_MONSTER_IDS.filter((id) => id !== 'nightglass-alpha')
  const eligible = (id: typeof regular[number]) => Boolean(active && doesMonsterMatchHunterContract(active, id, 'hunters-ground'))
  const apex = getHunterAuthorization(state, 'nightglass-alpha', 'hunters-ground')
  const openGround = (monsterId?: MonsterId) => { setNavigationIntent({ combatDungeonId: 'hunters-ground', combatMonsterId: monsterId ?? null }); useGameStore.getState().setScreen('combat') }
  return <div className="hunter-grounds-stack"><Card className="hunter-ground-banner"><div><span className="hunter-overview-kicker"><Map size={15} /> HUNTING GROUND · NORTHERN FRONTIER</span><h2>Gloamridge</h2><p>A marked ridge beyond the Howling Den, bridging the Den’s threats toward the Abandoned Catacombs.</p></div><div className="hunter-ground-counts"><strong>06<small>REGULAR QUARRY</small></strong><strong>01<small>APEX</small></strong></div><div className="hunter-ground-authorization">{active ? <><Status tone="success">CONTRACT ACTIVE</Status><strong>{active.targetSpec.type === 'monster' || active.targetSpec.type === 'boss' ? MONSTERS[active.targetSpec.monsterId]?.name : active.targetSpec.type === 'region' ? 'Gloamridge patrol' : 'Authorized quarry'}</strong></> : <Status tone="neutral">NO ACTIVE CONTRACT</Status>}</div></Card>
    <section className="hunter-ground-quarry-section"><header><div><span className="hunter-card-kicker">AUTHORIZED ROSTER</span><h2>Regular Quarry</h2></div><span>{active ? `${regular.filter(eligible).length} / 6 eligible` : 'Accept a contract to authorize quarry'}</span></header><div className="hunter-quarry-grid">{regular.map((id) => { const monster = MONSTERS[id]; const authorized = eligible(id); const current = active?.targetSpec.type === 'monster' && active.targetSpec.monsterId === id; const blocked = state.progress.huntersOrder.blockedTargets.includes(id); const metadata = monster.hunter; return <Card className={`hunter-quarry-card ${authorized ? 'is-authorized' : ''} ${current ? 'is-current-target' : ''} ${blocked ? 'is-blocked' : ''}`} key={id}><div className="hunter-quarry-card-heading"><span><Target size={18} /></span><div><small>{metadata?.contractTier.toUpperCase()} QUARRY</small><h3>{monster.name}</h3></div></div><div className="hunter-quarry-meta"><span>{metadata?.family}</span><span>{metadata?.alignment}</span></div><div className="hunter-quarry-state">{current ? <Status tone="active">CURRENT TARGET</Status> : blocked ? <Status tone="warning">BLOCKED FROM FUTURE CONTRACTS</Status> : authorized ? <Status tone="success">CONTRACT ELIGIBLE</Status> : <Status tone="neutral">{active ? 'OUTSIDE ACTIVE CONTRACT' : 'NOT AUTHORIZED'}</Status>}</div>{authorized && <GameTooltip content={`Hunt ${monster.name} in Gloamridge under your active Contract.`}><Button variant="secondary" onClick={() => openGround(id)}>HUNT TARGET</Button></GameTooltip>}</Card> })}</div></section>
    <Card className={`hunter-apex-card ${apex.authorized ? 'is-authorized' : ''}`}><div className="hunter-apex-crest"><Crown size={23} /></div><div><span className="hunter-card-kicker">APEX HUNT</span><h2>Nightglass Alpha</h2><p>Master Hunter standing and an active Apex Contract are required. This quarry remains separate from routine Gloamridge assignments.</p></div><div className="hunter-apex-requirements"><span>Required rank <strong>Master Hunter</strong></span><span>Contract type <strong>Apex / Boss</strong></span><span>Threat <strong>{DUNGEONS['hunters-ground'].threatRequired.toLocaleString()}</strong></span></div><GameTooltip content={apex.authorized ? 'Open Combat with Nightglass Alpha selected.' : 'Reach Master Hunter and accept its Apex Contract.'}><Button variant={apex.authorized ? 'primary' : 'secondary'} disabled={!apex.authorized} onClick={() => openGround('nightglass-alpha')}>{apex.authorized ? 'HUNT APEX' : 'LOCKED'}</Button></GameTooltip></Card>
  </div>
}
