import { useGameStore } from '../../store/gameStore'
import { Button, Card, GameTooltip } from '../../components/ui'
import { BookOpen, Map, ScrollText, Shield, Trophy } from 'lucide-react'
import { DUNGEONS } from '../../game/content/dungeons/dungeons'
import { MONSTERS } from '../../game/content/monsters'
import { getHunterHeaderPresentation } from '../../game/presentation/huntersOrder/hunterPresentation'
import { getHunterBlockSlotCount, getHunterRankProgress, getHunterRerollMarkCost } from '../../game/systems/huntersOrder/huntersOrderRuntime'
import type { GameState } from '../../game/types'
import { openHunterContractInCombat } from '../../ui/navigation/hunterContractNavigation'
import { getHunterContractEligibleCount, getMonsterHunterContractRelation } from '../../game/presentation/huntersOrder/hunterContractCombatPresentation'
import { getHunterContractPresentation } from '../../game/presentation/huntersOrder/hunterPresentation'
import type { MonsterId } from '../../game/types'
import type { HuntersOrderScreenTab } from '../../ui/preferences/uiPreferencesTypes'
import { MonsterPortrait } from '../combat/MonsterPortrait'
import { openHunterBestiaryEntry } from '../../ui/navigation/hunterOrderNavigation'
import { HunterContractArt } from './HunterContractArt'

export function HunterOverviewTab({ state, onNavigate }: { state: GameState; onNavigate: (tab: HuntersOrderScreenTab) => void }) {
  const order = state.progress.huntersOrder
  const active = order.activeContract
  const header = getHunterHeaderPresentation(state)
  const rankProgress = getHunterRankProgress(order.reputation)
  const eligibleCount = getHunterContractEligibleCount(state, active)
  const activeContractView = active ? getHunterContractPresentation(state, active) : null
  const activeDossierId: MonsterId | null = active?.targetSpec.type === 'monster' || active?.targetSpec.type === 'boss' ? active.targetSpec.monsterId : activeContractView?.eligibleMonsterIds[0] ?? null
  const refreshCost = getHunterRerollMarkCost(state)
  const openGround = () => active ? openHunterContractInCombat(state, useGameStore.getState().setScreen) : onNavigate('contracts')
  return <div className="hunter-overview-grid">
    <Card className="hunter-overview-active"><div className="hunter-overview-kicker"><ScrollText size={15} /> ACTIVE HUNT</div>{active ? <><div className="hunter-overview-target"><HunterContractArt contract={active} state={state} /><div><span>{active.tier.toUpperCase()} CONTRACT</span><h2>{active.targetSpec.type === 'monster' || active.targetSpec.type === 'boss' ? MONSTERS[active.targetSpec.monsterId]?.name : active.targetSpec.type === 'family' ? `${active.targetSpec.familyId} Family` : active.targetSpec.type === 'alignment' ? `${active.targetSpec.alignmentId} Quarry` : 'Gloamridge patrol'}</h2></div></div><div className="hunter-overview-progress-label"><strong>{active.progress.toLocaleString()} / {active.target.toLocaleString()}</strong><span>{Math.max(0, active.target - active.progress).toLocaleString()} remaining</span></div><div className="hunter-progress-track"><span style={{ width: `${Math.min(100, active.progress / active.target * 100)}%` }} /></div><div className="hunter-overview-rewards"><span>+{active.reputationReward.toLocaleString()} REP</span><strong>+{active.marksReward} MARKS</strong></div><div className="hunter-overview-actions"><GameTooltip content="Open Combat with Gloamridge selected for your authorized quarry."><Button variant="primary" onClick={openGround}><Map size={15} /> OPEN GLOAMRIDGE</Button></GameTooltip>{activeDossierId && <Button variant="ghost" onClick={() => openHunterBestiaryEntry(activeDossierId)}><BookOpen size={14} /> VIEW DOSSIER</Button>}</div></> : <><h2>{order.totalContractsAccepted === 0 ? 'Assignment desk is ready.' : `${header.currentRank.name} dispatch is ready.`}</h2><p>{header.currentRank.id === 'tracker' ? 'The Order issues one routine quarry assignment at a time.' : `${order.availableContracts.length} contract choices are waiting on the board.`}</p><Button variant="primary" onClick={() => onNavigate('contracts')}>{header.currentRank.id === 'tracker' ? 'REQUEST ASSIGNMENT' : 'OPEN CONTRACT BOARD'}</Button></>}</Card>
    <Card className="hunter-overview-rank"><div className="hunter-overview-kicker"><Shield size={15} /> RANK PROGRESS</div><div className="hunter-overview-rank-line"><strong>{rankProgress.currentRank.name}</strong><span>{header.nextRank ? `Next: ${header.nextRank.name}` : 'Highest rank reached'}</span></div><div className="hunter-overview-progress-label"><b>{header.reputation.toLocaleString()} / {header.nextRank?.reputation.toLocaleString() ?? header.reputation.toLocaleString()} Reputation</b><span>{header.remaining.toLocaleString()} remaining</span></div><div className="hunter-progress-track"><span style={{ width: `${header.progressPercent}%` }} /></div><ul>{(header.nextRank ?? header.currentRank).unlocks.slice(0, 3).map((item) => <li key={item}>{item}</li>)}</ul><Button variant="ghost" onClick={() => onNavigate('rank')}>VIEW ORDER RANK</Button></Card>
    <Card className="hunter-overview-ground"><div className="hunter-overview-kicker"><Map size={15} /> HUNTING GROUND</div><h2>Gloamridge</h2><p>{DUNGEONS['hunters-ground'].monsterPool.length} quarry</p><div className="hunter-quarry-strip">{DUNGEONS['hunters-ground'].monsterPool.map((id) => { const relation = getMonsterHunterContractRelation(state, id, 'hunters-ground'); return <GameTooltip key={id} content={`${MONSTERS[id]?.name} · ${MONSTERS[id]?.hunter?.contractTier ?? 'Routine'} · ${relation === 'exact-target' ? 'Exact target' : relation === 'eligible' ? 'Eligible for contract' : relation === 'matching-but-locked' ? 'Matching but locked' : 'Not authorized'}`}><button type="button" aria-label={`Open ${MONSTERS[id]?.name} dossier`} className={`hunter-quarry-portrait is-${relation}`} onClick={() => openHunterBestiaryEntry(id)}><MonsterPortrait monster={MONSTERS[id]} /></button></GameTooltip> })}</div><strong>{active ? `${eligibleCount} quarry can advance the current Contract` : 'Accept or request a Contract before hunting Order quarry.'}</strong><Button variant="secondary" onClick={openGround}>{active ? 'OPEN GLOAMRIDGE' : 'OPEN CONTRACTS'}</Button></Card>
    <Card className="hunter-overview-services"><div className="hunter-overview-kicker"><Trophy size={15} /> ORDER SERVICES</div><dl><div><dt>Contract choices</dt><dd>{order.availableContracts.length || (header.currentRank.id === 'tracker' ? 1 : 0)}</dd></div><div><dt>Target Block slots</dt><dd>{order.blockedTargets.length} / {getHunterBlockSlotCount(state)}</dd></div><div><dt>Refresh cost</dt><dd>{refreshCost} Marks</dd></div><div><dt>Available upgrades</dt><dd>{header.availableUpgradeCount}</dd></div></dl><Button variant="ghost" onClick={() => onNavigate('upgrades')}>VIEW ORDER SERVICES</Button></Card>
  </div>
}
