import { useState } from 'react'
import { BookOpen, Compass, Crown, Eye, Footprints, Map, Medal, PawPrint, ScrollText, Shield, ShieldCheck, Sparkles, Target, Trophy, Wrench } from 'lucide-react'
import { Button, Card } from '../../components/ui'
import { getHunterRankPresentation } from '../../game/presentation/huntersOrder/hunterPresentation'
import type { GameState, HunterRankId } from '../../game/types'

const rankIcons = [Footprints, Compass, Eye, Shield, Medal, Crown]
const benefitIcon = (label: string) => /family|quarry/i.test(label) ? PawPrint : /alignment|special/i.test(label) ? Sparkles : /region|gloamridge/i.test(label) ? Map : /block|trail|route/i.test(label) ? ShieldCheck : /upgrade|service|privilege|reroll|marks|pockets|kit/i.test(label) ? Wrench : /board|contract|assignment/i.test(label) ? ScrollText : BookOpen

export function HunterRankTab({ state }: { state: GameState }) {
  const presentation = getHunterRankPresentation(state)
  const [selectedId, setSelectedId] = useState<HunterRankId>(presentation.currentRank.id)
  const selected = getHunterRankPresentation(state, selectedId).selectedRank
  const reached = presentation.reputation >= selected.reputation
  return <div className="hunter-rank-layout"><Card className="hunter-rank-dossier"><div className="hunter-overview-kicker"><Shield size={15} /> ORDER RANK DOSSIER</div><div className="hunter-rank-hero"><span><Trophy size={23} /></span><div><small>CURRENT STANDING</small><h2>{presentation.currentRank.name}</h2></div><strong>{presentation.progressPercent}%</strong></div><div className="hunter-rank-path"><span>{presentation.currentRank.name}</span><i aria-hidden="true">›</i><strong>{presentation.nextRank?.name ?? 'Master Hunter'}</strong></div><div className="hunter-overview-progress-label"><b>{presentation.reputation.toLocaleString()} / {presentation.nextRank?.reputation.toLocaleString() ?? presentation.reputation.toLocaleString()} Reputation</b><span>{presentation.remaining.toLocaleString()} remaining</span></div><div className="hunter-progress-track"><span style={{ width: `${presentation.progressPercent}%` }} /></div>
    <div className="hunter-rank-ladder" aria-label="Hunter rank progression">{presentation.ladder.map((rank, index) => { const Icon = rankIcons[index] ?? Target; const stateLabel = rank.current ? 'CURRENT' : rank.reached ? 'REACHED' : 'LOCKED'; return <Button key={rank.id} variant="ghost" className={`hunter-rank-node ${rank.reached ? 'is-reached' : 'is-locked'} ${rank.current ? 'is-current' : ''} ${selectedId === rank.id ? 'is-selected' : ''}`} aria-pressed={selectedId === rank.id} aria-label={`${rank.name}, ${rank.reputation.toLocaleString()} reputation, ${stateLabel}`} onClick={() => setSelectedId(rank.id)}><span className="hunter-rank-node-icon"><Icon size={17} /></span><strong>{rank.name}</strong><small>{rank.reputation.toLocaleString()} REP</small><i>{stateLabel}</i></Button> })}</div>
    <div className="hunter-rank-detail"><div><span>{reached ? selected.id === presentation.currentRank.id ? 'CURRENT RANK' : 'RANK RECORD' : 'LOCKED RANK'}</span><h3>{selected.name}</h3><strong>{selected.reputation.toLocaleString()} Reputation</strong></div><div className="hunter-rank-unlock-tiles" aria-label={`${selected.name} unlocks`}>{selected.unlocks.map((item) => { const Icon = benefitIcon(item); return <div className="hunter-rank-unlock-tile" key={item}><span><Icon size={15} /></span><strong>{item}</strong></div> })}</div></div>
  </Card><div className="hunter-rank-side"><Card><div className="hunter-overview-kicker"><Medal size={15} /> CURRENT BENEFITS</div><div className="hunter-benefit-tiles">{presentation.currentRank.unlocks.map((item) => { const Icon = benefitIcon(item); return <div key={item}><span><Icon size={14} /></span><strong>{item}</strong></div> })}</div></Card>{presentation.nextRank ? <Card><div className="hunter-overview-kicker"><Map size={15} /> NEXT RANK UNLOCKS</div><h3>{presentation.nextRank.name}</h3><div className="hunter-benefit-tiles">{presentation.nextRank.unlocks.map((item) => { const Icon = benefitIcon(item); return <div key={item}><span><Icon size={14} /></span><strong>{item}</strong></div> })}</div></Card> : <Card><div className="hunter-overview-kicker"><Crown size={15} /> MASTER HUNTER SERVICES</div><p>Highest Order rank reached. Master Quarry Contracts include Nightglass Alpha.</p></Card>}<Card className="hunter-rank-stats"><div><span>CONTRACTS COMPLETED</span><strong>{state.progress.huntersOrder.totalContractsCompleted}</strong></div><div><span>HUNTER MARKS</span><strong>{state.progress.huntersOrder.hunterMarks}</strong></div><div><span>CONTRACT CHOICES</span><strong>{state.progress.huntersOrder.availableContracts.length}</strong></div></Card></div></div>
}
