import { useRef, useState, type CSSProperties, type PointerEvent as ReactPointerEvent, type WheelEvent as ReactWheelEvent } from 'react'
import { Crosshair, RotateCcw, Sparkles, X, ZoomIn, ZoomOut } from 'lucide-react'
import { Button, Card, GameTooltip, ModalPortal, Status } from '../../components/ui'
import { ArcaneCorePresetPanel } from '../../components/arcane-core/ArcaneCorePresetPanel'
import { ScreenGrid } from '../../components/layout/ScreenGrid'
import { ARCANE_CORE_BRANCHES } from '../../game/content/arcaneCore/arcaneCoreBranches'
import { ARCANE_CORE_MAJOR_GATES, ARCANE_CORE_RING_GATES, getArcaneCoreRingName } from '../../game/content/arcaneCore/arcaneCoreRings'
import { formatArcaneCoreModifierValue, formatArcaneCoreNodeEffect, getArcaneCoreModifierLabel, getArcaneCoreNodeEffectTexts, getArcaneCoreNodePosition } from '../../game/presentation/arcaneCore/arcaneCorePresentation'
import { getArcaneCoreBranchResetPreview, getArcaneCoreHighestUnlockedRing, getArcaneCoreLevelInfo, getArcaneCoreNodeProgress, getArcaneCoreNodeRank, getArcaneCorePointsSpent, getArcaneCoreRefundPreview, getArcaneCoreRingPointsSpent, getArcaneCoreStaticStats, isArcaneCoreMajorUnlocked, isArcaneCoreNodeReachable } from '../../game/systems/arcaneCore'
import type { ArcaneCoreBranchDefinition, ArcaneCoreBranchId, ArcaneCoreModifierKey, ArcaneCoreNodeDefinition } from '../../game/types'
import { useGameStore } from '../../store/gameStore'

function CoreProgress({ core }: { core: ReturnType<typeof useGameStore.getState>['arcaneCore'] }) {
  const info = getArcaneCoreLevelInfo(core)
  const progress = info.xpToNextLevel > 0 ? Math.min(100, info.xpIntoLevel / (info.xpIntoLevel + info.xpToNextLevel) * 100) : 100
  return <div className="arcane-core-wallet" aria-label="Arcane Core progression"><div><span>ARCANE CORE LEVEL</span><strong>Level {info.level}</strong><small>{info.totalXp.toLocaleString()} total XP</small><i><em style={{ width: `${progress}%` }} /></i></div><div><span>XP</span><strong>{info.xpToNextLevel > 0 ? `${info.xpIntoLevel.toLocaleString()} / ${(info.xpIntoLevel + info.xpToNextLevel).toLocaleString()}` : 'MAX'}</strong><small>{info.xpToNextLevel > 0 ? `${info.xpToNextLevel.toLocaleString()} XP to next level` : 'Maximum level reached'}</small><i><em style={{ width: `${progress}%` }} /></i></div><div><span>CORE POINTS</span><strong>{info.pointsAvailable} Available</strong><small>{info.pointsEarned} Earned · {info.pointsSpent} Spent globally</small></div></div>
}

function BranchCard({ branch, onOpen, state }: { branch: ArcaneCoreBranchDefinition; onOpen: () => void; state: ReturnType<typeof useGameStore.getState>['arcaneCore'] }) {
  const spent = getArcaneCorePointsSpent({ nodes: Object.fromEntries(branch.nodes.map((node) => [node.id, state.nodes[node.id]]).filter(([, value]) => value)) })
  const highest = getArcaneCoreHighestUnlockedRing(state, branch.id)
  return <button type="button" className="arcane-core-branch-card" style={{ '--branch-accent': branch.accent } as CSSProperties} onClick={onOpen}><span className="arcane-core-branch-mark"><Sparkles size={17} /></span><span className="arcane-core-branch-copy"><span className="eyebrow">{branch.name.toUpperCase()} CORE</span><strong>{branch.name} Core</strong><small>{branch.description}</small></span><span className="arcane-core-branch-progress"><b>{spent} / 172</b><small>Core Points invested</small><i><em style={{ width: `${spent / 172 * 100}%` }} /></i><small className="arcane-core-branch-active">Ring {highest} unlocked</small></span><span className="arcane-core-branch-open">OPEN CORE ›</span></button>
}

type PendingConfirmation = { label: string; points: number; ranks: number; majors: number; rings: number; confirm: () => void }

function effectText(node: ArcaneCoreNodeDefinition, rank: number) {
  return rank > 0 ? formatArcaneCoreNodeEffect(node, rank) : 'Not active yet.'
}

function CoreModal({ branch, onClose }: { branch: ArcaneCoreBranchDefinition; onClose: () => void }) {
  const core = useGameStore((state) => state.arcaneCore)
  const purchase = useGameStore((state) => state.purchaseArcaneCoreNode)
  const refund = useGameStore((state) => state.refundArcaneCoreNode)
  const resetBranch = useGameStore((state) => state.resetArcaneCoreBranch)
  const [selectedId, setSelectedId] = useState(branch.nodes[0]?.id ?? '')
  const [zoom, setZoom] = useState(.62)
  const [offset, setOffset] = useState({ x: 0, y: 0 })
  const [confirmation, setConfirmation] = useState<PendingConfirmation | null>(null)
  const drag = useRef<{ x: number; y: number; offsetX: number; offsetY: number } | null>(null)
  const selected = branch.nodes.find((node) => node.id === selectedId) ?? branch.nodes[0]
  const selectedRank = selected ? getArcaneCoreNodeRank(core, selected.id) : 0
  const selectedAvailable = selected ? isArcaneCoreNodeReachable(core, selected.id) && (selected.nodeType !== 'major' || isArcaneCoreMajorUnlocked(core, selected)) : false
  const highestRing = getArcaneCoreHighestUnlockedRing(core, branch.id)
  const spent = getArcaneCorePointsSpent({ nodes: Object.fromEntries(branch.nodes.map((node) => [node.id, core.nodes[node.id]]).filter(([, value]) => value)) })
  const startDrag = (event: ReactPointerEvent<HTMLDivElement>) => { if ((event.target as Element | null)?.closest('button, [data-no-pan]')) return; drag.current = { x: event.clientX, y: event.clientY, offsetX: offset.x, offsetY: offset.y }; event.currentTarget.setPointerCapture?.(event.pointerId) }
  const moveDrag = (event: ReactPointerEvent<HTMLDivElement>) => { if (drag.current) setOffset({ x: drag.current.offsetX + event.clientX - drag.current.x, y: drag.current.offsetY + event.clientY - drag.current.y }) }
  const endDrag = (event: ReactPointerEvent<HTMLDivElement>) => { drag.current = null; if (event.currentTarget.hasPointerCapture?.(event.pointerId)) event.currentTarget.releasePointerCapture?.(event.pointerId) }
  const handleWheel = (event: ReactWheelEvent<HTMLDivElement>) => { event.preventDefault(); setZoom((value) => Math.max(.42, Math.min(1.1, value * (event.deltaY > 0 ? .9 : 1.1)))) }
  const requestRefund = () => { if (!selected || selectedRank <= 0) return; const preview = getArcaneCoreRefundPreview(core, selected.id); if (preview.ok) setConfirmation({ label: `Refund ${selected.name} rank?`, points: preview.corePointsReturned, ranks: preview.ranksAffected, majors: preview.majorsAffected, rings: preview.ringsRelocked.length, confirm: () => { refund(selected.id); setConfirmation(null) } }) }
  const requestReset = () => { const preview = getArcaneCoreBranchResetPreview(core, branch.id); if (preview.ok && preview.corePointsReturned > 0) setConfirmation({ label: `Reset ${branch.name} Core?`, points: preview.corePointsReturned, ranks: preview.ranksAffected, majors: preview.majorsAffected, rings: preview.ringsRelocked.length, confirm: () => { resetBranch(branch.id); setConfirmation(null) } }) }
  const selectedCurrent = selected ? effectText(selected, selectedRank) : ''
  const selectedNext = selected && selectedRank < selected.maxRank ? effectText(selected, selectedRank + 1) : 'Maximum rank reached.'
  const selectedMax = selected ? effectText(selected, selected.maxRank) : ''

  return <ModalPortal open onClose={onClose} onEscape={() => confirmation ? setConfirmation(null) : onClose()} surfaceStyle={{ '--branch-accent': branch.accent } as CSSProperties} backdropClassName="arcane-core-modal-backdrop" surfaceClassName="arcane-core-modal" ariaLabel={`${branch.name} Core`}>
    <div className="arcane-core-modal-head"><div><span className="eyebrow" style={{ color: branch.accent }}>{branch.name.toUpperCase()} CORE · CONCENTRIC PATH</span><h2>{branch.name} Core</h2><p>Invest Core Points from the center outward. Each Ring unlocks by investment; every rank is permanent until refunded.</p></div><div className="arcane-core-modal-actions"><Status tone="active">{spent} / 172 invested</Status><Button variant="ghost" onClick={onClose} ariaLabel="Close Arcane Core"><X size={17} /></Button></div></div>
    <div className="arcane-core-modal-toolbar"><span><Crosshair size={14} /> Drag to pan · wheel to zoom</span><span>Ring {highestRing} unlocked · {Math.round(zoom * 100)}%</span><Button variant="ghost" onClick={() => setZoom(.62)}><Crosshair size={13} /> Fit Core</Button><Button variant="ghost" onClick={() => { setZoom(.62); setOffset({ x: 0, y: 0 }) }}><RotateCcw size={13} /> Reset View</Button><Button variant="danger" onClick={requestReset} disabled={spent === 0}>Reset Core</Button></div>
    <div className="arcane-core-modal-body"><div className="arcane-core-ring-viewport" onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag} onWheel={handleWheel}><div className="arcane-core-ring-canvas" style={{ transform: `translate(calc(-50% + ${offset.x}px), calc(-50% + ${offset.y}px)) scale(${zoom})` }}>
      <div className="arcane-core-hub"><Sparkles size={22} /><span>{branch.name.toUpperCase()} CORE</span><small>{spent} / 172 POINTS</small></div>
      {[1, 2, 3, 4].map((ring) => <div key={ring} className={`arcane-core-ring ring-${ring} ${ring <= highestRing ? 'is-unlocked' : 'is-locked'}`}><span className="arcane-core-ring-label">RING {ring} · {getArcaneCoreRingName(branch.id, ring as 1 | 2 | 3 | 4).toUpperCase()}</span>{branch.nodes.filter((node) => node.ring === ring).map((node) => { const position = getArcaneCoreNodePosition(node); const rank = getArcaneCoreNodeRank(core, node.id); const reachable = isArcaneCoreNodeReachable(core, node.id); const majorAvailable = isArcaneCoreMajorUnlocked(core, node); return <GameTooltip key={node.id} content={`${node.name} · Rank ${rank}/${node.maxRank} · ${formatArcaneCoreNodeEffect(node, Math.max(1, rank))}`}><button type="button" className={`arcane-core-ring-node node-${node.nodeType} ${rank > 0 ? 'is-active' : ''} ${reachable && majorAvailable ? 'is-available' : 'is-locked'} ${selected?.id === node.id ? 'is-selected' : ''}`} style={{ left: position.left, top: position.top }} onClick={() => setSelectedId(node.id)} aria-label={`${node.name}, rank ${rank} of ${node.maxRank}`}><span className="arcane-core-node-dot">{node.nodeType === 'major' ? '✦' : '◆'}</span><strong>{node.name}</strong><small>{rank}/{node.maxRank}</small>{node.nodeType !== 'major' && <i className="arcane-core-rank-pips">{[1, 2, 3, 4, 5].map((pip) => <b key={pip} className={pip <= rank ? 'is-paid' : undefined} />)}</i>}</button></GameTooltip> })}<span className="arcane-core-ring-gate">{ring === 1 ? 'UNLOCKED' : `${getArcaneCoreRingPointsSpent(core, branch.id, (ring - 1) as 1 | 2 | 3 | 4)} / ${ARCANE_CORE_RING_GATES[ring as 1 | 2 | 3 | 4]} PREVIOUS RING`}</span></div>)}
    </div></div><aside className="arcane-core-node-inspector">{selected && <><div className="arcane-core-inspector-title"><span className="arcane-core-inspector-glyph" style={{ background: branch.accent }}><Sparkles size={17} /></span><div><span className="eyebrow">RING {selected.ring} · {selected.nodeType.toUpperCase()}</span><h3>{selected.name}</h3></div></div><p className="muted">{selected.description}</p><div className="arcane-core-inspector-effect"><span>CURRENT EFFECT · RANK {selectedRank}/{selected.maxRank}</span><strong>{selectedCurrent}</strong><small>NEXT · {selectedNext}</small><small>MAX · {selectedMax}</small></div><div className="arcane-core-inspector-meta"><span>RING<strong>{getArcaneCoreRingName(branch.id, selected.ring)}</strong></span><span>STATUS<strong>{selectedRank >= selected.maxRank ? 'MAX RANK' : selectedAvailable ? 'AVAILABLE' : selected.nodeType === 'major' ? `${ARCANE_CORE_MAJOR_GATES[selected.ring]} POINT GATE` : `${ARCANE_CORE_RING_GATES[selected.ring]} POINT GATE`}</strong></span><span>COST<strong>{selected.rankCost} CORE POINT{selected.rankCost > 1 ? 'S' : ''}</strong></span><span>RANK<strong>{selectedRank} / {selected.maxRank}</strong></span></div><div className="arcane-core-inspector-actions"><Button variant="primary" onClick={() => purchase(selected.id)} disabled={selectedRank >= selected.maxRank || !selectedAvailable}>Purchase Rank · {selected.rankCost} Point{selected.rankCost > 1 ? 's' : ''}</Button><Button variant="ghost" onClick={requestRefund} disabled={selectedRank === 0}>Refund One Rank</Button></div><div className="arcane-core-effect-list">{getArcaneCoreNodeEffectTexts(selected, Math.max(1, selectedRank)).map((text) => <span key={text}>{text}</span>)}</div></>}</aside></div>
    {confirmation && <div className="arcane-core-confirm-layer" onMouseDown={(event) => event.stopPropagation()}><section className="arcane-core-confirmation" role="alertdialog" aria-modal="true"><span className="eyebrow">CONFIRM REFUND CASCADE</span><h3>{confirmation.label}</h3><p className="muted">Outer allocations become invalid if this refund closes a Ring gate.</p><div className="arcane-core-confirm-summary"><span><small>RANKS RETURNED</small><strong>{confirmation.ranks}</strong></span><span><small>POINTS RETURNED</small><strong>{confirmation.points}</strong></span><span><small>MAJORS AFFECTED</small><strong>{confirmation.majors}</strong></span><span><small>RINGS RELOCKED</small><strong>{confirmation.rings}</strong></span></div><div className="button-row"><Button variant="ghost" onClick={() => setConfirmation(null)}>Cancel</Button><Button variant="danger" onClick={confirmation.confirm}>Confirm Refund</Button></div></section></div>}
  </ModalPortal>
}

export function ArcaneCoreScreen() {
  const core = useGameStore((state) => state.arcaneCore)
  const [branchId, setBranchId] = useState<ArcaneCoreBranchId | null>(null)
  const activeBranch = branchId ? ARCANE_CORE_BRANCHES.find((branch) => branch.id === branchId) : null
  const stats = getArcaneCoreStaticStats(core)
  const pointsSpent = getArcaneCorePointsSpent(core)
  return <div className="screen-content arcane-core-screen"><div className="screen-header"><div><div className="eyebrow">HERO · PERMANENT PROGRESSION</div><h1>Arcane Core</h1><p>Shape the permanent engine beneath the wizard. Earn XP in combat, gain Core Points, and grow four independent concentric Cores.</p></div><Status tone="active">{pointsSpent} / 688 points invested</Status></div><ScreenGrid screen="arcane-core" panels={[{ id: 'arcane-core-overview', content: <div className="arcane-core-overview-stack"><Card title="Core progression"><CoreProgress core={core} /></Card><div className="arcane-core-branch-grid">{ARCANE_CORE_BRANCHES.map((branch) => <BranchCard key={branch.id} branch={branch} state={core} onOpen={() => setBranchId(branch.id)} />)}</div><Card title="Active resonance" action={<Status tone="success">Permanent Core modifiers</Status>}><div className="arcane-core-resonance">{Object.entries(stats).filter(([, value]) => typeof value === 'number' && value !== 0).map(([key, value]) => <span key={key}><small>{getArcaneCoreModifierLabel(key as ArcaneCoreModifierKey)}</small><strong>{formatArcaneCoreModifierValue(key as ArcaneCoreModifierKey, Number(value))}</strong></span>)}{!Object.values(stats).some((value) => typeof value === 'number' && value !== 0) && <p className="muted">Purchase ranks to bring permanent modifiers online.</p>}</div></Card><ArcaneCorePresetPanel /></div> }]} />{activeBranch && <CoreModal branch={activeBranch} onClose={() => setBranchId(null)} />}</div>
}
