import { Pause } from 'lucide-react'
import { BALANCE } from '../../game/data/balance'
import { useGameStore } from '../../store/gameStore'
import { selectAutoHuntUnlocked } from '../../store/selectors'
import { Button, Card, Status } from '../../components/ui'
import { formatNumber, formatTime } from '../../game/utils'
import { MONSTERS } from '../../game/data/monsters'

export function DungeonPanel() { const combat = useGameStore((state) => state.combat); const progress = useGameStore((state) => state.progress); const enter = useGameStore((state) => state.enterDungeon); const leave = useGameStore((state) => state.leaveDungeon); const engage = useGameStore((state) => state.engageBoss); const toggle = useGameStore((state) => state.toggleAutoHunt); const unlocked = useGameStore(selectAutoHuntUnlocked); const enemy = combat.enemyId ? MONSTERS[combat.enemyId] : null; return <Card title="Whispering Woods" action={<Status tone={combat.active ? 'active' : 'neutral'}>{combat.active ? 'Combat Active' : 'At the Tower'}</Status>}><div className="forest-scene"><div className="moon" /><div className="tree tree-a" /><div className="tree tree-b" /><div className="tree tree-c" /><div className="forest-rune">✦</div></div><div className="dungeon-stat-row"><div className="metric"><span>Threat Cleared</span><strong>{combat.threatCleared} / {BALANCE.dungeon.whisperingWoodsThreatRequired}</strong></div><div className="metric"><span>Lifetime kills</span><strong>{formatNumber(progress.lifetimeKills)}</strong></div><div className="metric"><span>Encounter</span><strong>{enemy ? 'Engaged' : combat.active ? formatTime(combat.encounterTimerMs) : '—'}</strong></div></div><div className="auto-hunt-row"><div><strong>Auto Hunt Boss</strong><small>{unlocked ? `Finish the current normal encounter, then engage Grove Sentinel at ${BALANCE.dungeon.whisperingWoodsThreatRequired} Threat.` : 'Locked until the first Grove Sentinel kill.'}</small></div><Button disabled={!unlocked} variant={progress.autoHuntBossByDungeon['whispering-woods'] ? 'success' : 'secondary'} onClick={toggle}>{unlocked ? progress.autoHuntBossByDungeon['whispering-woods'] ? 'ON' : 'OFF' : 'LOCKED'}</Button></div>{combat.threatCleared >= BALANCE.dungeon.whisperingWoodsThreatRequired && combat.active && !combat.inBossFight && !progress.autoHuntBossByDungeon['whispering-woods'] && <div className="boss-ready"><div><Status tone="success">Boss Ready</Status><strong>Grove Sentinel can be challenged.</strong><span>Threat may continue above the requirement while Auto Hunt is OFF.</span></div><Button variant="success" onClick={() => engage('grove-sentinel')}>Engage Sentinel</Button></div>}{progress.forestHeartUnlocked && combat.active && !combat.inBossFight && <div className="boss-ready heart"><div><Status tone="warning">Main Boss Unlocked</Status><strong>Forest Heart waits beneath the grove.</strong><span>First kill raises the cap and grants permanent Focus.</span></div><Button variant="danger" onClick={() => engage('forest-heart')}>Engage Forest Heart</Button></div>}{combat.active ? <Button variant="danger" onClick={leave}><Pause size={15} /> Leave Dungeon</Button> : <Button onClick={enter}>Enter Whispering Woods</Button>}</Card> }
