import type { MonsterId } from '../../../types'
import { authorExpansionBoss, bossAction, hit, status } from './authoring'

export const EXPANSION_BOSSES = [
  authorExpansionBoss({
    id: 'moonwake-leviathan', name: 'Moonwake Leviathan', locationId: 'brineveil-marsh', affinity: 'water', subtitle: 'A vast marsh leviathan rising beneath a moonlit sheet of black water.',
    hp: 14400, damage: 110, defense: 75, targetPower: 2400, resonanceYield: { water: 80 },
    traitId: 'moonwake-leviathan-phase', traitName: 'Rising Tide', phaseName: 'awakened', phaseOneLabel: 'submerged', phaseTwoLabel: 'awakened',
    specials: [
      bossAction('Tidal Crush', { damage: [hit('water', 1.55)] }),
      bossAction('Brine Coil', { damage: [hit('water', 1.1)], status: status('chilled') }),
      bossAction('Drowning Arc', { damage: [hit('water', 1), hit('air', .6)] }),
      bossAction('Abyssal Hide', { barrier: .1 }),
      bossAction('Undertow Pull', { damage: [hit('water', .8)], delayOpponentMs: 700 }),
      bossAction('Moonwake Surge', { damage: [hit('water', 2.3)], actionTimeMs: 2800 }),
    ],
    phaseOne: ['skill-1', 'basic', 'skill-2', 'basic', 'skill-4', 'skill-3', 'basic'],
    phaseTwo: ['skill-6', 'basic', 'skill-5', 'skill-1', 'basic', 'skill-2', 'skill-3'],
  }),
  authorExpansionBoss({
    id: 'furnace-maw', name: 'The Furnace Maw', locationId: 'cinderwild-expanse', affinity: 'fire', subtitle: 'A cavernous fire beast gnawing at the magma vents beneath the wilds.',
    hp: 16200, damage: 117, defense: 78, targetPower: 4200, resonanceYield: { fire: 80 },
    traitId: 'furnace-maw-phase', traitName: 'Overheat', phaseName: 'overheated', phaseOneLabel: 'feeding', phaseTwoLabel: 'overheated',
    specials: [
      bossAction('Magma Bite', { damage: [hit('fire', 1.45)], status: status('burning') }),
      bossAction('Furnace Breath', { damage: [hit('fire', 1.8)] }),
      bossAction('Ashquake', { damage: [hit('fire', .9), hit('earth', .7)] }),
      bossAction('Cinder Carapace', { barrier: .1 }),
      bossAction('Devour Cinders', { damage: [hit('fire', 1)], detonateStatus: { statusId: 'burning', multiplier: 1 } }),
      bossAction('Eruption', { damage: [hit('fire', 2.4)], actionTimeMs: 2800 }),
    ],
    phaseOne: ['skill-1', 'basic', 'skill-2', 'basic', 'skill-4', 'skill-3'],
    phaseTwo: ['skill-6', 'basic', 'skill-1', 'skill-5', 'skill-2', 'basic', 'skill-3'],
  }),
  authorExpansionBoss({
    id: 'tempest-sovereign', name: 'Tempest Sovereign', locationId: 'skybreak-cliffs', affinity: 'air', subtitle: 'A crowned storm predator reigning over the knife-edge cliffs.',
    hp: 18000, damage: 124, defense: 82, targetPower: 6000, resonanceYield: { air: 80 },
    traitId: 'tempest-sovereign-phase', traitName: 'Crowned Tempest', phaseName: 'sovereign storm', phaseOneLabel: 'high-sky', phaseTwoLabel: 'sovereign-storm', hasteAtPhaseChange: true,
    specials: [
      bossAction('Talon Tempest', { damage: [hit('air', 1.6)] }),
      bossAction('Thunder Crown', { damage: [hit('air', 1.2)], status: status('shock') }),
      bossAction('Crosswind Rend', { damage: [hit('air', 1.1)], status: status('fragile') }),
      bossAction('Eye of the Storm', { barrier: .08 }),
      bossAction('Rainburst', { damage: [hit('water', .8), hit('air', .8)] }),
      bossAction('Skyfall', { damage: [hit('air', 2.4)], actionTimeMs: 2800 }),
    ],
    phaseOne: ['skill-1', 'basic', 'skill-2', 'basic', 'skill-4', 'skill-5'],
    phaseTwo: ['skill-6', 'skill-3', 'basic', 'skill-2', 'skill-1', 'skill-5', 'basic'],
  }),
  authorExpansionBoss({
    id: 'unmade-magister', name: 'The Unmade Magister', locationId: 'runeblight-expanse', affinity: 'arcane', subtitle: 'A ley-warped scholar whose unfinished spells tear at the world.',
    hp: 19000, damage: 128, defense: 84, targetPower: 7000, resonanceYield: { arcane: 80 },
    traitId: 'unmade-magister-phase', traitName: 'Unbound Formula', phaseName: 'unbound', phaseOneLabel: 'formula', phaseTwoLabel: 'unbound',
    specials: [
      bossAction('Arcane Lance', { damage: [hit('arcane', 1.45)] }),
      bossAction('Prism Divide', { damage: [hit('fire', .75), hit('water', .75)] }),
      bossAction('Ley Rupture', { damage: [hit('earth', .75), hit('air', .75)] }),
      bossAction('Counterseal', { barrier: .09 }),
      bossAction('Mana Collapse', { damage: [hit('arcane', .9)], manaDrain: 10 }),
      bossAction('Unmake', { damage: [hit('arcane', 2.5)], actionTimeMs: 2800 }),
    ],
    phaseOne: ['skill-1', 'basic', 'skill-2', 'skill-4', 'basic', 'skill-3'],
    phaseTwo: ['skill-6', 'skill-5', 'basic', 'skill-2', 'skill-3', 'skill-1', 'basic'],
  }),
  authorExpansionBoss({
    id: 'pyrehold-castellan', name: 'Pyrehold Castellan', locationId: 'pyrehold-bastion', affinity: 'fire', subtitle: 'The fortress commander still enforcing orders through ash and flame.',
    hp: 22000, damage: 140, defense: 90, targetPower: 10000, resonanceYield: { fire: 80 },
    traitId: 'pyrehold-castellan-phase', traitName: 'Castellan’s Last Command', phaseName: 'last command', phaseOneLabel: 'castellan', phaseTwoLabel: 'last-command',
    specials: [
      bossAction("Castellan's Brand", { damage: [hit('fire', 1.3)], status: status('kindled') }),
      bossAction('Furnace Decree', { damage: [hit('fire', 1.65)] }),
      bossAction('Bastion Flame', { barrier: .1 }),
      bossAction('Molten Counter', { damage: [hit('fire', 1)], delayOpponentMs: 400 }),
      bossAction('Execution Pyre', { damage: [hit('fire', 2.2)] }),
      bossAction('Ashen Command', { status: status('haste', 'self') }),
    ],
    phaseOne: ['skill-1', 'basic', 'skill-2', 'skill-3', 'basic', 'skill-4'],
    phaseTwo: ['skill-5', 'basic', 'skill-1', 'skill-6', 'skill-2', 'skill-4', 'basic'],
  }),
  authorExpansionBoss({
    id: 'drowned-regent', name: 'The Drowned Regent', locationId: 'abyssal-reservoir', affinity: 'water', subtitle: 'A sovereign preserved beneath the reservoir’s immense pressure.',
    hp: 22500, damage: 142, defense: 91, targetPower: 10500, resonanceYield: { water: 80 },
    traitId: 'drowned-regent-phase', traitName: 'Sovereign Depths', phaseName: 'deep throne', phaseOneLabel: 'regent', phaseTwoLabel: 'deep-throne',
    specials: [
      bossAction("Regent's Tide", { damage: [hit('water', 1.5)] }),
      bossAction('Pressure Crown', { barrier: .1 }),
      bossAction('Deep Decree', { damage: [hit('water', .9)], status: status('cursed') }),
      bossAction('Nullwater Sentence', { damage: [hit('arcane', 1)], status: status('silenced') }),
      bossAction('Undertow Collapse', { damage: [hit('water', 1.25)], delayOpponentMs: 600 }),
      bossAction('Drown the Hall', { damage: [hit('water', 2.35)], actionTimeMs: 2800 }),
    ],
    phaseOne: ['skill-1', 'basic', 'skill-3', 'skill-2', 'basic', 'skill-4'],
    phaseTwo: ['skill-6', 'skill-5', 'basic', 'skill-1', 'skill-4', 'basic'],
  }),
  authorExpansionBoss({
    id: 'steam-tyrant', name: 'The Steam Tyrant', locationId: 'scalding-rift', affinity: 'fire', subtitle: 'A volatile ruler of the rift where boiling water meets molten stone.',
    hp: 24500, damage: 150, defense: 95, targetPower: 12500, resonanceYield: { fire: 80 },
    traitId: 'steam-tyrant-phase', traitName: 'Critical Pressure', phaseName: 'critical pressure', phaseOneLabel: 'boiling-throne', phaseTwoLabel: 'critical-pressure',
    specials: [
      bossAction('Boiling Crown', { damage: [hit('fire', 1), hit('water', 1)] }),
      bossAction('Scalding Edict', { damage: [hit('fire', 1.35)], status: status('burning') }),
      bossAction('Steam Hammer', { damage: [hit('water', 1.4)] }),
      bossAction('Vapor Armor', { barrier: .1 }),
      bossAction('Flash Boil', { damage: [hit('fire', 1.2)], delayOpponentMs: 500 }),
      bossAction('Pressure Rupture', { damage: [hit('fire', 1.2), hit('water', 1.2)], actionTimeMs: 2800 }),
    ],
    phaseOne: ['skill-1', 'basic', 'skill-2', 'skill-4', 'basic', 'skill-3'],
    phaseTwo: ['skill-6', 'skill-5', 'basic', 'skill-1', 'skill-2', 'skill-3'],
  }),
  authorExpansionBoss({
    id: 'sepulcher-flamekeeper', name: 'Sepulcher Flamekeeper', locationId: 'cinder-sepulcher', affinity: 'fire', subtitle: 'A funerary guardian tending flames that have burned for centuries.',
    hp: 23500, damage: 146, defense: 93, targetPower: 11500, resonanceYield: { fire: 80 },
    traitId: 'sepulcher-flamekeeper-phase', traitName: 'Eternal Flame', phaseName: 'eternal flame', phaseOneLabel: 'keeper', phaseTwoLabel: 'eternal-flame',
    specials: [
      bossAction('Funeral Pyre', { damage: [hit('fire', 1.4)], status: status('burning') }),
      bossAction('Ashen Procession', { damage: [hit('fire', 1.2)] }),
      bossAction("Keeper's Ward", { barrier: .1 }),
      bossAction('Cinder Rite', { heal: .05 }),
      bossAction('Last Ember', { damage: [hit('fire', 1.8)] }),
      bossAction('Cremation Bell', { damage: [hit('fire', 2.4)], actionTimeMs: 2800 }),
    ],
    phaseOne: ['skill-1', 'basic', 'skill-2', 'skill-3', 'basic', 'skill-4'],
    phaseTwo: ['skill-6', 'basic', 'skill-1', 'skill-5', 'skill-2', 'basic'],
  }),
  authorExpansionBoss({
    id: 'deep-bell-saint', name: 'The Deep Bell Saint', locationId: 'temple-of-the-sunken-bell', affinity: 'water', subtitle: 'A drowned holy figure whose voice sounds through the sunken bell.',
    hp: 23500, damage: 146, defense: 93, targetPower: 11500, resonanceYield: { water: 80 },
    traitId: 'deep-bell-saint-phase', traitName: 'Second Toll', phaseName: 'second toll', phaseOneLabel: 'first-toll', phaseTwoLabel: 'second-toll',
    specials: [
      bossAction('Bell Toll', { damage: [hit('water', 1.3)], status: status('staggered') }),
      bossAction('Drowned Hymn', { damage: [hit('water', 1.1)], status: status('cursed') }),
      bossAction('Resonant Tide', { damage: [hit('water', 1), hit('air', .6)] }),
      bossAction('Deep Sanctuary', { barrier: .1 }),
      bossAction('Sunken Benediction', { heal: .06 }),
      bossAction('Final Toll', { damage: [hit('water', 2.45)], actionTimeMs: 2800 }),
    ],
    phaseOne: ['skill-1', 'basic', 'skill-2', 'skill-4', 'basic', 'skill-3'],
    phaseTwo: ['skill-6', 'basic', 'skill-3', 'skill-1', 'skill-5', 'skill-2'],
  }),
  authorExpansionBoss({
    id: 'abbot-ninth-gale', name: 'Abbot of the Ninth Gale', locationId: 'stormspire-monastery', affinity: 'air', subtitle: 'The monastery’s master of winds, still commanding the stormbound towers.',
    hp: 24500, damage: 150, defense: 95, targetPower: 12500, resonanceYield: { air: 80 },
    traitId: 'abbot-ninth-gale-phase', traitName: 'Ninth Wind', phaseName: 'ninth wind', phaseOneLabel: 'seven-winds', phaseTwoLabel: 'ninth-wind', hasteAtPhaseChange: true,
    specials: [
      bossAction('First Gale', { damage: [hit('air', 1.2)] }),
      bossAction('Third Gale', { damage: [hit('air', .75), hit('air', .75)] }),
      bossAction('Fifth Gale', { damage: [hit('air', 1), hit('water', .55)] }),
      bossAction('Seventh Gale', { barrier: .08 }),
      bossAction('Skychain Silence', { damage: [hit('arcane', .8)], status: status('silenced') }),
      bossAction('Ninth Gale', { damage: [hit('air', 2.5)], actionTimeMs: 2800 }),
    ],
    phaseOne: ['skill-1', 'basic', 'skill-2', 'basic', 'skill-3', 'skill-4'],
    phaseTwo: ['skill-6', 'skill-5', 'basic', 'skill-2', 'skill-3', 'skill-1', 'basic'],
  }),
  authorExpansionBoss({
    id: 'closed-index', name: 'The Closed Index', locationId: 'nullstone-archive', affinity: 'arcane', subtitle: 'A sealed catalogue given form to guard the archive’s forbidden lore.',
    hp: 27000, damage: 160, defense: 100, targetPower: 15000, resonanceYield: { arcane: 80 },
    traitId: 'closed-index-phase', traitName: 'Open Index', phaseName: 'open index', phaseOneLabel: 'closed-index', phaseTwoLabel: 'open-index',
    specials: [
      bossAction('Redaction', { damage: [hit('arcane', 1.2)], status: status('silenced') }),
      bossAction('Null Entry', { damage: [hit('arcane', 1.45)] }),
      bossAction('Stone Seal', { damage: [hit('earth', 1.2)] }),
      bossAction('Ember Clause', { damage: [hit('fire', 1.2)] }),
      bossAction('Archive Lock', { barrier: .1 }),
      bossAction('Final Index', { damage: [hit('arcane', 2.5)], actionTimeMs: 2800 }),
    ],
    phaseOne: ['skill-1', 'basic', 'skill-3', 'skill-5', 'basic', 'skill-2'],
    phaseTwo: ['skill-6', 'skill-4', 'skill-1', 'basic', 'skill-2', 'skill-3'],
  }),
] as const

export const EXPANSION_BOSS_IDS = EXPANSION_BOSSES.map(({ id }) => id as MonsterId)
