import type { ReactNode } from 'react'
import { Card } from '../../../components/ui'
import { GameTooltip, TooltipContent } from '../../../components/ui/tooltip/Tooltip'
import { BALANCE } from '../../../game/data/balance'
import { getManaCapacityBreakdown, getManaRegenBreakdown } from '../../../game/engine/channelingEngine'
import { useGameStore } from '../../../store/gameStore'
import { formatChannelingPercent, formatChannelingRate } from './channelingPresentation'

export function ChannelingBreakdownPanel() {
  const player = useGameStore((state) => state.player)
  const activities = useGameStore((state) => state.activities)
  const progress = useGameStore((state) => state.progress)
  const equipment = useGameStore((state) => state.equipment)
  const artifactProgress = useGameStore((state) => state.artifactProgress)
  const regen = getManaRegenBreakdown({ activities, progress, equipment, artifactProgress })
  const capacity = getManaCapacityBreakdown({ player, progress, equipment, artifactProgress })
  const echoResonanceUnlocked = progress.channeling.discoveries['echo-resonance']

  return <Card className="channeling-breakdown-panel" title="Channeling Breakdown" action={<div className="channeling-breakdown-total"><span>TOTAL FLOW</span><strong>+{formatChannelingRate(regen.total)}/s</strong></div>}>
    <p className="channeling-breakdown-intro">Understand where your Mana production and capacity come from.</p>
    <div className="channeling-breakdown-grid">
      <BreakdownSection title="PASSIVE MANA">
        <BreakdownRow label="Base Natural" value={`+${formatChannelingRate(regen.baseNatural)}/s`} />
        <BreakdownRow label="Leyline Conduit" value={`+${formatChannelingRate(regen.leylineConduitBonus)}/s`} />
        <BreakdownRow label="Stable Leyline" value={`+${formatChannelingRate(regen.stableLeylineBonus)}/s`} />
        <BreakdownRow label="Equipment" value={`+${formatChannelingRate(regen.equipmentPassiveBonus)}/s`} />
        <BreakdownRow label="Mana Resonance" value={formatChannelingPercent(regen.manaResonanceMultiplier)} tooltip="Amplifies passive Mana regeneration after flat bonuses are applied." />
        <BreakdownRow label="PASSIVE TOTAL" value={`+${formatChannelingRate(regen.passiveAfterResonance)}/s`} total />
      </BreakdownSection>
      <BreakdownSection title="ARCANE ECHOES">
        <BreakdownRow label="Assigned Echoes" value={activities.channeling.echoesAssigned} />
        <BreakdownRow label="Base Mana / Echo" value={`+${formatChannelingRate(BALANCE.channeling.echoManaPerSecond)}/s`} />
        <BreakdownRow label="Echo Attunement" value={formatChannelingPercent(regen.echoAttunementMultiplier)} tooltip="Increases Mana generated by each Arcane Echo." />
        {echoResonanceUnlocked && <BreakdownRow label="Echo Resonance" value={formatChannelingPercent(regen.echoDiscoveryMultiplier)} tooltip="Amplifies total Arcane Echo production after Echo Attunement." />}
        <BreakdownRow label="ECHO PRODUCTION" value={`+${formatChannelingRate(regen.echoTotal)}/s`} total />
      </BreakdownSection>
      <BreakdownSection title="MAX MANA" wide>
        <div className="channeling-breakdown-capacity-summary">
          <BreakdownRow label="Base Mana" value={capacity.base} />
          <BreakdownRow label="Arcane Reservoir" value={formatSigned(capacity.arcaneReservoirBonus)} />
          <BreakdownRow label="Deep Reservoir" value={formatSigned(capacity.deepReservoirBonus)} />
          <BreakdownRow label="Equipment" value={formatSigned(capacity.equipmentBonus)} />
        </div>
        <BreakdownRow label="Astral Expansion" value={formatChannelingPercent(capacity.astralExpansionMultiplier)} tooltip="Amplifies Max Mana after flat capacity bonuses are applied." />
        <BreakdownRow label="FINAL MAX MANA" value={capacity.total} total />
      </BreakdownSection>
    </div>
  </Card>
}

function BreakdownSection({ title, wide = false, children }: { title: string; wide?: boolean; children: ReactNode }) {
  return <section className={`channeling-breakdown-section ${wide ? 'is-wide' : ''}`}><h3>{title}</h3>{children}</section>
}

function BreakdownRow({ label, value, total = false, tooltip }: { label: string; value: ReactNode; total?: boolean; tooltip?: string }) {
  const labelContent = <span className={`channeling-breakdown-label ${tooltip ? 'has-tooltip' : ''}`}>{label}</span>
  return <div className={`channeling-breakdown-row ${total ? 'is-total' : ''}`}>{tooltip ? <GameTooltip content={<TooltipContent title={label} description={tooltip} />} accent="mana">{labelContent}</GameTooltip> : labelContent}<strong>{value}</strong></div>
}

function formatSigned(value: number) {
  return `${value >= 0 ? '+' : ''}${formatChannelingRate(value)}`
}
