import { MAX_RESISTANCE } from '../../core/balance/combatStats'

export const EQUIPMENT_STAT_VISIBILITY_EPSILON = 0.00001
export const isMeaningfulEquipmentStatValue = (value: number | null | undefined) => typeof value === 'number' && Number.isFinite(value) && Math.abs(value) >= EQUIPMENT_STAT_VISIBILITY_EPSILON

export interface EquipmentStatPresentation {
  key: string
  label: string
  description: string
  format: (value: number, signed?: boolean) => string
}

export interface EquipmentStatDescriptionContext {}

const STAT_LABELS: Record<string, string> = {
  maxHealth: 'Max Health',
  healthRegen: 'Health Regen',
  maxMana: 'Max Mana',
  manaRegen: 'Mana Regen',
  maxFocus: 'Max Focus',
  spellPower: 'Spell Power',
  critChance: 'Crit Chance',
  critDamage: 'Crit Damage',
  critDamageMultiplier: 'Crit Damage',
  defense: 'Defense',
  damageReduction: 'Damage Reduction',
  cooldownRecoveryPct: 'Cooldown Recovery',
  cooldownRecovery: 'Cooldown Recovery',
  healingDonePct: 'Healing Done',
  healingDoneBonus: 'Healing Done',
  barrierPowerPct: 'Barrier Power',
  barrierPowerBonus: 'Barrier Power',
  damageOverTimePct: 'Damage over Time',
  damageOverTimeBonus: 'Damage over Time',
  statusDurationPct: 'Status Duration',
  statusDurationBonus: 'Status Duration',
  manaCostReductionPct: 'Mana Cost Reduction',
  manaCostReduction: 'Mana Cost Reduction',
  focusEfficiencyPct: 'Focus Efficiency',
  focusEfficiency: 'Focus Efficiency',
  fireSpellDamage: 'Fire Spell Damage',
  airSpellDamage: 'Air Spell Damage',
  waterBarrierPower: 'Water Barrier Power',
  barrierReceivedFlat: 'Barrier Received',
  negativeStatusDurationReceived: 'Received Negative Status Duration',
}

const STAT_DESCRIPTIONS: Record<string, string> = {
  maxHealth: 'Increases your maximum Health.',
  healthRegen: 'Restores Health over time while outside a full-health state.',
  maxMana: 'Increases the amount of Mana available for Spells.',
  manaRegen: 'Restores Mana over time.',
  maxFocus: 'Increases the Focus capacity available to supported activities.',
  spellPower: 'Increases spell scaling for effects that use Spell Power.',
  critChance: 'Chance for a Direct Hit to critically strike. Damage over Time, Healing and Barrier effects cannot Crit.',
  critDamage: 'Damage multiplier applied to a Critical Direct Hit.',
  critDamageMultiplier: 'Damage multiplier applied to a Critical Direct Hit.',
  defense: 'Reduces Direct Hit damage with diminishing returns. Damage over Time ignores Defense.',
  damageReduction: 'Current Direct Hit reduction produced by Defense. Damage over Time ignores Defense.',
  cooldownRecoveryPct: 'Reduces effective Spell cooldown duration.',
  cooldownRecovery: 'Reduces effective Spell cooldown duration.',
  healingDonePct: 'Increases healing produced by your effects.',
  healingDoneBonus: 'Increases healing produced by your effects.',
  barrierPowerPct: 'Increases Barrier generated by your effects.',
  barrierPowerBonus: 'Increases Barrier generated by your effects.',
  damageOverTimePct: 'Increases periodic DoT damage. It does not increase Direct Hits.',
  damageOverTimeBonus: 'Increases periodic DoT damage. It does not increase Direct Hits.',
  statusDurationPct: 'Increases the duration of Statuses you apply.',
  statusDurationBonus: 'Increases the duration of Statuses you apply.',
  manaCostReductionPct: 'Reduces Spell Mana costs, subject to the current cap.',
  manaCostReduction: 'Reduces Spell Mana costs, subject to the current cap.',
  focusEfficiencyPct: 'Reduces Focus reserved by supported systems such as Auto-Cast.',
  focusEfficiency: 'Reduces Focus reserved by supported systems such as Auto-Cast.',
  fireSpellDamage: 'Additional damage for Fire Spells only.',
  airSpellDamage: 'Additional damage for Air Spells only.',
  waterBarrierPower: 'Additional Barrier power for Water Spells that generate Barrier.',
  barrierReceivedFlat: 'Adds flat Barrier capacity whenever you gain Barrier.',
  negativeStatusDurationReceived: 'Changes the duration of debuffs applied to you. Positive buffs are unaffected.',
}

const PERCENT_KEYS = new Set([
  'critChance', 'critDamage', 'critDamageMultiplier', 'cooldownRecoveryPct', 'healingDonePct', 'healingDoneBonus',
  'barrierPowerPct', 'barrierPowerBonus', 'damageOverTimePct', 'damageOverTimeBonus', 'statusDurationPct', 'statusDurationBonus',
  'manaCostReductionPct', 'manaCostReduction', 'focusEfficiencyPct', 'focusEfficiency', 'fireSpellDamage', 'airSpellDamage',
  'waterBarrierPower', 'negativeStatusDurationReceived',
])

export function getEquipmentStatLabel(key: string): string {
  if (STAT_LABELS[key]) return STAT_LABELS[key]
  if (key.startsWith('resistance-')) return `${key.slice('resistance-'.length).replace(/^./, (value) => value.toUpperCase())} Resistance`
  return key.replace(/([A-Z])/g, ' $1').replace(/^./, (value) => value.toUpperCase())
}

export function getEquipmentStatDescription(key: string, context: EquipmentStatDescriptionContext = {}): string {
  if (key.startsWith('resistance-')) return `Reduces ${key.slice('resistance-'.length)} damage. Ordinary Resistance is capped at ${Math.round(MAX_RESISTANCE * 100)}%. Negative Resistance increases damage taken.`
  return STAT_DESCRIPTIONS[key] ?? 'A current Equipment stat that contributes to your loadout.'
}

export function formatEquipmentStat(key: string, value: number, signed = true): string {
  const sign = signed && value > 0 ? '+' : ''
  if (key === 'healthRegen') return `${sign}${value}/s`
  if (key === 'manaRegen') return `${sign}${Math.ceil(value)}/s`
  if (key === 'cooldownRecovery') return `${sign}${value.toFixed(2)}x`
  if (key === 'damageReduction') return `${sign}${(value * 100).toFixed(1)}%`
  if (PERCENT_KEYS.has(key) || key.endsWith('Pct') || key.startsWith('resistance-')) return `${sign}${Math.round(value * 100)}%`
  return `${sign}${Number.isInteger(value) ? value : Math.round(value * 100) / 100}`
}

export function getEquipmentStatPresentation(key: string, context?: EquipmentStatDescriptionContext): EquipmentStatPresentation {
  return { key, label: getEquipmentStatLabel(key), description: getEquipmentStatDescription(key, context), format: (value, signed = true) => formatEquipmentStat(key, value, signed) }
}

/** Backwards-compatible names used by shared item and archive presentations. */
export const friendlyStatLabel = getEquipmentStatLabel
export const formatStat = formatEquipmentStat
