import type { MonsterId } from '../../../../types'
import { makeCombatMonster, type CombatMonsterSpec } from '../../combatMonsterAuthoring'
import type { MonsterDefinition } from '../../monsterTypes'

const specs: CombatMonsterSpec[] = [
  { locationId: 'stormvault-gallery', id: 'volt-wisp', combatV2: true, primaryAffinity: 'air', basicAttackElement: 'air', targetPower: 5600, name: 'Volt Wisp', subtitle: 'A spark trapped between two storm records', hp: 2188, damage: 96, defense: 28, time: 2300, resonanceYield: { air: 30 }, resistances: { air: 0.2 }, icon: { portraitIcon: 'wisp' }, specials: [{ id: 'volt-spark', name: 'Volt Spark', damage: [{ type: 'air', coefficient: 1.1 }], status: { id: 'shock', stacks: 1 } }, { id: 'static-charge', name: 'Static Charge', status: { id: 'haste', target: 'self' } }] },
  { locationId: 'stormvault-gallery', id: 'gale-scribe', combatV2: true, primaryAffinity: 'air', basicAttackElement: 'air', targetPower: 5900, name: 'Gale Scribe', subtitle: 'A storm historian writing faster than thought', hp: 2438, damage: 94, defense: 34, time: 2300, resonanceYield: { air: 34 }, specials: [{ id: 'gale-script', name: 'Gale Script', damage: [{ type: 'air', coefficient: 1.3 }] }, { id: 'acceleration-rune', name: 'Acceleration Rune', status: { id: 'haste', target: 'self' } }] },
  { locationId: 'stormvault-gallery', id: 'charged-seeker', combatV2: true, primaryAffinity: 'air', basicAttackElement: 'air', targetPower: 6200, name: 'Charged Seeker', subtitle: 'A hunting current searching for a grounded target', hp: 2813, damage: 100, defense: 30, time: 2300, resonanceYield: { air: 40 }, specials: [{ id: 'twin-arc', name: 'Twin Arc', description: 'Two Air arcs each deal 0.65× Basic damage and build one Shock stack.', damage: [{ type: 'air', coefficient: 0.65 }, { type: 'air', coefficient: 0.65 }], status: { id: 'shock', stacks: 1 } }, { id: 'seek', name: 'Seek', status: { id: 'haste', target: 'self' } }] },
  { locationId: 'stormvault-gallery', id: 'thundercoil-serpent', combatV2: true, primaryAffinity: 'air', basicAttackElement: 'air', targetPower: 6500, name: 'Thundercoil Serpent', subtitle: 'A storm serpent that stores lightning in every coil', hp: 3000, damage: 110, defense: 34, time: 2100, resonanceYield: { air: 44 }, icon: { portraitIcon: 'wolf' }, specials: [{ id: 'coil-arc', name: 'Coil Arc', description: 'Two Air arcs each deal 0.7× Basic damage and build one Shock stack.', damage: [{ type: 'air', coefficient: 0.7 }, { type: 'air', coefficient: 0.7 }], status: { id: 'shock', stacks: 1 } }, { id: 'lightning-shed', name: 'Lightning Shed', status: { id: 'haste', target: 'self' } }] },
  { locationId: 'stormvault-gallery', id: 'static-armor', combatV2: true, primaryAffinity: 'air', basicAttackElement: 'air', targetPower: 6800, name: 'Static Armor', subtitle: 'A walking shell charged by a vault gallery', hp: 3750, damage: 90, defense: 66, time: 2300, resonanceYield: { air: 38 }, specials: [{ id: 'static-ward', name: 'Static Ward', barrier: 0.08 }, { id: 'armor-crush', name: 'Armor Crush', damage: [{ type: 'air', coefficient: 1.5 }] }] },
  { locationId: 'stormvault-gallery', id: 'stormbound-curator', combatV2: true, primaryAffinity: 'air', basicAttackElement: 'air', targetPower: 7150, name: 'Stormbound Curator', subtitle: 'A curator defending the vault with sealed gales', hp: 3600, damage: 116, defense: 52, time: 2450, resonanceYield: { air: 50 }, icon: { portraitIcon: 'mage' }, specials: [{ id: 'archive-gale', name: 'Archive Gale', damage: [{ type: 'air', coefficient: 1.5 }] }, { id: 'storm-seal', name: 'Storm Seal', barrier: 0.06 }] },
  { locationId: 'stormvault-gallery', id: 'tempest-engine', combatV2: true, primaryAffinity: 'air', basicAttackElement: 'air', targetPower: 7550, name: 'Tempest Engine', subtitle: 'A high-pressure engine built from captured thunder', hp: 4600, damage: 126, defense: 72, time: 2700, resonanceYield: { air: 62 }, icon: { portraitIcon: 'guardian' }, specials: [{ id: 'thunder-ram', name: 'Thunder Ram', description: 'Two Air impacts total 1.8× Basic damage and build one Shock stack.', damage: [{ type: 'air', coefficient: 0.8 }, { type: 'air', coefficient: 1.0 }], status: { id: 'shock', stacks: 1 } }, { id: 'overcharge', name: 'Overcharge', status: { id: 'haste', target: 'self' } }] },
  { locationId: 'stormvault-gallery', id: 'storm-archivist', combatV2: true, primaryAffinity: 'air', basicAttackElement: 'air', targetPower: 9000, name: 'Storm Archivist', subtitle: 'The gallery keeper cataloguing every lightning strike', hp: 25000, damage: 115, defense: 70, time: 2500, resistances: { air: 0.25, earth: -0.1 }, resonanceYield: { air: 150 }, boss: true, specials: [{ id: 'archive-spark', name: 'Archive Spark', damage: [{ type: 'air', coefficient: 1.2 }], status: { id: 'shock', stacks: 1 } }, { id: 'rapid-annotation', name: 'Rapid Annotation', status: { id: 'haste', target: 'self' } }, { id: 'forked-bolt', name: 'Forked Bolt', description: 'The Archivist releases two Air bolts, each dealing 0.75× Basic damage.', damage: [{ type: 'air', coefficient: 0.75 }, { type: 'air', coefficient: 0.75 }] }, { id: 'static-barrier', name: 'Static Barrier', barrier: 0.08 }, { id: 'final-discharge', name: 'Final Discharge', actionTimeMs: 3200, damage: [{ type: 'air', coefficient: 2.15 }] }] },
]

export const STORMVAULT_GALLERY_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeCombatMonster(spec)])) as Record<MonsterId, MonsterDefinition>
