import { useState } from 'react'
import { MONSTERS } from '../../game/data/monsters'
import { ITEMS } from '../../game/data/items'
import { SPELLS } from '../../game/data/spells'
import { SCHOOLS } from '../../game/data/schools'
import type { ItemId, MonsterId, SpellId } from '../../game/types'
import { useGameStore } from '../../store/gameStore'
import { Button, Card, Status, Tabs } from '../../components/ui'
import { formatNumber } from '../../game/utils'
import { EditableGrid } from '../../ui/layout-editor/EditableGrid'

const tabs = ['Monsters', 'Bosses', 'Items', 'Spells'] as const
export function CollectionScreenV2() {
  const [tab, setTab] = useState<typeof tabs[number]>('Monsters'); const progress = useGameStore((state) => state.progress); const discovered = progress.discoveredMonsters; const bossKills = progress.bossKillsByBoss as Partial<Record<MonsterId, number>>
  const summary = <Card title="Archive" action={<span className="muted">{discovered.length} / 5 creatures discovered</span>}><p className="muted">Every encounter leaves a trace. Sequences, traits, drops, and spell details stay visible after discovery.</p></Card>
  const content = <Card title="Collection content"><Tabs items={tabs} active={tab} onChange={setTab} />{tab === 'Monsters' && <div className="collection-grid collection-v2">{(['forest-wisp', 'thornling', 'stone-root'] as MonsterId[]).map((id) => <MonsterEntry key={id} id={id} discovered={discovered.includes(id)} kills={progress.lifetimeKillsByMonster[id] ?? 0} />)}</div>}{tab === 'Bosses' && <div className="collection-grid collection-v2">{(['grove-sentinel', 'forest-heart'] as MonsterId[]).map((id) => <MonsterEntry key={id} id={id} discovered={discovered.includes(id)} kills={bossKills[id] ?? 0} boss />)}</div>}{tab === 'Items' && <div className="collection-grid collection-v2">{(Object.keys(ITEMS) as ItemId[]).map((id) => <div className="collection-entry found" key={id}><div className="collection-creature" style={{ '--enemy-color': ITEMS[id].color } as React.CSSProperties}>{ITEMS[id].icon}</div><div><strong>{ITEMS[id].name}</strong><small>{ITEMS[id].category.replace('-', ' ')} · Source: {ITEMS[id].source}</small></div></div>)}</div>}{tab === 'Spells' && <div className="collection-grid collection-v2">{(Object.keys(SPELLS) as SpellId[]).map((id) => { const spell = SPELLS[id]; const unlocked = progress.unlockedSpells.includes(id); return <div className={`collection-entry ${unlocked ? 'found' : ''}`} key={id}><div className="collection-creature" style={{ '--enemy-color': SCHOOLS[spell.school].color } as React.CSSProperties}>{SCHOOLS[spell.school].glyph}</div><div><strong>{spell.name}</strong><small>{SCHOOLS[spell.school].name} · Level {spell.unlockLevel} · {spell.manaCost} Mana · {spell.cooldownMs / 1000}s · {spell.autoCastFocus} Auto Focus</small></div><Status tone={unlocked ? 'success' : 'locked'}>{unlocked ? 'Known' : 'Locked'}</Status></div> })}</div>}</Card>
  return <div className="screen-content"><div className="screen-header"><div><div className="eyebrow">FIELD NOTES</div><h1>Collection</h1><p>Every encounter leaves a trace. Sequences, traits, drops, and spell details stay visible after discovery.</p></div></div><EditableGrid screen="collection" panels={[{ id: 'collection-summary', content: summary }, { id: 'collection-content', content }]} /></div>
}
function MonsterEntry({ id, discovered, kills, boss = false }: { id: MonsterId; discovered: boolean; kills: number; boss?: boolean }) { const monster = MONSTERS[id]; return <div className={`collection-entry ${discovered ? 'found' : ''}`}><div className="collection-creature" style={{ '--enemy-color': monster.color } as React.CSSProperties}>{discovered ? boss ? '♛' : '◈' : '?'}</div><div><strong>{discovered ? monster.name : 'Undiscovered'}</strong><small>{discovered ? `${monster.subtitle} · ${formatNumber(kills)} kills` : 'Encounter it in the woods.'}</small>{discovered && <><div className="trait-row">{monster.traits.map((trait) => <span className="trait" key={trait.name}>{trait.name}</span>)}</div><small className="collection-sequence">Sequence: {monster.actionSequence.map((step) => step.name).join(' → ')}</small><small>Known drops: {monster.loot.map((drop) => drop.itemId).join(', ')}</small></>}</div></div> }
