import type { GuildRankId, ItemId } from '../../types'
import type { GuildFacilityId } from './guildFacilities'
export type { GuildFacilityId } from './guildFacilities'
import type { GuildStandingId } from './guildStandings'
export type GuildProjectEffectType = 'guild-reputation' | 'research-speed' | 'research-xp' | 'transmutation-speed' | 'transmutation-output' | 'transmutation-cost' | 'arcane-flux' | 'arcane-flux-capacity' | 'acolyte-capacity' | 'commission-refresh' | 'commission-choice' | 'registry-cost'
export interface GuildProjectDefinition {
  id: string; facilityId: GuildFacilityId; name: string; description: string; requirements: readonly { itemId: ItemId; quantity: number }[]
  reputationReward: number; advancementPointsReward: number; minimumGuildRank: GuildRankId; minimumStandingId: GuildStandingId; prerequisiteProjectIds?: readonly string[]; effect?: { type: GuildProjectEffectType; amount: number }
}
const defaultStanding: Record<GuildRankId, GuildStandingId> = { outsider: 'initiate-1', initiate: 'initiate-5', apprentice: 'apprentice-1', adept: 'adept-1', magister: 'magister-1', 'circle-master': 'circle-master-1' }
const project = (id: string, facilityId: GuildFacilityId, name: string, description: string, requirements: { itemId: ItemId; quantity: number }[], minimumGuildRank: GuildRankId, reputationReward: number, effect: GuildProjectDefinition['effect'], prerequisiteProjectIds?: string[], minimumStandingId = defaultStanding[minimumGuildRank]): GuildProjectDefinition => ({ id, facilityId, name, description, requirements, minimumGuildRank, minimumStandingId, reputationReward, advancementPointsReward: 1, effect, prerequisiteProjectIds })
const projectStandingOverrides: Readonly<Record<string, GuildStandingId>> = {
  'restore-arcane-archive': 'initiate-5', 'catalogue-field-index': 'initiate-5', 'seal-master-archive': 'circle-master-3',
  'expand-research-wing': 'apprentice-2', 'install-peer-review-chambers': 'adept-2', 'open-astral-library': 'magister-4',
  'rebuild-transmutation-hall': 'apprentice-5', 'stabilize-resonance-vault': 'adept-2', 'attune-prismatic-arrays': 'magister-4',
  'calibrate-leyline-intake': 'adept-3', 'expand-flux-reservoir': 'adept-3', 'build-grand-leyline-conduit': 'circle-master-3',
  'restore-acolyte-quarters': 'magister-2', 'expand-acolyte-quarters': 'magister-4',
  'restore-dispatch-office': 'apprentice-1', 'establish-senior-clerk-desk': 'magister-3', 'open-grand-service-hall': 'magister-5',
}

export const GUILD_PROJECTS: readonly GuildProjectDefinition[] = [
  project('restore-arcane-archive', 'archive', 'Restore the Arcane Archive', 'Reinforce the Guild stacks with elemental records and stable resonance.', [{ itemId: 'fire-fragment', quantity: 12 }, { itemId: 'water-fragment', quantity: 12 }, { itemId: 'air-fragment', quantity: 12 }, { itemId: 'prismatic-fragment', quantity: 3 }], 'initiate', 220, { type: 'guild-reputation', amount: .01 }),
  project('catalogue-field-index', 'archive', 'Index the Resonance Catalog', 'Bind field materials and recovered records into the restored stacks.', [{ itemId: 'life-essence', quantity: 20 }, { itemId: 'earth-fragment', quantity: 24 }], 'apprentice', 260, { type: 'registry-cost', amount: .05 }, ['restore-arcane-archive']),
  project('seal-master-archive', 'archive', 'Open the Grand Archive Stacks', 'Complete the archive’s permanent registration and indexing wards.', [{ itemId: 'artifact-essence', quantity: 50 }, { itemId: 'prismatic-fragment', quantity: 15 }, { itemId: 'black-portal-shard', quantity: 8 }], 'magister', 600, { type: 'guild-reputation', amount: .02 }, ['catalogue-field-index']),
  project('expand-research-wing', 'research-wing', 'Expand the Research Wing', 'Supply the annex with catalysts for longer-running school studies.', [{ itemId: 'artifact-essence', quantity: 20 }, { itemId: 'water-fragment', quantity: 8 }], 'apprentice', 180, { type: 'research-speed', amount: .03 }, ['restore-arcane-archive']),
  project('install-peer-review-chambers', 'research-wing', 'Build the Peer Review Hall', 'Equip the faculty to cross-check studies and preserve their findings.', [{ itemId: 'artifact-essence', quantity: 35 }, { itemId: 'air-fragment', quantity: 30 }], 'adept', 300, { type: 'research-xp', amount: .05 }, ['expand-research-wing']),
  project('open-astral-library', 'research-wing', 'Establish the Grand Laboratory', 'Extend the Research Wing with rare materials and indexed formulae.', [{ itemId: 'prismatic-fragment', quantity: 18 }, { itemId: 'black-portal-shard', quantity: 10 }], 'magister', 500, { type: 'research-speed', amount: .03 }, ['install-peer-review-chambers']),
  project('rebuild-transmutation-hall', 'transmutation-hall', 'Rebuild the Transmutation Hall', 'Restore the marked arrays used by the Guild’s materialists.', [{ itemId: 'fire-fragment', quantity: 10 }, { itemId: 'earth-fragment', quantity: 10 }, { itemId: 'air-fragment', quantity: 10 }], 'adept', 180, { type: 'transmutation-speed', amount: .03 }, ['expand-research-wing']),
  project('stabilize-resonance-vault', 'transmutation-hall', 'Stabilize Catalytic Arrays', 'Reinforce the array vault against excess Resonance loss.', [{ itemId: 'water-fragment', quantity: 35 }, { itemId: 'prismatic-fragment', quantity: 8 }], 'adept', 320, { type: 'transmutation-cost', amount: .03 }, ['rebuild-transmutation-hall']),
  project('attune-prismatic-arrays', 'transmutation-hall', 'Open the Precision Fabrication Wing', 'Calibrate advanced arrays for consistent secondary output.', [{ itemId: 'prismatic-fragment', quantity: 25 }, { itemId: 'artifact-essence', quantity: 40 }], 'magister', 500, { type: 'transmutation-output', amount: .03 }, ['stabilize-resonance-vault']),
  project('calibrate-leyline-intake', 'leyline-annex', 'Calibrate the Leyline Intake', 'Tune the tower connection for steady Arcane Flux production.', [{ itemId: 'air-fragment', quantity: 24 }, { itemId: 'artifact-essence', quantity: 16 }], 'apprentice', 240, { type: 'arcane-flux', amount: .03 }, ['restore-arcane-archive']),
  project('expand-flux-reservoir', 'leyline-annex', 'Expand the Flux Reservoir', 'Add a stable reservoir to hold more Arcane Flux.', [{ itemId: 'earth-fragment', quantity: 38 }, { itemId: 'prismatic-fragment', quantity: 8 }], 'adept', 340, { type: 'arcane-flux-capacity', amount: .05 }, ['calibrate-leyline-intake']),
  project('build-grand-leyline-conduit', 'leyline-annex', 'Build the Grand Leyline Conduit', 'Open a durable conduit for stronger tower-wide Flux flow.', [{ itemId: 'prismatic-fragment', quantity: 30 }, { itemId: 'black-portal-shard', quantity: 12 }], 'magister', 560, { type: 'arcane-flux', amount: .03 }, ['expand-flux-reservoir']),
  project('restore-acolyte-quarters', 'acolyte-quarters', 'Restore Acolyte Quarters', 'Reopen safe quarters and add one available Acolyte place.', [{ itemId: 'water-fragment', quantity: 24 }, { itemId: 'life-essence', quantity: 15 }], 'adept', 280, { type: 'acolyte-capacity', amount: 1 }, ['rebuild-transmutation-hall']),
  project('expand-acolyte-quarters', 'acolyte-quarters', 'Expand Acolyte Quarters', 'Extend the safe sleeping and training wing for another Acolyte.', [{ itemId: 'earth-fragment', quantity: 45 }, { itemId: 'artifact-essence', quantity: 35 }], 'magister', 460, { type: 'acolyte-capacity', amount: 1 }, ['restore-acolyte-quarters']),
  project('restore-dispatch-office', 'commission-office', 'Restore the Dispatch Office', 'Repair the office desk and grant one stored free Board refresh.', [{ itemId: 'fire-fragment', quantity: 28 }, { itemId: 'life-essence', quantity: 24 }], 'apprentice', 250, { type: 'commission-refresh', amount: 1 }, ['restore-arcane-archive']),
  project('establish-senior-clerk-desk', 'commission-office', 'Establish the Senior Clerk Desk', 'Add a senior clerk to prepare one more Commission choice.', [{ itemId: 'artifact-essence', quantity: 32 }, { itemId: 'air-fragment', quantity: 40 }], 'adept', 360, { type: 'commission-choice', amount: 1 }, ['restore-dispatch-office']),
  project('open-grand-service-hall', 'commission-office', 'Open the Grand Service Hall', 'Complete a central hall that rewards reliable Commission service.', [{ itemId: 'prismatic-fragment', quantity: 20 }, { itemId: 'black-portal-shard', quantity: 10 }, { itemId: 'life-essence', quantity: 40 }], 'magister', 600, { type: 'guild-reputation', amount: .03 }, ['establish-senior-clerk-desk']),
].map((entry) => ({ ...entry, minimumStandingId: projectStandingOverrides[entry.id] ?? entry.minimumStandingId }))
