import type { ItemId, ManaPillarId } from '../types'

export interface ManaPillarLevelCost {
  fragment: number
  lifeEssence: number
}

export interface ManaPillarDefinition {
  id: ManaPillarId
  name: string
  description: string
  effect: 'flat-regen' | 'flat-capacity' | 'passive-regen-percent' | 'capacity-percent' | 'echo-percent'
  effectLabel: string
  valuePerLevel: number
  maxLevel: 10
  fragmentRequirements: readonly ItemId[]
}

export const MANA_PILLAR_IDS: readonly ManaPillarId[] = [
  'leyline-conduit',
  'arcane-reservoir',
  'mana-resonance',
  'astral-expansion',
  'echo-attunement',
]

export const PILLAR_LEVEL_COSTS: Record<1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10, ManaPillarLevelCost> = {
  1: { fragment: 5, lifeEssence: 10 },
  2: { fragment: 10, lifeEssence: 20 },
  3: { fragment: 15, lifeEssence: 30 },
  4: { fragment: 25, lifeEssence: 50 },
  5: { fragment: 40, lifeEssence: 80 },
  6: { fragment: 60, lifeEssence: 120 },
  7: { fragment: 90, lifeEssence: 180 },
  8: { fragment: 130, lifeEssence: 260 },
  9: { fragment: 180, lifeEssence: 360 },
  10: { fragment: 250, lifeEssence: 500 },
}

export const MANA_PILLARS: Record<ManaPillarId, ManaPillarDefinition> = {
  'leyline-conduit': {
    id: 'leyline-conduit',
    name: 'Leyline Conduit',
    description: 'Strengthens the tower\'s natural connection to the leyline.',
    effect: 'flat-regen',
    effectLabel: 'PASSIVE MANA REGEN',
    valuePerLevel: 1,
    maxLevel: 10,
    fragmentRequirements: ['water-fragment', 'air-fragment'],
  },
  'arcane-reservoir': {
    id: 'arcane-reservoir',
    name: 'Arcane Reservoir',
    description: 'Expands the tower\'s capacity to hold Mana.',
    effect: 'flat-capacity',
    effectLabel: 'MAX MANA',
    valuePerLevel: 25,
    maxLevel: 10,
    fragmentRequirements: ['earth-fragment', 'water-fragment'],
  },
  'mana-resonance': {
    id: 'mana-resonance',
    name: 'Mana Resonance',
    description: 'Amplifies all passive non-Echo Mana regeneration.',
    effect: 'passive-regen-percent',
    effectLabel: 'PASSIVE MANA AMPLIFICATION',
    valuePerLevel: 5,
    maxLevel: 10,
    fragmentRequirements: ['fire-fragment', 'air-fragment'],
  },
  'astral-expansion': {
    id: 'astral-expansion',
    name: 'Astral Expansion',
    description: 'Amplifies final Max Mana, including equipment bonuses.',
    effect: 'capacity-percent',
    effectLabel: 'MAX MANA AMPLIFICATION',
    valuePerLevel: 5,
    maxLevel: 10,
    fragmentRequirements: ['earth-fragment', 'fire-fragment'],
  },
  'echo-attunement': {
    id: 'echo-attunement',
    name: 'Echo Attunement',
    description: 'Increases Mana generated by Arcane Echoes.',
    effect: 'echo-percent',
    effectLabel: 'ECHO MANA',
    valuePerLevel: 5,
    maxLevel: 10,
    fragmentRequirements: ['fire-fragment', 'water-fragment', 'earth-fragment', 'air-fragment'],
  },
}

export const getManaPillarLevelCost = (level: number): ManaPillarLevelCost | null => (
  level >= 1 && level <= 10 ? PILLAR_LEVEL_COSTS[level as keyof typeof PILLAR_LEVEL_COSTS] : null
)

export const createInitialManaPillars = () => Object.fromEntries(
  MANA_PILLAR_IDS.map((id) => [id, { rank: 1, level: 0 }]),
) as Record<ManaPillarId, { rank: number; level: number }>
