import { useState } from 'react'
import { Archive, Check, LockKeyhole, ScrollText, Sparkles } from 'lucide-react'
import { Button, Card, GameTooltip, Progress, Status } from '../../components/ui'
import { GUILD_PROJECTS, type GuildFacilityId } from '../../game/content/guild/guildProjects'
import { GUILD_FACILITIES } from '../../game/content/guild/guildFacilities'
import { GUILD_COMMISSION_CHAINS } from '../../game/content/guild/guildCommissionChains'
import { GUILD_STANDINGS } from '../../game/content/guild/guildStandings'
import { ITEMS } from '../../game/content/items/items'
import { useGameStore } from '../../store/gameStore'
import { getGuildProjectEffectiveRequirements, getGuildProjectStatus } from '../../game/systems/guild/guildProjects'
import { getGuildProgressionBonuses } from '../../game/systems/guild/guildSelectors'

const projectEffectLabel = (project: (typeof GUILD_PROJECTS)[number]) => {
  const effect = project.effect
  if (!effect) return 'No permanent effect.'
  const value = effect.type === 'acolyte-capacity' || effect.type === 'commission-refresh' || effect.type === 'commission-choice' ? `+${effect.amount}` : `+${Math.round(effect.amount * 100)}%`
  const labels: Record<typeof effect.type, string> = { 'guild-reputation': 'Guild Reputation from Commissions', 'research-speed': 'Research speed', 'research-xp': 'Research experience', 'transmutation-speed': 'Transmutation speed', 'transmutation-output': 'Transmutation extra-output chance', 'transmutation-cost': 'Transmutation Resonance cost reduction', 'arcane-flux': 'Arcane Flux production', 'arcane-flux-capacity': 'Arcane Flux capacity', 'acolyte-capacity': 'Acolyte capacity', 'commission-refresh': 'stored free Board refresh', 'commission-choice': 'Commission Board choice', 'registry-cost': 'consumptive Registry requirements' }
  return `${value} ${labels[effect.type]}.`
}

export function GuildProjectsTab() {
  const state = useGameStore()
  const guild = state.progress.arcaneGuild
  const [selectedFacilityId, setSelectedFacilityId] = useState<GuildFacilityId>('archive')
  const projects = GUILD_PROJECTS.filter((project) => project.facilityId === selectedFacilityId)
  const [selectedProjectId, setSelectedProjectId] = useState(projects[0]?.id ?? GUILD_PROJECTS[0].id)
  const selectedProject = GUILD_PROJECTS.find((project) => project.id === selectedProjectId && project.facilityId === selectedFacilityId) ?? projects[0]
  const selectedRequirements = selectedProject ? getGuildProjectEffectiveRequirements(state, selectedProject.id) : []
  const totalRequired = selectedRequirements.reduce((sum, entry) => sum + entry.quantity, 0)
  const totalContributed = selectedRequirements.reduce((sum, entry) => sum + Math.min(entry.quantity, guild.projects[selectedProject?.id ?? '']?.[entry.itemId] ?? 0), 0)
  const selectedStatus = selectedProject ? getGuildProjectStatus(state, selectedProject.id) : null
  const selectedRank = selectedProject ? GUILD_STANDINGS.find((standing) => standing.id === selectedProject.minimumStandingId)?.name ?? selectedProject.minimumStandingId : ''
  const lockReason = selectedStatus?.reason === 'standing-required' ? `Requires ${selectedRank} Guild Standing.` : selectedStatus?.reason === 'prerequisite-required' ? `Prerequisites: ${selectedStatus.missingProjects.map((id) => GUILD_PROJECTS.find((entry) => entry.id === id)?.name ?? id).join(', ')}.` : null
  const chooseFacility = (facilityId: GuildFacilityId) => { setSelectedFacilityId(facilityId); const first = GUILD_PROJECTS.find((project) => project.facilityId === facilityId); if (first) setSelectedProjectId(first.id) }
  return <section className="guild-project-workspace" aria-label="Guild Facilities and Projects">
    <Card className="guild-facility-catalog"><div className="guild-v3-panel-heading"><div><span className="guild-v3-kicker">SIX GUILD FACILITIES</span><h2>Facilities</h2><p>Select a facility, then inspect its project docket.</p></div><Archive size={17} /></div><div className="guild-facility-list">{GUILD_FACILITIES.map((facility) => { const facilityProjects = GUILD_PROJECTS.filter((project) => project.facilityId === facility.id); const complete = facilityProjects.filter((project) => guild.completedProjectIds.includes(project.id)).length; const current = facilityProjects.find((project) => !guild.completedProjectIds.includes(project.id)); return <Button key={facility.id} variant={selectedFacilityId === facility.id ? 'primary' : 'ghost'} ariaPressed={selectedFacilityId === facility.id} className="guild-facility-choice" onClick={() => chooseFacility(facility.id)}><span className="guild-facility-seal">{facility.seal}</span><span><strong>{facility.name}</strong><small>{complete} / {facilityProjects.length} projects{current ? ` · ${current.name}` : ' · restored'}</small></span><b>{complete === facilityProjects.length ? <Check size={15} /> : `${complete}/${facilityProjects.length}`}</b></Button> })}</div></Card>
    <Card className="guild-project-catalog"><div className="guild-v3-panel-heading"><div><span className="guild-v3-kicker">FACILITY DOCKET</span><h2>{GUILD_FACILITIES.find((facility) => facility.id === selectedFacilityId)?.name}</h2></div><Status tone="active">{projects.length} Projects</Status></div><div className="guild-project-list">{projects.map((project) => { const completed = guild.completedProjectIds.includes(project.id); const status = getGuildProjectStatus(state, project.id); const requiredStanding = GUILD_STANDINGS.find((standing) => standing.id === project.minimumStandingId)?.name ?? project.minimumStandingId; return <GameTooltip key={project.id} content={`${project.name} · ${completed ? 'complete' : status.available ? 'available' : status.reason === 'standing-required' ? `requires ${requiredStanding} Standing` : 'prerequisite locked'}`} block><Button variant={selectedProject?.id === project.id ? 'primary' : 'ghost'} ariaPressed={selectedProject?.id === project.id} className={`guild-project-choice${completed ? ' complete' : ''}`} onClick={() => setSelectedProjectId(project.id)}><span className="guild-project-choice-state">{completed ? <Check size={14} /> : status.available ? <Sparkles size={14} /> : <LockKeyhole size={14} />}</span><span><strong>{project.name}</strong><small>{completed ? 'Complete · permanent effect active' : project.description}</small></span><b>{completed ? 'DONE' : `${project.advancementPointsReward} AP`}</b></Button></GameTooltip>})}</div></Card>
    {selectedProject && selectedStatus && <Card className="guild-project-inspector"><div className="guild-v3-panel-heading"><div><span className="guild-v3-kicker">PROJECT INSPECTOR · {selectedRank.toUpperCase()}</span><h2>{selectedProject.name}</h2></div><Status tone={selectedStatus.complete ? 'success' : selectedStatus.available ? 'active' : 'locked'}>{selectedStatus.complete ? 'Complete' : selectedStatus.available ? 'Available' : 'Locked'}</Status></div><p>{selectedProject.description}</p><div className="guild-project-effect">{projectEffectLabel(selectedProject)}</div>{lockReason && <div className="guild-project-lock-reason">{lockReason}</div>}<div className="guild-project-rewards"><span>+{selectedProject.reputationReward} Reputation</span><strong>+{selectedProject.advancementPointsReward} AP · first completion</strong></div><div className="guild-project-progress-label"><span>Materials contributed</span><strong>{totalContributed} / {totalRequired}</strong></div><Progress value={totalRequired ? totalContributed / totalRequired * 100 : 100} tone="gold" /><div className="guild-project-requirements">{selectedRequirements.map((entry) => { const amount = guild.projects[selectedProject.id]?.[entry.itemId] ?? 0; const remaining = Math.max(0, entry.quantity - amount); const owned = state.inventory[entry.itemId] ?? 0; return <div key={entry.itemId}><span>{ITEMS[entry.itemId].name} <b>{amount} / {entry.quantity}</b></span><GameTooltip content={`Contribute up to ${Math.min(remaining, owned)}. Protected materials cannot be contributed.`}><Button variant="secondary" disabled={!selectedStatus.available || remaining < 1 || owned < 1} onClick={() => state.contributeGuildProject(selectedProject.id, entry.itemId, 'max')}>{selectedStatus.complete ? 'Complete' : !selectedStatus.available ? 'Locked' : `Contribute · ${Math.min(remaining, owned)}`}</Button></GameTooltip></div>})}</div>{selectedStatus.complete && <div className="guild-project-complete"><Check size={15} /> Effect active · materials are permanently recorded</div>}</Card>}
  </section>
}

export function GuildCommissionChainsTab() {
  const state = useGameStore()
  const guild = state.progress.arcaneGuild
  const active = guild.activeCommissionChain
  const [selectedId, setSelectedId] = useState(GUILD_COMMISSION_CHAINS[0].id)
  const selected = GUILD_COMMISSION_CHAINS.find((entry) => entry.id === selectedId) ?? GUILD_COMMISSION_CHAINS[0]
  const activeStudy = active?.id === selected.id ? active : null
  const activeStage = activeStudy ? selected.stages[activeStudy.stageIndex] : null
  const requiredStanding = GUILD_STANDINGS.find((standing) => standing.id === selected.minimumStandingId)
  const unlocked = state.progress.guildReputation >= (requiredStanding?.reputation ?? Number.POSITIVE_INFINITY)
  const firstClear = !guild.completedChainIds.includes(selected.id)
  const repeatReward = Math.round(selected.repeatReputationReward * getGuildProgressionBonuses(state).repeatStudyReputationMultiplier)
  const stageLabel = (entry: typeof selected.stages[number]) => entry.category === 'delivery' ? `Deliver ${entry.target} ${ITEMS[entry.itemId].name}` : entry.category === 'production' ? `Produce ${entry.target} ${ITEMS[entry.itemId].name}` : `${entry.category === 'research' ? 'Complete Research' : 'Perform Transmutation'} · ${entry.target}`
  return <section className="guild-study-workspace" aria-label="Guild Studies">
    <Card className="guild-study-catalog"><div className="guild-v3-panel-heading"><div><span className="guild-v3-kicker">REPEATABLE FACULTY RESEARCH</span><h2>Guild Studies</h2><p>{guild.completedChainIds.length} / {GUILD_COMMISSION_CHAINS.length} first clears · one Study can run beside a Commission.</p></div><ScrollText size={17} /></div><div className="guild-study-list">{GUILD_COMMISSION_CHAINS.map((study) => { const activeEntry = active?.id === study.id; const complete = guild.completedChainIds.includes(study.id); const standing = GUILD_STANDINGS.find((entry) => entry.id === study.minimumStandingId); const locked = state.progress.guildReputation < (standing?.reputation ?? Number.POSITIVE_INFINITY); return <GameTooltip key={study.id} content={`${study.name} · ${complete ? 'first clear complete' : locked ? `Requires ${standing?.name ?? study.minimumStandingId}` : activeEntry ? 'currently active' : 'available to study'}`} block><Button variant={selected.id === study.id ? 'primary' : 'ghost'} ariaPressed={selected.id === study.id} className={`guild-study-choice${complete ? ' complete' : ''}`} onClick={() => setSelectedId(study.id)}><span className="guild-study-choice-state">{activeEntry ? <Sparkles size={14} /> : complete ? <Check size={14} /> : locked ? <LockKeyhole size={14} /> : <ScrollText size={14} />}</span><span><strong>{study.name}</strong><small>{complete ? `Repeatable · ${study.stages.length} stages · REP only` : `${study.stages.length} stages · first clear · +${study.advancementPointsReward} AP · ${standing?.name ?? study.minimumStandingId}`}</small></span><b>{activeEntry ? `${active!.stageIndex + 1}/${study.stages.length}` : complete ? 'DONE' : 'STUDY'}</b></Button></GameTooltip> })}</div></Card>
    <Card className="guild-study-inspector"><div className="guild-v3-panel-heading"><div><span className="guild-v3-kicker">STUDY INSPECTOR · {requiredStanding?.name ?? selected.minimumStandingId}</span><h2>{selected.name}</h2></div><Status tone={activeStudy ? 'active' : guild.completedChainIds.includes(selected.id) ? 'success' : unlocked ? 'neutral' : 'locked'}>{activeStudy ? 'In Progress' : guild.completedChainIds.includes(selected.id) ? 'Repeatable' : unlocked ? 'Available' : 'Locked'}</Status></div><p>{selected.description}</p><ol className="guild-study-stage-list">{selected.stages.map((entry, index) => { const complete = Boolean(activeStudy && index < activeStudy.stageIndex) || (!activeStudy && guild.completedChainIds.includes(selected.id)); const current = activeStudy?.stageIndex === index; return <li key={`${selected.id}:${index}`} className={`${complete ? 'complete' : ''}${current ? ' current' : ''}`}><span className="guild-study-stage-index">{complete ? <Check size={13} /> : index + 1}</span><div><small>STAGE {index + 1} · {entry.category.toUpperCase()}</small><strong>{stageLabel(entry)}</strong></div>{current && <Status tone="active">Current</Status>}</li>})}</ol><div className="guild-project-rewards"><strong>{firstClear ? `First clear · +${selected.reputationReward} REP · +${selected.advancementPointsReward} AP` : `Repeat · +${repeatReward} REP · no AP`}</strong></div>
      {activeStudy && activeStage ? <div className="guild-study-active-stage"><div><span>STAGE PROGRESS</span><strong>{activeStudy.stageProgress} / {activeStage.target}{'itemId' in activeStage ? ` · ${ITEMS[activeStage.itemId].name}` : ''}</strong></div><Progress value={activeStudy.stageProgress / activeStage.target * 100} tone="gold" />{activeStage.category === 'delivery' && <GameTooltip content={`Contribute ${ITEMS[activeStage.itemId].name} to this Study stage. Protected items are excluded.`}><Button variant="primary" disabled={(state.inventory[activeStage.itemId] ?? 0) < 1} onClick={() => state.contributeGuildCommissionChainDelivery('max')}>Deliver max · {state.inventory[activeStage.itemId] ?? 0}</Button></GameTooltip>}</div> : <GameTooltip content={unlocked ? 'Start this Study. A Study can run alongside your active regular Commission.' : `Reach ${requiredStanding?.name ?? 'the required'} Guild Standing to unlock this Study.`}><Button variant="primary" disabled={!unlocked || Boolean(active)} onClick={() => state.startGuildCommissionChain(selected.id)}>{unlocked ? active ? 'Another Study is active' : 'Start Study' : `${requiredStanding?.name ?? 'Standing'} required`}</Button></GameTooltip>}
    </Card>
  </section>
}
