import { ClipboardList, RefreshCw, Truck } from 'lucide-react'
import { Button, Card, GameTooltip, Progress } from '../../components/ui'
import { GUILD_COMMISSION_TEMPLATES } from '../../game/content/guild/guildRequests'
import { ITEMS } from '../../game/content/items/items'
import type { GameStore } from '../../store/gameStore'

const templateFor = (id: string) => GUILD_COMMISSION_TEMPLATES.find((template) => template.id === id)
const qualityLabel = { routine: 'ROUTINE', special: 'SPECIAL', prestigious: 'PRESTIGIOUS' } as const
const categoryLabel: Record<import('../../game/types').GuildCommissionCategory, string> = { delivery: 'DELIVERY', production: 'PRODUCTION', research: 'RESEARCH', transmutation: 'TRANSMUTATION', mixed: 'MIXED' }
const objectiveLabel = (commission: NonNullable<GameStore['progress']['arcaneGuild']['activeCommission']>) => {
  if (commission.category === 'delivery' && commission.itemId) return `Deliver ${commission.target.toLocaleString()} ${ITEMS[commission.itemId].name}`
  if (commission.category === 'production' && commission.itemId) return `Produce ${commission.target.toLocaleString()} ${ITEMS[commission.itemId].name}`
  if (commission.category === 'mixed') return commission.components?.map((component) => {
    const item = component.itemId ? ` ${ITEMS[component.itemId].name}` : ''
    const verb = component.category === 'production' ? 'Produce' : component.category === 'research' ? 'Complete Research' : 'Complete Transmutations'
    return `${verb} ${component.target.toLocaleString()}${item}`
  }).join(' + ') || 'Complete a mixed Guild assignment'
  if (commission.category === 'research') return `Complete ${commission.target.toLocaleString()} Research cycles`
  return `Complete ${commission.target.toLocaleString()} Transmutations`
}

export function GuildContractsBoard({ state }: { state: GameStore }) {
  const guild = state.progress.arcaneGuild
  const active = guild.activeCommission
  return <section className="guild-v3-tab-content guild-v3-contracts-view arcane-commission-board">
    <div className="guild-v3-section-heading"><div><span className="guild-v3-kicker">ARCANE GUILD · WORK ORDERS</span><h2>{active ? 'Your active commission' : 'Choose a commission'}</h2><p>Accept one noncombat assignment. Registering, studying, transmuting, and delivering materials build professional standing.</p></div><div className="guild-v3-board-stamp"><ClipboardList size={16} /> {guild.completedCommissions.toLocaleString()} completed</div></div>
    {active && <Card className="guild-commission-active"><div className="guild-commission-emblem"><Truck size={19} /></div><div className="guild-commission-active-copy"><div className="guild-commission-tags"><span>{categoryLabel[active.category]}</span><span className={`guild-commission-quality ${active.quality}`}>{qualityLabel[active.quality]}</span></div><h3>{objectiveLabel(active)}</h3><p>{active.progress.toLocaleString()} / {active.target.toLocaleString()} · +{active.reputationReward.toLocaleString()} Reputation</p>{active.components ? active.components.map((component) => <div className="guild-commission-component" key={`${component.category}:${component.itemId ?? 'any'}`}><span>{component.category.toUpperCase()}{component.itemId ? ` · ${ITEMS[component.itemId].name}` : ''}</span><strong>{component.progress.toLocaleString()} / {component.target.toLocaleString()}</strong><Progress value={Math.min(100, component.progress / component.target * 100)} tone="gold" /></div>) : <Progress value={Math.min(100, active.progress / active.target * 100)} tone="gold" />}{active.category === 'delivery' && active.itemId && <div className="guild-commission-delivery"><span>Available: {(state.inventory[active.itemId] ?? 0).toLocaleString()}</span><div><GameTooltip content="Deliver one unprotected item toward this commission."><Button variant="ghost" disabled={(state.inventory[active.itemId] ?? 0) < 1} onClick={() => state.deliverGuildCommissionItems(1)}>Deliver 1</Button></GameTooltip><GameTooltip content="Deliver up to five unprotected items toward this commission."><Button variant="secondary" disabled={(state.inventory[active.itemId] ?? 0) < 1} onClick={() => state.deliverGuildCommissionItems(5)}>Deliver 5</Button></GameTooltip><GameTooltip content="Deliver as much as possible, up to the remaining requirement."><Button variant="primary" disabled={(state.inventory[active.itemId] ?? 0) < 1} onClick={() => state.deliverGuildCommissionItems('max')}>Deliver max</Button></GameTooltip></div></div>}</div></Card>}
    <div className="guild-commission-offer-heading"><h3>Available commissions</h3><GameTooltip content={guild.freeRefreshes ? 'Use the refresh earned by completing a Commission to replace this board.' : 'Complete a Commission to earn one free board refresh.'}><Button variant="secondary" disabled={guild.freeRefreshes < 1} onClick={() => state.refreshGuildCommissionChoices()}><RefreshCw size={14} /> Refresh · {guild.freeRefreshes}</Button></GameTooltip></div>
    {guild.availableCommissions.length ? <div className="guild-commission-grid">{guild.availableCommissions.map((commission) => { const template = templateFor(commission.templateId); return <Card className="guild-commission-offer" key={commission.id}><div className="guild-commission-tags"><span>{categoryLabel[commission.category]}</span><span className={`guild-commission-quality ${commission.quality}`}>{qualityLabel[commission.quality]}</span></div><h3>{objectiveLabel(commission)}</h3><p>{commission.category === 'delivery' ? template?.itemId ? ITEMS[template.itemId].source : 'Deliver Guild materials.' : commission.category === 'production' ? 'Successful Transmutation outputs advance this work order.' : commission.category === 'mixed' ? 'Complete each listed professional objective.' : commission.category === 'research' ? 'Any successful Research completion advances this work order.' : 'Any successful Transmutation cycle advances this work order.'}</p><div className="guild-commission-reward"><span>+{commission.reputationReward.toLocaleString()} Reputation</span>{commission.advancementPointReward > 0 && <strong>+{commission.advancementPointReward} Advancement Point</strong>}</div><GameTooltip content="Accept this noncombat work order. One Guild Commission can be active at a time."><Button variant="primary" disabled={Boolean(active)} onClick={() => state.acceptGuildCommission(commission.id)}>Accept Commission</Button></GameTooltip></Card> })}</div> : <Card className="guild-v3-empty-filter-state">No commission templates are currently available. Unlock Research or Transmutation to broaden the board.</Card>}
  </section>
}
