import { useState } from 'react'
import { Archive, Check, LockKeyhole, Sparkles } from 'lucide-react'
import { Button, Card, GameTooltip, Progress, Status } from '../../components/ui'
import { GUILD_PROJECTS, type GuildFacilityId } from '../../game/content/guild/guildProjects'
import { GUILD_FACILITIES } from '../../game/content/guild/guildFacilities'
import { GUILD_STANDINGS } from '../../game/content/guild/guildStandings'
import { ITEMS } from '../../game/content/items/items'
import { useGameStore } from '../../store/gameStore'
import { getGuildProjectEffectiveRequirements, getGuildProjectStatus } from '../../game/systems/guild/guildProjects'

const projectEffectLabel = (project: (typeof GUILD_PROJECTS)[number]) => {
  const effect = project.effect
  if (!effect) return 'No permanent effect.'
  const value = effect.type === 'acolyte-capacity' || effect.type === 'commission-refresh' || effect.type === 'commission-choice' ? `+${effect.amount}` : `+${Math.round(effect.amount * 100)}%`
  const labels: Record<typeof effect.type, string> = { 'guild-reputation': 'Guild Reputation from Commissions', 'research-speed': 'Research speed', 'research-xp': 'Research experience', 'transmutation-speed': 'Transmutation speed', 'transmutation-output': 'Transmutation extra-output chance', 'transmutation-cost': 'Transmutation Resonance cost reduction', 'arcane-flux': 'Arcane Flux production', 'arcane-flux-capacity': 'Arcane Flux capacity', 'acolyte-capacity': 'Acolyte capacity', 'commission-refresh': 'stored free Board refresh', 'commission-choice': 'Commission Board choice', 'registry-cost': 'consumptive Registry requirements' }
  return `${value} ${labels[effect.type]}.`
}

export function GuildProjectsTab() {
  const state = useGameStore()
  const guild = state.progress.arcaneGuild
  const [selectedFacilityId, setSelectedFacilityId] = useState<GuildFacilityId>('archive')
  const projects = GUILD_PROJECTS.filter((project) => project.facilityId === selectedFacilityId)
  const [selectedProjectId, setSelectedProjectId] = useState(projects[0]?.id ?? GUILD_PROJECTS[0].id)
  const selectedProject = GUILD_PROJECTS.find((project) => project.id === selectedProjectId && project.facilityId === selectedFacilityId) ?? projects[0]
  const selectedRequirements = selectedProject ? getGuildProjectEffectiveRequirements(state, selectedProject.id) : []
  const totalRequired = selectedRequirements.reduce((sum, entry) => sum + entry.quantity, 0)
  const totalContributed = selectedRequirements.reduce((sum, entry) => sum + Math.min(entry.quantity, guild.projects[selectedProject?.id ?? '']?.[entry.itemId] ?? 0), 0)
  const selectedStatus = selectedProject ? getGuildProjectStatus(state, selectedProject.id) : null
  const selectedRank = selectedProject ? GUILD_STANDINGS.find((standing) => standing.id === selectedProject.minimumStandingId)?.name ?? selectedProject.minimumStandingId : ''
  const lockReason = selectedStatus?.reason === 'standing-required' ? `Requires ${selectedRank} Guild Standing.` : selectedStatus?.reason === 'prerequisite-required' ? `Prerequisites: ${selectedStatus.missingProjects.map((id) => GUILD_PROJECTS.find((entry) => entry.id === id)?.name ?? id).join(', ')}.` : null
  const chooseFacility = (facilityId: GuildFacilityId) => { setSelectedFacilityId(facilityId); const first = GUILD_PROJECTS.find((project) => project.facilityId === facilityId); if (first) setSelectedProjectId(first.id) }
  return <section className="guild-project-workspace" aria-label="Guild Facilities and Projects">
    <Card className="guild-facility-catalog"><div className="guild-v3-panel-heading"><div><span className="guild-v3-kicker">SIX GUILD FACILITIES</span><h2>Facilities</h2><p>Select a facility, then inspect its project docket.</p></div><Archive size={17} /></div><div className="guild-facility-list">{GUILD_FACILITIES.map((facility) => { const facilityProjects = GUILD_PROJECTS.filter((project) => project.facilityId === facility.id); const complete = facilityProjects.filter((project) => guild.completedProjectIds.includes(project.id)).length; const current = facilityProjects.find((project) => !guild.completedProjectIds.includes(project.id)); return <Button key={facility.id} variant={selectedFacilityId === facility.id ? 'primary' : 'ghost'} ariaPressed={selectedFacilityId === facility.id} className="guild-facility-choice" onClick={() => chooseFacility(facility.id)}><span className="guild-facility-seal">{facility.seal}</span><span><strong>{facility.name}</strong><small>{complete} / {facilityProjects.length} projects{current ? ` · ${current.name}` : ' · restored'}</small></span><b>{complete === facilityProjects.length ? <Check size={15} /> : `${complete}/${facilityProjects.length}`}</b></Button> })}</div></Card>
    <Card className="guild-project-catalog"><div className="guild-v3-panel-heading"><div><span className="guild-v3-kicker">FACILITY DOCKET</span><h2>{GUILD_FACILITIES.find((facility) => facility.id === selectedFacilityId)?.name}</h2></div><Status tone="active">{projects.length} Projects</Status></div><div className="guild-project-list">{projects.map((project) => { const completed = guild.completedProjectIds.includes(project.id); const status = getGuildProjectStatus(state, project.id); const requiredStanding = GUILD_STANDINGS.find((standing) => standing.id === project.minimumStandingId)?.name ?? project.minimumStandingId; return <GameTooltip key={project.id} content={`${project.name} · ${completed ? 'complete' : status.available ? 'available' : status.reason === 'standing-required' ? `requires ${requiredStanding} Standing` : 'prerequisite locked'}`} block><Button variant={selectedProject?.id === project.id ? 'primary' : 'ghost'} ariaPressed={selectedProject?.id === project.id} className={`guild-project-choice${completed ? ' complete' : ''}`} onClick={() => setSelectedProjectId(project.id)}><span className="guild-project-choice-state">{completed ? <Check size={14} /> : status.available ? <Sparkles size={14} /> : <LockKeyhole size={14} />}</span><span><strong>{project.name}</strong><small>{completed ? 'Complete · permanent effect active' : project.description}</small></span><b>{completed ? 'DONE' : `${project.advancementPointsReward} AP`}</b></Button></GameTooltip>})}</div></Card>
    {selectedProject && selectedStatus && <Card className="guild-project-inspector"><div className="guild-v3-panel-heading"><div><span className="guild-v3-kicker">PROJECT INSPECTOR · {selectedRank.toUpperCase()}</span><h2>{selectedProject.name}</h2></div><Status tone={selectedStatus.complete ? 'success' : selectedStatus.available ? 'active' : 'locked'}>{selectedStatus.complete ? 'Complete' : selectedStatus.available ? 'Available' : 'Locked'}</Status></div><p>{selectedProject.description}</p><div className="guild-project-effect">{projectEffectLabel(selectedProject)}</div>{lockReason && <div className="guild-project-lock-reason">{lockReason}</div>}<div className="guild-project-rewards"><span>+{selectedProject.reputationReward} Reputation</span><strong>+{selectedProject.advancementPointsReward} AP · first completion</strong></div><div className="guild-project-progress-label"><span>Materials contributed</span><strong>{totalContributed} / {totalRequired}</strong></div><Progress value={totalRequired ? totalContributed / totalRequired * 100 : 100} tone="gold" /><div className="guild-project-requirements">{selectedRequirements.map((entry) => { const amount = guild.projects[selectedProject.id]?.[entry.itemId] ?? 0; const remaining = Math.max(0, entry.quantity - amount); const owned = state.inventory[entry.itemId] ?? 0; return <div key={entry.itemId}><span>{ITEMS[entry.itemId].name} <b>{amount} / {entry.quantity}</b></span><GameTooltip content={`Contribute up to ${Math.min(remaining, owned)}. Protected materials cannot be contributed.`}><Button variant="secondary" disabled={!selectedStatus.available || remaining < 1 || owned < 1} onClick={() => state.contributeGuildProject(selectedProject.id, entry.itemId, 'max')}>{selectedStatus.complete ? 'Complete' : !selectedStatus.available ? 'Locked' : `Contribute · ${Math.min(remaining, owned)}`}</Button></GameTooltip></div>})}</div>{selectedStatus.complete && <div className="guild-project-complete"><Check size={15} /> Effect active · materials are permanently recorded</div>}</Card>}
  </section>
}
