import { Check, Crown, Gift, Lock, Sparkles } from 'lucide-react'
import { GUILD_REQUESTS } from '../../game/data/guildRequests'
import { useGameStore } from '../../store/gameStore'
import { Button, Card, Progress, Status } from '../../components/ui'
import { EditableGrid } from '../../ui/layout-editor/EditableGrid'

export function GuildScreenV2() {
  const progress = useGameStore((state) => state.progress); const inventory = useGameStore((state) => state.inventory); const donate = useGameStore((state) => state.donateGuildRequest); const claim = useGameStore((state) => state.claimGuildReward); const promote = useGameStore((state) => state.promoteGuild)
  if (!progress.guildUnlocked) return <div className="screen-content"><div className="screen-header"><div><div className="eyebrow">THE VERDANT CIRCLE</div><h1>A guild invitation, still sealed.</h1><p>Defeat Grove Sentinel to unlock Requests, Reputation, and the Initiate → Apprentice progression.</p></div></div><EditableGrid screen="guild" panels={[{ id: 'guild-banner', content: <div className="locked-screen"><div className="locked-seal"><Lock size={28} /></div><h2>Guild Locked</h2><p>The forest guardian holds the first letter of introduction.</p></div> }]} /></div>
  const requestViews = Object.values(GUILD_REQUESTS).map((request) => ({ request, value: progress.requestProgress[request.id] ?? 0, claimed: Boolean(progress.requestClaims[request.id]) })); const allComplete = requestViews.every(({ value, request }) => value >= request.target)
  const banner = <div className="guild-banner"><div className="guild-emblem">¤</div><div><Status tone="success">Unlocked</Status><h2>Verdant Circle</h2><p>Current rank · {progress.guildRank === 'initiate' ? 'Initiate' : 'Apprentice'}</p></div><div className="rank-step"><span>Outsider</span><span>→ Initiate</span><strong>→ Apprentice</strong></div></div>
  const requests = requestViews.map(({ request, value, claimed }, index) => ({ id: `guild-request-${index + 1}`, content: <Card className={`request-card ${value >= request.target ? 'done' : ''}`}><div className="request-icon">{value >= request.target ? <Check size={20} /> : <Gift size={20} />}</div><div><Status tone={claimed ? 'success' : value >= request.target ? 'warning' : 'neutral'}>{claimed ? 'Reward claimed' : value >= request.target ? 'Request complete' : 'Active Request'}</Status><h3>{request.name}</h3><p>{request.description}</p><Progress value={value / request.target * 100} tone="gold" right={`${Math.min(value, request.target)} / ${request.target}`} />{request.kind === 'donation' && <div className="donation-buttons"><Button variant="ghost" onClick={() => donate(request.id, 1)}>Donate 1</Button><Button variant="ghost" onClick={() => donate(request.id, 5)}>Donate 5</Button><Button variant="ghost" onClick={() => donate(request.id, 'max')}>Donate Max</Button><small>Available: {inventory[request.itemId] ?? 0}</small></div>}{value >= request.target && !claimed && <Button variant="success" className="wide" onClick={() => claim(request.id)}>Claim +{request.reputation} Reputation</Button>}</div></Card> }))
  const rank = <Card title="Rank promotion"><div className="rank-promotion"><div><Crown size={22} color="var(--gold)" /><strong>{progress.guildRank === 'apprentice' ? 'Apprentice achieved' : 'Initiate → Apprentice'}</strong><span>{allComplete ? 'All Requests complete.' : 'Complete all three Requests.'} Reputation {progress.guildReputation} / 175.</span></div><Button variant={progress.guildRank === 'apprentice' ? 'success' : 'secondary'} disabled={progress.guildRank === 'apprentice' || !allComplete || progress.guildReputation < 175} onClick={promote}>{progress.guildRank === 'apprentice' ? 'Promoted' : 'Promote'}</Button></div><div className="equipment-note"><Sparkles size={15} /><span>Apprentice reward: +10 permanent Max Focus. It is stored by reward ID and cannot duplicate after reload.</span></div></Card>
  return <div className="screen-content"><div className="screen-header"><div><div className="eyebrow">THE VERDANT CIRCLE</div><h1>Your first guild hall.</h1><p>Donate selectively, claim rewards once, and earn enough Reputation to become an Apprentice.</p></div><div className="focus-summary"><span>GUILD REPUTATION</span><strong>{progress.guildReputation}</strong><em>{progress.guildRank}</em></div></div><EditableGrid screen="guild" panels={[{ id: 'guild-banner', content: banner }, ...requests, { id: 'guild-rank', content: rank }]} /></div>
}
