import { BALANCE } from '../../src/game/core/balance/balance'
import * as CombatBalance from '../../src/game/core/balance/combatStats'
import { DUNGEONS, DUNGEON_ORDER } from '../../src/game/content/dungeons/dungeons'
import { ARCANE_CORE_BRANCHES, ARCANE_CORE_NODES } from '../../src/game/content/arcaneCore/arcaneCoreBranches'
import { ARCANE_CORE_FULL_RING_COST_BY_RING, ARCANE_CORE_MAJOR_COST_BY_RING, ARCANE_CORE_STANDARD_RANK_COST_BY_RING, ARCANE_CORE_TOTAL_COST_PER_CORE, ARCANE_CORE_TOTAL_TREE_COST } from '../../src/game/content/arcaneCore/arcaneCoreBalance'
import { getArcaneCoreV6CatalogEntry } from '../../src/game/content/arcaneCore/arcaneCoreV6Catalog'
import { ARCANE_CORE_MAJOR_GATES, ARCANE_CORE_RING_GATES } from '../../src/game/content/arcaneCore/arcaneCoreRings'
import { ARCANE_CORE_REWARDS } from '../../src/game/content/arcaneCore/arcaneCoreRewards'
import { ARTIFACT_EQUIPMENT_IDS } from '../../src/game/content/equipment/equipmentSets'
import { CHANNELING_DISCOVERIES } from '../../src/game/content/channeling/channelingDiscoveries'
import { MANA_PILLARS, MANA_PILLAR_IDS, PILLAR_LEVEL_COSTS } from '../../src/game/content/channeling/manaPillars'
import { FOCUS_IMPROVEMENT } from '../../src/game/content/focus/focusImprovement'
import { GUILD_REQUESTS } from '../../src/game/content/guild/guildRequests'
import { ITEMS, getResearchableItemIds } from '../../src/game/content/items/items'
import { MONSTERS, MONSTER_IDS, WHISPERING_WOODS_MONSTER_IDS, isBossMonster } from '../../src/game/content/monsters'
import { RESONANCE_METADATA, RESONANCE_TYPES } from '../../src/game/content/resonance/resonance'
import { WORLD_TIER_IDS, WORLD_TIERS } from '../../src/game/content/world-tier/worldTiers'
import { ARTIFICING_RECIPES, ARTIFICING_RECIPE_ORDER } from '../../src/game/content/recipes/artificingRecipes'
import { TRANSMUTATION_RECIPES, TRANSMUTATION_RECIPE_ORDER } from '../../src/game/content/recipes/transmutationRecipes'
import { RECIPES, RECIPE_ORDER } from '../../src/game/content/recipes/recipes'
import { SCHOOLS } from '../../src/game/content/schools/schools'
import { SPELLS } from '../../src/game/content/spells/spells'
import { STATUS_DEFINITIONS, STATUS_ORDER } from '../../src/game/content/statuses/statuses'
import { TRAIT_DEFINITIONS } from '../../src/game/content/traits/traits'
import { formatAutoCastCondition, formatCompactCombatEffect, formatCompactCombatRule, formatCompactEquipmentSpecial, formatCompactPattern, formatDuration, formatNumber, formatPercent, formatReadableId, formatRecipeUnlock, formatSignedPercent } from '../../src/game/content/presentation/balanceFormatters'
import { getAutoCastFocusCostForRank } from '../../src/game/systems/spells'
import type { ItemDefinition, ItemId } from '../../src/game/types'
import { cleanDocument, compactTable } from './markdown'

export interface BalancingDocumentInfo { stableIds: string[]; runtimeSources: string[] }
export interface BalancingDocumentBuild { docs: Map<string, string>; documentInfo: Record<string, BalancingDocumentInfo>; registries: Record<string, { count: number; ids: string[]; documents: string[]; runtimeSources: string[] }>; invariants: { recipes: number; equipment: number; equipmentRecipeCoverage: number; directEquipmentLoot: number }; canonicalLocations: Record<string, string>; mirrors: Record<string, string> }
const dash = '—'
const block = (...parts: Array<string | readonly string[]>) => parts.flatMap((part) => Array.isArray(part) ? [...part] : [part]).join('\n')
const withId = (label: string, id: string) => `${label} (${id})`
const item = (id: string) => withId(ITEMS[id as ItemId]?.name ?? formatReadableId(id), id)
const monster = (id: string) => withId(MONSTERS[id]?.name ?? formatReadableId(id), id)
const dungeonFile = (id: string) => id.split('-').map((part) => `${part[0].toUpperCase()}${part.slice(1)}`).join('_')
const compact = (values: readonly string[]) => values.length ? values.join(', ') : dash
const number = (value: number | undefined) => value === undefined ? dash : formatNumber(value)
const percent = (value: number | undefined) => value === undefined ? dash : formatSignedPercent(value)
const sell = (definition: ItemDefinition) => definition.sellValue === null ? dash : formatNumber(definition.sellValue)
const docs = new Map<string, string>(); const documentInfo: Record<string, BalancingDocumentInfo> = {}
const add = (path: string, body: string, stableIds: readonly string[], runtimeSources: readonly string[]) => { docs.set(path, cleanDocument(body)); documentInfo[path] = { stableIds: [...stableIds], runtimeSources: [...runtimeSources] } }
const materials = Object.keys(ITEMS).filter((id) => ITEMS[id as ItemId].kind === 'material') as ItemId[]
const items = Object.keys(ITEMS) as ItemId[]; const equipment = [...ARTIFACT_EQUIPMENT_IDS]; const spells = Object.keys(SPELLS); const statuses = [...STATUS_ORDER]; const traits = Object.keys(TRAIT_DEFINITIONS)
const balanceRows = (group: Record<string, unknown>) => Object.entries(group).map(([key, value]) => [formatReadableId(key), typeof value === 'number' ? formatNumber(value) : String(value)])
const invariants = { recipes: RECIPE_ORDER.length, equipment: equipment.length, equipmentRecipeCoverage: equipment.filter((id) => Object.values(ARTIFICING_RECIPES).filter((r) => r.output.itemId === id && r.output.quantity === 1).length === 1).length, directEquipmentLoot: MONSTER_IDS.reduce((n, id) => n + MONSTERS[id].loot.filter((drop) => ITEMS[drop.itemId]?.kind === 'equipment').length, 0) }
const actionRows = (monsterIds: readonly string[]) => monsterIds.flatMap((id) => Object.values(MONSTERS[id].actions).map((action) => [monster(id), withId(action.name, action.id), formatDuration(action.actionTimeMs), action.effects.map(formatCompactCombatEffect).join('; ') || dash, [...new Set(action.effects.flatMap((effect) => effect.type === 'deal-damage' ? effect.components.map((c) => formatReadableId(c.damageType)) : []))].join(' + ') || dash]))
const lootRows = (monsterIds: readonly string[]) => monsterIds.flatMap((id) => MONSTERS[id].loot.map((drop) => [monster(id), item(drop.itemId), drop.min, drop.max, formatPercent(drop.chance), formatNumber(((drop.min + drop.max) / 2) * drop.chance)]))

add('README.md', block('# SSS Wizard balancing workbook', '', 'TypeScript runtime content is authoritative. Markdown is a human review surface and is never parsed by the game.', '', 'Edit one canonical page per value domain. Export with `npm run balancing:export -- --force --prune`, then run coverage.', '', '## Workbook map', '', '- Combat: shared formulas, statuses, traits, and damage types.', '- Dungeons: each dungeon owns its monsters and loot.', '- Items: materials and all equipment stats and sell values.', '- Crafting: Artificing equipment recipes and Transmutation production recipes.', '- Magic: schools, spells, and auto-cast behavior.', '- Progression: progression systems and unlocks.', '- Economy: derived activity timing summaries.'), [], ['scripts/export-balancing-docs.ts', 'src/game/content'])
add('BALANCE_OVERVIEW.md', block('# Balance overview', '', compactTable(['Domain', 'Entries', 'Canonical page'], [['Items', items.length, 'Items/Items.md'], ['Equipment', equipment.length, 'Items/Items.md'], ['Monsters', MONSTER_IDS.length, 'Dungeons/<Dungeon>.md'], ['Dungeons', DUNGEON_ORDER.length, 'Dungeons/<Dungeon>.md'], ['Recipes', RECIPE_ORDER.length, 'Crafting/Crafting.md'], ['Spells', spells.length, 'Magic/Magic.md'], ['Statuses', statuses.length, 'Combat/Combat.md'], ['Traits', traits.length, 'Combat/Combat.md'], ['Arcane Core', ARCANE_CORE_NODES.length, 'Progression/Arcane_Core.md']]), '', 'Canonical pages contain each authored value once. Cross-page references are not numeric mirrors.'), [], ['src/game/content', 'src/game/core/balance'])
const allBalance = Object.entries(BALANCE).flatMap(([group, values]) => balanceRows(values as Record<string, unknown>).map(([key, value]) => [`${formatReadableId(group)}: ${key}`, value]))
add('Combat/Combat.md', block('# Combat', '', 'Shared combat rules and authored combat values live here. Monster-specific values belong to dungeon pages.', '', '## Values', '', compactTable(['Setting', 'Value'], allBalance), '', '## Combat bounds', '', compactTable(['Rule', 'Value', 'Notes'], [['Resistance floor', formatSignedPercent(CombatBalance.MIN_RESISTANCE), 'Shared rule'], ['Resistance cap', formatSignedPercent(CombatBalance.MAX_RESISTANCE), 'Shared rule'], ['Defense curve', formatNumber(CombatBalance.DEFENSE_K), 'Shared rule']]), '', '## Damage types', '', compactTable(['Type', 'Meaning'], ['physical', 'arcane', 'fire', 'water', 'earth', 'air'].map((type) => [formatReadableId(type), `${formatReadableId(type)} damage`])), '', '## Status effects', '', compactTable(['Status', 'Class', 'Duration', 'Max stacks', 'Effects', 'Description'], statuses.map((id) => { const s = STATUS_DEFINITIONS[id]; return [withId(s.name, id), formatReadableId(s.classification), formatDuration(s.defaultDurationMs), number(s.stacking.maxStacks), s.periodic?.effects.map(formatCompactCombatEffect).join('; ') || dash, s.description] })), '', '## Shared traits', '', compactTable(['Trait', 'Description', 'Rules'], traits.map((id) => { const t = TRAIT_DEFINITIONS[id]; return [withId(t.name, id), t.description, (t.rules ?? []).map(formatCompactCombatRule).join('; ') || dash] })), '', '## Formula notes', '', 'Direct damage resolves magnitude, modifiers, Crit, Defense, resistance, and Block before Barrier and Health. Damage over Time does not roll direct-hit Crit or Block.'), allBalance.map((r) => String(r[0])).concat(statuses, traits), ['src/game/core/balance', 'src/game/content/statuses', 'src/game/content/traits'])
add('Combat/Resonance.md', block('# Resonance Harvest', '', 'Phase 1 prototype status: Combat defeats can harvest Resonance into a dedicated persisted player resource. Resonance is not an Item, Arcane Points, Fragment, or Transmutation output.', '', '## Categories', '', compactTable(['Resonance type', 'Label'], RESONANCE_TYPES.map((type) => [withId(RESONANCE_METADATA[type].shortLabel, type), RESONANCE_METADATA[type].label])), '', '## Storage and reward seam', '', 'The player stores one whole, finite, non-negative balance per Phase 1 category. Enemy profiles are authored per enemy. The Phase 1 reward resolver exposes World Tier 1 and a 1× multiplier as a compatibility seam; World Tier state is intentionally not implemented.', '', '## Whispering Woods prototype profiles', '', compactTable(['Enemy', 'Profile'], WHISPERING_WOODS_MONSTER_IDS.map((id) => [monster(id), Object.entries(MONSTERS[id].resonanceYield ?? {}).map(([type, amount]) => `${formatNumber(amount as number)} ${formatReadableId(type)} Resonance`).join(', ')])), '', 'Unconverted enemies intentionally yield zero until a later content-conversion phase. These bootstrap values are not final balance. Phase 1 has no Resonance sinks, spending rules, Fragment conversion, or Arcane Resonance category.'), [...RESONANCE_TYPES, ...WHISPERING_WOODS_MONSTER_IDS], ['src/game/content/resonance', 'src/game/content/monsters/act0/whisperingWoods.ts', 'src/game/systems/resonance'])
for (const id of DUNGEON_ORDER) { const dungeon = DUNGEONS[id]; const roster = [...dungeon.monsterPool, dungeon.boss]; add(`Dungeons/${dungeonFile(id)}.md`, block(`# ${dungeon.name}`, '', compactTable(['Setting', 'Value'], [['Dungeon', withId(dungeon.name, id)], ['Threat requirement', number(dungeon.threatRequired)], ['Encounter delay', formatDuration(dungeon.encounterDelayMs)], ['Boss', monster(dungeon.boss)], ['Unlock', dungeon.unlock?.type === 'boss-kill' ? `Defeat ${monster(dungeon.unlock.bossId)}` : 'Available from the start']]), '', '## Monster roster', '', compactTable(['Monster', 'Type'], roster.map((monsterId) => [monster(monsterId), isBossMonster(MONSTERS[monsterId]) ? 'Boss' : 'Normal'])), '', '## Core stats', '', compactTable(['Monster', 'Type', 'HP', 'Basic damage', 'Attack time', 'Defense', 'Crit', 'Block'], roster.map((monsterId) => { const m = MONSTERS[monsterId]; return [monster(monsterId), isBossMonster(m) ? 'Boss' : 'Normal', number(m.maxHealth), number(m.basicAttackDamage), formatDuration(m.basicAttackTimeMs), number(m.defense), formatPercent(m.critChance ?? 0), formatPercent(m.blockChance ?? 0)] })), '', '## Traits and patterns', '', compactTable(['Monster', 'Traits', 'Default pattern', 'Other patterns'], roster.map((monsterId) => { const m = MONSTERS[monsterId]; return [monster(monsterId), compact(m.traitIds.map(formatReadableId)), formatCompactPattern(m.actionPatterns[m.defaultActionPatternId], m.actions), compact(Object.values(m.actionPatterns).filter((p) => p.id !== m.defaultActionPatternId).map((p) => formatReadableId(p.id)))] })), '', '## Special actions', '', compactTable(['Monster', 'Action', 'Cast time', 'Effects', 'Damage type'], actionRows(roster)), '', '## Loot', '', compactTable(['Monster', 'Item', 'Min', 'Max', 'Chance', 'Expected / kill'], lootRows(roster))), [id, ...roster], ['src/game/content/dungeons', 'src/game/content/monsters']) }
add('Items/Items.md', block('# Items', '', '## Materials', '', compactTable(['Item', 'Category', 'Tier', 'Sell', 'Source', 'Research school'], materials.map((id) => { const i = ITEMS[id]; return [item(id), formatReadableId(i.materialSubtype ?? i.category), i.materialTier ? `T${i.materialTier}` : dash, sell(i), i.source || dash, i.researchSchool ? SCHOOLS[i.researchSchool].name : dash] })), '', '## Equipment identity', '', compactTable(['Item', 'Source', 'Slot', 'Hands', 'Sell'], equipment.map((id) => { const i = ITEMS[id]; return [item(id), i.source || 'Artifact progression', formatReadableId(i.equipmentSlot ?? ''), i.weaponHands ? `${i.weaponHands}H` : dash, sell(i)] })), '', '## Equipment stats', '', compactTable(['Item', 'HP', 'Mana', 'Mana regen', 'Focus', 'Spell power', 'Basic damage', 'Defense'], equipment.map((id) => { const s = ITEMS[id].stats ?? {}; return [item(id), number(s.maxHealth), number(s.maxMana), number(s.manaRegen), number(s.maxFocus), number(s.spellPower), number(s.basicDamage), number(s.defense)] })), '', '## Equipment combat effects', '', compactTable(['Item', 'Basic speed', 'Crit', 'Block', 'Physical res', 'Arcane res', 'Fire res', 'Water res', 'Earth res', 'Air res'], equipment.map((id) => { const s = ITEMS[id].stats ?? {}; return [item(id), percent(s.basicAttackSpeedPct), percent(s.critChance), percent(s.blockChance), percent(s.resistances?.physical), percent(s.resistances?.arcane), percent(s.resistances?.fire), percent(s.resistances?.water), percent(s.resistances?.earth), percent(s.resistances?.air)] })), '', '## Special effects', '', compactTable(['Item', 'Cooldown', 'Mana cost', 'Status duration', 'Healing', 'Barrier', 'DoT', 'Special'], equipment.map((id) => { const i = ITEMS[id]; const s = i.stats ?? {}; return [item(id), percent(s.cooldownRecoveryPct), number(s.manaCostReductionPct), percent(s.statusDurationPct), percent(s.healingDonePct), percent(s.barrierPowerPct), percent(s.damageOverTimePct), formatCompactEquipmentSpecial(i) || dash] }))), items, ['src/game/content/items', 'src/game/content/equipment'])
const recipeIngredients = (source: typeof ARTIFICING_RECIPES | typeof TRANSMUTATION_RECIPES, order: readonly string[]) => order.flatMap((id) => source[id as keyof typeof source].ingredients.map((i) => [withId(source[id as keyof typeof source].name, id), item(i.itemId), formatNumber(i.quantity)]))
add('Crafting/Crafting.md', block('# Crafting', '', 'Artificing forges magical Artifacts. Transmutation produces elemental and material outputs.', '', '## Artificing', '', compactTable(['Recipe', 'Output', 'Origin', 'Craft time', 'Unlock'], ARTIFICING_RECIPE_ORDER.map((id) => { const r = ARTIFICING_RECIPES[id]; return [withId(r.name, id), item(r.output.itemId), r.sourceDungeonId ? DUNGEONS[r.sourceDungeonId].name : 'Starter Artifact', 'Manual, 5 seconds', formatRecipeUnlock(r.unlock)] })), '', compactTable(['Recipe', 'Ingredient', 'Qty'], recipeIngredients(ARTIFICING_RECIPES, ARTIFICING_RECIPE_ORDER)), '', '## Transmutation', '', compactTable(['Recipe', 'Output', 'Qty', 'Time', 'Mana', 'Unlock'], TRANSMUTATION_RECIPE_ORDER.map((id) => { const r = TRANSMUTATION_RECIPES[id]; return [withId(r.name, id), item(r.output.itemId), formatNumber(r.output.quantity), formatDuration(r.baseDurationMs), formatNumber(r.manaCost), formatRecipeUnlock(r.unlock)] })), '', compactTable(['Recipe', 'Ingredient', 'Qty'], recipeIngredients(TRANSMUTATION_RECIPES, TRANSMUTATION_RECIPE_ORDER))), RECIPE_ORDER, ['src/game/content/recipes'])
add('Magic/Magic.md', block('# Magic', '', '## Schools', '', compactTable(['School', 'ID', 'Fragment', 'Tagline'], Object.values(SCHOOLS).map((s) => [s.name, s.id, item(s.fragment), s.tagline])), '', '## Spells', '', compactTable(['Spell', 'School', 'Unlock', 'Mana', 'Cooldown', 'Damage', 'Type', 'Status', 'Auto-cast'], spells.map((id) => { const s = SPELLS[id]; const damage = s.effects.filter((e) => e.type === 'deal-damage'); return [withId(s.name, id), SCHOOLS[s.school].name, number(s.unlockLevel), number(s.manaCost), formatDuration(s.cooldownMs), damage.map(formatCompactCombatEffect).join('; ') || dash, [...new Set(damage.flatMap((e) => e.type === 'deal-damage' ? e.components.map((c) => formatReadableId(c.damageType)) : []))].join(' + ') || dash, s.effects.filter((e) => e.type === 'apply-status').map(formatCompactCombatEffect).join('; ') || dash, formatAutoCastCondition(s.autoCondition)] })), '', '## Auto-cast focus costs', '', compactTable(['Rank', 'Focus'], Array.from({ length: 8 }, (_, i) => [i + 1, formatNumber(getAutoCastFocusCostForRank((i + 1) as 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8))]))), spells.concat(Object.keys(SCHOOLS)), ['src/game/content/spells', 'src/game/content/schools'])
add('Progression/Channeling.md', block('# Channeling', '', compactTable(['Setting', 'Value'], balanceRows(BALANCE.channeling as Record<string, unknown>)), '', '## Discoveries', '', compactTable(['Discovery', 'Unlock', 'Effect'], CHANNELING_DISCOVERIES.map((d) => [withId(d.name, d.id), d.conditionDescription, d.rewardDescription])), '', '## Mana pillars', '', compactTable(['Pillar', 'Level', 'Cost', 'Effect'], MANA_PILLAR_IDS.flatMap((id) => Object.keys(PILLAR_LEVEL_COSTS).map((level) => [withId(MANA_PILLARS[id].name, id), level, JSON.stringify(PILLAR_LEVEL_COSTS[Number(level) as keyof typeof PILLAR_LEVEL_COSTS]), `${MANA_PILLARS[id].effectLabel}: ${MANA_PILLARS[id].valuePerLevel}`])))), MANA_PILLAR_IDS.concat(CHANNELING_DISCOVERIES.map((d) => d.id)), ['src/game/content/channeling', 'src/game/core/balance'])
add('Progression/Research.md', block('# Research', compactTable(['Setting', 'Value'], balanceRows(BALANCE.research as Record<string, unknown>)), '', compactTable(['Item', 'School'], getResearchableItemIds().map((id) => [item(id), SCHOOLS[ITEMS[id].researchSchool!].name]))), getResearchableItemIds(), ['src/game/core/balance', 'src/game/content/items'])
add('Progression/Focus.md', block('# Focus', '', compactTable(['Setting', 'Value'], [['Starting capacity', BALANCE.focus.startingMax], ['Forest Heart bonus', BALANCE.focus.forestHeartBonus], ['Guild Apprentice bonus', BALANCE.focus.guildApprenticeBonus], [FOCUS_IMPROVEMENT.name, FOCUS_IMPROVEMENT.focusPerLevel]]), '', compactTable(['System', 'Action', 'Cost'], [['Channeling', 'Arcane Echo', BALANCE.channeling.echoFocusCost], ['Research', 'Echo assignment', BALANCE.research.echoFocusCost], ['Transmutation', 'Echo assignment', BALANCE.transmutation.echoFocusCost]])), Object.keys(BALANCE.focus).map((key) => `focus.${key}`).concat(FOCUS_IMPROVEMENT.id), ['src/game/core/balance', 'src/game/content/focus'])
const arcaneCoreIds = ARCANE_CORE_BRANCHES.flatMap((branch) => [branch.id, ...branch.nodes.map((node) => node.id)]).concat(DUNGEON_ORDER)
const arcaneCoreRingSlots: Record<string, number> = {}
const arcaneCoreRows = ARCANE_CORE_NODES.map((node) => {
  const slotIndex = node.nodeType === 'major' ? 9 : (arcaneCoreRingSlots[`${node.branchId}:${node.ring}`] = (arcaneCoreRingSlots[`${node.branchId}:${node.ring}`] ?? 0) + 1)
  const slot = slotIndex === 9 ? 'M' : `S${slotIndex}`
  const entry = getArcaneCoreV6CatalogEntry(node.branchId, node.ring, slotIndex)
  const cost = node.nodeType === 'major' ? ARCANE_CORE_MAJOR_COST_BY_RING[node.ring] : ARCANE_CORE_STANDARD_RANK_COST_BY_RING[node.ring]
  return [node.branchId, node.id, node.ring, slot, entry?.name ?? node.name, entry?.type ?? formatReadableId(node.nodeType), node.maxRank, cost, entry?.description ?? node.description]
})
add('Progression/Arcane_Core.md', block('# Arcane Core', '', 'Permanent specialization grows through combat-earned Arcane Points. Points are a capped wallet; node ranks are permanent and refund using their authored Ring cost.', '', '## Branches', '', compactTable(['Branch', 'ID', 'Purchasable nodes'], ARCANE_CORE_BRANCHES.map((branch) => [branch.name, branch.id, branch.nodes.length])), '', '## Progression', '', compactTable(['Setting', 'Value'], [['Starting Arcane Points', 0], ['Maximum Arcane Points', ARCANE_CORE_TOTAL_TREE_COST], ['Cores', 4], ['Rings per Core', 8], ['Nodes per Ring', 9], ['Total authored nodes', ARCANE_CORE_NODES.length], ['Full Core cost', ARCANE_CORE_TOTAL_COST_PER_CORE], ['Full tree cost', ARCANE_CORE_TOTAL_TREE_COST]]), '', '## Ring costs and gates', '', compactTable(['Ring', 'Standard rank cost', 'Major cost', 'Full Ring cost', 'Previous-Ring standard ranks', 'Major standard ranks'], ARCANE_CORE_BRANCHES[0].nodes.slice(0, 8).map((_, index) => { const ring = (index + 1) as 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8; return [ring, ARCANE_CORE_STANDARD_RANK_COST_BY_RING[ring], ARCANE_CORE_MAJOR_COST_BY_RING[ring], ARCANE_CORE_FULL_RING_COST_BY_RING[ring], ARCANE_CORE_RING_GATES[ring], ARCANE_CORE_MAJOR_GATES[ring]] })), '', '## Node catalog', '', compactTable(['Branch', 'Node', 'Ring', 'Slot', 'Name', 'Type', 'Max rank', 'Rank cost', 'Effect'], arcaneCoreRows), '', '## Combat rewards', '', compactTable(['Dungeon', 'Normal kill points', 'Boss kill points'], DUNGEON_ORDER.map((id) => [withId(DUNGEONS[id].name, id), ARCANE_CORE_REWARDS[id].normalKillPoints, ARCANE_CORE_REWARDS[id].bossKillPoints])), '', 'Normal and boss Arcane Point rewards are repeatable and resolved from centralized dungeon configuration through live Combat and Offline Bank.'), arcaneCoreIds, ['src/game/content/arcaneCore', 'src/game/systems/arcaneCore', 'src/game/systems/combat']);
const guildRanks = compactTable(['Rank', 'Requirement', 'Reward'], [['Outsider', 'Before Forest Heart clear', dash], ['Initiate', 'Defeat Forest Heart', 'Guild requests'], ['Apprentice', 'Complete authored requests', `+${BALANCE.focus.guildApprenticeBonus} Focus`]])
const guildRequests = compactTable(['Request', 'Item', 'Qty', 'Reputation'], Object.values(GUILD_REQUESTS).map((r) => [withId(r.name, r.id), 'itemId' in r ? item(r.itemId) : dash, 'target' in r ? r.target : dash, r.reputation]))
const unlockRows = [...DUNGEON_ORDER.map((id) => [withId(DUNGEONS[id].name, id), DUNGEONS[id].unlock?.type === 'boss-kill' ? `Defeat ${monster(DUNGEONS[id].unlock.bossId)}` : 'Start']), ...RECIPE_ORDER.filter((id) => RECIPES[id].unlock.type !== 'always').map((id) => [withId(RECIPES[id].name, id), formatRecipeUnlock(RECIPES[id].unlock)])]
add('Progression/Guild_And_Unlocks.md', block('# Guild and unlocks', '', guildRanks, '', guildRequests, '', '## Dungeon and recipe unlocks', '', compactTable(['Content', 'Requirement'], unlockRows)), Object.keys(GUILD_REQUESTS).concat(DUNGEON_ORDER, RECIPE_ORDER), ['src/game/content/guild', 'src/game/content/dungeons', 'src/game/content/recipes'])
add('Economy/Economy.md', block('# Economy', '', 'Item sell values are canonical in `Items/Items.md`; recipe costs and times are canonical in `Crafting/Crafting.md`.', '', compactTable(['Activity', 'Summary'], [['Research', 'See Progression/Research.md'], ['Production', 'See Crafting/Crafting.md']])), [], ['src/game/content', 'src/game/core/balance'])
add('Combat/Resonance.md', block('# Resonance Harvest', '', 'Combat defeats can harvest Resonance into a dedicated persisted player resource. Resonance is not an Item, Arcane Points, Fragment, or Transmutation output.', '', '## Categories', '', compactTable(['Resonance type', 'Label'], RESONANCE_TYPES.map((type) => [withId(RESONANCE_METADATA[type].shortLabel, type), RESONANCE_METADATA[type].label])), '', '## Storage and reward resolution', '', 'The player stores one whole, finite, non-negative balance per category. Enemy profiles are authored per enemy. Final reward is the authored base yield multiplied by the active encounter World Tier Resonance multiplier, then granted through the canonical combat finish path with saturation-safe deltas.', '', '## Whispering Woods prototype profiles', '', compactTable(['Enemy', 'Profile'], WHISPERING_WOODS_MONSTER_IDS.map((id) => [monster(id), Object.entries(MONSTERS[id].resonanceYield ?? {}).map(([type, amount]) => `${formatNumber(amount as number)} ${formatReadableId(type)} Resonance`).join(', ')])), '', 'Unconverted enemies intentionally yield zero. These bootstrap values are not final balance. World Tier multipliers and unlock behavior are canonical in `Combat/World_Tiers.md`.'), [...RESONANCE_TYPES, ...WHISPERING_WOODS_MONSTER_IDS], ['src/game/content/resonance', 'src/game/content/monsters/act0/whisperingWoods.ts', 'src/game/systems/resonance'])
const combatWithWorldTierLootRule = `${docs.get('Combat/Combat.md') ?? ''}\n## World Tier loot rule\n\nMonster and boss loot tables author the WT1/base material quantity and drop chance. World Tier does not change the authored chance; when a material drop succeeds, its rolled quantity is multiplied by the encounter World Tier material-loot multiplier. The canonical WT1-WT5 values and unlock policy are documented in [World Tiers](World_Tiers.md).`
add('Combat/Combat.md', combatWithWorldTierLootRule, documentInfo['Combat/Combat.md']?.stableIds ?? [], documentInfo['Combat/Combat.md']?.runtimeSources ?? [])
add('Combat/World_Tiers.md', block('# World Tiers', '', 'World Tier is a global persisted combat setting. It is captured on enemy spawn so an active encounter remains stable if the profile setting changes later. Normal tier changes require no active combat; developer actions may force a tier for testing.', '', 'These WT1-WT5 values are Phase 4B prototype placeholders, not final combat balance. They are authored in `src/game/content/world-tier/worldTiers.ts` and must remain the runtime source of truth.', '', '## Authored definitions', '', compactTable(['Tier', 'Enemy health', 'Enemy damage', 'Enemy defense', 'Resonance rewards', 'Material loot quantity', 'Unlock'], WORLD_TIER_IDS.map((tier) => { const definition = WORLD_TIERS[tier]; return [`WT${tier} (${definition.name})`, `x${definition.enemyHealthMultiplier.toFixed(2)}`, `x${definition.enemyDamageMultiplier.toFixed(2)}`, `x${definition.enemyDefenseMultiplier.toFixed(2)}`, `x${definition.resonanceRewardMultiplier.toFixed(2)}`, `x${definition.itemLootQuantityMultiplier.toFixed(2)}`, tier === 1 ? 'Available by default' : tier === 2 ? 'First defeat of Archmage Edrin Shade' : 'Future progression; currently locked'] })), '', 'Resonance-specific presentation and reward notes cross-reference this page; this page owns the World Tier multiplier values.', '', '## Runtime rules', '', '- Enemy health is rounded at spawn with a minimum of 1.', '- Enemy outgoing damage uses the shared single-application World Tier multiplier.', '- Defense rating is scaled before the normal defense curve.', '- Authored material drop chance is unchanged by World Tier.', '- A successful authored base material quantity is multiplied by the encounter tier material loot quantity multiplier and rounded to the final granted quantity. Inventory, loot events, Combat Loot Reveal, and Offline Bank reports all consume that final quantity.', '- Life Essence and Artifact Essence remain inventory material Items. Monster and boss loot remains material-only.', '- Arcane Points, Threat, kill counts, request progress, boss flags, and other progression credit are not multiplied by World Tier.', '- Offline Bank and Fast Resolve reuse the canonical combat and loot resolution path; they do not have separate World Tier formulas.', '- The enemy captured `enemyWorldTier` is authoritative for both Resonance and item rewards until the encounter resolves. Abandoning an encounter still grants no rewards.', '- WT2 unlocks on the first Archmage Edrin Shade defeat and does not auto-select WT2. WT3-WT5 have no temporary Act or Dungeon gate; their normal-profile copy is "Unlocks through future progression."', '', '## Non-final scope', '', 'This page documents the architecture and prototype values only. It does not decide final Acts, Zones, Dungeons, enemy roles, or final World Tier balance.'), WORLD_TIER_IDS.map((tier) => `world-tier-${tier}`), ['src/game/content/world-tier', 'src/game/systems/world-tier', 'src/game/systems/combat', 'src/game/systems/loot'])
const registry = (ids: readonly string[], documents: readonly string[], runtimeSources: readonly string[]) => ({ count: ids.length, ids: [...ids], documents: [...documents], runtimeSources: [...runtimeSources] })
export const buildBalancingDocuments = (): BalancingDocumentBuild => ({ docs, documentInfo, registries: { items: registry(items, ['Items/Items.md'], ['src/game/content/items']), equipment: registry(equipment, ['Items/Items.md'], ['src/game/content/items', 'src/game/content/equipment']), monsters: registry(MONSTER_IDS, DUNGEON_ORDER.map((id) => `Dungeons/${dungeonFile(id)}.md`), ['src/game/content/monsters']), dungeons: registry(DUNGEON_ORDER, DUNGEON_ORDER.map((id) => `Dungeons/${dungeonFile(id)}.md`), ['src/game/content/dungeons']), recipes: registry(RECIPE_ORDER, ['Crafting/Crafting.md'], ['src/game/content/recipes']), spells: registry(spells, ['Magic/Magic.md'], ['src/game/content/spells']), statuses: registry(statuses, ['Combat/Combat.md'], ['src/game/content/statuses']), traits: registry(traits, ['Combat/Combat.md'], ['src/game/content/traits']), arcaneCore: registry(arcaneCoreIds, ['Progression/Arcane_Core.md'], ['src/game/content/arcaneCore', 'src/game/systems/arcaneCore', 'src/game/systems/combat']) }, invariants, canonicalLocations: { combat: 'Combat/Combat.md', dungeons: 'Dungeons/{Dungeon}.md', items: 'Items/Items.md', crafting: 'Crafting/Crafting.md', magic: 'Magic/Magic.md', progression: 'Progression/{System}.md', economy: 'Economy/Economy.md' }, mirrors: {} })
