import { BALANCE } from '../../src/game/core/balance/balance'
import * as CombatBalance from '../../src/game/core/balance/combatStats'
import { DUNGEONS, DUNGEON_ORDER } from '../../src/game/content/dungeons/dungeons'
import { ARTIFACT_EQUIPMENT_IDS, DUNGEON_EQUIPMENT_BY_DUNGEON } from '../../src/game/content/equipment/equipmentSets'
import { CHANNELING_DISCOVERIES } from '../../src/game/content/channeling/channelingDiscoveries'
import { MANA_PILLARS, MANA_PILLAR_IDS, PILLAR_LEVEL_COSTS } from '../../src/game/content/channeling/manaPillars'
import { FOCUS_IMPROVEMENT } from '../../src/game/content/focus/focusImprovement'
import { GUILD_REQUESTS } from '../../src/game/content/guild/guildRequests'
import { ITEMS, getResearchableItemIds } from '../../src/game/content/items/items'
import { MONSTERS, MONSTER_IDS, isBossMonster } from '../../src/game/content/monsters'
import { ARTIFICING_RECIPES, ARTIFICING_RECIPE_ORDER } from '../../src/game/content/recipes/artificingRecipes'
import { TRANSMUTATION_RECIPES, TRANSMUTATION_RECIPE_ORDER } from '../../src/game/content/recipes/transmutationRecipes'
import { RECIPES, RECIPE_ORDER } from '../../src/game/content/recipes/recipes'
import { SCHOOLS } from '../../src/game/content/schools/schools'
import { SPELLS } from '../../src/game/content/spells/spells'
import { STATUS_DEFINITIONS, STATUS_ORDER } from '../../src/game/content/statuses/statuses'
import { TRAIT_DEFINITIONS } from '../../src/game/content/traits/traits'
import { formatAutoCastCondition, formatCompactCombatEffect, formatCompactCombatRule, formatCompactEquipmentSpecial, formatCompactPattern, formatDuration, formatNumber, formatPercent, formatReadableId, formatRecipeUnlock, formatSignedPercent } from '../../src/game/content/presentation/balanceFormatters'
import { getAutoCastFocusCostForRank } from '../../src/game/systems/spells'
import type { ItemDefinition, ItemId } from '../../src/game/types'
import { cleanDocument, compactTable } from './markdown'

export interface BalancingDocumentInfo { stableIds: string[]; runtimeSources: string[] }
export interface BalancingDocumentBuild { docs: Map<string, string>; documentInfo: Record<string, BalancingDocumentInfo>; registries: Record<string, { count: number; ids: string[]; documents: string[]; runtimeSources: string[] }>; invariants: { recipes: number; equipment: number; equipmentRecipeCoverage: number; directEquipmentLoot: number }; canonicalLocations: Record<string, string>; mirrors: Record<string, string> }
const dash = '—'
const block = (...parts: Array<string | readonly string[]>) => parts.flatMap((part) => Array.isArray(part) ? [...part] : [part]).join('\n')
const withId = (label: string, id: string) => `${label} (${id})`
const item = (id: string) => withId(ITEMS[id as ItemId]?.name ?? formatReadableId(id), id)
const monster = (id: string) => withId(MONSTERS[id]?.name ?? formatReadableId(id), id)
const dungeonFile = (id: string) => id === 'whispering-woods' ? 'Whispering_Woods' : id === 'howling-den' ? 'Howling_Den' : 'Abandoned_Catacombs'
const compact = (values: readonly string[]) => values.length ? values.join(', ') : dash
const number = (value: number | undefined) => value === undefined ? dash : formatNumber(value)
const percent = (value: number | undefined) => value === undefined ? dash : formatSignedPercent(value)
const sell = (definition: ItemDefinition) => definition.sellValue === null ? dash : formatNumber(definition.sellValue)
const docs = new Map<string, string>(); const documentInfo: Record<string, BalancingDocumentInfo> = {}
const add = (path: string, body: string, stableIds: readonly string[], runtimeSources: readonly string[]) => { docs.set(path, cleanDocument(body)); documentInfo[path] = { stableIds: [...stableIds], runtimeSources: [...runtimeSources] } }
const materials = Object.keys(ITEMS).filter((id) => ITEMS[id as ItemId].kind === 'material') as ItemId[]
const items = Object.keys(ITEMS) as ItemId[]; const equipment = [...ARTIFACT_EQUIPMENT_IDS, ...Object.values(DUNGEON_EQUIPMENT_BY_DUNGEON).flat()]; const spells = Object.keys(SPELLS); const statuses = [...STATUS_ORDER]; const traits = Object.keys(TRAIT_DEFINITIONS)
const balanceRows = (group: Record<string, unknown>) => Object.entries(group).map(([key, value]) => [formatReadableId(key), typeof value === 'number' ? formatNumber(value) : String(value)])
const invariants = { recipes: RECIPE_ORDER.length, equipment: equipment.length, equipmentRecipeCoverage: equipment.filter((id) => Object.values(ARTIFICING_RECIPES).filter((r) => r.output.itemId === id && r.output.quantity === 1).length === 1).length, directEquipmentLoot: MONSTER_IDS.reduce((n, id) => n + MONSTERS[id].loot.filter((drop) => ITEMS[drop.itemId]?.kind === 'equipment').length, 0) }
const actionRows = (monsterIds: readonly string[]) => monsterIds.flatMap((id) => Object.values(MONSTERS[id].actions).map((action) => [monster(id), withId(action.name, action.id), formatDuration(action.actionTimeMs), action.effects.map(formatCompactCombatEffect).join('; ') || dash, [...new Set(action.effects.flatMap((effect) => effect.type === 'deal-damage' ? effect.components.map((c) => formatReadableId(c.damageType)) : []))].join(' + ') || dash]))
const lootRows = (monsterIds: readonly string[]) => monsterIds.flatMap((id) => MONSTERS[id].loot.map((drop) => [monster(id), item(drop.itemId), drop.min, drop.max, formatPercent(drop.chance), formatNumber(((drop.min + drop.max) / 2) * drop.chance)]))

add('README.md', block('# SSS Wizard balancing workbook', '', 'TypeScript runtime content is authoritative. Markdown is a human review surface and is never parsed by the game.', '', 'Edit one canonical page per value domain. Export with `npm run balancing:export -- --force --prune`, then run coverage.', '', '## Workbook map', '', '- Combat: shared formulas, statuses, traits, and damage types.', '- Dungeons: each dungeon owns its monsters and loot.', '- Items: materials and all equipment stats and sell values.', '- Crafting: Artificing equipment recipes and Transmutation production recipes.', '- Magic: schools, spells, and auto-cast behavior.', '- Progression: progression systems and unlocks.', '- Economy: derived activity timing summaries.'), [], ['scripts/export-balancing-docs.ts', 'src/game/content'])
add('BALANCE_OVERVIEW.md', block('# Balance overview', '', compactTable(['Domain', 'Entries', 'Canonical page'], [['Items', items.length, 'Items/Items.md'], ['Equipment', equipment.length, 'Items/Items.md'], ['Monsters', MONSTER_IDS.length, 'Dungeons/<Dungeon>.md'], ['Dungeons', DUNGEON_ORDER.length, 'Dungeons/<Dungeon>.md'], ['Recipes', RECIPE_ORDER.length, 'Crafting/Crafting.md'], ['Spells', spells.length, 'Magic/Magic.md'], ['Statuses', statuses.length, 'Combat/Combat.md'], ['Traits', traits.length, 'Combat/Combat.md']]), '', 'Canonical pages contain each authored value once. Cross-page references are not numeric mirrors.'), [], ['src/game/content', 'src/game/core/balance'])
const allBalance = Object.entries(BALANCE).flatMap(([group, values]) => balanceRows(values as Record<string, unknown>).map(([key, value]) => [`${formatReadableId(group)}: ${key}`, value]))
add('Combat/Combat.md', block('# Combat', '', 'Shared combat rules and authored combat values live here. Monster-specific values belong to dungeon pages.', '', '## Values', '', compactTable(['Setting', 'Value'], allBalance), '', '## Combat bounds', '', compactTable(['Rule', 'Value', 'Notes'], [['Resistance floor', formatSignedPercent(CombatBalance.MIN_RESISTANCE), 'Shared rule'], ['Resistance cap', formatSignedPercent(CombatBalance.MAX_RESISTANCE), 'Shared rule'], ['Defense curve', formatNumber(CombatBalance.DEFENSE_K), 'Shared rule']]), '', '## Damage types', '', compactTable(['Type', 'Meaning'], ['physical', 'arcane', 'fire', 'water', 'earth', 'air'].map((type) => [formatReadableId(type), `${formatReadableId(type)} damage`])), '', '## Status effects', '', compactTable(['Status', 'Class', 'Duration', 'Max stacks', 'Effects', 'Description'], statuses.map((id) => { const s = STATUS_DEFINITIONS[id]; return [withId(s.name, id), formatReadableId(s.classification), formatDuration(s.defaultDurationMs), number(s.stacking.maxStacks), s.periodic?.effects.map(formatCompactCombatEffect).join('; ') || dash, s.description] })), '', '## Shared traits', '', compactTable(['Trait', 'Description', 'Rules'], traits.map((id) => { const t = TRAIT_DEFINITIONS[id]; return [withId(t.name, id), t.description, (t.rules ?? []).map(formatCompactCombatRule).join('; ') || dash] })), '', '## Formula notes', '', 'Direct damage resolves magnitude, modifiers, Crit, Defense, resistance, and Block before Barrier and Health. Damage over Time does not roll direct-hit Crit or Block.'), allBalance.map((r) => String(r[0])).concat(statuses, traits), ['src/game/core/balance', 'src/game/content/statuses', 'src/game/content/traits'])
for (const id of DUNGEON_ORDER) { const dungeon = DUNGEONS[id]; const roster = [...dungeon.monsterPool, dungeon.boss]; add(`Dungeons/${dungeonFile(id)}.md`, block(`# ${dungeon.name}`, '', compactTable(['Setting', 'Value'], [['Dungeon', withId(dungeon.name, id)], ['Threat requirement', number(dungeon.threatRequired)], ['Encounter delay', formatDuration(dungeon.encounterDelayMs)], ['Boss', monster(dungeon.boss)], ['Unlock', dungeon.unlock?.type === 'boss-kill' ? `Defeat ${monster(dungeon.unlock.bossId)}` : 'Available from the start']]), '', '## Monster roster', '', compactTable(['Monster', 'Type'], roster.map((monsterId) => [monster(monsterId), isBossMonster(MONSTERS[monsterId]) ? 'Boss' : 'Normal'])), '', '## Core stats', '', compactTable(['Monster', 'Type', 'HP', 'Basic damage', 'Attack time', 'Defense', 'Crit', 'Block'], roster.map((monsterId) => { const m = MONSTERS[monsterId]; return [monster(monsterId), isBossMonster(m) ? 'Boss' : 'Normal', number(m.maxHealth), number(m.basicAttackDamage), formatDuration(m.basicAttackTimeMs), number(m.defense), formatPercent(m.critChance ?? 0), formatPercent(m.blockChance ?? 0)] })), '', '## Traits and patterns', '', compactTable(['Monster', 'Traits', 'Default pattern', 'Other patterns'], roster.map((monsterId) => { const m = MONSTERS[monsterId]; return [monster(monsterId), compact(m.traitIds.map(formatReadableId)), formatCompactPattern(m.actionPatterns[m.defaultActionPatternId], m.actions), compact(Object.values(m.actionPatterns).filter((p) => p.id !== m.defaultActionPatternId).map((p) => formatReadableId(p.id)))] })), '', '## Special actions', '', compactTable(['Monster', 'Action', 'Cast time', 'Effects', 'Damage type'], actionRows(roster)), '', '## Loot', '', compactTable(['Monster', 'Item', 'Min', 'Max', 'Chance', 'Expected / kill'], lootRows(roster))), [id, ...roster], ['src/game/content/dungeons', 'src/game/content/monsters']) }
const origin = (id: string) => Object.entries(DUNGEON_EQUIPMENT_BY_DUNGEON).find(([, ids]) => ids.includes(id as ItemId))?.[0]
add('Items/Items.md', block('# Items', '', '## Materials', '', compactTable(['Item', 'Category', 'Tier', 'Sell', 'Source', 'Research school'], materials.map((id) => { const i = ITEMS[id]; return [item(id), formatReadableId(i.materialSubtype ?? i.category), i.materialTier ? `T${i.materialTier}` : dash, sell(i), i.source || dash, i.researchSchool ? SCHOOLS[i.researchSchool].name : dash] })), '', '## Equipment identity', '', compactTable(['Item', 'Dungeon', 'Slot', 'Hands', 'Sell'], equipment.map((id) => { const i = ITEMS[id]; return [item(id), origin(id) ? DUNGEONS[origin(id)!].name : dash, formatReadableId(i.equipmentSlot ?? ''), i.weaponHands ? `${i.weaponHands}H` : dash, sell(i)] })), '', '## Equipment stats', '', compactTable(['Item', 'HP', 'Mana', 'Mana regen', 'Focus', 'Spell power', 'Basic damage', 'Defense'], equipment.map((id) => { const s = ITEMS[id].stats ?? {}; return [item(id), number(s.maxHealth), number(s.maxMana), number(s.manaRegen), number(s.maxFocus), number(s.spellPower), number(s.basicDamage), number(s.defense)] })), '', '## Equipment combat effects', '', compactTable(['Item', 'Basic speed', 'Crit', 'Block', 'Physical res', 'Arcane res', 'Fire res', 'Water res', 'Earth res', 'Air res'], equipment.map((id) => { const s = ITEMS[id].stats ?? {}; return [item(id), percent(s.basicAttackSpeedPct), percent(s.critChance), percent(s.blockChance), percent(s.resistances?.physical), percent(s.resistances?.arcane), percent(s.resistances?.fire), percent(s.resistances?.water), percent(s.resistances?.earth), percent(s.resistances?.air)] })), '', '## Special effects', '', compactTable(['Item', 'Cooldown', 'Mana cost', 'Status duration', 'Healing', 'Barrier', 'DoT', 'Special'], equipment.map((id) => { const i = ITEMS[id]; const s = i.stats ?? {}; return [item(id), percent(s.cooldownRecoveryPct), number(s.manaCostReductionPct), percent(s.statusDurationPct), percent(s.healingDonePct), percent(s.barrierPowerPct), percent(s.damageOverTimePct), formatCompactEquipmentSpecial(i) || dash] }))), items, ['src/game/content/items', 'src/game/content/equipment'])
const recipeIngredients = (source: typeof ARTIFICING_RECIPES | typeof TRANSMUTATION_RECIPES, order: readonly string[]) => order.flatMap((id) => source[id as keyof typeof source].ingredients.map((i) => [withId(source[id as keyof typeof source].name, id), item(i.itemId), formatNumber(i.quantity)]))
add('Crafting/Crafting.md', block('# Crafting', '', 'Artificing creates finished Equipment. Transmutation produces elemental and material outputs.', '', '## Artificing', '', compactTable(['Recipe', 'Output', 'Origin', 'Craft time', 'Unlock'], ARTIFICING_RECIPE_ORDER.map((id) => { const r = ARTIFICING_RECIPES[id]; return [withId(r.name, id), item(r.output.itemId), r.sourceDungeonId ? DUNGEONS[r.sourceDungeonId].name : 'Starter Artifact', 'Manual, 5 seconds', formatRecipeUnlock(r.unlock)] })), '', compactTable(['Recipe', 'Ingredient', 'Qty'], recipeIngredients(ARTIFICING_RECIPES, ARTIFICING_RECIPE_ORDER)), '', '## Transmutation', '', compactTable(['Recipe', 'Output', 'Qty', 'Time', 'Mana', 'Unlock'], TRANSMUTATION_RECIPE_ORDER.map((id) => { const r = TRANSMUTATION_RECIPES[id]; return [withId(r.name, id), item(r.output.itemId), formatNumber(r.output.quantity), formatDuration(r.baseDurationMs), formatNumber(r.manaCost), formatRecipeUnlock(r.unlock)] })), '', compactTable(['Recipe', 'Ingredient', 'Qty'], recipeIngredients(TRANSMUTATION_RECIPES, TRANSMUTATION_RECIPE_ORDER))), RECIPE_ORDER, ['src/game/content/recipes'])
add('Magic/Magic.md', block('# Magic', '', '## Schools', '', compactTable(['School', 'ID', 'Fragment', 'Tagline'], Object.values(SCHOOLS).map((s) => [s.name, s.id, item(s.fragment), s.tagline])), '', '## Spells', '', compactTable(['Spell', 'School', 'Unlock', 'Mana', 'Cooldown', 'Damage', 'Type', 'Status', 'Auto-cast'], spells.map((id) => { const s = SPELLS[id]; const damage = s.effects.filter((e) => e.type === 'deal-damage'); return [withId(s.name, id), SCHOOLS[s.school].name, number(s.unlockLevel), number(s.manaCost), formatDuration(s.cooldownMs), damage.map(formatCompactCombatEffect).join('; ') || dash, [...new Set(damage.flatMap((e) => e.type === 'deal-damage' ? e.components.map((c) => formatReadableId(c.damageType)) : []))].join(' + ') || dash, s.effects.filter((e) => e.type === 'apply-status').map(formatCompactCombatEffect).join('; ') || dash, formatAutoCastCondition(s.autoCondition)] })), '', '## Auto-cast focus costs', '', compactTable(['Rank', 'Focus'], Array.from({ length: 8 }, (_, i) => [i + 1, formatNumber(getAutoCastFocusCostForRank((i + 1) as 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8))]))), spells.concat(Object.keys(SCHOOLS)), ['src/game/content/spells', 'src/game/content/schools'])
add('Progression/Channeling.md', block('# Channeling', '', compactTable(['Setting', 'Value'], balanceRows(BALANCE.channeling as Record<string, unknown>)), '', '## Discoveries', '', compactTable(['Discovery', 'Unlock', 'Effect'], CHANNELING_DISCOVERIES.map((d) => [withId(d.name, d.id), d.conditionDescription, d.rewardDescription])), '', '## Mana pillars', '', compactTable(['Pillar', 'Level', 'Cost', 'Effect'], MANA_PILLAR_IDS.flatMap((id) => Object.keys(PILLAR_LEVEL_COSTS).map((level) => [withId(MANA_PILLARS[id].name, id), level, JSON.stringify(PILLAR_LEVEL_COSTS[Number(level) as keyof typeof PILLAR_LEVEL_COSTS]), `${MANA_PILLARS[id].effectLabel}: ${MANA_PILLARS[id].valuePerLevel}`])))), MANA_PILLAR_IDS.concat(CHANNELING_DISCOVERIES.map((d) => d.id)), ['src/game/content/channeling', 'src/game/core/balance'])
add('Progression/Research.md', block('# Research', compactTable(['Setting', 'Value'], balanceRows(BALANCE.research as Record<string, unknown>)), '', compactTable(['Item', 'School'], getResearchableItemIds().map((id) => [item(id), SCHOOLS[ITEMS[id].researchSchool!].name]))), getResearchableItemIds(), ['src/game/core/balance', 'src/game/content/items'])
add('Progression/Focus.md', block('# Focus', '', compactTable(['Setting', 'Value'], [['Starting capacity', BALANCE.focus.startingMax], ['Forest Heart bonus', BALANCE.focus.forestHeartBonus], ['Guild Apprentice bonus', BALANCE.focus.guildApprenticeBonus], [FOCUS_IMPROVEMENT.name, FOCUS_IMPROVEMENT.focusPerLevel]]), '', compactTable(['System', 'Action', 'Cost'], [['Channeling', 'Arcane Echo', BALANCE.channeling.echoFocusCost], ['Research', 'Echo assignment', BALANCE.research.echoFocusCost], ['Transmutation', 'Echo assignment', BALANCE.transmutation.echoFocusCost]])), Object.keys(BALANCE.focus).map((key) => `focus.${key}`).concat(FOCUS_IMPROVEMENT.id), ['src/game/core/balance', 'src/game/content/focus'])
const guildRanks = compactTable(['Rank', 'Requirement', 'Reward'], [['Outsider', 'Before Forest Heart clear', dash], ['Initiate', 'Defeat Forest Heart', 'Guild requests'], ['Apprentice', 'Complete authored requests', `+${BALANCE.focus.guildApprenticeBonus} Focus`]])
const guildRequests = compactTable(['Request', 'Item', 'Qty', 'Reputation'], Object.values(GUILD_REQUESTS).map((r) => [withId(r.name, r.id), 'itemId' in r ? item(r.itemId) : dash, 'target' in r ? r.target : dash, r.reputation]))
const unlockRows = [...DUNGEON_ORDER.map((id) => [withId(DUNGEONS[id].name, id), DUNGEONS[id].unlock?.type === 'boss-kill' ? `Defeat ${monster(DUNGEONS[id].unlock.bossId)}` : 'Start']), ...RECIPE_ORDER.filter((id) => RECIPES[id].unlock.type !== 'always').map((id) => [withId(RECIPES[id].name, id), formatRecipeUnlock(RECIPES[id].unlock)])]
add('Progression/Guild_And_Unlocks.md', block('# Guild and unlocks', '', guildRanks, '', guildRequests, '', '## Dungeon and recipe unlocks', '', compactTable(['Content', 'Requirement'], unlockRows)), Object.keys(GUILD_REQUESTS).concat(DUNGEON_ORDER, RECIPE_ORDER), ['src/game/content/guild', 'src/game/content/dungeons', 'src/game/content/recipes'])
add('Economy/Economy.md', block('# Economy', '', 'Item sell values are canonical in `Items/Items.md`; recipe costs and times are canonical in `Crafting/Crafting.md`.', '', compactTable(['Activity', 'Summary'], [['Research', 'See Progression/Research.md'], ['Production', 'See Crafting/Crafting.md']])), [], ['src/game/content', 'src/game/core/balance'])
const registry = (ids: readonly string[], documents: readonly string[], runtimeSources: readonly string[]) => ({ count: ids.length, ids: [...ids], documents: [...documents], runtimeSources: [...runtimeSources] })
export const buildBalancingDocuments = (): BalancingDocumentBuild => ({ docs, documentInfo, registries: { items: registry(items, ['Items/Items.md'], ['src/game/content/items']), equipment: registry(equipment, ['Items/Items.md'], ['src/game/content/items', 'src/game/content/equipment']), monsters: registry(MONSTER_IDS, DUNGEON_ORDER.map((id) => `Dungeons/${dungeonFile(id)}.md`), ['src/game/content/monsters']), dungeons: registry(DUNGEON_ORDER, DUNGEON_ORDER.map((id) => `Dungeons/${dungeonFile(id)}.md`), ['src/game/content/dungeons']), recipes: registry(RECIPE_ORDER, ['Crafting/Crafting.md'], ['src/game/content/recipes']), spells: registry(spells, ['Magic/Magic.md'], ['src/game/content/spells']), statuses: registry(statuses, ['Combat/Combat.md'], ['src/game/content/statuses']), traits: registry(traits, ['Combat/Combat.md'], ['src/game/content/traits']) }, invariants, canonicalLocations: { combat: 'Combat/Combat.md', dungeons: 'Dungeons/{Dungeon}.md', items: 'Items/Items.md', crafting: 'Crafting/Crafting.md', magic: 'Magic/Magic.md', progression: 'Progression/{System}.md', economy: 'Economy/Economy.md' }, mirrors: {} })
