import { render, screen, waitFor, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { ScreenErrorBoundary } from '../components/errors/ScreenErrorBoundary'
import { GameShell } from '../app/GameShell'
import { resetAllUiPreferences, setUiPreferences } from '../ui/preferences/uiPreferencesStore'
import { useGameStore } from '../store/gameStore'

vi.mock('../components/ArcaneAtmosphere', () => ({ ArcaneAtmosphere: () => null }))

const nav = () => within(screen.getByRole('navigation', { name: 'Main navigation' }))
const navItem = (label: string) => nav().getAllByRole('button', { name: label }).find((button) => button.classList.contains('nav-item'))!
const navGroup = (label: string) => nav().getByRole('button', { name: `Toggle ${label} group` })
const goToTower = async (user: ReturnType<typeof userEvent.setup>, label: string) => { const group = navGroup('Wizard Tower'); if (group.getAttribute('aria-expanded') === 'false') await user.click(group); await user.click(navItem(label)) }

describe('screen smoke coverage', () => {
  beforeEach(() => { window.localStorage.clear(); useGameStore.getState().resetSave(); resetAllUiPreferences() })

  it('renders each Wizard Tower system as its own focused screen', async () => {
    const user = userEvent.setup()
    render(<GameShell />)
    const screenScroll = document.querySelector('.screen-scroll')
    expect(screenScroll).toBeTruthy()
    expect(screenScroll?.firstElementChild?.classList.contains('game-screen-transition')).toBe(true)
    expect(screenScroll?.querySelector('.screen-content')).toBeTruthy()
    for (const item of [{ label: 'Channeling', heading: 'Channeling Chamber' }, { label: 'Focus', heading: 'Focus governs every parallel action.' }, { label: 'Transmutation', heading: 'Shape Mana into elemental matter.' }, { label: 'Research', heading: 'Research turns fragments into understanding.' }]) { await goToTower(user, item.label); expect(screen.getByRole('heading', { name: item.heading })).toBeTruthy() }
  })

  it('opens and closes the Arcane Discoveries modal with three real cards and six placeholders', async () => {
    const user = userEvent.setup()
    render(<GameShell />)
    await goToTower(user, 'Channeling')
    await user.click(screen.getByRole('button', { name: 'Arcane Discoveries 0/3' }))
    expect(screen.getByRole('dialog', { name: 'Arcane Discoveries' })).toBeTruthy()
    expect(screen.getByRole('heading', { name: 'Stable Leyline' })).toBeTruthy()
    expect(screen.getByRole('heading', { name: 'Echo Resonance' })).toBeTruthy()
    expect(screen.getByRole('heading', { name: 'Deep Reservoir' })).toBeTruthy()
    expect(screen.getAllByText('Undiscovered')).toHaveLength(6)
    await user.keyboard('{Escape}')
    expect(screen.queryByRole('dialog', { name: 'Arcane Discoveries' })).toBeNull()
  })

  it('renders the five available Pillars and the item-only archive', async () => {
    const user = userEvent.setup()
    render(<GameShell />)
    await goToTower(user, 'Channeling')
    expect(screen.getByRole('heading', { name: 'PILLARS OF MANA' })).toBeTruthy()
    for (const name of ['Leyline Conduit', 'Arcane Reservoir', 'Mana Resonance', 'Astral Expansion', 'Echo Attunement']) expect(screen.getByRole('button', { name: new RegExp(name) })).toBeTruthy()
    await user.click(navItem('Collection'))
    expect(screen.getByRole('heading', { name: 'ITEM COLLECTION' })).toBeTruthy()
    expect(screen.queryByText('Apprentice Wand')).toBeNull()
    expect(screen.queryByText('Forest Wisp')).toBeNull()
  })

  it('keeps Channeling readable with a persistent breakdown and grouped Pillars', async () => {
    const user = userEvent.setup()
    render(<GameShell />)
    await goToTower(user, 'Channeling')
    expect(screen.getByRole('heading', { name: 'PILLARS OF MANA' })).toBeTruthy()
    expect(screen.getByRole('heading', { name: 'Channeling Breakdown' })).toBeTruthy()
    expect(screen.getAllByText('PASSIVE MANA').length).toBeGreaterThan(0)
    expect(screen.getByText('Base Mana / Echo')).toBeTruthy()
    expect(screen.getByText('PASSIVE TOTAL')).toBeTruthy()
    expect(screen.queryByRole('button', { name: 'View Detailed Breakdown' })).toBeNull()
    expect(screen.queryByRole('button', { name: 'View Echo Modifiers' })).toBeNull()
  })

  it('navigates every major screen through grouped shell navigation', async () => {
    const user = userEvent.setup()
    render(<GameShell />)
    expect(screen.getByText('Complete First Frontier')).toBeTruthy()
    expect(screen.queryByText(/first three dungeons/i)).toBeNull()
    const screens = [{ nav: 'Overview', heading: 'Good evening, apprentice.' }, { nav: 'Combat', heading: 'Combat' }, { nav: 'Magic Schools', heading: 'Magic Schools' }, { nav: 'Inventory', heading: 'Everything the tower currently holds.' }, { nav: 'Equipment', heading: 'Build the tower’s answer.' }, { nav: 'Arcane Core', heading: 'Arcane Core' }, { nav: 'Guild', heading: 'A guild invitation, still sealed.' }, { nav: 'Collection', heading: 'Every relic leaves a record.' }, { nav: 'Bestiary', heading: 'Know what waits beyond the tower.' }, { nav: 'Settings / Info', heading: 'Settings / Info' }]
    for (const item of screens) { await user.click(navItem(item.nav)); expect(screen.getByRole('heading', { name: item.heading })).toBeTruthy() }
    expect(navGroup('Combat')).toBeTruthy()
    expect(navGroup('Hero')).toBeTruthy()
    expect(navGroup('Wizard Tower')).toBeTruthy()
    expect(navGroup('World')).toBeTruthy()
    expect(navGroup('System')).toBeTruthy()
  }, 10_000)

  it('keeps the shell mounted when a screen throws', () => {
    const error = vi.spyOn(console, 'error').mockImplementation(() => undefined)
    function BrokenScreen(): never { throw new Error('intentional screen failure') }
    render(<div><aside data-testid="shell-sidebar">Sidebar</aside><ScreenErrorBoundary screen="tower-channeling"><BrokenScreen /></ScreenErrorBoundary></div>)
    expect(screen.getByTestId('shell-sidebar')).toBeTruthy()
    expect(screen.getByText('This screen failed to render.')).toBeTruthy()
    expect(screen.getByRole('button', { name: 'Return Home' })).toBeTruthy()
    error.mockRestore()
  })

  it('opens and closes an Arcane Core branch without leaving an orphan modal', async () => {
    const user = userEvent.setup()
    render(<GameShell />)
    await user.click(navItem('Arcane Core'))
    expect(screen.getByRole('heading', { name: 'Arcane Core' })).toBeTruthy()
    expect(screen.queryByText('This screen failed to render.')).toBeNull()

    await user.click(screen.getByRole('button', { name: /POWER CORE/i }))
    expect(screen.getByRole('dialog', { name: 'Power Core' })).toBeTruthy()
    await user.keyboard('{Escape}')
    expect(screen.queryByRole('dialog', { name: 'Power Core' })).toBeNull()

    await user.click(navItem('Overview'))
    expect(document.querySelector('.arcane-core-modal')).toBeNull()
    expect(document.querySelector('.modal-portal-backdrop')).toBeNull()
  })

  it('opens the Developer Console without changing the gameplay screen', async () => {
    const user = userEvent.setup()
    render(<GameShell />)
    await user.click(screen.getByRole('button', { name: 'Dev Tools' }))
    expect(screen.getByRole('dialog', { name: 'Developer Tools' })).toBeTruthy()
    await user.click(within(screen.getByRole('navigation', { name: 'Developer tool sections' })).getByRole('button', { name: 'Spells & Schools' }))
    await user.click(screen.getByRole('tab', { name: 'SCHOOLS' }))
    expect(screen.getByRole('heading', { name: 'Magic schools' })).toBeTruthy()
    for (const label of ['Set all to Level 2', 'Set all to Level 8', 'Set all to Level 16', 'Set all to Level 20', 'Set cap to 20', 'Set cap to 40', 'Unlock all Rank-I spells', 'Reset spell cooldowns']) expect(screen.getByRole('button', { name: label })).toBeTruthy()
    expect(screen.getAllByRole('button', { name: 'Unlock Rank I' })).toHaveLength(32)
    await user.click(screen.getByRole('button', { name: 'Character' }))
    expect(screen.getByRole('heading', { name: 'Player values' })).toBeTruthy()
    await user.keyboard('{Escape}')
    expect(screen.getByRole('dialog', { name: 'Developer Tools' })).toBeTruthy()
    await user.click(screen.getByRole('button', { name: 'Close Developer Tools' }))
    expect(screen.queryByRole('dialog', { name: 'Developer Tools' })).toBeNull()
    expect(screen.getByRole('heading', { name: 'Good evening, apprentice.' })).toBeTruthy()
  })

  it('collapses a navigation group and reopens it when its screen becomes active', async () => {
    const user = userEvent.setup()
    render(<GameShell />)
    const towerHeader = navGroup('Wizard Tower')
    await user.click(towerHeader)
    expect(nav().queryByRole('button', { name: 'Channeling' })).toBeNull()
    useGameStore.getState().setScreen('tower-research')
    expect(await nav().findByRole('button', { name: 'Research' })).toBeTruthy()
  })

  it.each(['default', 'dark', 'light', 'custom'] as const)('renders %s appearance on Settings', async (theme) => {
    const user = userEvent.setup()
    render(<GameShell />)
    await user.click(navItem('Settings / Info'))
    const themeButton = screen.getAllByRole('button', { name: new RegExp(`^${theme === 'default' ? 'Default' : theme[0].toUpperCase() + theme.slice(1)}`) })[0]
    await user.click(themeButton)
    expect(screen.getByRole('heading', { name: 'Settings / Info' })).toBeTruthy()
    expect(document.documentElement.dataset.theme).toBe(theme)
    expect(screen.getByText('UI Sandbox')).toBeTruthy()
  })

  it('renders all primary surfaces under a custom theme', async () => {
    const user = userEvent.setup()
    setUiPreferences({ theme: 'custom' })
    render(<GameShell />)
    expect(screen.getByRole('heading', { name: 'Good evening, apprentice.' })).toBeTruthy()
    await goToTower(user, 'Research')
    expect(screen.getByRole('heading', { name: 'Research turns fragments into understanding.' })).toBeTruthy()
    await user.click(navItem('Combat'))
    expect(screen.getByRole('heading', { name: 'Combat' })).toBeTruthy()
  })

  it('shows shared School Mastery and Current Arcane Work on Overview', () => {
    render(<GameShell />)
    expect(screen.getByRole('heading', { name: 'MAGIC SCHOOL MASTERY' })).toBeTruthy()
    expect(screen.getByRole('heading', { name: 'CURRENT ARCANE WORK' })).toBeTruthy()
    for (const school of ['Fire', 'Water', 'Earth', 'Air']) expect(screen.getByText(school, { selector: 'strong' })).toBeTruthy()
    expect(screen.getAllByText('No Echoes assigned').length).toBeGreaterThan(0)
    expect(screen.getByText('No active recipes')).toBeTruthy()
  })

  it('renders the fresh spellbook state and canonical spell Focus costs', async () => {
    const user = userEvent.setup()
    render(<GameShell />)

    await user.click(navItem('Magic Schools'))
    expect(screen.getByRole('heading', { name: 'Magic Schools' })).toBeTruthy()
    expect(screen.getByRole('textbox', { name: 'Search Spells' })).toBeTruthy()
    expect(screen.queryByText('Fire Bolt')).toBeNull()
    expect((screen.getByRole('checkbox', { name: 'Unlocked Only' }) as HTMLInputElement).checked).toBe(true)
    expect(screen.getByText('NO SPELLS LEARNED YET')).toBeTruthy()
    expect(screen.getByRole('heading', { name: 'SELECT A SPELL' })).toBeTruthy()
    expect(screen.queryByText(/EDRIN|CAP|Next Lv/)).toBeNull()

    const progress = useGameStore.getState().progress
    useGameStore.setState({ progress: { ...progress, spellRanks: { 'fire-bolt': 1, 'water-bolt': 1 } } })
    await user.click(navItem('Combat'))
    await user.click(navItem('Magic Schools'))
    expect(screen.getByText('Fire Bolt', { selector: 'strong' })).toBeTruthy()
    expect(screen.getByText('Water Bolt', { selector: 'strong' })).toBeTruthy()
    expect(screen.queryAllByText('???')).toHaveLength(0)
    const fireBoltTile = screen.getByRole('button', { name: /Fire Bolt,/ })
    expect(fireBoltTile.querySelector('.spell-browser-rank-badge')).toBeNull()
    expect(fireBoltTile.querySelector('.spell-tile-status')).toBeNull()
    await user.click(fireBoltTile)
    const spellInspectorScroll = document.querySelector('.schools-inspector-panel .spell-inspector-scroll')
    expect(spellInspectorScroll?.classList.contains('smart-scroll-region')).toBe(true)
    expect(screen.getByText(/Auto-Cast Focus/)).toBeTruthy()
    expect(screen.queryByText('Current Rank')).toBeNull()
    expect(screen.getByRole('button', { name: 'Auto-Cast OFF' })).toBeTruthy()
    expect(screen.getByText('10 Focus when enabled')).toBeTruthy()
    await user.click(screen.getByRole('button', { name: 'Auto-Cast OFF' }))
    expect(screen.getByRole('button', { name: 'Auto-Cast ON' })).toBeTruthy()
    expect(screen.getByText('10 Focus reserved')).toBeTruthy()
    expect(fireBoltTile.querySelector('.spell-tile-status')).toBeTruthy()
    await user.click(screen.getByRole('button', { name: /Water Bolt,/ }))
    expect(screen.getByRole('heading', { name: 'Water Bolt' })).toBeTruthy()
    expect(screen.getByRole('button', { name: /Water Bolt,/ }).getAttribute('aria-pressed')).toBe('true')
    expect(screen.getByRole('button', { name: /Fire Bolt,/ }).getAttribute('aria-pressed')).toBe('false')
    await user.click(navItem('Combat'))
    await user.click(navItem('Magic Schools'))
    await user.click(screen.getByRole('checkbox', { name: 'Unlocked Only' }))
    expect(screen.getAllByText('???').length).toBeGreaterThan(0)
  })

  it('shows a themed insufficient-Focus Auto-Cast state without enabling it', async () => {
    const user = userEvent.setup()
    const progress = useGameStore.getState().progress
    const player = useGameStore.getState().player
    useGameStore.setState({ progress: { ...progress, spellRanks: { 'fire-bolt': 1 } }, player: { ...player, maxFocus: 0 } })
    render(<GameShell />)
    await user.click(navItem('Magic Schools'))
    await user.click(screen.getByRole('button', { name: /Fire Bolt,/ }))
    const toggle = screen.getByRole('button', { name: 'Auto-Cast OFF' })
    expect(toggle.hasAttribute('disabled')).toBe(true)
    expect(screen.getByText('Need 10 Focus')).toBeTruthy()
  })

  it('derives effect micro-icons and exposes rich mouse and keyboard effect tooltips', async () => {
    const user = userEvent.setup()
    const progress = useGameStore.getState().progress
    useGameStore.setState({ progress: { ...progress, spellRanks: { 'searing-touch': 1 } } })
    render(<GameShell />)
    await user.click(navItem('Magic Schools'))

    const searingTouchTile = screen.getByRole('button', { name: /Searing Touch,/ })
    const tileShell = searingTouchTile.closest('.spell-browser-tile-shell')!
    const microIcons = tileShell.querySelectorAll('.spell-browser-effect-icon')
    expect(microIcons).toHaveLength(2)
    expect(microIcons[0].getAttribute('aria-label')).toBe('Damage')
    expect(microIcons[1].getAttribute('aria-label')).toBe('DoT')
    await user.hover(microIcons[1])
    expect((await screen.findByRole('tooltip')).textContent).toContain('DoT')
    await user.unhover(microIcons[1])
    await waitFor(() => expect(screen.queryByRole('tooltip')).toBeNull())

    await user.click(searingTouchTile)
    const effectRow = screen.getByLabelText('DOT: Burning')
    await user.hover(effectRow)
    const tooltip = await screen.findByRole('tooltip')
    expect(tooltip.textContent).toContain('Burning')
    expect(tooltip.textContent).toContain('Damage Per Tick')
    expect(tooltip.textContent).toContain('1.0s')
    expect(tooltip.textContent).toContain('Alt')
    await user.keyboard('{Alt>}')
    await waitFor(() => expect(screen.getByRole('tooltip').textContent).toContain('Source'))
    effectRow.focus()
    await user.keyboard('{/Alt}')
    await waitFor(() => expect(screen.getByRole('tooltip').textContent).toContain('Burning'))
    await user.keyboard('{Escape}')
    expect(screen.queryByRole('tooltip')).toBeNull()
  })

  it('shows the full spell tooltip and keeps prioritized Inspector details inline', async () => {
    const user = userEvent.setup()
    const progress = useGameStore.getState().progress
    const equipment = useGameStore.getState().equipment
    useGameStore.setState({ progress: { ...progress, spellRanks: { 'fire-bolt': 1, harden: 1, 'frost-touch': 1 } }, equipment: { ...equipment, weapon: 'ember-staff' } })
    render(<GameShell />)
    await user.click(navItem('Magic Schools'))

    const fireBoltTile = screen.getByRole('button', { name: /Fire Bolt,/ })
    const fireBoltIcon = fireBoltTile.querySelector('.spell-browser-icon-frame')!
    await user.hover(fireBoltIcon)
    const spellTooltip = await screen.findByRole('tooltip')
    await user.keyboard('{Alt>}')
    await waitFor(() => expect(screen.getByRole('tooltip').textContent).toContain('Base Damage'))
    expect(spellTooltip.classList.contains('game-tooltip-wide')).toBe(true)
    expect(spellTooltip.textContent).toContain('FIRE · RANK I')
    expect(spellTooltip.textContent).toContain('Fire Bolt')
    expect(spellTooltip.textContent).toContain('MANA')
    expect(spellTooltip.textContent).toContain('30')
    expect(spellTooltip.textContent).toContain('COOLDOWN')
    expect(spellTooltip.textContent).toContain('6.0s')
    expect(spellTooltip.textContent).toContain('AUTO-CAST')
    expect(spellTooltip.textContent).toContain('10 Focus')
    expect(spellTooltip.textContent).toContain('Base Damage')
    expect(spellTooltip.textContent).toContain('75% Spell Power')
    expect(spellTooltip.textContent).not.toContain('Select to inspect this Spell')
    await user.keyboard('{/Alt}')
    await user.unhover(fireBoltIcon)
    await waitFor(() => expect(screen.queryByRole('tooltip')).toBeNull())
    await user.click(fireBoltTile)
    expect(screen.getByRole('heading', { name: 'Fire Bolt' })).toBeTruthy()
    expect(screen.getByText('Base Damage')).toBeTruthy()
    expect(screen.getByText('75% Spell Power')).toBeTruthy()

    await user.click(screen.getByRole('button', { name: /Harden,/ }))
    const fortifyRow = screen.getByLabelText('BUFF: Hardened')
    expect(fortifyRow.textContent).toContain('Damage Taken')
    expect(fortifyRow.textContent).toContain('-25%')
    expect(fortifyRow.textContent).toContain('Duration')
    expect(fortifyRow.textContent).toContain('5.0s')
    expect(fortifyRow.textContent).toContain('Target')
    expect(fortifyRow.textContent).toContain('Self')
    await user.hover(fortifyRow)
    await screen.findByRole('tooltip')
    await user.keyboard('{Alt>}')
    await waitFor(() => expect(screen.getByRole('tooltip').textContent).toContain('Source'))
    fortifyRow.focus()
    await user.keyboard('{/Alt}')
    await user.keyboard('{Escape}')
    expect(screen.queryByRole('tooltip')).toBeNull()

    await user.click(screen.getByRole('button', { name: /Frost Touch,/ }))
    expect(screen.getByLabelText('DAMAGE: Water Damage')).toBeTruthy()
    expect(screen.getByLabelText('CONTROL: Chilled')).toBeTruthy()
  })

  it('keeps locked spell entries secret in their hover copy', async () => {
    const user = userEvent.setup()
    const progress = useGameStore.getState().progress
    useGameStore.setState({ progress: { ...progress, spellRanks: { 'fire-bolt': 1 } } })
    render(<GameShell />)
    await user.click(navItem('Magic Schools'))
    await user.click(screen.getByRole('checkbox', { name: 'Unlocked Only' }))

    const lockedTile = screen.getAllByRole('button', { name: /Locked Fire spell/ })[0]
    await user.hover(lockedTile.querySelector('.spell-browser-icon-frame')!)
    const tooltip = await screen.findByRole('tooltip')
    expect(tooltip.textContent).toContain('Locked spell')
    expect(tooltip.textContent).not.toContain('Base Damage')
    expect(tooltip.textContent).not.toContain('Current Base Preview')
    expect(tooltip.textContent).not.toContain('Fireball')
  })

  it('creates, saves, and applies an Auto-Cast preset from the Schools screen', async () => {
    const user = userEvent.setup()
    const progress = useGameStore.getState().progress
    useGameStore.setState({ progress: { ...progress, spellRanks: { 'fire-bolt': 1 } } })
    render(<GameShell />)
    await user.click(navItem('Magic Schools'))
    await user.click(screen.getByRole('button', { name: 'MANAGE PRESETS' }))
    const dialog = screen.getByRole('dialog', { name: 'SPELL PRESET MANAGER' })
    expect(within(dialog).getByText('FIRE · RANK I')).toBeTruthy()
    await user.clear(within(dialog).getByRole('textbox', { name: 'Preset name' }))
    await user.type(within(dialog).getByRole('textbox', { name: 'Preset name' }), 'Fire opener')
    await user.click(within(dialog).getByRole('button', { name: /Fire Bolt/ }))
    await user.click(within(dialog).getByRole('button', { name: 'SAVE' }))
    await user.click(within(dialog).getByRole('button', { name: 'SELECT PRESET' }))
    expect(useGameStore.getState().spellPresets.presets[0]).toMatchObject({ name: 'Fire opener', slots: [{ spellId: 'fire-bolt', autoCast: false }] })
    expect(useGameStore.getState().spellPresets.selectedPresetId).toBe('spell-preset-1')
    expect(useGameStore.getState().activities.autoCast['fire-bolt']).toBe(false)
  })

  it('opens a local first-use preset draft without persisting it', async () => {
    const user = userEvent.setup()
    render(<GameShell />)
    await user.click(navItem('Magic Schools'))
    expect(screen.getByText('0 AUTO · 0 MANUAL · 0 Focus')).toBeTruthy()
    await user.click(screen.getByRole('button', { name: 'MANAGE PRESETS' }))
    const dialog = screen.getByRole('dialog', { name: 'SPELL PRESET MANAGER' })
    expect(within(dialog).getByRole('heading', { name: 'AVAILABLE SPELLS' })).toBeTruthy()
    expect(within(dialog).getByRole('heading', { name: 'COMBAT LOADOUT' })).toBeTruthy()
    expect(within(dialog).getByText('NO SPELLS IN THIS PRESET')).toBeTruthy()
    expect(within(dialog).getByText('FOCUS BUDGET')).toBeTruthy()
    await user.click(within(dialog).getByRole('button', { name: 'Close spell preset manager' }))
    expect(screen.queryByRole('dialog', { name: 'SPELL PRESET MANAGER' })).toBeNull()
    expect(useGameStore.getState().spellPresets.presets).toHaveLength(0)
  })

  it('keeps a dirty preset draft behind a themed discard confirmation', async () => {
    const user = userEvent.setup()
    const progress = useGameStore.getState().progress
    useGameStore.setState({ progress: { ...progress, spellRanks: { 'fire-bolt': 1 } } })
    render(<GameShell />)
    await user.click(navItem('Magic Schools'))
    await user.click(screen.getByRole('button', { name: 'MANAGE PRESETS' }))
    const dialog = screen.getByRole('dialog', { name: 'SPELL PRESET MANAGER' })
    await user.clear(within(dialog).getByRole('textbox', { name: 'Preset name' }))
    await user.type(within(dialog).getByRole('textbox', { name: 'Preset name' }), 'Unsaved')
    await user.click(within(dialog).getByRole('button', { name: 'Close spell preset manager' }))
    expect(screen.getByRole('alertdialog', { name: 'DISCARD UNSAVED CHANGES?' })).toBeTruthy()
    expect(useGameStore.getState().spellPresets.presets).toHaveLength(0)
    await user.click(within(screen.getByRole('alertdialog')).getByRole('button', { name: 'DISCARD' }))
    expect(screen.queryByRole('dialog', { name: 'SPELL PRESET MANAGER' })).toBeNull()
  })

  it('uses the themed Type menu and disables Apply when the projected Focus overflows', async () => {
    const user = userEvent.setup()
    const progress = useGameStore.getState().progress
    const player = useGameStore.getState().player
    useGameStore.setState({ progress: { ...progress, spellRanks: { 'fire-bolt': 1, 'earthen-barrier': 1 } }, player: { ...player, maxFocus: 0 } })
    render(<GameShell />)
    await user.click(navItem('Magic Schools'))
    expect(document.querySelector('.schools-browser-panel select')).toBeNull()
    await user.click(screen.getByRole('button', { name: 'Spell type filter' }))
    await user.click(screen.getByRole('option', { name: 'Barrier' }))
    expect(screen.getByText('Earthen Barrier', { selector: 'strong' })).toBeTruthy()
    expect(screen.queryByText('Fire Bolt', { selector: 'strong' })).toBeNull()
    await user.click(screen.getByRole('button', { name: 'MANAGE PRESETS' }))
    const dialog = screen.getByRole('dialog', { name: 'SPELL PRESET MANAGER' })
    await user.click(within(dialog).getByRole('button', { name: /Earthen Barrier/ }))
    await user.click(within(dialog).getByRole('button', { name: 'Enable Auto-Cast for Earthen Barrier' }))
    expect(within(dialog).getByText('Need 10 more Focus.')).toBeTruthy()
    expect(within(dialog).getByRole('button', { name: 'SELECT PRESET' }).hasAttribute('disabled')).toBe(true)
  })

  it('dismisses the Rank Path rail from outside clicks, Escape, and Preset Manager', async () => {
    const user = userEvent.setup()
    const progress = useGameStore.getState().progress
    useGameStore.setState({ progress: { ...progress, spellRanks: { 'fire-bolt': 1 } } })
    render(<GameShell />)
    await user.click(navItem('Magic Schools'))
    await user.click(screen.getByRole('button', { name: /Fire Bolt,/ }))
    await user.click(screen.getByRole('button', { name: /VIEW RANK PATH/ }))
    const rail = screen.getByRole('complementary', { name: 'Spell rank path' })
    expect(rail).toBeTruthy()
    await user.click(within(rail).getByRole('heading', { name: 'Rank Path' }))
    expect(screen.getByRole('complementary', { name: 'Spell rank path' })).toBeTruthy()
    await user.keyboard('{Escape}')
    expect(screen.queryByRole('complementary', { name: 'Spell rank path' })).toBeNull()
    await user.click(screen.getByRole('button', { name: /VIEW RANK PATH/ }))
    await user.click(screen.getByText('EFFECTS', { selector: 'div' }))
    expect(screen.queryByRole('complementary', { name: 'Spell rank path' })).toBeNull()
    await user.click(screen.getByRole('button', { name: /VIEW RANK PATH/ }))
    await user.click(screen.getByRole('button', { name: 'Close rank path' }))
    expect(screen.queryByRole('complementary', { name: 'Spell rank path' })).toBeNull()
    await user.click(screen.getByRole('button', { name: /VIEW RANK PATH/ }))
    await user.click(screen.getByRole('button', { name: 'MANAGE PRESETS' }))
    expect(screen.queryByRole('complementary', { name: 'Spell rank path' })).toBeNull()
    expect(screen.getByRole('dialog', { name: 'SPELL PRESET MANAGER' })).toBeTruthy()
  })

  it('uses title mode for saved preset names and themed inline editing', async () => {
    const user = userEvent.setup()
    const progress = useGameStore.getState().progress
    useGameStore.setState({ progress: { ...progress, spellRanks: { 'fire-bolt': 1 } } })
    render(<GameShell />)
    await user.click(navItem('Magic Schools'))
    await user.click(screen.getByRole('button', { name: 'MANAGE PRESETS' }))
    const dialog = screen.getByRole('dialog', { name: 'SPELL PRESET MANAGER' })
    await user.clear(within(dialog).getByRole('textbox', { name: 'Preset name' }))
    await user.type(within(dialog).getByRole('textbox', { name: 'Preset name' }), 'Themed Build')
    await user.click(within(dialog).getByRole('button', { name: /Fire Bolt/ }))
    await user.click(within(dialog).getByRole('button', { name: 'SAVE' }))
    await user.click(within(dialog).getByRole('button', { name: 'CANCEL' }))
    await user.click(screen.getByRole('button', { name: 'MANAGE PRESETS' }))
    const reopened = screen.getByRole('dialog', { name: 'SPELL PRESET MANAGER' })
    expect(within(reopened).queryByRole('textbox', { name: 'Preset name' })).toBeNull()
    await user.click(within(reopened).getByRole('button', { name: 'Edit preset name' }))
    const nameInput = within(reopened).getByRole('textbox', { name: 'Preset name' })
    await user.clear(nameInput)
    await user.type(nameInput, 'Renamed Build')
    await user.keyboard('{Enter}')
    expect(within(reopened).getByText('Renamed Build')).toBeTruthy()
  }, 30_000)
})
