import type { ReactNode } from 'react'
import { Check, ChevronRight, CircleHelp, FlaskConical, Lock, Pause, Play, RotateCcw, Save, ShieldCheck, Sparkles, Swords, Target, Zap } from 'lucide-react'
import { BALANCE, SCHOOL_LEVEL_XP } from '../game/data/balance'
import { FRAGMENT_ORDER, ITEMS, MONSTERS, RESEARCH_ITEMS, SCHOOLS, SPELLS } from '../game/data/content'
import { freeFocus, schoolProgress, usedFocus } from '../game/engine'
import type { ElementId, ItemId, ScreenId, SchoolId, SpellId } from '../game/types'
import { formatNumber, formatTime } from '../game/utils'
import { selectFreeFocus, selectManaRegen, selectUsedFocus, useGameStore } from '../store/gameStore'

export function Screen() {
  const screen = useGameStore((state) => state.ui.screen)
  return <>{screen === 'home' && <HomeScreen />} {screen === 'tower' && <TowerScreen />} {screen === 'schools' && <SchoolsScreen />} {screen === 'combat' && <CombatScreen />} {screen === 'inventory' && <InventoryScreen />} {screen === 'equipment' && <EquipmentScreen />} {screen === 'guild' && <GuildScreen />} {screen === 'collection' && <CollectionScreen />} {screen === 'settings' && <SettingsScreen />} <DebugPanel /></>
}

function ScreenHeader({ kicker, title, description, action }: { kicker: string; title: string; description: string; action?: ReactNode }) {
  return <div className="screen-header"><div><div className="eyebrow">{kicker}</div><h1>{title}</h1><p>{description}</p></div>{action && <div className="header-action">{action}</div>}</div>
}

function Card({ children, className = '', title, action, style }: { children: ReactNode; className?: string; title?: string; action?: ReactNode; style?: React.CSSProperties }) {
  return <section style={style} className={`card ${className}`}><>{title && <div className="card-head"><h2>{title}</h2>{action}</div>}{children}</></section>
}

function Button({ children, onClick, variant = 'primary', disabled = false, className = '', title }: { children: ReactNode; onClick?: () => void; variant?: 'primary' | 'secondary' | 'ghost' | 'danger' | 'success'; disabled?: boolean; className?: string; title?: string }) {
  return <button title={title} className={`button ${variant} ${className}`} onClick={onClick} disabled={disabled}>{children}</button>
}

function Progress({ value, tone = 'violet', label, right }: { value: number; tone?: string; label?: string; right?: ReactNode }) {
  return <div className="progress-wrap">{(label || right) && <div className="progress-label"><span>{label}</span><strong>{right}</strong></div>}<div className="progress"><i className={tone} style={{ width: `${Math.max(0, Math.min(100, value))}%` }} /></div></div>
}

function Status({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'success' | 'warning' | 'active' | 'locked' }) { return <span className={`status ${tone}`}>{children}</span> }
function Tooltip({ children, text }: { children: ReactNode; text: string }) { return <span className="tooltip-wrap">{children}<span className="tooltip">{text}</span></span> }

function HomeScreen() {
  const player = useGameStore((state) => state.player)
  const combat = useGameStore((state) => state.combat)
  const progress = useGameStore((state) => state.progress)
  const activities = useGameStore((state) => state.activities)
  const setScreen = useGameStore((state) => state.setScreen)
  const objective = progress.firstMainBossKill ? { title: 'First MVP Chapter Complete', body: 'The Forest Heart has fallen. Your save continues normally.', tone: 'success' } : progress.firstBossKill ? { title: 'Defeat Forest Heart', body: 'The first kill raises the Magic School level cap from 10 → 20.', tone: 'gold' } : { title: 'Clear Whispering Woods', body: `Reach ${BALANCE.dungeon.whisperingWoodsThreatRequired} Threat Cleared and defeat Grove Sentinel.`, tone: 'violet' }
  const activeCount = Number(combat.active) + Number(activities.autoChannel) + Number(activities.condense.running) + Number(activities.research.running) + Number(activities.transmutation.running)
  return <div className="screen-content">
    <ScreenHeader kicker="WIZARD TOWER · OVERVIEW" title="Good evening, apprentice." description="One wizard. One tower. Every system is competing for the same Focus." action={<Button variant="secondary" onClick={() => setScreen('tower')}><TowerGlyph /> Open Tower <ChevronRight size={15} /></Button>} />
    <div className={`objective-card ${objective.tone}`}><div className="objective-icon"><Target size={22} /></div><div className="objective-copy"><span>MAIN OBJECTIVE</span><h2>{objective.title}</h2><p>{objective.body}</p></div><div className="objective-state">{progress.firstMainBossKill ? <Check size={24} /> : <span>CAP {progress.magicLevelCap}</span>}</div></div>
    <div className="home-grid">
      <Card className="loop-card" title="The First Loop" action={<Status tone="active">Live systems</Status>}><div className="loop-line"><LoopStep icon="✦" label="Mana" /><ChevronRight /><LoopStep icon="◆" label="Materials" /><ChevronRight /><LoopStep icon="⌁" label="Research" /><ChevronRight /><LoopStep icon="⚔" label="Combat" /><ChevronRight /><LoopStep icon="✤" label="Boss" /></div><p className="muted">Keep Research, production, and Combat running together. The choice is how you spend Focus.</p><div className="metric-row"><Metric label="Active systems" value={String(activeCount)} /><Metric label="Lifetime kills" value={formatNumber(progress.lifetimeKills)} /><Metric label="Offline Bank" value={formatTime(useGameStore.getState().offlineBankMs)} /></div></Card>
      <Card className="wizard-card" title="The Wizard"><div className="wizard-portrait"><div className="wizard-orbit orbit-one" /><div className="wizard-orbit orbit-two" /><div className="wizard-silhouette">♙</div><div className="wizard-sigil">✦</div></div><div className="wizard-details"><h3>Apprentice of the Tower</h3><p>Magic School cap <strong>{progress.magicLevelCap}</strong></p><div className="equip-line"><span>Equipped focus</span><strong>⌁ Apprentice Wand</strong></div><Button className="wide" variant="ghost" onClick={() => setScreen('equipment')}>Inspect equipment <ChevronRight size={15} /></Button></div></Card>
    </div>
    <div className="section-label">Quick access</div>
    <div className="quick-grid"><QuickCard icon={<TowerGlyph />} title="Wizard Tower" text="Channel Mana and run parallel activities." onClick={() => setScreen('tower')} /><QuickCard icon={<SwordsGlyph />} title="Whispering Woods" text={combat.active ? 'Combat is active in the background.' : 'Enter the first dungeon.'} onClick={() => setScreen('combat')} /><QuickCard icon={<BookGlyph />} title="Magic Schools" text="Research fragments into spells." onClick={() => setScreen('schools')} /></div>
  </div>
}

function TowerGlyph() { return <span className="button-glyph">⌂</span> }
function SwordsGlyph() { return <span className="button-glyph">⚔</span> }
function BookGlyph() { return <span className="button-glyph">✧</span> }
function LoopStep({ icon, label }: { icon: string; label: string }) { return <div className="loop-step"><span>{icon}</span><small>{label}</small></div> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="metric"><span>{label}</span><strong>{value}</strong></div> }
function QuickCard({ icon, title, text, onClick }: { icon: ReactNode; title: string; text: string; onClick: () => void }) { return <button className="quick-card" onClick={onClick}><span className="quick-icon">{icon}</span><span><strong>{title}</strong><small>{text}</small></span><ChevronRight size={16} /></button> }

function TowerScreen() {
  const player = useGameStore((state) => state.player)
  const activities = useGameStore((state) => state.activities)
  const inventory = useGameStore((state) => state.inventory)
  const progress = useGameStore((state) => state.progress)
  const toggleAutoChannel = useGameStore((state) => state.toggleAutoChannel)
  const toggleCondense = useGameStore((state) => state.toggleCondense)
  const toggleResearch = useGameStore((state) => state.toggleResearch)
  const toggleTransmutation = useGameStore((state) => state.toggleTransmutation)
  const channelMana = useGameStore((state) => state.channelMana)
  const focusUsed = useGameStore(selectUsedFocus)
  const focusFree = useGameStore(selectFreeFocus)
  const manaRegen = useGameStore(selectManaRegen)
  const activeResearch = activities.research.itemId
  return <div className="screen-content">
    <ScreenHeader kicker="ROOM 01 · WIZARD TOWER" title="The tower is awake." description="Keep the tower working while the wizard fights below. Every automated room reserves Focus." action={<div className="focus-summary"><span>FOCUS RESERVATION</span><strong>{focusUsed} <small>/ {player.maxFocus}</small></strong><em>{focusFree} free</em></div>} />
    <div className="tower-grid">
      <Card className="channel-card" title="Channeling Chamber" action={<Status tone="active">Passive +{manaRegen}/s</Status>}><div className="channel-visual"><div className="mana-core"><span>✦</span><i /></div><div><div className="eyebrow">CURRENT MANA</div><strong className="big-number">{formatNumber(player.mana)} <small>/ {player.maxMana}</small></strong><p className="muted">Manual channeling costs no Focus. Automation does.</p></div></div><div className="button-row"><Button onClick={channelMana} disabled={player.mana >= player.maxMana}><Zap size={16} /> Channel Mana <small>+{BALANCE.mana.manualChannelAmount}</small></Button><Button variant={activities.autoChannel ? 'success' : 'secondary'} onClick={toggleAutoChannel}>{activities.autoChannel ? <Pause size={15} /> : <Play size={15} />} {activities.autoChannel ? 'Pause Auto Channeling' : 'Enable Auto Channeling'} <small>−{BALANCE.mana.autoChannelFocus} Focus</small></Button></div><div className="info-strip"><span>Mana regeneration</span><strong>{manaRegen}/s</strong><span>Net with active drains</span><strong className="positive">{manaRegen}/s baseline</strong></div></Card>
      <FocusPanel />
    </div>
    <div className="section-label">Parallel activities</div>
    <div className="tower-grid lower">
      <Card title="Elemental Condensation" className="activity-card" action={<Status tone={activities.condense.running ? 'active' : 'neutral'}>{activities.condense.running ? (activities.condense.progressMs >= BALANCE.condense.durationMs && player.mana < BALANCE.condense.manaCost ? 'Waiting for Mana' : 'Running') : 'Paused'}</Status>}><p className="muted">Turn Mana into fragments. One batch every {formatTime(BALANCE.condense.durationMs)}.</p><div className="element-pills">{FRAGMENT_ORDER.map((element) => <button key={element} className={`element-pill ${activities.condense.element === element ? 'selected' : ''}`} style={{ '--element-color': SCHOOLS[element].color } as React.CSSProperties} onClick={() => { if (activities.condense.running) toggleCondense(); else toggleCondense(element) }}><span>{SCHOOLS[element].glyph}</span>{SCHOOLS[element].name}<small>{inventory[SCHOOLS[element].fragment] ?? 0}</small></button>)}</div>{activities.condense.running && <Progress value={activities.condense.progressMs / BALANCE.condense.durationMs * 100} tone="orange" label={`Condensing ${SCHOOLS[activities.condense.element].name}`} right={<>{activities.condense.progressMs >= BALANCE.condense.durationMs && player.mana < BALANCE.condense.manaCost ? 'Waiting for Mana' : formatTime(BALANCE.condense.durationMs - activities.condense.progressMs)}</>} />}<div className="card-foot"><span>Reserve {BALANCE.condense.focusCost} Focus · Spend {BALANCE.condense.manaCost} Mana / batch</span><Button variant={activities.condense.running ? 'ghost' : 'secondary'} onClick={() => toggleCondense()}>{activities.condense.running ? 'Pause' : 'Start Condensing'}</Button></div></Card>
      <Card title="Arcane Crucible" className="activity-card" action={<Status tone={activities.research.running ? 'active' : 'neutral'}>{activities.research.running ? 'Running' : 'Paused'}</Status>}><p className="muted">Destroy a fragment to gain Magic School XP. The next item is never consumed at the level cap.</p><div className="research-list">{RESEARCH_ITEMS.map((item) => { const school = SCHOOLS[item.school]; const isActive = activeResearch === item.itemId; const level = useGameStore.getState().schools[item.school].level; const atCap = level >= progress.magicLevelCap; return <div key={item.itemId} className={`research-row ${isActive ? 'selected' : ''}`}><div className="item-glyph" style={{ color: school.color }}>{school.glyph}</div><div className="research-name"><strong>{item.label}</strong><small>{item.xp} XP · {item.mana} Mana · School Lv {level}</small></div><span className="quantity">×{inventory[item.itemId] ?? 0}</span><Button variant={isActive ? 'ghost' : 'secondary'} disabled={atCap && !isActive} onClick={() => toggleResearch(item.itemId)}>{atCap ? 'Cap' : isActive ? 'Pause' : 'Research'}</Button></div> })}</div>{activities.research.running && activeResearch && <Progress value={activities.research.progressMs / BALANCE.research.durationPerItemMs * 100} tone="violet" label="Current cycle" right={activities.research.progressMs >= BALANCE.research.durationPerItemMs ? 'Ready' : formatTime(BALANCE.research.durationPerItemMs - activities.research.progressMs)} />}<div className="card-foot"><span>Reserve {BALANCE.research.focusCost} Focus · cap {progress.magicLevelCap}</span><span className="protected"><ShieldCheck size={14} /> Cap-safe</span></div></Card>
      <Card title="Transmutation" className="activity-card" action={<Status tone={activities.transmutation.running ? 'active' : progress.emberStaffUnlocked ? 'neutral' : 'locked'}>{activities.transmutation.running ? 'Running' : progress.emberStaffUnlocked ? 'Ready' : 'Locked'}</Status>}><div className="recipe-visual"><div className="recipe-item">⚚</div><div className="recipe-arrow">→</div><div className="recipe-item muted-item">✦</div></div><h3>Ember Staff</h3><p className="muted">A simple magical weapon from the first forest loot.</p><div className="cost-line"><span>Wisp Essence <strong>{inventory['wisp-essence'] ?? 0} / 4</strong></span><span>Fire Fragment <strong>{inventory['fire-fragment'] ?? 0} / 4</strong></span></div><Progress value={activities.transmutation.running ? activities.transmutation.progressMs / BALANCE.transmutation.durationMs * 100 : 0} tone="gold" label={activities.transmutation.running ? 'Transmuting' : '8 second recipe'} /> <Button className="wide" variant={activities.transmutation.running ? 'ghost' : 'secondary'} disabled={!progress.emberStaffUnlocked || Boolean(inventory['ember-staff'])} onClick={toggleTransmutation}>{inventory['ember-staff'] ? 'Ember Staff crafted' : activities.transmutation.running ? 'Pause Transmutation' : 'Begin Transmutation'} </Button></Card>
    </div>
  </div>
}

function FocusPanel() {
  const player = useGameStore((state) => state.player)
  const activities = useGameStore((state) => state.activities)
  const progress = useGameStore((state) => state.progress)
  const focusUsed = useGameStore(selectUsedFocus)
  const rows = [{ label: 'Auto Channeling', amount: activities.autoChannel ? 15 : 0 }, { label: 'Fragment Condensation', amount: activities.condense.running ? 20 : 0 }, { label: 'Arcane Research', amount: activities.research.running ? 25 : 0 }, { label: 'Transmutation', amount: activities.transmutation.running ? 20 : 0 }, ...Object.entries(activities.autoCast).filter(([id, enabled]) => enabled && progress.unlockedSpells.includes(id as SpellId)).map(([id]) => ({ label: `${SPELLS[id as SpellId].name} Auto-Cast`, amount: 15 }))].filter((row) => row.amount)
  return <Card className="focus-card" title="Focus Allocation" action={<span className="focus-ring"><strong>{focusUsed}</strong><small>/ {player.maxFocus}</small></span>}><p className="muted">Focus is reserved, never spent. Pause an activity to release it immediately.</p><div className="focus-total"><span>Used</span><Progress value={focusUsed / player.maxFocus * 100} tone="violet" /><strong>{player.maxFocus - focusUsed} free</strong></div><div className="reservation-list">{rows.length ? rows.map((row) => <div className="reservation" key={row.label}><span className="reservation-dot" /><span>{row.label}</span><strong>{row.amount}</strong></div>) : <div className="empty-state small">No automated activities are reserving Focus.</div>}</div><div className="focus-rule"><CircleHelp size={15} /><span>Combat Basic Attack requires <strong>0 Focus</strong>. Mana, production, Research, and Auto-Cast compete for the rest.</span></div></Card>
}

function SchoolsScreen() {
  const schools = useGameStore((state) => state.schools)
  const cap = useGameStore((state) => state.progress.magicLevelCap)
  const unlocked = useGameStore((state) => state.progress.unlockedSpells)
  const setScreen = useGameStore((state) => state.setScreen)
  return <div className="screen-content"><ScreenHeader kicker="MAGIC SCHOOL ARCHIVE" title="Four paths, one Focus pool." description="Research elemental fragments in the Arcane Crucible. Level 2 reveals each school’s first spell." action={<Button variant="secondary" onClick={() => setScreen('tower')}><FlaskConical size={16} /> Open Crucible</Button>} /><div className="schools-grid">{FRAGMENT_ORDER.map((id) => { const school = SCHOOLS[id]; const state = schools[id]; const spell = Object.values(SPELLS).find((candidate) => candidate.school === id)!; const isUnlocked = unlocked.includes(spell.id); return <Card key={id} className="school-card" style={{ borderTopColor: school.color } as React.CSSProperties}><div className="school-card-head"><div className="school-glyph" style={{ color: school.color }}>{school.glyph}</div><div><h2>{school.name}</h2><p>{school.tagline}</p></div><span className="school-level">{state.level}<small>LV</small></span></div><Progress value={schoolProgress(useGameStore.getState(), id) * 100} tone={id} label="School XP" right={<>{formatNumber(state.xp)} XP</>} /><div className="school-cap"><span>Level cap</span><strong>{state.level >= cap ? 'Level Cap Reached' : cap}</strong></div><div className={`spell-unlock ${isUnlocked ? 'unlocked' : ''}`}><span className="spell-icon">✧</span><div><strong>{spell.name}</strong><small>{isUnlocked ? spell.description : 'Unlock at School Level 2'}</small></div>{isUnlocked ? <Check size={17} /> : <Lock size={15} />}</div></Card> })}</div><Card title="Level ceiling" className="ceiling-card"><div className="ceiling-line"><span className="ceiling-number">{cap}</span><div><strong>Magic School level cap</strong><p className="muted">Defeat Forest Heart once to raise the first chapter ceiling from 10 to 20. Research remains safe at the cap.</p></div><div className="ceiling-arrow">{cap >= 20 ? '20' : '10'} → 20</div></div></Card></div>
}

function CombatScreen() {
  const player = useGameStore((state) => state.player)
  const combat = useGameStore((state) => state.combat)
  const progress = useGameStore((state) => state.progress)
  const unlocked = progress.unlockedSpells
  const enterDungeon = useGameStore((state) => state.enterDungeon)
  const leaveDungeon = useGameStore((state) => state.leaveDungeon)
  const engageBoss = useGameStore((state) => state.engageBoss)
  const castSpell = useGameStore((state) => state.castSpell)
  const toggleAutoCast = useGameStore((state) => state.toggleAutoCast)
  const enemy = combat.enemyId ? MONSTERS[combat.enemyId] : null
  return <div className="screen-content"><ScreenHeader kicker="REGION 01 · WHISPERING WOODS" title="The clearing watches back." description="Basic Attack runs automatically. Spells and automation are your active decisions." action={combat.active ? <Button variant="danger" onClick={leaveDungeon}><Pause size={15} /> Leave Dungeon</Button> : <Button onClick={enterDungeon}><Swords size={16} /> Enter Whispering Woods</Button>} />
    <div className="combat-layout"><Card className="dungeon-card" title="Whispering Woods" action={<Status tone={combat.active ? 'active' : 'neutral'}>{combat.active ? 'Combat Active' : 'At the Tower'}</Status>}><div className="forest-scene"><div className="moon" /><div className="tree tree-a" /><div className="tree tree-b" /><div className="tree tree-c" /><div className="forest-rune">✦</div></div><div className="dungeon-stat-row"><Metric label="Threat Cleared" value={`${combat.threatCleared} / ${BALANCE.dungeon.whisperingWoodsThreatRequired}`} /><Metric label="Lifetime kills" value={formatNumber(progress.lifetimeKills)} /><Metric label="Encounter" value={enemy ? 'Engaged' : combat.active ? formatTime(combat.encounterTimerMs) : '—'} /></div>{combat.threatCleared >= BALANCE.dungeon.whisperingWoodsThreatRequired && combat.active && !combat.inBossFight && <div className="boss-ready"><div><Status tone="success">Boss Ready</Status><strong>Grove Sentinel can be challenged.</strong><span>Threat can continue beyond the requirement without forcing the fight.</span></div><Button variant="success" onClick={() => engageBoss('grove-sentinel')}>Engage Sentinel <ChevronRight size={15} /></Button></div>}{progress.forestHeartUnlocked && combat.active && !combat.inBossFight && <div className="boss-ready heart"><div><Status tone="warning">Main Boss Unlocked</Status><strong>Forest Heart waits beneath the grove.</strong><span>First kill raises the level cap to 20.</span></div><Button variant="danger" onClick={() => engageBoss('forest-heart')}>Engage Forest Heart <ChevronRight size={15} /></Button></div>}</Card>
      <Card className="enemy-card" title={enemy ? enemy.name : 'No current enemy'} action={enemy ? <Status tone={enemy.boss ? 'warning' : 'active'}>{enemy.boss ? 'Boss Fight' : 'Normal Monster'}</Status> : <Status>{combat.active ? 'Next encounter' : 'Idle'}</Status>}><div className={`enemy-portrait ${enemy?.boss ? 'boss' : ''}`} style={{ '--enemy-color': enemy?.color ?? '#8c83b5' } as React.CSSProperties}><div className="enemy-aura" /><span>{enemy?.boss ? '♛' : enemy ? '◈' : '∅'}</span></div>{enemy ? <><h2 className="enemy-name">{enemy.name}</h2><p className="muted center">{enemy.subtitle}</p><Progress value={combat.enemyHp / combat.enemyMaxHp * 100} tone={enemy.boss ? 'red' : 'violet'} label="Enemy Health" right={`${formatNumber(combat.enemyHp)} / ${formatNumber(combat.enemyMaxHp)}`} /><div className="trait-row">{enemy.traits.map((trait) => <Tooltip key={trait.name} text={trait.description}><span className="trait">{trait.name}</span></Tooltip>)}</div></> : <div className="empty-state">{combat.active ? `Next encounter in ${formatTime(combat.encounterTimerMs)}` : 'Enter the woods to begin.'}</div>}<div className="combat-statline"><span>Basic attack <strong>{BALANCE.player.basicAttackDamage + (useGameStore.getState().equipment.weapon === 'ember-staff' ? 4 : 0)} dmg / 2.2s</strong></span><span>Enemy actions <strong>data-driven</strong></span></div></Card>
    </div>
    <div className="combat-bottom"><Card title="Spell Bar" className="spell-card" action={<span className="muted">Manual cast costs Mana · Auto-Cast costs 15 Focus</span>}><div className="spell-list">{(Object.keys(SPELLS) as SpellId[]).map((id) => { const spell = SPELLS[id]; const isUnlocked = unlocked.includes(id); const auto = combat.active && useGameStore.getState().activities.autoCast[id]; return <div key={id} className={`spell-row ${isUnlocked ? '' : 'locked'}`}><div className="spell-mini" style={{ color: SCHOOLS[spell.school].color }}>{SCHOOLS[spell.school].glyph}</div><div className="spell-copy"><strong>{spell.name}</strong><small>{isUnlocked ? `${spell.manaCost} Mana · ${spell.damage ? `${spell.damage} damage` : `${spell.barrier} barrier`}` : `Unlock ${SCHOOLS[spell.school].name} Level 2`}</small></div><Button variant={auto ? 'success' : 'ghost'} disabled={!isUnlocked || !combat.active} onClick={() => toggleAutoCast(id)}>{auto ? 'Auto-Casting' : 'Auto-Cast'}</Button><Button disabled={!isUnlocked || !combat.active || combat.spellCooldowns[id] > 0} onClick={() => castSpell(id)}>{combat.spellCooldowns[id] > 0 ? formatTime(combat.spellCooldowns[id]) : 'Cast'}</Button></div> })}</div></Card><Card title="Combat Log" className="log-card"><div className="combat-log">{combat.log.length ? combat.log.map((line, index) => <div key={`${line}-${index}`} className={index === 0 ? 'latest' : ''}><span>{String(combat.log.length - index).padStart(2, '0')}</span>{line}</div>) : <div className="empty-state">Combat events will appear here.</div>}</div></Card></div>
  </div>
}

function InventoryScreen() {
  const inventory = useGameStore((state) => state.inventory)
  const progress = useGameStore((state) => state.progress)
  return <div className="screen-content"><ScreenHeader kicker="TOWER VAULT · INVENTORY" title="Everything the tower has earned." description="Materials are persistent. Loot fuels Research, Transmutation, and the next decision." /><Card title="Materials & loot" action={<span className="muted">{Object.values(inventory).filter((quantity) => (quantity ?? 0) > 0).length} discovered stacks</span>}><div className="inventory-grid">{(Object.keys(ITEMS) as ItemId[]).map((id) => { const item = ITEMS[id]; const quantity = inventory[id] ?? 0; return <div key={id} className={`inventory-item ${quantity ? '' : 'empty'}`}><div className="item-icon" style={{ color: item.color }}>{item.icon}</div><div><strong>{item.name}</strong><small>{item.kind === 'equipment' ? 'Equipment' : item.description}</small></div><b>×{formatNumber(quantity)}</b></div> })}</div></Card><Card title="Protection rules" className="info-card"><div className="info-columns"><div><ShieldCheck size={19} /><strong>Safe progression</strong><p>Death never removes inventory, XP, or lifetime kills.</p></div><div><Sparkles size={19} /><strong>Discovery</strong><p>{progress.discoveredMonsters.length} of 5 creatures discovered in the collection.</p></div><div><RotateCcw size={19} /><strong>Repeatable</strong><p>Dungeon loot remains farmable after first-kill rewards.</p></div></div></Card></div>
}

function EquipmentScreen() {
  const weapon = useGameStore((state) => state.equipment.weapon)
  const inventory = useGameStore((state) => state.inventory)
  const progress = useGameStore((state) => state.progress)
  return <div className="screen-content"><ScreenHeader kicker="WIZARD LOADOUT" title="A small build, a real difference." description="The MVP has one weapon slot. The Ember Staff improves every Basic Attack and persists through defeat." /><div className="equipment-layout"><Card title="Weapon slot" className="equipment-card"><div className="equipment-slot"><div className="equipment-art" style={{ color: ITEMS[weapon].color }}>{ITEMS[weapon].icon}</div><div><Status tone="success">Equipped</Status><h2>{ITEMS[weapon].name}</h2><p>{ITEMS[weapon].description}</p></div></div><div className="stat-compare"><div><span>Basic Attack</span><strong>{BALANCE.player.basicAttackDamage} damage</strong></div><ChevronRight /><div><span>With Ember Staff</span><strong className="positive">+4 damage</strong></div></div></Card><Card title="Available upgrade" className="upgrade-card"><div className="upgrade-head"><div className="equipment-art small" style={{ color: ITEMS['ember-staff'].color }}>{ITEMS['ember-staff'].icon}</div><div><h2>Ember Staff</h2><p>Transmute it in the Wizard Tower after Grove Sentinel is defeated.</p></div></div><div className="cost-line"><span>Wisp Essence <strong>{inventory['wisp-essence'] ?? 0} / 4</strong></span><span>Fire Fragment <strong>{inventory['fire-fragment'] ?? 0} / 4</strong></span></div><Status tone={progress.emberStaffUnlocked ? 'active' : 'locked'}>{progress.emberStaffUnlocked ? 'Recipe available in Transmutation' : 'Locked · Defeat Grove Sentinel'}</Status></Card></div></div>
}

function GuildScreen() {
  const progress = useGameStore((state) => state.progress)
  const inventory = useGameStore((state) => state.inventory)
  if (!progress.guildUnlocked) return <div className="screen-content"><ScreenHeader kicker="THE VERDANT CIRCLE" title="A guild invitation, still sealed." description="Defeat Grove Sentinel to unlock the Guild, starter Requests, and the Initiate → Apprentice rank path." /><div className="locked-screen"><div className="locked-seal"><Lock size={28} /></div><h2>Guild Locked</h2><p>The forest guardian holds the first letter of introduction.</p><Button onClick={() => useGameStore.getState().setScreen('combat')}><Swords size={16} /> Go to Combat</Button></div></div>
  return <div className="screen-content"><ScreenHeader kicker="THE VERDANT CIRCLE" title="Your first guild hall." description="Requests turn the same materials and kills into long-term progression. Guild Shop is intentionally beyond this MVP." /><div className="guild-banner"><div className="guild-emblem">✤</div><div><Status tone="success">Unlocked</Status><h2>Verdant Circle</h2><p>Three starter Requests · Rank {progress.guildRank === 'outsider' ? 'Initiate' : 'Apprentice'}</p></div><div className="rank-step"><span>Initiate</span><ChevronRight /><strong>Apprentice</strong></div></div><div className="request-grid"><RequestCard title="A Spark for the Hall" description="Donate Fire Fragments to light the guild hearth." progress={Math.min(3, inventory['fire-fragment'] ?? 0)} target={3} reward="Guild standing" /><RequestCard title="Woods Report" description="Defeat creatures in Whispering Woods." progress={Math.min(5, progress.lifetimeKills)} target={5} reward="Rank progress" /><RequestCard title="Sentinel Proof" description="The guild recognizes the guardian’s defeat." progress={progress.firstBossKill ? 1 : 0} target={1} reward="Forest Heart access" /></div></div>
}

function RequestCard({ title, description, progress, target, reward }: { title: string; description: string; progress: number; target: number; reward: string }) { const done = progress >= target; return <Card className={`request-card ${done ? 'done' : ''}`}><div className="request-icon">{done ? <Check size={20} /> : <Target size={20} />}</div><div><Status tone={done ? 'success' : 'neutral'}>{done ? 'Completed' : 'Request'}</Status><h3>{title}</h3><p>{description}</p><Progress value={progress / target * 100} tone="gold" right={`${progress} / ${target}`} /><small>Reward · {reward}</small></div></Card> }

function CollectionScreen() {
  const discovered = useGameStore((state) => state.progress.discoveredMonsters)
  const kills = useGameStore((state) => state.progress.lifetimeKills)
  return <div className="screen-content"><ScreenHeader kicker="FIELD NOTES" title="Collection" description="Every encounter leaves a trace. Traits are visible before the fight so the wizard can plan." /><Card title="Whispering Woods bestiary" action={<span className="muted">{discovered.length} / 5 discovered · {kills} lifetime kills</span>}><div className="collection-grid">{(Object.keys(MONSTERS) as (keyof typeof MONSTERS)[]).map((id) => { const monster = MONSTERS[id]; const isFound = discovered.includes(id); return <div className={`collection-entry ${isFound ? 'found' : ''}`} key={id}><div className="collection-creature" style={{ '--enemy-color': monster.color } as React.CSSProperties}>{isFound ? monster.boss ? '♛' : '◈' : '?'}</div><div><strong>{isFound ? monster.name : 'Undiscovered'}</strong><small>{isFound ? monster.subtitle : 'Encounter it in the woods.'}</small>{isFound && <div className="trait-row">{monster.traits.map((trait) => <span className="trait" key={trait.name}>{trait.name}</span>)}</div>}</div></div> })}</div></Card></div>
}

function SettingsScreen() {
  const setScreen = useGameStore((state) => state.setScreen)
  const saveGame = useGameStore((state) => state.saveGame)
  const resetSave = useGameStore((state) => state.resetSave)
  const setDebug = useGameStore((state) => state.setDebug)
  const toggleEditMode = useGameStore((state) => state.toggleEditMode)
  const debug = useGameStore((state) => state.ui.showDebug)
  const editMode = useGameStore((state) => state.ui.editMode)
  return <div className="screen-content"><ScreenHeader kicker="TOWER SYSTEMS" title="Settings / Info" description="Local-only save controls and developer tools for testing the first vertical slice." /><div className="settings-grid"><Card title="Save" className="settings-card"><div className="setting-row"><div><strong>Local save</strong><small>Autosaves every 15 seconds and on demand.</small></div><Button variant="success" onClick={saveGame}><Save size={15} /> Save now</Button></div><div className="setting-row"><div><strong>Reset gameplay state</strong><small>Returns to a fresh Apprentice Wand save.</small></div><Button variant="danger" onClick={() => { if (window.confirm('Reset the current save?')) resetSave() }}><RotateCcw size={15} /> Reset save</Button></div></Card><Card title="Developer tools" className="settings-card"><div className="setting-row"><div><strong>Testing panel</strong><small>Changes here modify the current save.</small></div><Button variant={debug ? 'success' : 'secondary'} onClick={() => setDebug(!debug)}>{debug ? 'Hide tools' : 'Show tools'}</Button></div><div className="setting-row"><div><strong>UI Edit mode</strong><small>Highlights panels for local layout inspection.</small></div><Button variant={editMode ? 'success' : 'secondary'} onClick={toggleEditMode}>{editMode ? 'Exit edit mode' : 'Edit layout'}</Button></div><div className="setting-row"><div><strong>Visual atmosphere</strong><small>Subtle Three.js particles are non-essential to gameplay.</small></div><Status tone="active">Enabled</Status></div></Card><Card title="MVP rules" className="settings-card full"><div className="rules-list"><Rule text="Combat, Research, and Transmutation continue when you navigate." /><Rule text="Focus is reserved, never spent, and pausing releases it." /><Rule text="Death resets Threat Cleared but keeps inventory, XP, and lifetime kills." /><Rule text="Forest Heart’s first kill raises the Magic School cap from 10 to 20." /></div></Card></div><div className="footer-note">SSS Wizard · First Playable MVP · local save version 1</div></div>
}
function Rule({ text }: { text: string }) { return <div><Check size={15} />{text}</div> }

function DebugPanel() {
  const open = useGameStore((state) => state.ui.showDebug)
  const setPlayer = useGameStore((state) => state.setPlayer)
  const setSchoolDebug = useGameStore((state) => state.setSchoolDebug)
  const unlockAll = useGameStore((state) => state.unlockAllSpells)
  const setThreat = useGameStore((state) => state.setThreat)
  const addItem = useGameStore((state) => state.addItem)
  const engage = useGameStore((state) => state.engageBoss)
  const kill = useGameStore((state) => state.killCurrentEnemy)
  const enter = useGameStore((state) => state.enterDungeon)
  const preset = useGameStore((state) => state.preset)
  if (!open) return null
  return <aside className="debug-panel"><div className="debug-head"><div><span>DEVELOPER TOOLS</span><strong>Current save mutation</strong></div><CircleHelp size={16} /></div><p>Changes here modify the current save.</p><div className="debug-buttons"><Button variant="ghost" onClick={() => { setPlayer({ health: 100, mana: 100 }); setThreat(20) }}>Fill HP / Mana</Button><Button variant="ghost" onClick={() => setPlayer({ maxFocus: 140 })}>Max Focus 140</Button><Button variant="ghost" onClick={() => setPlayer({ godMode: true })}>God Mode</Button><Button variant="ghost" onClick={() => setSchoolDebug('fire', 180, 10)}>Fire Level 10</Button><Button variant="ghost" onClick={unlockAll}>Unlock MVP spells</Button><Button variant="ghost" onClick={() => { addItem('fire-fragment', 12); addItem('wisp-essence', 8) }}>Add materials</Button><Button variant="ghost" onClick={() => { enter(); setThreat(20) }}>Combat ready</Button><Button variant="danger" onClick={kill}>Kill current enemy</Button><Button variant="success" onClick={() => engage('grove-sentinel')}>Spawn Sentinel</Button><Button variant="danger" onClick={() => engage('forest-heart')}>Spawn Forest Heart</Button></div><div className="debug-presets"><span>Presets</span><button onClick={() => preset('fresh')}>Fresh</button><button onClick={() => preset('research')}>Research</button><button onClick={() => preset('combat')}>Combat</button><button onClick={() => preset('boss')}>Boss</button><button onClick={() => preset('main-boss')}>Main Boss</button></div></aside>
}

function TowerControlGlyph() { return <span /> }
