import type { ItemId, ArtificingRecipeId, DungeonId, RecipeUnlockCondition } from '../../types'
export interface ArtificingRecipeDefinition {
 id: ArtificingRecipeId
 name: string
 output: { itemId: ArtificingRecipeId; quantity: 1 }
 ingredients: { itemId: ItemId; quantity: number }[]
 unlock: RecipeUnlockCondition
 sourceDungeonId: DungeonId
 description?: string
 baseDurationMs: number
}
const whisperingWoodsMonsterKill: RecipeUnlockCondition = { type: 'dungeon-monster-kills', dungeonId: 'whispering-woods', count: 1 }
const howlingDen: RecipeUnlockCondition = { type: 'dungeon-monster-kills', dungeonId: 'howling-den', count: 1 }
const abandonedCatacombs: RecipeUnlockCondition = { type: 'dungeon-monster-kills', dungeonId: 'abandoned-catacombs', count: 1 }

const equipmentRecipe = (id: ArtificingRecipeId, name: string, ingredients: { itemId: ItemId; quantity: number }[], sourceDungeonId: DungeonId, unlock: RecipeUnlockCondition, description: string): ArtificingRecipeDefinition => ({ id, name, output: { itemId: id, quantity: 1 }, ingredients, sourceDungeonId, unlock, baseDurationMs: 5000, description })
export const ARTIFICING_RECIPES: Record<ArtificingRecipeId, ArtificingRecipeDefinition> = {
  'ember-staff': equipmentRecipe('ember-staff', 'Ember Staff', [{ itemId: 'fire-fragment', quantity: 20 }, { itemId: 'wisp-essence', quantity: 10 }, { itemId: 'thorn-fiber', quantity: 10 }, { itemId: 'grove-bark', quantity: 5 }, { itemId: 'life-essence', quantity: 24 }], 'whispering-woods', whisperingWoodsMonsterKill, 'A blackened staff veined with embers that never cool; each reforging wakes a deeper furnace sealed within its core.'),
  'tideglass-wand': equipmentRecipe('tideglass-wand', 'Tideglass Wand', [{ itemId: 'water-fragment', quantity: 20 }, { itemId: 'wisp-essence', quantity: 7 }, { itemId: 'rootstone-shard', quantity: 8 }, { itemId: 'grove-bark', quantity: 5 }, { itemId: 'life-essence', quantity: 25 }], 'whispering-woods', whisperingWoodsMonsterKill, 'Sea-blue glass beads with cold water even in dry air, bending every incantation into a steadier and more deliberate current.'),
  'stoneheart-scepter': equipmentRecipe('stoneheart-scepter', 'Stoneheart Scepter', [{ itemId: 'earth-fragment', quantity: 20 }, { itemId: 'rootstone-shard', quantity: 10 }, { itemId: 'grove-bark', quantity: 10 }, { itemId: 'life-essence', quantity: 25 }], 'whispering-woods', whisperingWoodsMonsterKill, 'Carved around a living stone core, the scepter answers every spell with a deeper pulse, as though the earth itself were listening.'),
  'windthread-wand': equipmentRecipe('windthread-wand', 'Windthread Wand', [{ itemId: 'air-fragment', quantity: 20 }, { itemId: 'wisp-essence', quantity: 5 }, { itemId: 'thorn-fiber', quantity: 10 }, { itemId: 'grove-bark', quantity: 5 }, { itemId: 'life-essence', quantity: 25 }], 'whispering-woods', whisperingWoodsMonsterKill, 'Silverwood bound with threads of captive wind trembles before a spell is spoken, snapping released magic forward like a drawn bowstring.'),
  'wispweave-robe': equipmentRecipe('wispweave-robe', 'Wispweave Robe', [{ itemId: 'wisp-essence', quantity: 15 }, { itemId: 'thorn-fiber', quantity: 15 }, { itemId: 'grove-bark', quantity: 10 }, { itemId: 'rootstone-shard', quantity: 10 }, { itemId: 'life-essence', quantity: 25 }], 'whispering-woods', whisperingWoodsMonsterKill, 'Pale spirit-thread tightens around incoming force as though unseen hands were pulling every stitch into place at the moment of impact.'),
  'wispveil-hood': equipmentRecipe('wispveil-hood', 'Wispveil Hood', [{ itemId: 'wisp-essence', quantity: 10 }, { itemId: 'thorn-fiber', quantity: 10 }, { itemId: 'rootstone-shard', quantity: 5 }, { itemId: 'grove-bark', quantity: 5 }, { itemId: 'prismatic-fragment', quantity: 5 }, { itemId: 'life-essence', quantity: 25 }], 'whispering-woods', whisperingWoodsMonsterKill, 'Violet mist clings to the inside of this hood; beneath its veil, wandering thoughts sharpen and hostile enchantments struggle to take hold.'),
  'windthread-charm': equipmentRecipe('windthread-charm', 'Windthread Charm', [{ itemId: 'air-fragment', quantity: 40 }, { itemId: 'wisp-essence', quantity: 8 }, { itemId: 'thorn-fiber', quantity: 12 }, { itemId: 'grove-bark', quantity: 9 }], 'whispering-woods', whisperingWoodsMonsterKill, 'A knot of silver thread wound around a captured gust, keeping a sliver of the mind clear even while several spells compete for attention.'),
  'grovekeeper-mantle': equipmentRecipe('grovekeeper-mantle', 'Grovekeeper Mantle', [{ itemId: 'earth-fragment', quantity: 30 }, { itemId: 'rootstone-shard', quantity: 14 }, { itemId: 'grove-bark', quantity: 14 }, { itemId: 'thorn-fiber', quantity: 8 }], 'whispering-woods', whisperingWoodsMonsterKill, 'Living fibers run through bark-soft cloth, stiffening under impact like a grove closing ranks around its keeper.'),
  'wispglass-earring': equipmentRecipe('wispglass-earring', 'Wispglass Earring', [{ itemId: 'wisp-essence', quantity: 10 }, { itemId: 'thorn-fiber', quantity: 8 }, { itemId: 'rootstone-shard', quantity: 8 }, { itemId: 'air-fragment', quantity: 18 }, { itemId: 'prismatic-fragment', quantity: 2 }], 'whispering-woods', whisperingWoodsMonsterKill, 'A loop of translucent wispglass rings without sound whenever mana slips from a spell, drawing the loose current back toward its wearer.'),
  'wispbound-ring': equipmentRecipe('wispbound-ring', 'Wispbound Ring', [{ itemId: 'water-fragment', quantity: 22 }, { itemId: 'air-fragment', quantity: 22 }, { itemId: 'wisp-essence', quantity: 10 }, { itemId: 'grove-bark', quantity: 8 }, { itemId: 'rootstone-shard', quantity: 7 }], 'whispering-woods', whisperingWoodsMonsterKill, 'A pale ring that drinks the mana left between incantations and returns it in a slow, steady pulse against the wearer\'s hand.'),
  'heartseed-necklace': equipmentRecipe('heartseed-necklace', 'Heartseed Necklace', [{ itemId: 'heartseed', quantity: 8 }, { itemId: 'rootstone-shard', quantity: 8 }, { itemId: 'grove-bark', quantity: 10 }, { itemId: 'thorn-fiber', quantity: 2 }, { itemId: 'life-essence', quantity: 10 }], 'whispering-woods', { type: 'boss-kill', bossId: 'forest-heart' }, 'The seed still beats faintly against the chest; when its wearer falters, roots of light flare outward before the killing blow can land.'),
  'predator-hide-mantle': equipmentRecipe('predator-hide-mantle', 'Predator-Hide Mantle', [{ itemId: 'predator-hide', quantity: 20 }, { itemId: 'predator-sinew', quantity: 14 }, { itemId: 'predator-fang', quantity: 10 }, { itemId: 'corrupted-beast-essence', quantity: 8 }, { itemId: 'earth-fragment', quantity: 14 }], 'howling-den', howlingDen, 'Cured from hides steeped in corrupted moonlight, the mantle carries a hunter\'s stubbornness and refuses to let wounds slow the chase.'),
  'fangwire-earring': equipmentRecipe('fangwire-earring', 'Fangwire Earring', [{ itemId: 'predator-fang', quantity: 18 }, { itemId: 'predator-sinew', quantity: 14 }, { itemId: 'corrupted-beast-essence', quantity: 8 }, { itemId: 'predator-hide', quantity: 6 }, { itemId: 'air-fragment', quantity: 32 }], 'howling-den', howlingDen, 'A predator fang hung from blackened wire warms against the skin when an opening appears, turning hesitation into a sharper strike.'),
  'howling-signet': equipmentRecipe('howling-signet', 'Howling Signet', [{ itemId: 'corrupted-beast-essence', quantity: 16 }, { itemId: 'predator-fang', quantity: 10 }, { itemId: 'predator-sinew', quantity: 8 }, { itemId: 'predator-hide', quantity: 5 }, { itemId: 'water-fragment', quantity: 22 }, { itemId: 'air-fragment', quantity: 22 }], 'howling-den', howlingDen, 'Scratched with the marks of successful hunts, the signet drinks the last warmth of a fallen foe and feeds it back into its bearer.'),
  'greatbear-heartstone': equipmentRecipe('greatbear-heartstone', 'Greatbear Heartstone', [{ itemId: 'greatbear-core', quantity: 8 }, { itemId: 'predator-hide', quantity: 9 }, { itemId: 'predator-sinew', quantity: 4 }, { itemId: 'predator-fang', quantity: 2 }, { itemId: 'corrupted-beast-essence', quantity: 9 }], 'howling-den', { type: 'boss-kill', bossId: 'corrupted-greatbear' }, 'A fist-sized core that pulses with the Greatbear\'s refusal to die, gathering shattered magic around the same stubborn rhythm.'),
  'ossuary-mantle': equipmentRecipe('ossuary-mantle', 'Ossuary Mantle', [{ itemId: 'ossuary-remnant', quantity: 20 }, { itemId: 'burial-cloth', quantity: 14 }, { itemId: 'soul-residue', quantity: 10 }, { itemId: 'graveglass-shard', quantity: 8 }, { itemId: 'prismatic-fragment', quantity: 2 }], 'abandoned-catacombs', abandonedCatacombs, 'Catacomb bone is stitched beneath dark cloth, each shard remembering a different element and dulling the bite of magic that strikes it.'),
  'mourning-glass-earring': equipmentRecipe('mourning-glass-earring', 'Mourning Glass Earring', [{ itemId: 'graveglass-shard', quantity: 18 }, { itemId: 'soul-residue', quantity: 12 }, { itemId: 'burial-cloth', quantity: 10 }, { itemId: 'ossuary-remnant', quantity: 8 }, { itemId: 'prismatic-fragment', quantity: 4 }], 'abandoned-catacombs', abandonedCatacombs, 'A sliver of graveglass polished with soul residue catches the dying echo of a curse and refuses to let the whisper fade too quickly.'),
  'gravebinder-ring': equipmentRecipe('gravebinder-ring', 'Gravebinder Ring', [{ itemId: 'graveglass-shard', quantity: 12 }, { itemId: 'soul-residue', quantity: 12 }, { itemId: 'ossuary-remnant', quantity: 12 }, { itemId: 'burial-cloth', quantity: 12 }], 'abandoned-catacombs', abandonedCatacombs, 'Tiny runes crawl around this graveglass band whenever an enemy is afflicted, tightening with every weakness already laid upon them.'),
  'edrins-signet': equipmentRecipe('edrins-signet', "Edrin's Signet", [{ itemId: 'edrin-remnant', quantity: 20 }, { itemId: 'burial-cloth', quantity: 8 }, { itemId: 'soul-residue', quantity: 6 }, { itemId: 'graveglass-shard', quantity: 5 }, { itemId: 'ossuary-remnant', quantity: 5 }], 'abandoned-catacombs', { type: 'boss-kill', bossId: 'archmage-edrin-shade' }, "The Archmage's broken seal still carries a fragment of his warding instinct, raising a pale remnant whenever hostile magic takes hold."),
  'soulglass-amulet': equipmentRecipe('soulglass-amulet', 'Soulglass Amulet', [{ itemId: 'edrin-remnant', quantity: 8 }, { itemId: 'graveglass-shard', quantity: 5 }, { itemId: 'soul-residue', quantity: 9 }, { itemId: 'ossuary-remnant', quantity: 4 }, { itemId: 'burial-cloth', quantity: 4 }, { itemId: 'prismatic-fragment', quantity: 2 }], 'abandoned-catacombs', { type: 'boss-kill', bossId: 'archmage-edrin-shade' }, "A shard of soulglass bound around the echo of Edrin's final spell; curses linger near it as though unwilling to leave."),
}
export const ARTIFICING_RECIPE_ORDER: readonly ArtificingRecipeId[] = ["ember-staff","tideglass-wand","stoneheart-scepter","windthread-wand","wispweave-robe","wispveil-hood","windthread-charm","grovekeeper-mantle","wispglass-earring","wispbound-ring","heartseed-necklace","predator-hide-mantle","fangwire-earring","howling-signet","greatbear-heartstone","ossuary-mantle","mourning-glass-earring","gravebinder-ring","edrins-signet","soulglass-amulet"]
