import type { MonsterId } from '../../../types'
import { authorExpansionNormalAt, hit, normalAction, status } from '../expansion/authoring'

const zone = 'cinderhex-barrens'
const huntingGround = { family: 'Cinderhex Scavengers', alignment: 'Corrupted', contractTier: 'routine' as const, minimumRank: 'warden' as const, exclusive: true, contractRequired: true, huntingGroundId: zone }
export const CINDERHEX_BARRENS_NORMALS = [
  authorExpansionNormalAt(zone, 8, 0, { id: 'hexjaw-hyena', name: 'Hexjaw Hyena', subtitle: 'A scavenger with a rune-scarred muzzle and a pack’s confidence.', affinity: 'arcane', resonance: 8, hunter: huntingGround, specials: [normalAction('first-special', 'Hex Bite', { damage: [hit('arcane', 1.2)], status: status('cursed') }), normalAction('second-special', 'Pack Echo', { damage: [hit('arcane', 1.4)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 8, 1, { id: 'runehide-scavenger', name: 'Runehide Scavenger', subtitle: 'A broad-backed prowler armoring itself with stolen glyphs.', affinity: 'arcane', resonance: 8, hunter: huntingGround, specials: [normalAction('first-special', 'Rune Rend', { damage: [hit('arcane', 1.3)] }), normalAction('second-special', 'Scavenged Ward', { barrier: .06 })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 8, 2, { id: 'glasshorn-beast', name: 'Glasshorn Beast', subtitle: 'A charging grazer whose crystal horns refract the scorched horizon.', affinity: 'arcane', resonance: 8, hunter: huntingGround, specials: [normalAction('first-special', 'Prism Charge', { damage: [hit('arcane', 1.5)] }), normalAction('second-special', 'Glasshide', { status: status('fortified', 'self') })], pattern: ['second', 'basic', 'first', 'basic'] }),
  authorExpansionNormalAt(zone, 8, 3, { id: 'ashmane-lion', name: 'Ashmane Lion', subtitle: 'A territorial cat stalking the barrens with embers in its mane.', affinity: 'fire', resonance: 8, hunter: huntingGround, specials: [normalAction('first-special', 'Ember Pounce', { damage: [hit('fire', 1.35)], status: status('burning') }), normalAction('second-special', 'Roaring Heat', { status: status('haste', 'self') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 8, 4, { id: 'emberback-rhino', name: 'Emberback Rhino', subtitle: 'A heavy browser with a furnace-hot ridge and scorched hide.', affinity: 'fire', resonance: 8, hunter: huntingGround, specials: [normalAction('first-special', 'Cinder Charge', { damage: [hit('fire', 1.65)] }), normalAction('second-special', 'Furnace Hide', { status: status('fortified', 'self') })], pattern: ['second', 'basic', 'first', 'basic'] }),
  authorExpansionNormalAt(zone, 8, 5, { id: 'dustshell-tortoise', name: 'Dustshell Tortoise', subtitle: 'A slow hunter carrying a layered shell of ash-hardened stone.', affinity: 'earth', resonance: 8, hunter: huntingGround, specials: [normalAction('first-special', 'Shell Ram', { damage: [hit('earth', 1.3)] }), normalAction('second-special', 'Dustshell', { barrier: .1 })], pattern: ['second', 'basic', 'first', 'basic'] }),
  authorExpansionNormalAt(zone, 8, 6, { id: 'galeclaw-vulture', name: 'Galeclaw Vulture', subtitle: 'A scavenger circling over the barrens on hot rising air.', affinity: 'air', resonance: 8, hunter: huntingGround, specials: [normalAction('first-special', 'Gale Talon', { damage: [hit('air', 1.2)], status: status('bleeding') }), normalAction('second-special', 'Carrion Dive', { damage: [hit('air', 1.5)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
] satisfies readonly ReturnType<typeof authorExpansionNormalAt>[]
export const CINDERHEX_BARRENS_ROSTER = CINDERHEX_BARRENS_NORMALS.map(({ id }) => id as MonsterId)
