import type { MonsterId } from '../../../types'
import { authorExpansionNormalAt, hit, normalAction, status } from '../expansion/authoring'

const zone = 'mistclaw-highlands'
const huntingGround = { family: 'Highland Stalkers', alignment: 'Wild', contractTier: 'routine' as const, minimumRank: 'warden' as const, exclusive: true, contractRequired: true, huntingGroundId: zone }
export const MISTCLAW_HIGHLANDS_NORMALS = [
  authorExpansionNormalAt(zone, 7, 0, { id: 'mistclaw-lynx', name: 'Mistclaw Lynx', subtitle: 'A highland ambusher whose paws vanish in the cliff mist.', affinity: 'air', resonance: 8, hunter: huntingGround, specials: [normalAction('first-special', 'Mist Pounce', { damage: [hit('air', 1.4)] }), normalAction('second-special', 'Claw Flurry', { damage: [hit('air', .675)], hitCount: 2 })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 7, 1, { id: 'stormhorn-elk', name: 'Stormhorn Elk', subtitle: 'A great antlered grazer charging through the storm-wet pines.', affinity: 'air', resonance: 8, hunter: huntingGround, specials: [normalAction('first-special', 'Gale Charge', { damage: [hit('air', 1.5)] }), normalAction('second-special', 'Storm Antlers', { damage: [hit('air', 1.05)], status: status('shock') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 7, 2, { id: 'razorwing-kite', name: 'Razorwing Kite', subtitle: 'A cliff-dwelling bird sweeping low over the mountain streams.', affinity: 'air', resonance: 8, hunter: huntingGround, specials: [normalAction('first-special', 'Razor Sweep', { damage: [hit('air', 1.3)] }), normalAction('second-special', 'Updraft', { status: status('haste', 'self') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 7, 3, { id: 'riverhide-boar', name: 'Riverhide Boar', subtitle: 'A thick-skinned boar rooting through cold streams and fern beds.', affinity: 'water', resonance: 8, hunter: huntingGround, specials: [normalAction('first-special', 'River Rush', { damage: [hit('water', 1.5)] }), normalAction('second-special', 'Thick Hide', { status: status('fortified', 'self') })], pattern: ['second', 'basic', 'first', 'basic'] }),
  authorExpansionNormalAt(zone, 7, 4, { id: 'cloudwater-serpent', name: 'Cloudwater Serpent', subtitle: 'A pale serpent rising from cloud-fed pools above the treeline.', affinity: 'water', resonance: 8, hunter: huntingGround, specials: [normalAction('first-special', 'Mist Bite', { damage: [hit('water', 1.2)], status: status('chilled') }), normalAction('second-special', 'Cloudcoil', { damage: [hit('water', .8), hit('air', .5)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 7, 5, { id: 'runemark-stag', name: 'Runemark Stag', subtitle: 'A wild stag with old Arcane sigils glowing beneath its coat.', affinity: 'arcane', resonance: 8, hunter: huntingGround, specials: [normalAction('first-special', 'Rune Gore', { damage: [hit('arcane', 1.3)] }), normalAction('second-special', 'Leyflash', { damage: [hit('arcane', 1.05)], status: status('vulnerable') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 7, 6, { id: 'slateback-yak', name: 'Slateback Yak', subtitle: 'A sure-footed grazer with a slate ridge along its shoulders.', affinity: 'earth', resonance: 8, hunter: huntingGround, specials: [normalAction('first-special', 'Slate Charge', { damage: [hit('earth', 1.6)] }), normalAction('second-special', 'Stone Hide', { status: status('fortified', 'self') })], pattern: ['second', 'basic', 'first', 'basic'] }),
] satisfies readonly ReturnType<typeof authorExpansionNormalAt>[]
export const MISTCLAW_HIGHLANDS_ROSTER = MISTCLAW_HIGHLANDS_NORMALS.map(({ id }) => id as MonsterId)
