import { Check, Lock } from 'lucide-react'
import { FRAGMENT_ORDER, SCHOOLS } from '../../game/data/schools'
import { SPELLS } from '../../game/data/spells'
import { schoolProgress } from '../../game/engine'
import { useGameStore } from '../../store/gameStore'
import { formatNumber } from '../../game/utils'
import { Button, Card, Progress } from '../../components/ui'
import { EditableGrid } from '../../ui/layout-editor/EditableGrid'

export function MagicSchoolsScreenV2() {
  const schools = useGameStore((state) => state.schools); const cap = useGameStore((state) => state.progress.magicLevelCap); const unlocked = useGameStore((state) => state.progress.unlockedSpells); const setScreen = useGameStore((state) => state.setScreen); const game = useGameStore.getState()
  const schoolCards = FRAGMENT_ORDER.map((id) => { const school = SCHOOLS[id]; const state = schools[id]; const spells = Object.values(SPELLS).filter((spell) => spell.school === id).sort((a, b) => a.unlockLevel - b.unlockLevel); return { id: `school-${id}`, content: <Card className="school-card" style={{ borderTopColor: school.color } as React.CSSProperties}><div className="school-card-head"><div className="school-glyph" style={{ color: school.color }}>{school.glyph}</div><div><h2>{school.name}</h2><p>{school.tagline}</p></div><span className="school-level">{state.level}<small>LV</small></span></div><Progress value={schoolProgress(game, id) * 100} tone={id} label="School XP" right={<>{formatNumber(state.xp)} XP</>} /><div className="school-cap"><span>Level cap</span><strong>{state.level >= cap ? 'Level Cap Reached' : cap}</strong></div><div className="school-spells">{spells.map((spell) => { const known = unlocked.includes(spell.id); return <div className={`spell-unlock ${known ? 'unlocked' : ''}`} key={spell.id}><span className="spell-icon">✦</span><div><strong>{spell.name} <small>Lv {spell.unlockLevel}</small></strong><small>{known ? spell.description : `Unlock at School Level ${spell.unlockLevel}`}</small></div>{known ? <Check size={17} /> : <Lock size={15} />}</div> })}</div><div className="next-unlock">Next unlock <strong>{spells.find((spell) => !unlocked.includes(spell.id))?.name ?? 'All first-chapter spells known'}</strong></div></Card> } })
  return <div className="screen-content"><div className="screen-header"><div><div className="eyebrow">MAGIC SCHOOL ARCHIVE</div><h1>Four paths, one Focus pool.</h1><p>Research any elemental fragment into any school. Matching affinity is stronger, but the target school is always your choice.</p></div><Button variant="secondary" onClick={() => setScreen('tower-research')}>Open Crucible</Button></div><EditableGrid screen="schools" panels={[...schoolCards, { id: 'school-ceiling', content: <Card title="Level ceiling" className="ceiling-card"><div className="ceiling-line"><span className="ceiling-number">{cap}</span><div><strong>Magic School level cap</strong><p className="muted">Forest Heart raises the first chapter ceiling from 10 to 20. Research queues pause safely at the cap.</p></div><div className="ceiling-arrow">{cap >= 20 ? '20' : '10'} → 20</div></div></Card> }]} /></div>
}
