import { Shield, Sparkles } from 'lucide-react'
import { ITEMS } from '../../game/data/items'
import type { EquipmentSlot, ItemId } from '../../game/types'
import { equipmentStats } from '../../game/engine'
import { useGameStore } from '../../store/gameStore'
import { selectPlayerBasicDamage } from '../../store/selectors'
import { Button, Card, Status } from '../../components/ui'
import { EditableGrid } from '../../ui/layout-editor/EditableGrid'

const slots: EquipmentSlot[] = ['weapon', 'robe', 'focus', 'charm']
export function EquipmentScreenV2() {
  const equipment = useGameStore((state) => state.equipment); const inventory = useGameStore((state) => state.inventory); const player = useGameStore((state) => state.player); const equipItem = useGameStore((state) => state.equipItem); const unequipItem = useGameStore((state) => state.unequipItem); const stats = equipmentStats({ equipment }); const basicDamage = useGameStore(selectPlayerBasicDamage); const available = (Object.keys(ITEMS) as ItemId[]).filter((id) => ITEMS[id].kind === 'equipment' && (inventory[id] ?? 0) > 0)
  const loadout = <Card title="Loadout" action={<Status tone="success">{available.length} owned pieces</Status>}><div className="equipment-slots">{slots.map((slot) => { const itemId = equipment[slot]; const item = itemId ? ITEMS[itemId] : null; return <div className="equipment-slot-row" key={slot}><div className="slot-label"><span>{slot}</span><small>{slot === 'weapon' ? 'Basic damage' : slot === 'robe' ? 'Survival' : slot === 'focus' ? 'Mana / barriers' : 'Automation'}</small></div><div className="slot-item">{item ? <><div className="item-icon" style={{ color: item.color }}>{item.icon}</div><div><strong>{item.name}</strong><small>{Object.entries(item.stats ?? {}).map(([key, value]) => `${key}: ${value}`).join(' · ') || 'Starter equipment'}</small></div><Button variant="ghost" onClick={() => unequipItem(slot)}>Unequip</Button></> : <span className="muted">Empty slot</span>}</div></div> })}</div></Card>
  const statsPanel = <Card title="Derived stats" action={<Sparkles size={16} color="var(--gold)" />}><div className="derived-stats"><div><span>Max Health</span><strong>{player.maxHealth}</strong></div><div><span>Max Mana</span><strong>{player.maxMana}</strong></div><div><span>Max Focus</span><strong>{player.maxFocus}</strong></div><div><span>Basic Damage</span><strong>{basicDamage}</strong></div><div><span>Fire Spell Damage</span><strong>+{Math.round((stats.fireSpellDamagePct ?? 0) * 100)}%</strong></div><div><span>Water Barrier</span><strong>+{Math.round((stats.waterBarrierPct ?? 0) * 100)}%</strong></div></div><div className="equipment-note"><Shield size={15} /><span>Equipped items are always protected from Research, donations, and recipes.</span></div></Card>
  const owned = <Card title="Owned equipment"><div className="owned-equipment-grid">{available.map((id) => { const item = ITEMS[id]; const equipped = Object.values(equipment).includes(id); return <div className={`owned-piece ${equipped ? 'equipped' : ''}`} key={id}><div className="item-icon" style={{ color: item.color }}>{item.icon}</div><div><strong>{item.name}</strong><small>{item.equipmentSlot} · {Object.entries(item.stats ?? {}).map(([key, value]) => `${key}: ${value}`).join(' · ') || 'Starter equipment'}</small></div><Button variant={equipped ? 'success' : 'secondary'} onClick={() => equipItem(id)}>{equipped ? 'Equipped' : 'Equip'}</Button></div> })}</div></Card>
  return <div className="screen-content"><div className="screen-header"><div><div className="eyebrow">WIZARD LOADOUT</div><h1>Build the tower’s answer.</h1><p>Equipment is owned independently from its slot. Equip, replace, and keep every item safe in the Inventory.</p></div></div><EditableGrid screen="equipment" panels={[{ id: 'equipment-loadout', content: loadout }, { id: 'equipment-stats', content: statsPanel }, { id: 'equipment-owned', content: owned }]} /></div>
}
