import type { MonsterId } from '../../../types'
import { authorExpansionNormalAt, hit, normalAction, status } from '../expansion/authoring'

const zone = 'abyssal-reservoir'
export const ABYSSAL_RESERVOIR_NORMALS = [
  authorExpansionNormalAt(zone, 5, 0, { id: 'depthbound-knight', name: 'Depthbound Knight', subtitle: 'A drowned sentinel weighed down by the reservoir’s crushing pressure.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Pressure Slash', { damage: [hit('water', 1.4)] }), normalAction('second-special', 'Pressure Guard', { status: status('fortified', 'self') })], pattern: ['second', 'basic', 'first', 'basic'] }),
  authorExpansionNormalAt(zone, 5, 1, { id: 'pressure-wraith', name: 'Pressure Wraith', subtitle: 'A translucent shape shuddering in the deep machinery’s current.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Compression Wave', { damage: [hit('water', 1.25)], status: status('staggered') }), normalAction('second-special', 'Phase Drift', { status: status('spectral-fade', 'self') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 5, 2, { id: 'brine-hulk', name: 'Brine Hulk', subtitle: 'A swollen brute dragging mineral crust through the flooded halls.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Brine Slam', { damage: [hit('water', 1.6)] }), normalAction('second-special', 'Saline Recovery', { heal: .06 })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 5, 3, { id: 'glassfin-horror', name: 'Glassfin Horror', subtitle: 'A razor-finned predator circling through the reservoir’s dark water.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Glassfin Rend', { damage: [hit('water', 1.25)], status: status('bleeding') }), normalAction('second-special', 'Undertow Dash', { damage: [hit('water', 1.1)], delayOpponentMs: 350 })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 5, 4, { id: 'undertow-priest', name: 'Undertow Priest', subtitle: 'A keeper of the lower sanctum singing into a flooded mask.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Undertow Bolt', { damage: [hit('water', 1.15)] }), normalAction('second-special', 'Deep Mend', { heal: .07 })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 5, 5, { id: 'nullwater-scribe', name: 'Nullwater Scribe', subtitle: 'A submerged archivist etching Arcane formulae into the pressure field.', affinity: 'arcane', resonance: 8, specials: [normalAction('first-special', 'Nullwater Script', { damage: [hit('arcane', 1.15)], status: status('arcane-disruption') }), normalAction('second-special', 'Pressure Rune', { damage: [hit('water', 1), hit('arcane', .45)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 5, 6, { id: 'stormcurrent-hunter', name: 'Stormcurrent Hunter', subtitle: 'A swift predator that follows charged currents through submerged ruins.', affinity: 'air', resonance: 8, specials: [normalAction('first-special', 'Current Spear', { damage: [hit('air', 1.05), hit('water', .55)] }), normalAction('second-special', 'Slipstream', { status: status('haste', 'self') })], pattern: ['first', 'basic', 'second', 'basic'] }),
] satisfies readonly ReturnType<typeof authorExpansionNormalAt>[]
export const ABYSSAL_RESERVOIR_ROSTER = ABYSSAL_RESERVOIR_NORMALS.map(({ id }) => id as MonsterId)
