import type { MonsterId } from '../../../types'
import { makeCombatMonster, type CombatMonsterSpec } from '../combatMonsterAuthoring'
import type { MonsterDefinition } from '../monsterTypes'

const specs: CombatMonsterSpec[] = [
  { locationId: 'graveglass-hollow', id: 'graveglass-shade', combatV2: true, primaryAffinity: 'water', basicAttackElement: 'water', targetPower: 5700, name: 'Graveglass Shade', subtitle: 'A reflection that learned how to curse the living', hp: 3125, damage: 98, defense: 34, time: 2300, resonanceYield: { water: 24, earth: 12 }, icon: { portraitIcon: 'ghost' }, specials: [{ id: 'graveglass-touch', name: 'Graveglass Touch', damage: [{ type: 'arcane', coefficient: 1.35 }], status: { id: 'cursed' } }, { id: 'shard-step', name: 'Shard Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { locationId: 'graveglass-hollow', id: 'bone-shardling', combatV2: true, primaryAffinity: 'earth', basicAttackElement: 'earth', targetPower: 5950, name: 'Bone Shardling', subtitle: 'A splinter of a tomb animated by pressure', hp: 2313, damage: 100, defense: 45, time: 2300, resonanceYield: { earth: 34 }, specials: [{ id: 'shard-rend', name: 'Shard Rend', damage: [{ type: 'earth', coefficient: 1.45 }], status: { id: 'fragile' } }, { id: 'bone-wall', name: 'Bone Wall', barrier: 0.05 }] },
  { locationId: 'graveglass-hollow', id: 'silent-mourner', combatV2: true, primaryAffinity: 'water', basicAttackElement: 'water', targetPower: 6200, name: 'Silent Mourner', subtitle: 'A mourner whose grief has outlived its voice', hp: 2125, damage: 92, defense: 32, time: 2300, resonanceYield: { water: 32 }, icon: { portraitIcon: 'ghost' }, specials: [{ id: 'mourning-curse', name: 'Mourning Curse', damage: [{ type: 'arcane', coefficient: 1.1 }], status: { id: 'cursed' } }, { id: 'quiet-step', name: 'Quiet Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { locationId: 'graveglass-hollow', id: 'crypt-guardian', combatV2: true, primaryAffinity: 'earth', basicAttackElement: 'earth', targetPower: 6450, name: 'Crypt Guardian', subtitle: 'A sealed defender carrying a garden of grave moss', hp: 2875, damage: 90, defense: 62, time: 2300, resonanceYield: { earth: 38 }, specials: [{ id: 'crypt-ward', name: 'Crypt Ward', barrier: 0.09 }, { id: 'grave-regrowth', name: 'Grave Regrowth', description: 'The Guardian braces against incoming damage with Fortified.', status: { id: 'fortified', target: 'self' } }] },
  { locationId: 'graveglass-hollow', id: 'epitaph-weaver', combatV2: true, primaryAffinity: 'arcane', basicAttackElement: 'arcane', targetPower: 6800, name: 'Epitaph Weaver', subtitle: 'A curse-caster stitching warnings into grave glass', hp: 3000, damage: 108, defense: 42, time: 2400, resonanceYield: { water: 38, earth: 16 }, icon: { portraitIcon: 'mage' }, specials: [{ id: 'epitaph-hex', name: 'Epitaph Hex', damage: [{ type: 'arcane', coefficient: 1.3 }], status: { id: 'cursed' } }, { id: 'funeral-glass', name: 'Funeral Glass', barrier: 0.08 }] },
  { locationId: 'graveglass-hollow', id: 'tombglass-reaver', combatV2: true, primaryAffinity: 'earth', basicAttackElement: 'earth', targetPower: 7200, name: 'Tombglass Reaver', subtitle: 'A shard-armored raider that breaks wards by force', hp: 3900, damage: 116, defense: 58, time: 2250, resonanceYield: { earth: 52, water: 20 }, icon: { portraitIcon: 'guardian' }, specials: [{ id: 'shard-cleave', name: 'Shard Cleave', damage: [{ type: 'earth', coefficient: 1.45 }], status: { id: 'fragile' } }, { id: 'refracted-step', name: 'Refracted Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { locationId: 'graveglass-hollow', id: 'ossuary-oracle', combatV2: true, primaryAffinity: 'arcane', basicAttackElement: 'arcane', targetPower: 7600, name: 'Ossuary Oracle', subtitle: 'A bone seer whose warnings arrive as curses', hp: 3500, damage: 122, defense: 50, time: 2500, resonanceYield: { water: 58, earth: 24 }, icon: { portraitIcon: 'mage' }, specials: [{ id: 'ossuary-omen', name: 'Ossuary Omen', damage: [{ type: 'arcane', coefficient: 1.55 }], status: { id: 'cursed' } }, { id: 'bone-sentence', name: 'Bone Sentence', damage: [{ type: 'arcane', coefficient: 1.25 }], status: { id: 'arcane-disruption' } }] },
  { locationId: 'graveglass-hollow', id: 'graveglass-behemoth', combatV2: true, primaryAffinity: 'earth', basicAttackElement: 'earth', targetPower: 9100, name: 'Graveglass Behemoth', subtitle: 'A giant of tomb glass and accumulated sorrow', hp: 25000, damage: 116, defense: 78, time: 2600, resistances: { arcane: 0.15 }, resonanceYield: { earth: 90, water: 70 }, boss: true, specials: [{ id: 'shard-break', name: 'Shard Break', damage: [{ type: 'earth', coefficient: 1.6 }], status: { id: 'fragile' } }, { id: 'grave-curse', name: 'Grave Curse', status: { id: 'cursed' } }, { id: 'crystal-burst', name: 'Crystal Burst', damage: [{ type: 'arcane', coefficient: 1.7 }] }, { id: 'graveglass-ward', name: 'Graveglass Ward', barrier: 0.1 }, { id: 'behemoth-crush', name: 'Behemoth Crush', actionTimeMs: 3200, damage: [{ type: 'earth', coefficient: 2.15 }] }] },
]

export const GRAVEGLASS_HOLLOW_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeCombatMonster(spec)])) as Record<MonsterId, MonsterDefinition>
