import type { MonsterId } from '../../../types'
import { authorExpansionNormalAt, hit, normalAction, status } from '../expansion/authoring'

const zone = 'pyrehold-bastion'
export const PYREHOLD_BASTION_NORMALS = [
  authorExpansionNormalAt(zone, 4, 0, { id: 'furnace-guard', name: 'Furnace Guard', subtitle: 'A fortress sentinel sealed inside heat-darkened plate.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Brand Cleave', { damage: [hit('fire', 1.4)] }), normalAction('second-special', 'Furnace Shield', { barrier: .1 })], pattern: ['second', 'basic', 'first', 'basic'] }),
  authorExpansionNormalAt(zone, 4, 1, { id: 'molten-penitent', name: 'Molten Penitent', subtitle: 'A former soldier carrying a mantle of slow-burning slag.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Penance Flame', { damage: [hit('fire', 1.2)], status: status('burning') }), normalAction('second-special', 'Last Ember', { status: status('haste', 'self') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 4, 2, { id: 'ashen-duelist', name: 'Ashen Duelist', subtitle: 'A quick blade-master fighting through a curtain of pale ash.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Twin Brands', { damage: [hit('fire', .75), hit('fire', .75)] }), normalAction('second-special', 'Riposte Veil', { status: status('spectral-fade', 'self') })], pattern: ['first', 'basic', 'second', 'first', 'basic'] }),
  authorExpansionNormalAt(zone, 4, 3, { id: 'brandkeeper', name: 'Brandkeeper', subtitle: 'A warding acolyte tending the fortress’s ancient fire seals.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Searing Seal', { damage: [hit('fire', 1.15)], status: status('kindled') }), normalAction('second-special', 'Brand Wall', { barrier: .08 })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 4, 4, { id: 'cinder-apostle', name: 'Cinder Apostle', subtitle: 'A zealot whose ash-dark prayers condemn intruders to the pyre.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Pyre Sermon', { damage: [hit('fire', .85)], status: status('cursed') }), normalAction('second-special', 'Flame Catechism', { damage: [hit('fire', 1.6)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 4, 5, { id: 'steamvein-marauder', name: 'Steamvein Marauder', subtitle: 'A raider wrapped in pressurized vapor from the fortress vents.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Scalding Slash', { damage: [hit('water', 1), hit('fire', .5)] }), normalAction('second-special', 'Steam Guard', { status: status('fortified', 'self') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 4, 6, { id: 'smokeveil-assassin', name: 'Smokeveil Assassin', subtitle: 'A silent infiltrator who disappears into the bastion’s drifting soot.', affinity: 'air', resonance: 8, specials: [normalAction('first-special', 'Smoke Cut', { damage: [hit('air', 1.25)], status: status('bleeding') }), normalAction('second-special', 'Vanish', { status: status('spectral-fade', 'self') })], pattern: ['first', 'basic', 'second', 'first'] }),
] satisfies readonly ReturnType<typeof authorExpansionNormalAt>[]
export const PYREHOLD_BASTION_ROSTER = PYREHOLD_BASTION_NORMALS.map(({ id }) => id as MonsterId)
