import type { MonsterId } from '../../../types'
import { authorExpansionNormalAt, hit, normalAction, status } from '../expansion/authoring'

const zone = 'scalding-rift'
export const SCALDING_RIFT_NORMALS = [
  authorExpansionNormalAt(zone, 6, 0, { id: 'scaldspawn', name: 'Scaldspawn', subtitle: 'A heat-born crawler erupting from the rift’s boiling pools.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Scald Claw', { damage: [hit('fire', 1.2)], status: status('burning') }), normalAction('second-special', 'Steam Burst', { damage: [hit('fire', .8), hit('water', .55)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 6, 1, { id: 'furnace-serpent', name: 'Furnace Serpent', subtitle: 'A molten coil winding through the cracks in the volcanic stone.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Coil Flame', { damage: [hit('fire', 1.35)] }), normalAction('second-special', 'Boiling Shed', { heal: .05 })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 6, 2, { id: 'redsteam-reaver', name: 'Redsteam Reaver', subtitle: 'A raider surging from vents in a cloud of red-hot vapor.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Redsteam Cleave', { damage: [hit('fire', 1.5)] }), normalAction('second-special', 'Vapor Rush', { status: status('haste', 'self') })], pattern: ['second', 'basic', 'first', 'basic'] }),
  authorExpansionNormalAt(zone, 6, 3, { id: 'boilborn-slime', name: 'Boilborn Slime', subtitle: 'A translucent mass pulsing with pockets of trapped steam.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Boiling Splash', { damage: [hit('water', .7), hit('fire', .55)] }), normalAction('second-special', 'Steam Shell', { barrier: .07 })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 6, 4, { id: 'pressure-eel', name: 'Pressure Eel', subtitle: 'A narrow-bodied hunter darting between molten and flooded channels.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Pressure Bite', { damage: [hit('water', 1.3)] }), normalAction('second-special', 'Discharge', { damage: [hit('water', .8), hit('air', .55)], status: status('shock') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 6, 5, { id: 'vaporbound-siren', name: 'Vaporbound Siren', subtitle: 'A drowned voice luring travelers toward the rift’s boiling edge.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Scalding Song', { damage: [hit('water', 1)], status: status('cursed') }), normalAction('second-special', 'Vapor Veil', { status: status('spectral-fade', 'self') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 6, 6, { id: 'brineforged-brute', name: 'Brineforged Brute', subtitle: 'A hulking guardian plated in mineral crust from the flooded fault.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Brine Hammer', { damage: [hit('water', 1.5)] }), normalAction('second-special', 'Scald Plate', { status: status('fortified', 'self') })], pattern: ['second', 'basic', 'first', 'basic'] }),
] satisfies readonly ReturnType<typeof authorExpansionNormalAt>[]
export const SCALDING_RIFT_ROSTER = SCALDING_RIFT_NORMALS.map(({ id }) => id as MonsterId)
