import type { MonsterId } from '../../../types'
import { makeCombatMonster, type CombatMonsterSpec } from '../combatMonsterAuthoring'
import type { MonsterDefinition } from '../monsterTypes'

const specs: CombatMonsterSpec[] = [
  { locationId: 'starfallen-observatory', id: 'starbound-eye', combatV2: true, primaryAffinity: 'arcane', basicAttackElement: 'arcane', targetPower: 5800, name: 'Starbound Eye', subtitle: 'A watching star that never learned mercy', hp: 2625, damage: 100, defense: 38, time: 2300, resonanceYield: { arcane: 30, air: 24, fire: 16 }, resistances: { arcane: 0.2 }, icon: { portraitIcon: 'wisp' }, specials: [{ id: 'star-gaze', name: 'Star Gaze', damage: [{ type: 'arcane', coefficient: 1.35 }], status: { id: 'arcane-disruption' } }, { id: 'orbit', name: 'Orbit', status: { id: 'spectral-fade', target: 'self' } }] },
  { locationId: 'starfallen-observatory', id: 'astral-husk', combatV2: true, primaryAffinity: 'arcane', basicAttackElement: 'arcane', targetPower: 6100, name: 'Astral Husk', subtitle: 'A shell left behind when an astronomer vanished', hp: 2250, damage: 98, defense: 50, time: 2300, resonanceYield: { arcane: 25, air: 20, fire: 12 }, resistances: { arcane: 0.25 }, specials: [{ id: 'astral-hammer', name: 'Astral Hammer', damage: [{ type: 'arcane', coefficient: 1.55 }] }, { id: 'dead-orbit', name: 'Dead Orbit', status: { id: 'fragile' } }] },
  { locationId: 'starfallen-observatory', id: 'orbiting-fragment', combatV2: true, primaryAffinity: 'arcane', basicAttackElement: 'arcane', targetPower: 6400, name: 'Orbiting Fragment', subtitle: 'A piece of the fallen star that refuses to land', hp: 2250, damage: 105, defense: 46, time: 2300, resonanceYield: { arcane: 35, air: 28, fire: 18 }, specials: [{ id: 'orbital-ward', name: 'Orbital Ward', barrier: 0.07 }, { id: 'falling-fragment', name: 'Falling Fragment', damage: [{ type: 'arcane', coefficient: 1.5 }] }] },
  { locationId: 'starfallen-observatory', id: 'lenskeeper-remnant', combatV2: true, primaryAffinity: 'arcane', basicAttackElement: 'arcane', targetPower: 6750, name: 'Lenskeeper Remnant', subtitle: 'A ruined curator still aligning the observatory lens', hp: 2563, damage: 96, defense: 44, time: 2300, resonanceYield: { arcane: 45, air: 36, fire: 16 }, specials: [{ id: 'broken-lens', name: 'Broken Lens', damage: [{ type: 'arcane', coefficient: 1.2 }], status: { id: 'arcane-disruption' } }, { id: 'focus-shift', name: 'Momentum Shift', status: { id: 'haste', target: 'self' } }] },
  { locationId: 'starfallen-observatory', id: 'comet-wraith', combatV2: true, primaryAffinity: 'fire', basicAttackElement: 'fire', targetPower: 7100, name: 'Comet Wraith', subtitle: 'A burning wraith that crosses the sky in a single breath', hp: 3100, damage: 116, defense: 36, time: 2200, resonanceYield: { fire: 42, air: 22 }, icon: { portraitIcon: 'ghost' }, specials: [{ id: 'comet-trail', name: 'Comet Trail', damage: [{ type: 'fire', coefficient: 1.1 }], dot: { statusId: 'burning', damageType: 'fire', coefficient: 1.1, durationMs: 5000 } }, { id: 'stellar-drift', name: 'Stellar Drift', status: { id: 'spectral-fade', target: 'self' } }] },
  { locationId: 'starfallen-observatory', id: 'voidglass-custodian', combatV2: true, primaryAffinity: 'arcane', basicAttackElement: 'arcane', targetPower: 7500, name: 'Voidglass Custodian', subtitle: "A silent custodian guarding the observatory's last lens", hp: 4100, damage: 120, defense: 64, time: 2700, resonanceYield: { arcane: 60, air: 48, fire: 24 }, icon: { portraitIcon: 'guardian' }, specials: [{ id: 'voidglass-ward', name: 'Voidglass Ward', barrier: 0.09 }, { id: 'refraction-burst', name: 'Refraction Burst', damage: [{ type: 'arcane', coefficient: 1.6 }], status: { id: 'arcane-disruption' } }] },
  { locationId: 'starfallen-observatory', id: 'zenith-horror', combatV2: true, primaryAffinity: 'fire', basicAttackElement: 'fire', targetPower: 7900, name: 'Zenith Horror', subtitle: 'A thing at the highest point where fire and air become one', hp: 3700, damage: 130, defense: 50, time: 2300, resonanceYield: { fire: 60, air: 30 }, icon: { portraitIcon: 'wisp' }, specials: [{ id: 'zenith-ray', name: 'Zenith Ray', damage: [{ type: 'fire', coefficient: 0.8 }, { type: 'air', coefficient: 0.8 }] }, { id: 'gravity-shear', name: 'Gravity Shear', damage: [{ type: 'arcane', coefficient: 1.5 }], status: { id: 'fragile' } }] },
  { locationId: 'starfallen-observatory', id: 'fallen-astromancer', combatV2: true, primaryAffinity: 'arcane', basicAttackElement: 'arcane', targetPower: 9300, name: 'Fallen Astromancer', subtitle: 'A scholar who mapped the sky until the sky answered', hp: 26000, damage: 120, defense: 72, time: 2500, resistances: { arcane: 0.25 }, resonanceYield: { arcane: 100, fire: 80, air: 80 }, boss: true, specials: [{ id: 'astral-ray', name: 'Astral Ray', damage: [{ type: 'arcane', coefficient: 1.4 }] }, { id: 'collapsed-orbit', name: 'Collapsed Orbit', description: 'A three-part Fire, Air, and Arcane strike dealing 1.8× Basic damage in total.', damage: [{ type: 'fire', coefficient: 0.6 }, { type: 'air', coefficient: 0.6 }, { type: 'arcane', coefficient: 0.6 }] }, { id: 'arcane-distortion', name: 'Arcane Distortion', status: { id: 'arcane-disruption' } }, { id: 'star-ward', name: 'Star Ward', barrier: 0.09 }, { id: 'falling-star', name: 'Falling Star', actionTimeMs: 3200, damage: [{ type: 'arcane', coefficient: 2.2 }] }] },
]

export const STARFALLEN_OBSERVATORY_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeCombatMonster(spec)])) as Record<MonsterId, MonsterDefinition>
