import type { MonsterId } from '../../../types'
import { makeCombatMonster, type CombatMonsterSpec } from '../combatMonsterAuthoring'
import { action, basic } from '../monsterTypes'
import type { MonsterDefinition } from '../monsterTypes'

const specs: CombatMonsterSpec[] = [
  { combatV2: true, locationId: 'black-gate', id: 'gatebound-remnant', name: 'Gatebound Remnant', subtitle: 'A fragment of a guardian still defending the threshold', hp: 6000, damage: 140, defense: 78, targetPower: 14000, primaryAffinity: 'earth', basicAttackElement: 'earth', specials: [{ id: 'gate-cleave', name: 'Gate Cleave', damage: [{ type: 'earth', coefficient: 1.6 }] }, { id: 'threshold-stance', name: 'Threshold Stance', status: { id: 'fortified', target: 'self' } }] },
  { combatV2: true, locationId: 'black-gate', id: 'black-rift-stalker', name: 'Black Rift Stalker', subtitle: 'A hunter that lives in the gap behind the portal', hp: 5375, damage: 148, defense: 55, targetPower: 14500, primaryAffinity: 'air', basicAttackElement: 'air', resistances: { arcane: .15 }, icon: { portraitIcon: 'claw' }, specials: [{ id: 'rift-claw', name: 'Rift Claw', damage: [{ type: 'air', coefficient: 1.1 }, { type: 'arcane', coefficient: .6 }], status: { id: 'corruption' } }, { id: 'void-step', name: 'Void Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { combatV2: true, locationId: 'black-gate', id: 'portalbound-acolyte', name: 'Portalbound Acolyte', subtitle: 'A final supplicant waiting for the gate to answer', hp: 5625, damage: 145, defense: 60, targetPower: 15000, primaryAffinity: 'arcane', basicAttackElement: 'arcane', resonanceYield: { arcane: 10 }, icon: { portraitIcon: 'mage' }, specials: [{ id: 'portal-hex', name: 'Portal Hex', damage: [{ type: 'arcane', coefficient: .65 }], status: { id: 'cursed' } }, { id: 'mute-sigil', name: 'Mute Sigil', damage: [{ type: 'arcane', coefficient: .65 }], status: { id: 'silenced' } }] },
  { combatV2: true, locationId: 'black-gate', id: 'sealbreaker-construct', name: 'Sealbreaker Construct', subtitle: 'A machine built to break every seal except its own', hp: 6500, damage: 138, defense: 95, targetPower: 15500, primaryAffinity: 'earth', basicAttackElement: 'earth', specials: [{ id: 'blackgate-ward', name: 'Blackgate Ward', barrier: .1 }, { id: 'sealbreaker-crush', name: 'Sealbreaker Crush', damage: [{ type: 'earth', coefficient: 1.7 }] }, { id: 'seal-fracture', name: 'Seal Fracture', damage: [{ type: 'arcane', coefficient: 1.2 }] }] },
  { combatV2: true, locationId: 'black-gate', id: 'black-gatekeeper', name: 'Black Gatekeeper', subtitle: 'The final sentinel before the darkness beyond', hp: 65000, damage: 170, defense: 110, time: 2400, targetPower: 20000, primaryAffinity: 'arcane', basicAttackElement: 'arcane', resistances: { arcane: .2, fire: .1, water: .1, earth: .1, air: .1 }, resonanceYield: { arcane: 188, fire: 150, water: 150, earth: 150, air: 150 }, boss: true, trait: 'black-gatekeeper-unbound-phase', specials: [{ id: 'gatefire', name: 'Gatefire', damage: [{ type: 'fire', coefficient: 1.25 }] }, { id: 'abyssal-tide', name: 'Abyssal Tide', damage: [{ type: 'water', coefficient: 1.25 }] }, { id: 'broken-earth', name: 'Broken Earth', damage: [{ type: 'earth', coefficient: 1.25 }] }, { id: 'black-gale', name: 'Black Gale', damage: [{ type: 'air', coefficient: 1.25 }] }, { id: 'gate-seal', name: 'Gate Seal', barrier: .1 }, { id: 'portal-corruption', name: 'Portal Corruption', damage: [{ type: 'arcane', coefficient: 1 }], status: { id: 'corruption', stacks: 2 } }, { id: 'unspoken-lock', name: 'Unspoken Lock', damage: [{ type: 'arcane', coefficient: .8 }], status: { id: 'silenced' } }, { id: 'rift-convergence', name: 'Rift Convergence', damage: [{ type: 'fire', coefficient: .8 }, { type: 'water', coefficient: .8 }] }, { id: 'rupture-axis', name: 'Rupture Axis', damage: [{ type: 'earth', coefficient: .8 }, { type: 'air', coefficient: .8 }] }, { id: 'black-rupture', name: 'Black Rupture', actionTimeMs: 3400, damage: [{ type: 'arcane', coefficient: 2.5 }] }], actionPatterns: { sealed: { id: 'sealed', steps: [action('gatefire-step', 'gatefire'), basic('sealed-basic-1'), action('abyssal-tide-step', 'abyssal-tide'), basic('sealed-basic-2'), action('broken-earth-step', 'broken-earth'), basic('sealed-basic-3'), action('black-gale-step', 'black-gale'), action('gate-seal-step', 'gate-seal'), basic('sealed-basic-4')] }, unbound: { id: 'unbound', steps: [action('portal-corruption-step', 'portal-corruption'), basic('unbound-basic-1'), action('unspoken-lock-step', 'unspoken-lock'), basic('unbound-basic-2'), action('rift-convergence-step', 'rift-convergence'), basic('unbound-basic-3'), action('rupture-axis-step', 'rupture-axis'), action('gate-seal-phase-two-step', 'gate-seal'), basic('unbound-basic-4'), action('black-rupture-step', 'black-rupture'), basic('unbound-basic-5')] } }, defaultActionPatternId: 'sealed' },
]

export const BLACK_GATE_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeCombatMonster(spec)])) as Record<MonsterId, MonsterDefinition>
