import { createInitialState } from '../../store/initialState'
import { SCHOOLS } from '../../game/content/schools/schools'
import { TRANSMUTATION_RECIPE_ORDER } from '../../game/content/recipes/transmutationRecipes'
import type { SchoolId } from '../../game/types'
import { useDeveloperGameStore as store } from '../developerSandbox'
import { createDefaultScenarioReadyPreset, type DeveloperScenarioGroup, type ScenarioReadyPreset } from './scenarioReadyPresetStore'
import { openHunterContractInCombat } from '../../ui/navigation/hunterContractNavigation'

export interface BuiltInDeveloperScenario {
  id: string
  group: DeveloperScenarioGroup
  label: string
  summary: readonly string[]
  run: () => boolean | void
  testReady: { supportsTestReady: boolean; defaultReadyPresetId?: string }
  tags?: readonly string[]
  defaultReadyPreset?: ScenarioReadyPreset
}
const ready = (changes: Partial<ScenarioReadyPreset> & { stats?: Record<string, number> } = {}): ScenarioReadyPreset => ({ ...createDefaultScenarioReadyPreset(), ...changes, stats: { ...createDefaultScenarioReadyPreset().stats, ...changes.stats } })
export const BUILT_IN_DEVELOPER_SCENARIOS = (prepareCombatLoadout: () => void): readonly BuiltInDeveloperScenario[] => [
  { id: 'fresh-start', group: 'Foundation', label: 'Fresh Start', summary: ['Reset runtime game data to a new profile state', 'No normal profile save is written'], testReady: { supportsTestReady: false }, run: () => store.getState().hydrateState(createInitialState()), tags: ['profile', 'reset'] },
  { id: 'forest-heart', group: 'Combat', label: 'Forest Heart Ready', summary: ['Resolve the authored Whispering Woods threat', 'Prepare a spell loadout for the Forest Heart encounter'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'forest-heart' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 500, 'core.spellPowerFlat': 100, 'modifiers.defense-flat': 60 } }), run: () => { prepareCombatLoadout(); let state = store.getState(); state.despawnDebugEnemy(); state.fastResolveDebugEnemies(100, 'whispering-woods'); store.getState().jumpDebugToBoss('whispering-woods'); return store.getState().combat.enemyId === 'forest-heart' } },
  { id: 'greatbear', group: 'Combat', label: 'Howling Den / Greatbear Ready', summary: ['Resolve Forest Heart to satisfy the authored Howling Den unlock', 'Clear the Den threat and prepare the Greatbear encounter'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'greatbear' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 1200, 'core.spellPowerFlat': 220, 'modifiers.defense-flat': 120, 'modifiers.crit-chance': 0.08 } }), run: () => { prepareCombatLoadout(); let state = store.getState(); state.despawnDebugEnemy(); state.fastResolveDebugEnemies(100, 'whispering-woods'); store.getState().jumpDebugToBoss('whispering-woods'); if (store.getState().combat.enemyId !== 'forest-heart') return false; store.getState().killCurrentEnemy(); state = store.getState(); state.fastResolveDebugEnemies(100, 'howling-den'); store.getState().jumpDebugToBoss('howling-den'); return store.getState().combat.enemyId === 'corrupted-greatbear' } },
  { id: 'hunter-first', group: 'Hunter’s Order', label: 'Hunter’s Order — First Contract', summary: ['Unlock the Order through its tester action', 'Issue the starter routine contract'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'hunter-first' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 450, 'core.spellPowerFlat': 80, 'modifiers.defense-flat': 50 } }), run: () => { let state = store.getState(); if (state.progress.huntersOrder.activeContract) { state.debugGrantHunterMarks(100); state.skipHunterContract() } state = store.getState(); state.debugSetHunterRngSeed(341); state.debugSetHuntersOrderUnlocked(true); return state.issueFirstHunterContract() } },
  { id: 'gloamridge-contract', group: 'Hunter’s Order', label: 'Gloamridge — Active Contract', summary: ['Prepare a Warden rank and regional contract', 'Accept an authored Gloamridge target'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'gloamridge' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 1100, 'core.spellPowerFlat': 200, 'modifiers.defense-flat': 110, 'modifiers.crit-chance': 0.06 } }), run: () => { let state = store.getState(); if (state.progress.huntersOrder.activeContract) { state.debugGrantHunterMarks(100); state.skipHunterContract() } state = store.getState(); state.debugSetHunterRank('warden'); state.debugSetHunterRngSeed(912); state.debugRegenerateHunterContractBoard({ archetype: 'region', tier: 'special' }); const contract = store.getState().progress.huntersOrder.availableContracts[0]; return Boolean(contract?.targetSpec.type === 'region' && contract.targetSpec.dungeonId === 'hunters-ground' && store.getState().acceptHunterContract(contract.id)) } },
  { id: 'hunter-veteran', group: 'Hunter’s Order', label: 'Hunter’s Order — Veteran Progression', summary: ['Set the authored Veteran reputation threshold', 'Generate prestigious contract offers'], testReady: { supportsTestReady: false }, run: () => { let state = store.getState(); if (state.progress.huntersOrder.activeContract) { state.debugGrantHunterMarks(100); state.skipHunterContract() } state = store.getState(); state.debugSetHunterRank('veteran'); state.debugSetHunterRngSeed(17500); state.debugRegenerateHunterContractBoard({ tier: 'prestigious' }); return store.getState().progress.huntersOrder.availableContracts.length > 0 } },
  { id: 'hunter-new-quarry', group: 'Hunter’s Order', label: 'Gloamridge — Expanded Quarry', summary: ['Prepare the seven-creature Gloamridge quarry roster', 'Generate and accept a single-monster contract'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'gloamridge' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 950, 'core.spellPowerFlat': 180, 'modifiers.defense-flat': 90 } }), run: () => { let state = store.getState(); if (state.progress.huntersOrder.activeContract) { state.debugGrantHunterMarks(100); state.skipHunterContract() } state = store.getState(); state.debugSetHunterRank('scout'); state.debugSetHunterRngSeed(77); state.debugRegenerateHunterContractBoard({ archetype: 'monster', tier: 'special' }); const offer = store.getState().progress.huntersOrder.availableContracts.find((candidate) => candidate.targetSpec.type === 'monster'); return Boolean(offer && store.getState().acceptHunterContract(offer.id)) } },
  { id: 'nightglass-contract', group: 'Hunter’s Order', label: 'Nightglass Alpha — Master Quarry', summary: ['Generate and accept a prestigious Nightglass monster contract', 'Open Gloamridge with Nightglass selected; combat does not auto-start'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'nightglass' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 1600, 'core.maxManaFlat': 400, 'core.spellPowerFlat': 420, 'modifiers.defense-flat': 210, 'modifiers.crit-chance': 0.12 } }), run: () => { let state = store.getState(); if (state.progress.huntersOrder.activeContract) { state.debugGrantHunterMarks(100); state.skipHunterContract() } state = store.getState(); if (!state.debugGrantNightglassContract()) return false; const offer = store.getState().progress.huntersOrder.availableContracts.find((entry) => entry.targetSpec.type === 'monster' && entry.targetSpec.monsterId === 'nightglass-alpha'); if (!offer || !store.getState().acceptHunterContract(offer.id)) return false; prepareCombatLoadout(); const open = openHunterContractInCombat(store.getState(), store.getState().setScreen); return open && store.getState().combat.enemyId === null && store.getState().progress.huntersOrder.activeContract?.targetSpec.type === 'monster' } },
  { id: 'guild-early', group: 'Arcane Guild', label: 'Arcane Guild — Early Progression', summary: ['Unlock Arcane Guild through its tester action', 'Generate its accessible commission board'], testReady: { supportsTestReady: false }, run: () => { const state = store.getState(); state.setTutorialStageForDebug('complete'); state.debugSetArcaneGuildUnlocked(true); state.debugRegenerateGuildCommissionBoard() } },
  { id: 'guild-advancement', group: 'Arcane Guild', label: 'Arcane Guild — Advancement Test', summary: ['Prepare Magister rank and Advancement Points', 'Generate a prestigious commission board'], testReady: { supportsTestReady: false }, run: () => { const state = store.getState(); state.setTutorialStageForDebug('complete'); state.debugSetArcaneGuildUnlocked(true); state.debugSetGuildRank('magister'); state.debugGrantGuildPoint(12); state.debugRegenerateGuildCommissionBoard({ quality: 'prestigious' }) } },
  { id: 'guild-commission-chain', group: 'Arcane Guild', label: 'Arcane Guild — Commission Chain', summary: ['Prepare the authored Magister commission context', 'Generate a board for commission-chain regression checks'], testReady: { supportsTestReady: false }, run: () => { const state = store.getState(); state.setTutorialStageForDebug('complete'); state.debugSetArcaneGuildUnlocked(true); state.debugSetGuildRank('magister'); state.debugGrantGuildPoint(8); state.debugRegenerateGuildCommissionBoard({ quality: 'prestigious' }); return store.getState().progress.arcaneGuild.availableCommissions.length > 0 } },
  { id: 'research-stress', group: 'Tower Systems', label: 'Research Stress Test', summary: ['Prepare an authored fragment batch for each School', 'Assign available Acolytes through Research actions'], testReady: { supportsTestReady: false }, run: () => { const state = store.getState(); state.clearPreparedResearch(); (Object.keys(SCHOOLS) as SchoolId[]).forEach((school) => { const itemId = SCHOOLS[school].fragment; state.addItem(itemId, 100); state.prepareResearch(itemId, school, 50) }); state.assignOneResearchAcolyteEach() } },
  { id: 'transmutation-stress', group: 'Tower Systems', label: 'Transmutation Stress Test', summary: ['Prepare authored inputs and elemental Resonance', 'Generate Arcane Flux, then assign the Prismatic recipe'], testReady: { supportsTestReady: false }, run: () => { const state = store.getState(); state.clearPreparedResearch(); state.clearTransmutationAssignments(); (['fire', 'water', 'earth', 'air'] as const).forEach((type) => state.debugGrantResonance(type, 10_000)); for (const itemId of ['fire-fragment', 'water-fragment', 'earth-fragment', 'air-fragment', 'life-essence'] as const) state.addItem(itemId, 10_000); state.setDebugArcaneFluxCapacity(100_000); state.setDebugAcolyteTotalOverride(100); state.setDebugIgnoreAcolyteLimit(true); state.setChannelingAcolytesDebug(100); state.tick(60_000); const recipeId = TRANSMUTATION_RECIPE_ORDER.find((id) => id === 'prismatic-fragment'); if (!recipeId) return false; store.getState().assignMaxTransmutationAcolytes(recipeId) } },
]
