import { createInitialState } from '../../store/initialState'
import { SCHOOLS } from '../../game/content/schools/schools'
import { TRANSMUTATION_RECIPE_ORDER } from '../../game/content/recipes/transmutationRecipes'
import type { SchoolId } from '../../game/types'
import { useDeveloperGameStore as store } from '../developerSandbox'
import { createDefaultScenarioReadyPreset, type DeveloperScenarioGroup, type ScenarioReadyPreset } from './scenarioReadyPresetStore'
import { openHunterContractInCombat } from '../../ui/navigation/hunterContractNavigation'
import { isCombatLocationUnlocked } from '../../game/content/combat-locations'
import { COMBAT_LOCATIONS } from '../../game/content/combat-locations/worldNavigation'

export interface BuiltInDeveloperScenario {
  id: string
  group: DeveloperScenarioGroup
  label: string
  summary: readonly string[]
  run: () => boolean | void
  testReady: { supportsTestReady: boolean; defaultReadyPresetId?: string }
  tags?: readonly string[]
  defaultReadyPreset?: ScenarioReadyPreset
}
const ready = (changes: Partial<ScenarioReadyPreset> & { stats?: Record<string, number> } = {}): ScenarioReadyPreset => ({ ...createDefaultScenarioReadyPreset(), ...changes, stats: { ...createDefaultScenarioReadyPreset().stats, ...changes.stats } })
const prepareElementalScar = (bossIds: readonly string[] = []) => {
  const fixture = createInitialState()
  fixture.progress.bossKillsByBoss['archmage-edrin-shade'] = 1
  bossIds.forEach((bossId) => { fixture.progress.bossKillsByBoss[bossId as keyof typeof fixture.progress.bossKillsByBoss] = 1 })
  fixture.progress.chronicle.eventFlags['first-elemental-tutorial-boss-defeated'] = true
  store.getState().hydrateState(fixture)
  store.getState().chooseStartingSchool('fire')
  return store.getState()
}
const prepareShatteredMeridian = (bossIds: readonly string[] = []) => prepareElementalScar([
  'corrupted-elemental-gatekeeper', 'drowned-keeper', 'flamebound-revenant', 'rootscar-ancient', 'crossroads-keeper', ...bossIds,
])
const prepareBlackSigil = (blackSigilBossIds: readonly string[] = []) => prepareShatteredMeridian([
  'graveglass-behemoth', 'storm-archivist', 'fallen-astromancer', 'meridian-splitter', ...blackSigilBossIds,
])
const scarReadyPreset = ready({ stats: { 'core.maxHealthFlat': 1800, 'core.spellPowerFlat': 360, 'modifiers.defense-flat': 160 } })
export const BUILT_IN_DEVELOPER_SCENARIOS = (prepareCombatLoadout: () => void): readonly BuiltInDeveloperScenario[] => [
  { id: 'fresh-start', group: 'Foundation', label: 'Fresh Start', summary: ['Reset runtime game data to a new profile state', 'No normal profile save is written'], testReady: { supportsTestReady: false }, run: () => store.getState().hydrateState(createInitialState()), tags: ['profile', 'reset'] },
  ...(['fire', 'water', 'earth', 'air'] as const).map((schoolId) => ({ id: `fresh-${schoolId}`, group: 'Combat' as const, label: `Fresh ${schoolId[0].toUpperCase()}${schoolId.slice(1)} Starter`, summary: [`Reset to a fresh ${schoolId} starter`, 'Choose the authored tutorial counter zone'], testReady: { supportsTestReady: false }, run: () => { const fresh = createInitialState(); store.getState().hydrateState(fresh); return store.getState().chooseStartingSchool(schoolId) } })),
  { id: 'tutorial-boss-ready', group: 'Combat', label: 'Elemental Tutorial Boss Ready', summary: ['Choose a fresh Fire starter and enter its counter zone', 'Resolve tutorial threat and prepare the boss encounter'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'tutorial-boss' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 500, 'core.spellPowerFlat': 100 } }), run: () => { store.getState().hydrateState(createInitialState()); store.getState().chooseStartingSchool('fire'); prepareCombatLoadout(); store.getState().enterDungeon('stonewake-hollow'); store.getState().fastResolveDebugEnemies(100, 'stonewake-hollow'); store.getState().jumpDebugToBoss('stonewake-hollow'); return store.getState().combat.enemyId === 'heartstone-colossus' } },
  { id: 'whispering-unlocked', group: 'Combat', label: 'Whispering Woods Unlocked', summary: ['Set the tutorial boss Chronicle evidence in the sandbox', 'Enter the starter Combat Location'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'forest-heart' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 500, 'core.spellPowerFlat': 100 } }), run: () => { const fixture = createInitialState(); fixture.progress.chronicle.eventFlags['first-elemental-tutorial-boss-defeated'] = true; store.getState().hydrateState(fixture); prepareCombatLoadout(); store.getState().enterDungeon('whispering-woods'); return store.getState().combat.locationId === 'whispering-woods' } },
  { id: 'howling-unlocked', group: 'Combat', label: 'Howling Den Unlocked', summary: ['Set the Forest Heart milestone in the sandbox', 'Verify the authored gate and inspect the elite roster'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'greatbear' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 900, 'core.spellPowerFlat': 180 } }), run: () => { const fixture = createInitialState(); fixture.progress.bossKillsByBoss['forest-heart'] = 1; store.getState().hydrateState(fixture); if (!isCombatLocationUnlocked('howling-den', store.getState().progress)) return false; store.getState().chooseStartingSchool('fire'); prepareCombatLoadout(); store.getState().spawnDebugEnemy('cavefang-wolf', 'howling-den'); return store.getState().combat.locationId === 'howling-den' && store.getState().combat.enemyId === 'cavefang-wolf' } },
  { id: 'forest-heart', group: 'Combat', label: 'Forest Heart Ready', summary: ['Set tutorial completion, then prepare the Forest Heart encounter', 'Prepare a spell loadout to inspect boss mechanics'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'forest-heart' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 500, 'core.spellPowerFlat': 100, 'modifiers.defense-flat': 60 } }), run: () => { const fixture = createInitialState(); fixture.progress.chronicle.eventFlags['first-elemental-tutorial-boss-defeated'] = true; store.getState().hydrateState(fixture); store.getState().chooseStartingSchool('fire'); prepareCombatLoadout(); store.getState().spawnDebugEnemy('forest-heart', 'whispering-woods'); return store.getState().combat.enemyId === 'forest-heart' } },
  { id: 'greatbear', group: 'Combat', label: 'Howling Den / Greatbear Ready', summary: ['Set the Forest Heart milestone', 'Prepare the Corrupted Greatbear boss encounter'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'greatbear' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 1200, 'core.spellPowerFlat': 220, 'modifiers.defense-flat': 120, 'modifiers.crit-chance': 0.08 } }), run: () => { const fixture = createInitialState(); fixture.progress.chronicle.eventFlags['first-elemental-tutorial-boss-defeated'] = true; fixture.progress.bossKillsByBoss['forest-heart'] = 1; store.getState().hydrateState(fixture); store.getState().chooseStartingSchool('fire'); prepareCombatLoadout(); store.getState().spawnDebugEnemy('corrupted-greatbear', 'howling-den'); return store.getState().combat.enemyId === 'corrupted-greatbear' } },
  { id: 'catacombs-run', group: 'Combat', label: 'Abandoned Catacombs Fresh Run', summary: ['Set the Greatbear milestone in the sandbox', 'Prepare the fixed Catacombs sequence at its first encounter'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'edrin' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 1500, 'core.spellPowerFlat': 300 } }), run: () => { const fixture = createInitialState(); fixture.progress.bossKillsByBoss['corrupted-greatbear'] = 1; store.getState().hydrateState(fixture); store.getState().chooseStartingSchool('fire'); prepareCombatLoadout(); store.getState().spawnDebugEnemy('restless-skeleton', 'abandoned-catacombs'); return store.getState().combat.locationId === 'abandoned-catacombs' && store.getState().combat.enemyId === 'restless-skeleton' } },
  { id: 'edrin-unbound', group: 'Combat', label: 'Edrin — Unbound Phase', summary: ['Prepare the Catacombs boss encounter', 'Drop Edrin below half Health to inspect the Unbound phase'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'edrin' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 1800, 'core.spellPowerFlat': 380, 'modifiers.defense-flat': 180 } }), run: () => { const fixture = createInitialState(); fixture.progress.bossKillsByBoss['corrupted-greatbear'] = 1; store.getState().hydrateState(fixture); store.getState().chooseStartingSchool('fire'); prepareCombatLoadout(); store.getState().spawnDebugEnemy('archmage-edrin-shade', 'abandoned-catacombs'); if (store.getState().combat.enemyId !== 'archmage-edrin-shade') return false; store.getState().setEnemyHealthPercent(40); return store.getState().combat.enemyActionPatternId === 'unbound-opening' || store.getState().combat.enemyActionPatternId === 'unbound' } },
  { id: 'scar-edrin-cleared', group: 'Combat', label: 'Edrin Cleared / T2 Combat Paths Open', summary: ['Set Archmage Edrin completion in the sandbox', 'Verify Fractured Approach access'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'fractured-approach' }, defaultReadyPreset: scarReadyPreset, run: () => { prepareElementalScar(); return isCombatLocationUnlocked('fractured-approach', store.getState().progress) && !isCombatLocationUnlocked('flooded-reliquary', store.getState().progress) } },
  { id: 'scar-fractured-start', group: 'Combat', label: 'Fractured Approach Start', summary: ['Prepare the fixed sequence after Edrin', 'Start on the first encounter in the approved roster'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'fractured-approach' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareElementalScar(); prepareCombatLoadout(); state.enterDungeon('fractured-approach'); return store.getState().combat.enemyId === COMBAT_LOCATIONS['fractured-approach'].encounterSequence?.[0] } },
  { id: 'scar-gatekeeper', group: 'Combat', label: 'Gatekeeper Encounter', summary: ['Prepare Fractured Approach at its boss', 'Inspect the corrupted elemental phase pattern'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'fractured-approach' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareElementalScar(); prepareCombatLoadout(); state.enterDungeon('fractured-approach'); state.jumpDebugToBoss('fractured-approach'); return store.getState().combat.enemyId === 'corrupted-elemental-gatekeeper' } },
  { id: 'scar-guardian-ready', group: 'Combat', label: 'Guardian Selection Ready', summary: ['Set Gatekeeper completion', 'Open the Guardian selection progression point'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'elemental-scar' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareElementalScar(['corrupted-elemental-gatekeeper']); return isCombatLocationUnlocked('flooded-reliquary', state.progress) && !isCombatLocationUnlocked('crossroads-of-ruin', state.progress) } },
  { id: 'scar-flooded-boss', group: 'Combat', label: 'Flooded Boss Ready', summary: ['Set Gatekeeper completion', 'Prepare the Drowned Keeper encounter'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'drowned-keeper' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareElementalScar(['corrupted-elemental-gatekeeper']); prepareCombatLoadout(); state.spawnDebugEnemy('drowned-keeper', 'flooded-reliquary'); return store.getState().combat.enemyId === 'drowned-keeper' } },
  { id: 'scar-ashen-boss', group: 'Combat', label: 'Ashen Boss Ready', summary: ['Set Gatekeeper completion', 'Prepare the Flamebound Revenant encounter'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'flamebound-revenant' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareElementalScar(['corrupted-elemental-gatekeeper']); prepareCombatLoadout(); state.spawnDebugEnemy('flamebound-revenant', 'ashen-watch'); return store.getState().combat.enemyId === 'flamebound-revenant' } },
  { id: 'scar-rootscar-boss', group: 'Combat', label: 'Rootscar Boss Ready', summary: ['Set Gatekeeper completion', 'Prepare the Rootscar Ancient encounter'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'rootscar-ancient' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareElementalScar(['corrupted-elemental-gatekeeper']); prepareCombatLoadout(); state.spawnDebugEnemy('rootscar-ancient', 'rootscar-hollow'); return store.getState().combat.enemyId === 'rootscar-ancient' } },
  { id: 'scar-two-regional-bosses', group: 'Combat', label: '2 / 3 Location Bosses Cleared', summary: ['Set Gatekeeper and two location boss wins', 'Verify Crossroads remains locked until the final location boss'], testReady: { supportsTestReady: false }, run: () => { const state = prepareElementalScar(['corrupted-elemental-gatekeeper', 'drowned-keeper', 'flamebound-revenant']); return !isCombatLocationUnlocked('crossroads-of-ruin', state.progress) } },
  { id: 'scar-crossroads-unlocked', group: 'Combat', label: 'Crossroads Unlocked', summary: ['Set the three location boss victories', 'Verify the all-boss gate opens Crossroads'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'crossroads-keeper' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareElementalScar(['corrupted-elemental-gatekeeper', 'drowned-keeper', 'flamebound-revenant', 'rootscar-ancient']); return isCombatLocationUnlocked('crossroads-of-ruin', state.progress) } },
  { id: 'scar-crossroads-start', group: 'Combat', label: 'Crossroads Start', summary: ['Set all location boss wins', 'Start the fixed sequence at Arcane Binder'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'crossroads-keeper' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareElementalScar(['corrupted-elemental-gatekeeper', 'drowned-keeper', 'flamebound-revenant', 'rootscar-ancient']); prepareCombatLoadout(); state.enterDungeon('crossroads-of-ruin'); return store.getState().combat.enemyId === 'arcane-binder' } },
  { id: 'scar-crossroads-keeper', group: 'Combat', label: 'Crossroads Keeper', summary: ['Set all location boss wins', 'Prepare the final Crossroads Keeper encounter'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'crossroads-keeper' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareElementalScar(['corrupted-elemental-gatekeeper', 'drowned-keeper', 'flamebound-revenant', 'rootscar-ancient']); prepareCombatLoadout(); state.enterDungeon('crossroads-of-ruin'); state.jumpDebugToBoss('crossroads-of-ruin'); return store.getState().combat.enemyId === 'crossroads-keeper' } },
  { id: 'shattered-open', group: 'Combat', label: 'Crossroads Cleared / Three Paths Open', summary: ['Set Crossroads Keeper completion in the sandbox', 'Verify all three Combat Locations are available and Broken Meridian remains gated'], testReady: { supportsTestReady: false }, run: () => { const state = prepareShatteredMeridian(); return ['graveglass-hollow', 'stormvault-gallery', 'starfallen-observatory'].every((id) => isCombatLocationUnlocked(id as never, state.progress)) && !isCombatLocationUnlocked('broken-meridian', state.progress) } },
  { id: 'shattered-graveglass-boss', group: 'Combat', label: 'Graveglass Boss Ready', summary: ['Unlock Shattered Meridian through Crossroads Keeper', 'Prepare the Warded Graveglass Behemoth encounter'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'elemental-scar' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareShatteredMeridian(); prepareCombatLoadout(); state.spawnDebugEnemy('graveglass-behemoth', 'graveglass-hollow'); return store.getState().combat.enemyId === 'graveglass-behemoth' } },
  { id: 'shattered-stormvault-boss', group: 'Combat', label: 'Stormvault Boss Ready', summary: ['Unlock Shattered Meridian through Crossroads Keeper', 'Prepare the Storm Archivist encounter'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'elemental-scar' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareShatteredMeridian(); prepareCombatLoadout(); state.spawnDebugEnemy('storm-archivist', 'stormvault-gallery'); return store.getState().combat.enemyId === 'storm-archivist' } },
  { id: 'shattered-starfallen-boss', group: 'Combat', label: 'Starfallen Boss Ready', summary: ['Unlock Shattered Meridian through Crossroads Keeper', 'Prepare the Relentless Fallen Astromancer encounter'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'elemental-scar' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareShatteredMeridian(); prepareCombatLoadout(); state.spawnDebugEnemy('fallen-astromancer', 'starfallen-observatory'); return store.getState().combat.enemyId === 'fallen-astromancer' } },
  { id: 'shattered-one-boss', group: 'Combat', label: '1 / 3 Shattered Bosses Cleared', summary: ['Set one Shattered anchor victory', 'Verify Broken Meridian remains locked'], testReady: { supportsTestReady: false }, run: () => { const state = prepareShatteredMeridian(['graveglass-behemoth']); return !isCombatLocationUnlocked('broken-meridian', state.progress) } },
  { id: 'shattered-two-bosses', group: 'Combat', label: '2 / 3 Shattered Bosses Cleared', summary: ['Set two Shattered anchor victories', 'Verify Broken Meridian remains locked'], testReady: { supportsTestReady: false }, run: () => { const state = prepareShatteredMeridian(['graveglass-behemoth', 'storm-archivist']); return !isCombatLocationUnlocked('broken-meridian', state.progress) } },
  { id: 'shattered-three-bosses', group: 'Combat', label: '3 / 3 Shattered Bosses Cleared', summary: ['Set all Shattered anchor victories', 'Verify Broken Meridian unlocks'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'elemental-scar' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareShatteredMeridian(['graveglass-behemoth', 'storm-archivist', 'fallen-astromancer']); return isCombatLocationUnlocked('broken-meridian', state.progress) } },
  { id: 'shattered-broken-unlocked', group: 'Combat', label: 'Broken Meridian Unlocked', summary: ['Set all three Shattered boss victories', 'Verify the fixed capstone Dungeon gate'], testReady: { supportsTestReady: false }, run: () => isCombatLocationUnlocked('broken-meridian', prepareShatteredMeridian(['graveglass-behemoth', 'storm-archivist', 'fallen-astromancer']).progress) },
  { id: 'shattered-broken-start', group: 'Combat', label: 'Broken Meridian Start', summary: ['Prepare the unlocked fixed sequence', 'Start at the first encounter in the approved roster'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'elemental-scar' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareShatteredMeridian(['graveglass-behemoth', 'storm-archivist', 'fallen-astromancer']); prepareCombatLoadout(); state.enterDungeon('broken-meridian'); return store.getState().combat.enemyId === COMBAT_LOCATIONS['broken-meridian'].encounterSequence?.[0] } },
  { id: 'shattered-splitter', group: 'Combat', label: 'Meridian Splitter', summary: ['Prepare the final fixed Dungeon step', 'Inspect both deterministic combat phases'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'elemental-scar' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareShatteredMeridian(['graveglass-behemoth', 'storm-archivist', 'fallen-astromancer']); prepareCombatLoadout(); state.enterDungeon('broken-meridian'); state.jumpDebugToBoss('broken-meridian'); return store.getState().combat.enemyId === 'meridian-splitter' } },
  { id: 'shattered-splitter-cleared', group: 'Combat', label: 'Meridian Splitter Cleared', summary: ['Set Meridian Splitter victory', 'Verify the Act handoff evidence'], testReady: { supportsTestReady: false }, run: () => (prepareShatteredMeridian(['graveglass-behemoth', 'storm-archivist', 'fallen-astromancer', 'meridian-splitter']).progress.bossKillsByBoss['meridian-splitter'] ?? 0) > 0 },
  { id: 'shattered-crystals-open', group: 'Combat', label: 'Crystals Unlocked', summary: ['Set Meridian Splitter victory', 'Verify Crystal Chronicle reward readiness'], testReady: { supportsTestReady: false }, run: () => (prepareShatteredMeridian(['graveglass-behemoth', 'storm-archivist', 'fallen-astromancer', 'meridian-splitter']).crystals.owned['force-t1'] ?? 0) > 0 },
  { id: 'shattered-black-sigil-open', group: 'Combat', label: 'Black Gate Paths Open', summary: ['Set Meridian Splitter victory', 'Verify the Hall of Unbound Names handoff without preparing Phase 06 content'], testReady: { supportsTestReady: false }, run: () => { const state = prepareShatteredMeridian(['graveglass-behemoth', 'storm-archivist', 'fallen-astromancer', 'meridian-splitter']); return isCombatLocationUnlocked('hall-of-unbound-names', state.progress) } },
  { id: 'black-sigil-open-handoff', group: 'Combat', label: 'Meridian Splitter Cleared / Black Sigil Open', summary: ['Set Meridian Splitter completion', 'Verify Hall and Vault access while the Black Gate stays locked'], testReady: { supportsTestReady: false }, run: () => { const state = prepareBlackSigil(); return isCombatLocationUnlocked('hall-of-unbound-names', state.progress) && isCombatLocationUnlocked('vault-of-the-black-sigil', state.progress) && !isCombatLocationUnlocked('black-gate', state.progress) } },
  { id: 'black-sigil-hall-start', group: 'Combat', label: 'Hall Start', summary: ['Open the Black Gate paths', 'Spawn Name-Eater with the Vicious normal enemy affix active'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'black-sigil' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareBlackSigil(); prepareCombatLoadout(); state.spawnDebugEnemy('name-eater', 'hall-of-unbound-names'); return store.getState().combat.enemyId === 'name-eater' } },
  { id: 'black-sigil-hall-boss-ready', group: 'Combat', label: 'Hall Boss Ready', summary: ['Open the Black Gate paths', 'Prepare Unspoken Prelate for mechanic inspection'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'black-sigil' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareBlackSigil(); prepareCombatLoadout(); state.spawnDebugEnemy('unspoken-prelate', 'hall-of-unbound-names'); return store.getState().combat.enemyId === 'unspoken-prelate' } },
  { id: 'black-sigil-unspoken-prelate', group: 'Combat', label: 'Unspoken Prelate', summary: ['Prepare the Hall boss', 'Inspect its Arcane, Air, Water and Silence pattern'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'black-sigil' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareBlackSigil(); prepareCombatLoadout(); state.spawnDebugEnemy('unspoken-prelate', 'hall-of-unbound-names'); return store.getState().combat.enemyId === 'unspoken-prelate' } },
  { id: 'black-sigil-vault-start', group: 'Combat', label: 'Vault Start', summary: ['Open the Black Gate paths', 'Spawn Black Seal Parasite with the Armored normal enemy affix active'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'black-sigil' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareBlackSigil(); prepareCombatLoadout(); state.spawnDebugEnemy('black-seal-parasite', 'vault-of-the-black-sigil'); return store.getState().combat.enemyId === 'black-seal-parasite' } },
  { id: 'black-sigil-vault-boss-ready', group: 'Combat', label: 'Vault Boss Ready', summary: ['Open the Black Gate paths', 'Prepare Sigil Warden for mechanic inspection'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'black-sigil' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareBlackSigil(); prepareCombatLoadout(); state.spawnDebugEnemy('sigil-warden', 'vault-of-the-black-sigil'); return store.getState().combat.enemyId === 'sigil-warden' } },
  { id: 'black-sigil-sigil-warden', group: 'Combat', label: 'Sigil Warden', summary: ['Prepare the Vault boss', 'Inspect Earth, Fire, Arcane and Corruption pressure'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'black-sigil' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareBlackSigil(); prepareCombatLoadout(); state.spawnDebugEnemy('sigil-warden', 'vault-of-the-black-sigil'); return store.getState().combat.enemyId === 'sigil-warden' } },
  { id: 'black-sigil-one-boss', group: 'Combat', label: '1 / 2 Black Sigil Bosses Cleared', summary: ['Set Unspoken Prelate completion only', 'Verify the Black Gate remains locked'], testReady: { supportsTestReady: false }, run: () => { const state = prepareBlackSigil(['unspoken-prelate']); return !isCombatLocationUnlocked('black-gate', state.progress) } },
  { id: 'black-sigil-two-bosses', group: 'Combat', label: '2 / 2 Black Sigil Bosses Cleared', summary: ['Set both parallel Black Sigil boss victories', 'Verify the fixed Black Gate unlocks'], testReady: { supportsTestReady: false }, run: () => { const state = prepareBlackSigil(['unspoken-prelate', 'sigil-warden']); return isCombatLocationUnlocked('black-gate', state.progress) } },
  { id: 'black-gate-unlocked', group: 'Combat', label: 'Black Gate Unlocked', summary: ['Set both Black Sigil boss victories', 'Verify fixed sequence access'], testReady: { supportsTestReady: false }, run: () => isCombatLocationUnlocked('black-gate', prepareBlackSigil(['unspoken-prelate', 'sigil-warden']).progress) },
  { id: 'black-gate-start', group: 'Combat', label: 'Black Gate Start', summary: ['Open the fixed sequence after both side bosses', 'Start at the first encounter in the approved roster'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'black-gate' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareBlackSigil(['unspoken-prelate', 'sigil-warden']); prepareCombatLoadout(); state.enterDungeon('black-gate'); return store.getState().combat.enemyId === COMBAT_LOCATIONS['black-gate'].encounterSequence?.[0] } },
  { id: 'black-gatekeeper-phase-one', group: 'Combat', label: 'Black Gatekeeper Phase 1', summary: ['Spawn the Black Gatekeeper', 'Inspect its four-element Sealed Gate cycle'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'black-gate' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareBlackSigil(['unspoken-prelate', 'sigil-warden']); prepareCombatLoadout(); state.spawnDebugEnemy('black-gatekeeper', 'black-gate'); return store.getState().combat.enemyActionPatternId === 'sealed' } },
  { id: 'black-gatekeeper-phase-two', group: 'Combat', label: 'Black Gatekeeper Phase 2', summary: ['Prepare the Black Gatekeeper', 'Cross 50% Health and verify Gate Unbound plus the new pattern'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'black-gate' }, defaultReadyPreset: scarReadyPreset, run: () => { const state = prepareBlackSigil(['unspoken-prelate', 'sigil-warden']); prepareCombatLoadout(); state.spawnDebugEnemy('black-gatekeeper', 'black-gate'); state.setEnemyHealthPercent(40); return store.getState().combat.enemyActionPatternId === 'unbound' && store.getState().combat.enemyStatuses.some((entry) => entry.statusId === 'gate-unbound') } },
  { id: 'black-gatekeeper-cleared', group: 'Combat', label: 'Black Gatekeeper Cleared', summary: ['Set Gatekeeper completion evidence', 'Verify final Dungeon completion'], testReady: { supportsTestReady: false }, run: () => { const state = prepareBlackSigil(['unspoken-prelate', 'sigil-warden', 'black-gatekeeper']); return (store.getState().progress.bossKillsByBoss['black-gatekeeper'] ?? 0) > 0 } },
  { id: 'hunter-first', group: 'Hunter’s Order', label: 'Hunter’s Order — First Contract', summary: ['Unlock the Order through its tester action', 'Issue the starter routine contract'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'hunter-first' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 450, 'core.spellPowerFlat': 80, 'modifiers.defense-flat': 50 } }), run: () => { let state = store.getState(); if (state.progress.huntersOrder.activeContract) { state.debugGrantHunterMarks(100); state.skipHunterContract() } state = store.getState(); state.debugSetHunterRngSeed(341); state.debugSetHuntersOrderUnlocked(true); return state.issueFirstHunterContract() } },
  { id: 'gloamridge-contract', group: 'Hunter’s Order', label: 'Gloamridge — Active Contract', summary: ['Unlock Gloamridge from the Greatbear milestone', 'Prepare a Warden rank and accept a Ground Patrol contract'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'gloamridge' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 1100, 'core.spellPowerFlat': 200, 'modifiers.defense-flat': 110, 'modifiers.crit-chance': 0.06 } }), run: () => { const fixture = createInitialState(); fixture.progress.bossKillsByBoss['corrupted-greatbear'] = 1; fixture.progress.huntersOrder.reputation = 9000; fixture.progress.huntersOrder.rankId = 'warden'; store.getState().hydrateState(fixture); store.getState().debugSetHunterRngSeed(912); store.getState().debugRegenerateHunterContractBoard({ archetype: 'ground', tier: 'special', huntingGroundId: 'hunters-ground' }); const contract = store.getState().progress.huntersOrder.availableContracts.find((offer) => offer.targetSpec.type === 'ground' && offer.targetSpec.groundId === 'hunters-ground'); return Boolean(contract && store.getState().acceptHunterContract(contract.id)) } },
  { id: 'hunter-veteran', group: 'Hunter’s Order', label: 'Hunter’s Order — Veteran Progression', summary: ['Set the authored Veteran reputation threshold', 'Generate prestigious contract offers'], testReady: { supportsTestReady: false }, run: () => { let state = store.getState(); if (state.progress.huntersOrder.activeContract) { state.debugGrantHunterMarks(100); state.skipHunterContract() } state = store.getState(); state.debugSetHunterRank('veteran'); state.debugSetHunterRngSeed(17500); state.debugRegenerateHunterContractBoard({ tier: 'prestigious' }); return store.getState().progress.huntersOrder.availableContracts.length > 0 } },
  { id: 'hunter-new-quarry', group: 'Hunter’s Order', label: 'Gloamridge — Expanded Quarry', summary: ['Prepare the seven-creature Gloamridge quarry roster', 'Generate and accept a single-monster contract'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'gloamridge' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 950, 'core.spellPowerFlat': 180, 'modifiers.defense-flat': 90 } }), run: () => { let state = store.getState(); if (state.progress.huntersOrder.activeContract) { state.debugGrantHunterMarks(100); state.skipHunterContract() } state = store.getState(); state.debugSetHunterRank('scout'); state.debugSetHunterRngSeed(77); state.debugRegenerateHunterContractBoard({ archetype: 'monster', tier: 'special' }); const offer = store.getState().progress.huntersOrder.availableContracts.find((candidate) => candidate.targetSpec.type === 'monster'); return Boolean(offer && store.getState().acceptHunterContract(offer.id)) } },
  { id: 'nightglass-contract', group: 'Hunter’s Order', label: 'Nightglass Alpha — Master Quarry', summary: ['Generate and accept a prestigious Nightglass monster contract', 'Open Gloamridge with Nightglass selected; combat does not auto-start'], testReady: { supportsTestReady: true, defaultReadyPresetId: 'nightglass' }, defaultReadyPreset: ready({ stats: { 'core.maxHealthFlat': 1600, 'core.maxManaFlat': 400, 'core.spellPowerFlat': 420, 'modifiers.defense-flat': 210, 'modifiers.crit-chance': 0.12 } }), run: () => { let state = store.getState(); if (state.progress.huntersOrder.activeContract) { state.debugGrantHunterMarks(100); state.skipHunterContract() } state = store.getState(); if (!state.debugGrantNightglassContract()) return false; const offer = store.getState().progress.huntersOrder.availableContracts.find((entry) => entry.targetSpec.type === 'monster' && entry.targetSpec.monsterId === 'nightglass-alpha'); if (!offer || !store.getState().acceptHunterContract(offer.id)) return false; prepareCombatLoadout(); const open = openHunterContractInCombat(store.getState(), store.getState().setScreen); return open && store.getState().combat.enemyId === null && store.getState().progress.huntersOrder.activeContract?.targetSpec.type === 'monster' } },
  { id: 'guild-early', group: 'Arcane Guild', label: 'Arcane Guild — Early Progression', summary: ['Unlock Arcane Guild through its tester action', 'Generate its accessible commission board'], testReady: { supportsTestReady: false }, run: () => { const state = store.getState(); state.setTutorialStageForDebug('complete'); state.debugSetArcaneGuildUnlocked(true); state.debugRegenerateGuildCommissionBoard() } },
  { id: 'guild-advancement', group: 'Arcane Guild', label: 'Arcane Guild — Advancement Test', summary: ['Prepare Magister rank and Advancement Points', 'Generate a prestigious commission board'], testReady: { supportsTestReady: false }, run: () => { const state = store.getState(); state.setTutorialStageForDebug('complete'); state.debugSetArcaneGuildUnlocked(true); state.debugSetGuildRank('magister'); state.debugGrantGuildPoint(12); state.debugRegenerateGuildCommissionBoard({ quality: 'prestigious' }) } },
  { id: 'guild-commission-chain', group: 'Arcane Guild', label: 'Arcane Guild — Commission Chain', summary: ['Prepare the authored Magister commission context', 'Generate a board for commission-chain regression checks'], testReady: { supportsTestReady: false }, run: () => { const state = store.getState(); state.setTutorialStageForDebug('complete'); state.debugSetArcaneGuildUnlocked(true); state.debugSetGuildRank('magister'); state.debugGrantGuildPoint(8); state.debugRegenerateGuildCommissionBoard({ quality: 'prestigious' }); return store.getState().progress.arcaneGuild.availableCommissions.length > 0 } },
  { id: 'research-stress', group: 'Tower Systems', label: 'Research Stress Test', summary: ['Prepare an authored fragment batch for each School', 'Assign available Acolytes through Research actions'], testReady: { supportsTestReady: false }, run: () => { const state = store.getState(); state.clearPreparedResearch(); (Object.keys(SCHOOLS) as SchoolId[]).forEach((school) => { const itemId = SCHOOLS[school].fragment; state.addItem(itemId, 100); state.prepareResearch(itemId, school, 50) }); state.assignOneResearchAcolyteEach() } },
  { id: 'transmutation-stress', group: 'Tower Systems', label: 'Transmutation Stress Test', summary: ['Prepare authored inputs and elemental Resonance', 'Generate Arcane Flux, then assign the Prismatic recipe'], testReady: { supportsTestReady: false }, run: () => { const state = store.getState(); state.clearPreparedResearch(); state.clearTransmutationAssignments(); (['fire', 'water', 'earth', 'air'] as const).forEach((type) => state.debugGrantResonance(type, 10_000)); for (const itemId of ['fire-fragment', 'water-fragment', 'earth-fragment', 'air-fragment', 'life-essence'] as const) state.addItem(itemId, 10_000); state.setDebugArcaneFluxCapacity(100_000); state.setDebugAcolyteTotalOverride(100); state.setDebugIgnoreAcolyteLimit(true); state.setChannelingAcolytesDebug(100); state.tick(60_000); const recipeId = TRANSMUTATION_RECIPE_ORDER.find((id) => id === 'prismatic-fragment'); if (!recipeId) return false; store.getState().assignMaxTransmutationAcolytes(recipeId) } },
]
