/** MVP provisional balance. Keep tuning values here rather than in UI components. */
export const BALANCE = {
  tickMs: 100,
  player: { maxHealth: 100, healthRegenPerSecond: 1, healthRegenIntervalMs: 1000, outOfCombatRegenMultiplier: 2, baseSpellPower: 50, baseDefense: 5, baseCritChance: 0.05, baseCritDamage: 1.5 },
  mana: { startingMana: 100, maxMana: 100, baseRegenPerSecond: 10 },
  acolytes: { startingCount: 5 },
  channeling: { baseArcaneFluxCapacity: 500, baseFluxPerAcolytePerSecond: 2, harmonicWorkforceAcolytes: 3, discoveryEchoMultiplier: 1.1, stableLeylineThreshold: 2500, echoResonanceDurationMs: 120000, deepReservoirThreshold: 1500, deepReservoirCapacityBonus: 250 },
  research: { maxPreparedSlots: 4, arcaneFluxPerItem: 5, durationPerItemMs: 10000, matchingXp: 12, nonMatchingXp: 8 },
  transmutation: {},
  dungeon: { encounterDelayMs: 5000, whisperingWoodsThreatRequired: 5000 },
  huntersOrder: { rerollMarkCost: 4, skipMarkCost: 6, baseBlockSlots: 0,
    starterTargetRange: [125, 175], starterReputationPerKill: 2, starterMarksReward: 3,
    targetRanges: {
      monster: { routine: [125, 175], special: [175, 225], prestigious: [225, 300] },
      family: { routine: [150, 200], special: [200, 275], prestigious: [275, 350] },
      alignment: { special: [200, 275], prestigious: [275, 350] },
      ground: { special: [225, 300], prestigious: [300, 400] },
    },
    bossTargetRanges: { prestigious: [1, 1] },
    reputationPerKill: 2, reputationMultipliers: { routine: 1, special: 1.75, prestigious: 3 }, markRewards: { routine: 3, special: 6, prestigious: 12 },
    tierMinimumReputation: { routine: 0, special: 2350, prestigious: 17500 },
    archetypeWeights: { monster: 5, family: 3, ground: 1, alignment: 2, boss: 1 },
    qualityWeights: { routine: 75, special: 20, prestigious: 5 } },
  arcaneGuild: { baseCommissionChoices: 3, maxFreeRefreshes: 2, qualityTargetMultipliers: { routine: 1, special: 1.5, prestigious: 2.2 }, rankMinimumQuality: { routine: 'outsider', special: 'apprentice', prestigious: 'magister' },
    qualityWeights: { routine: 75, special: 20, prestigious: 5 } },
  schoolProgression: { startingCap: 20, tutorialCompleteCap: 40 },
} as const
