/** MVP provisional balance. Keep tuning values here rather than in UI components. */
export const BALANCE = {
  tickMs: 100,
  player: { maxHealth: 100, healthRegenPerSecond: 1, healthRegenIntervalMs: 1000, outOfCombatRegenMultiplier: 2, baseSpellPower: 50, baseDefense: 5, baseCritChance: 0.05, baseCritDamage: 1.5 },
  mana: { startingMana: 100, maxMana: 100, baseRegenPerSecond: 10 },
  acolytes: { startingCount: 5 },
  channeling: { baseArcaneFluxCapacity: 500, baseFluxPerAcolytePerSecond: 2, harmonicWorkforceAcolytes: 3, discoveryEchoMultiplier: 1.1, stableLeylineThreshold: 2500, echoResonanceDurationMs: 120000, deepReservoirThreshold: 1500, deepReservoirCapacityBonus: 250 },
  research: { maxPreparedSlots: 4, arcaneFluxPerItem: 5, durationPerItemMs: 10000, matchingXp: 12, nonMatchingXp: 8 },
  transmutation: {},
  dungeon: { encounterDelayMs: 5000, whisperingWoodsThreatRequired: 5000 },
  huntersOrder: { rerollMarkCost: 1, skipMarkCost: 3, baseBlockSlots: 1,
    targetRanges: { routine: [12, 18], special: [18, 28], prestigious: [25, 40] },
    reputationPerKill: 25, reputationMultipliers: { routine: 1, special: 1.8, prestigious: 3.5 }, markRewards: { routine: 3, special: 6, prestigious: 12 }, markedQuarryBonusPerRank: 0.1, deepPocketsMarksPerRank: 1,
    tierMinimumReputation: { routine: 0, special: 250, prestigious: 3500 },
    archetypeWeights: { monster: 5, family: 3, region: 1, alignment: 2, boss: 1 },
    qualityWeights: { routine: 75, special: 20, prestigious: 5 } },
  arcaneGuild: { maxFreeRefreshes: 2, qualityTargetMultipliers: { routine: 1, special: 1.5, prestigious: 2.2 }, rankMinimumQuality: { routine: 'outsider', special: 'apprentice', prestigious: 'magister' },
    qualityWeights: { routine: 75, special: 20, prestigious: 5 } },
  schoolProgression: { startingCap: 20, tutorialCompleteCap: 40 },
} as const
