import type { CombatEffect, DamageType, DungeonId, MonsterId, StatusId, TraitId } from '../../../types'
import { action, applyStatus, basic, drainMana, gainBarrier, scaledDirectDamage, scaledDot, scaledHeal, scaledMultiDamage, withDungeonLoot, type MonsterDefinition } from '../monsterTypes'

type Special = { id: string; name: string; damage?: Array<{ type: DamageType; coefficient: number }>; status?: { id: StatusId; target?: 'self' | 'opponent'; stacks?: number }; dot?: { statusId: StatusId; damageType: DamageType; coefficient: number; durationMs: number }; barrier?: number; heal?: number; manaDrain?: number }
type MonsterSpec = { dungeonId: DungeonId; id: MonsterId; name: string; subtitle: string; hp: number; damage: number; defense: number; time?: number; resistances?: Partial<Record<DamageType, number>>; trait: TraitId; icon?: MonsterDefinition['ui']; color?: string; specials: Special[]; boss?: boolean; lifeEssence?: { min: number; max: number } }

const specialEffects = (special: Special): CombatEffect[] => [
  ...(special.damage?.length ? [special.damage.length === 1 ? scaledDirectDamage(special.damage[0].type, special.damage[0].coefficient) : scaledMultiDamage(special.damage.map(({ type, coefficient }) => ({ damageType: type, coefficient })))] : []),
  ...(special.dot ? [scaledDot(special.dot.statusId, special.dot.damageType, special.dot.coefficient, special.dot.durationMs)] : special.status ? [applyStatus(special.status.id, special.status.target ?? 'opponent', undefined, special.status.stacks)] : []),
  ...(special.barrier ? [gainBarrier({ type: 'source-max-health-percent', value: special.barrier })] : []),
  ...(special.heal ? [scaledHeal(special.heal)] : []),
  ...(special.manaDrain ? [drainMana(special.manaDrain)] : []),
]

const makeMonster = (spec: MonsterSpec): MonsterDefinition => {
  const actions: MonsterDefinition['actions'] = Object.fromEntries(spec.specials.map((special, index) => [special.id, {
    id: special.id, name: special.name, actionTimeMs: 1800 + index * 180, description: `${spec.name} uses ${special.name}.`, effects: specialEffects(special), tags: ['special'] as const,
  }]))
  const steps = spec.specials.length > 3
    ? spec.specials.flatMap((special, index) => [action(`${special.id}-step`, special.id), ...(index === spec.specials.length - 1 ? [] : [basic(`basic-${index + 1}`)])])
    : [basic('basic-1'), action(`${spec.specials[0].id}-step`, spec.specials[0].id), basic('basic-2'), action(`${spec.specials[1].id}-step`, spec.specials[1].id)]
  return {
    id: spec.id, bestiaryCategory: spec.boss ? 'boss' : 'monster', name: spec.name, subtitle: spec.subtitle, maxHealth: spec.hp, basicAttackDamage: spec.damage, basicAttackTimeMs: spec.time ?? 2300, defense: spec.defense,
    resistances: spec.resistances, color: spec.color ?? '#9b8dbd', ui: spec.icon ?? { portraitIcon: spec.boss ? 'boss' : 'guardian' }, traitIds: [spec.trait],
    actions, actionPatterns: { default: { id: 'default', steps } }, defaultActionPatternId: 'default', loot: withDungeonLoot(spec.dungeonId!, spec.boss ? 'boss' : 'normal', spec.lifeEssence),
  }
}

// Dungeon is kept on the authored spec so each record remains easy to audit.
const specs: MonsterSpec[] = [
  { dungeonId: 'flooded-reliquary', id: 'drowned-acolyte', name: 'Drowned Acolyte', subtitle: 'A waterlogged priest still chanting beneath the tide', hp: 1875, damage: 72, defense: 34, time: 2500, trait: 'drowned-acolyte-devotion', icon: { portraitIcon: 'mage' }, specials: [{ id: 'drowning-bolt', name: 'Drowning Bolt', damage: [{ type: 'water', coefficient: 1.4 }], status: { id: 'chilled' } }, { id: 'devotion', name: 'Drowned Devotion', status: { id: 'fortified', target: 'self' } }] },
  { dungeonId: 'flooded-reliquary', id: 'reliquary-slime', name: 'Reliquary Slime', subtitle: 'A living spill of preserved alchemical water', hp: 1813, damage: 68, defense: 40, time: 2700, resistances: { physical: .15, fire: -.1 }, trait: 'reliquary-slime-engulf', specials: [{ id: 'engulf', name: 'Engulf', damage: [{ type: 'water', coefficient: 1.2 }], manaDrain: 8 }, { id: 'slick-form', name: 'Slick Form', status: { id: 'fortified', target: 'self' } }] },
  { dungeonId: 'flooded-reliquary', id: 'mist-wraith', name: 'Mist Wraith', subtitle: 'A cold memory refusing to condense', hp: 1375, damage: 76, defense: 26, time: 2200, resistances: { physical: .35, fire: -.1 }, trait: 'mist-wraith-fade', icon: { portraitIcon: 'ghost' }, specials: [{ id: 'cold-veil', name: 'Cold Veil', damage: [{ type: 'water', coefficient: 1.15 }], status: { id: 'chilled' } }, { id: 'mist-fade', name: 'Mist Fade', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'flooded-reliquary', id: 'rune-leech', name: 'Rune Leech', subtitle: 'A parasite feeding on the reliquary’s arcane inscriptions', hp: 1563, damage: 70, defense: 28, time: 2150, resistances: { arcane: .15 }, trait: 'rune-leech-siphon', specials: [{ id: 'siphon-rune', name: 'Siphon Rune', damage: [{ type: 'arcane', coefficient: 1.1 }], manaDrain: 12 }, { id: 'rune-hunger', name: 'Rune Hunger', status: { id: 'arcane-disruption' } }] },
  { dungeonId: 'flooded-reliquary', id: 'drowned-keeper', name: 'Drowned Keeper', subtitle: 'The reliquary’s keeper, swollen with the weight of the deep', hp: 13500, damage: 88, defense: 58, time: 2450, resistances: { water: .2, fire: -.1 }, trait: 'drowned-acolyte-devotion', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'tidal-sweep', name: 'Tidal Sweep', damage: [{ type: 'water', coefficient: 1.35 }] }, { id: 'deep-chill', name: 'Deep Chill', damage: [{ type: 'water', coefficient: 1.1 }], status: { id: 'chilled' } }, { id: 'drowning-seal', name: 'Drowning Seal', damage: [{ type: 'arcane', coefficient: 1 }], manaDrain: 20 }, { id: 'reliquary-ward', name: 'Reliquary Ward', barrier: .07 }, { id: 'undertow', name: 'Undertow', damage: [{ type: 'water', coefficient: 2 }] }] },

  { dungeonId: 'ashen-watch', id: 'cinder-hound', name: 'Cinder Hound', subtitle: 'A hunting beast with a furnace under its ribs', hp: 1438, damage: 78, defense: 28, resistances: { fire: .2, water: -.15 }, trait: 'cinder-hound-flameblood', icon: { portraitIcon: 'wolf' }, specials: [{ id: 'cinder-bite', name: 'Cinder Bite', damage: [{ type: 'physical', coefficient: .8 }, { type: 'fire', coefficient: .7 }], status: { id: 'burning' } }, { id: 'ember-trail', name: 'Ember Trail', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'ashen-watch', id: 'ash-cultist', name: 'Ash Cultist', subtitle: 'A zealot who feeds old watchfires with forbidden rites', hp: 1563, damage: 74, defense: 30, resistances: { fire: .15 }, trait: 'ash-cultist-fan', icon: { portraitIcon: 'mage' }, specials: [{ id: 'ember-bolt', name: 'Ember Bolt', damage: [{ type: 'fire', coefficient: 1.45 }] }, { id: 'fan-flames', name: 'Fan Flames', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'ashen-watch', id: 'fire-elemental', name: 'Fire Elemental', subtitle: 'A watchfire given a shape and a violent will', hp: 1688, damage: 80, defense: 34, resistances: { fire: .35, water: -.2 }, trait: 'fire-elemental-emberheart', icon: { portraitIcon: 'guardian' }, specials: [{ id: 'flame-lash', name: 'Flame Lash', damage: [{ type: 'fire', coefficient: 1.25 }], status: { id: 'burning' } }, { id: 'ember-heart', name: 'Ember Heart', status: { id: 'regeneration', target: 'self' } }] },
  { dungeonId: 'ashen-watch', id: 'lava-eel', name: 'Lava Eel', subtitle: 'A molten river predator coiled beneath the ash', hp: 1875, damage: 82, defense: 26, resistances: { fire: .25, water: -.15 }, trait: 'lava-eel-molten-hide', icon: { portraitIcon: 'plant' }, specials: [{ id: 'lava-surge', name: 'Lava Surge', damage: [{ type: 'fire', coefficient: 1.65 }] }, { id: 'molten-hide', name: 'Molten Hide', status: { id: 'fortified', target: 'self' } }] },
  { dungeonId: 'ashen-watch', id: 'flamebound-revenant', name: 'Flamebound Revenant', subtitle: 'A fallen commander still burning behind its armor', hp: 14500, damage: 95, defense: 52, resistances: { fire: .25, water: -.1 }, trait: 'fire-elemental-emberheart', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'flame-brand', name: 'Flame Brand', damage: [{ type: 'fire', coefficient: 1.25 }], status: { id: 'burning' } }, { id: 'ashen-burst', name: 'Ashen Burst', damage: [{ type: 'fire', coefficient: 1.6 }] }, { id: 'burning-guard', name: 'Burning Guard', barrier: .06 }, { id: 'cremation', name: 'Cremation', damage: [{ type: 'fire', coefficient: 2.1 }] }, { id: 'rekindle', name: 'Rekindle', status: { id: 'regeneration', target: 'self' } }] },

  { dungeonId: 'rootscar-hollow', id: 'thorn-maw', name: 'Thorn Maw', subtitle: 'A carnivorous bloom grown around a poisoned root', hp: 1875, damage: 78, defense: 42, trait: 'thorn-maw-venom', icon: { portraitIcon: 'plant' }, specials: [{ id: 'venomous-bite', name: 'Venomous Bite', damage: [{ type: 'physical', coefficient: 1.25 }], dot: { statusId: 'poisoned', damageType: 'physical', coefficient: 0.5, durationMs: 8000 } }, { id: 'thorn-bloom', name: 'Thorn Bloom', status: { id: 'thorn-wound', target: 'self' } }] },
  { dungeonId: 'rootscar-hollow', id: 'rootbound-stalker', name: 'Rootbound Stalker', subtitle: 'A patient hunter hiding beneath the scarred soil', hp: 1250, damage: 82, defense: 32, trait: 'rootbound-stalker-ambush', icon: { portraitIcon: 'plant' }, specials: [{ id: 'root-ambush', name: 'Root Ambush', damage: [{ type: 'physical', coefficient: 1.35 }], status: { id: 'entangled' } }, { id: 'burrow', name: 'Burrow', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'rootscar-hollow', id: 'briar-sprite', name: 'Briar Sprite', subtitle: 'A small spirit with a spiteful garden to tend', hp: 1375, damage: 74, defense: 24, resistances: { earth: .15, fire: -.15 }, trait: 'briar-sprite-bloom', icon: { portraitIcon: 'wisp' }, specials: [{ id: 'briar-hex', name: 'Briar Hex', damage: [{ type: 'earth', coefficient: 1.15 }], dot: { statusId: 'poisoned', damageType: 'physical', coefficient: 0.45, durationMs: 8000 } }, { id: 'bloom', name: 'Bloom', status: { id: 'regeneration', target: 'self' } }] },
  { dungeonId: 'rootscar-hollow', id: 'moss-carapace', name: 'Moss Carapace', subtitle: 'A slow shell carrying a whole forest on its back', hp: 2063, damage: 72, defense: 52, resistances: { physical: .1 }, trait: 'moss-carapace-regrowth', specials: [{ id: 'shell-up', name: 'Shell Up', status: { id: 'fortified', target: 'self' } }, { id: 'moss-regrowth', name: 'Moss Regrowth', status: { id: 'regeneration', target: 'self' } }] },
  { dungeonId: 'rootscar-hollow', id: 'rootscar-ancient', name: 'Rootscar Ancient', subtitle: 'The oldest root beneath the frontier, awake and starving', hp: 15500, damage: 92, defense: 68, resistances: { earth: .25, fire: -.1 }, trait: 'moss-carapace-regrowth', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'entangling-roots', name: 'Entangling Roots', damage: [{ type: 'earth', coefficient: 1.1 }], status: { id: 'entangled' } }, { id: 'toxic-sap', name: 'Toxic Sap', dot: { statusId: 'poisoned', damageType: 'physical', coefficient: 0.7, durationMs: 8000 } }, { id: 'barkwall', name: 'Barkwall', barrier: .08 }, { id: 'ancient-regrowth', name: 'Ancient Regrowth', status: { id: 'regeneration', target: 'self' } }, { id: 'earthsplit', name: 'Earthsplit', damage: [{ type: 'earth', coefficient: 2 }] }] },

  { dungeonId: 'crossroads-of-ruin', id: 'remnant-marauder', name: 'Remnant Marauder', subtitle: 'A road-warrior assembled from every failed expedition', hp: 2063, damage: 88, defense: 38, trait: 'remnant-marauder-pressure', specials: [{ id: 'ruin-cleave', name: 'Ruin Cleave', damage: [{ type: 'physical', coefficient: 1.55 }] }, { id: 'pressure', name: 'Pressure', status: { id: 'vulnerable' } }] },
  { dungeonId: 'crossroads-of-ruin', id: 'arcane-binder', name: 'Arcane Binder', subtitle: 'A warden tying broken roads together with hostile sigils', hp: 1500, damage: 86, defense: 32, trait: 'arcane-binder-binding', specials: [{ id: 'binding-hex', name: 'Binding Hex', damage: [{ type: 'arcane', coefficient: 1.15 }], status: { id: 'arcane-disruption' } }, { id: 'bind', name: 'Bind', status: { id: 'entangled' } }] },
  { dungeonId: 'crossroads-of-ruin', id: 'broken-construct', name: 'Broken Construct', subtitle: 'A road marker that learned to defend itself', hp: 2375, damage: 80, defense: 58, trait: 'broken-construct-ward', specials: [{ id: 'road-ward', name: 'Road Ward', barrier: .08 }, { id: 'construct-slam', name: 'Construct Slam', damage: [{ type: 'physical', coefficient: 1.5 }] }] },
  { dungeonId: 'crossroads-of-ruin', id: 'rift-archer', name: 'Rift Archer', subtitle: 'A scout firing arrows through the space between roads', hp: 1813, damage: 90, defense: 30, trait: 'rift-archer-precision', icon: { portraitIcon: 'claw' }, specials: [{ id: 'rift-shot', name: 'Rift Shot', damage: [{ type: 'air', coefficient: 1.55 }] }, { id: 'split-step', name: 'Split Step', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'crossroads-of-ruin', id: 'crossroads-keeper', name: 'Crossroads Keeper', subtitle: 'A many-faced custodian of the broken convergence', hp: 19500, damage: 105, defense: 70, trait: 'broken-construct-ward', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'waystone-flame', name: 'Waystone Flame', damage: [{ type: 'fire', coefficient: 1.25 }] }, { id: 'flooded-path', name: 'Flooded Path', damage: [{ type: 'water', coefficient: 1.2 }], status: { id: 'chilled' } }, { id: 'rooted-road', name: 'Rooted Road', damage: [{ type: 'earth', coefficient: 1.15 }], status: { id: 'entangled' } }, { id: 'rift-lane', name: 'Rift Lane', damage: [{ type: 'air', coefficient: 1.25 }] }, { id: 'crossroads-ward', name: 'Crossroads Ward', barrier: .07 }, { id: 'convergence', name: 'Convergence', damage: [{ type: 'arcane', coefficient: 2.1 }] }] },

  { dungeonId: 'graveglass-hollow', id: 'graveglass-shade', name: 'Graveglass Shade', subtitle: 'A reflection that learned how to curse the living', hp: 3125, damage: 98, defense: 34, resistances: { physical: .25 }, trait: 'graveglass-shade-cursed', icon: { portraitIcon: 'ghost' }, specials: [{ id: 'graveglass-touch', name: 'Graveglass Touch', damage: [{ type: 'arcane', coefficient: 1.35 }], status: { id: 'cursed' } }, { id: 'shard-step', name: 'Shard Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'graveglass-hollow', id: 'bone-shardling', name: 'Bone Shardling', subtitle: 'A splinter of a tomb animated by pressure', hp: 2313, damage: 100, defense: 45, trait: 'bone-shardling-brittle', specials: [{ id: 'shard-rend', name: 'Shard Rend', damage: [{ type: 'physical', coefficient: 1.45 }], status: { id: 'fragile' } }, { id: 'bone-wall', name: 'Bone Wall', barrier: .05 }] },
  { dungeonId: 'graveglass-hollow', id: 'silent-mourner', name: 'Silent Mourner', subtitle: 'A mourner whose grief has outlived its voice', hp: 2125, damage: 92, defense: 32, trait: 'silent-mourner-fade', icon: { portraitIcon: 'ghost' }, specials: [{ id: 'mourning-curse', name: 'Mourning Curse', status: { id: 'cursed' } }, { id: 'quiet-step', name: 'Quiet Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'graveglass-hollow', id: 'crypt-guardian', name: 'Crypt Guardian', subtitle: 'A sealed defender carrying a garden of grave moss', hp: 2875, damage: 90, defense: 62, trait: 'crypt-guardian-ward', specials: [{ id: 'crypt-ward', name: 'Crypt Ward', barrier: .08 }, { id: 'grave-regrowth', name: 'Grave Regrowth', status: { id: 'regeneration', target: 'self' } }] },
  { dungeonId: 'graveglass-hollow', id: 'graveglass-behemoth', name: 'Graveglass Behemoth', subtitle: 'A giant of tomb glass and accumulated sorrow', hp: 25000, damage: 116, defense: 78, resistances: { physical: .15, arcane: .15 }, trait: 'crypt-guardian-ward', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'shard-break', name: 'Shard Break', damage: [{ type: 'physical', coefficient: 1.6 }], status: { id: 'fragile' } }, { id: 'grave-curse', name: 'Grave Curse', status: { id: 'cursed' } }, { id: 'crystal-burst', name: 'Crystal Burst', damage: [{ type: 'arcane', coefficient: 1.7 }] }, { id: 'graveglass-regeneration', name: 'Graveglass Regeneration', status: { id: 'regeneration', target: 'self' } }, { id: 'behemoth-crush', name: 'Behemoth Crush', damage: [{ type: 'physical', coefficient: 2.2 }] }] },

  { dungeonId: 'stormvault-gallery', id: 'volt-wisp', name: 'Volt Wisp', subtitle: 'A spark trapped between two storm records', hp: 2188, damage: 96, defense: 28, resistances: { air: .2 }, trait: 'volt-wisp-static', icon: { portraitIcon: 'wisp' }, specials: [{ id: 'volt-spark', name: 'Volt Spark', damage: [{ type: 'air', coefficient: 1.1 }], status: { id: 'shock', stacks: 1 } }, { id: 'static-charge', name: 'Static Charge', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'stormvault-gallery', id: 'static-armor', name: 'Static Armor', subtitle: 'A walking shell charged by a vault’s entire gallery', hp: 3750, damage: 90, defense: 66, resistances: { physical: .1 }, trait: 'static-armor-ward', specials: [{ id: 'static-ward', name: 'Static Ward', barrier: .08 }, { id: 'armor-crush', name: 'Armor Crush', damage: [{ type: 'physical', coefficient: 1.5 }] }] },
  { dungeonId: 'stormvault-gallery', id: 'gale-scribe', name: 'Gale Scribe', subtitle: 'A storm historian writing faster than thought', hp: 2438, damage: 94, defense: 34, trait: 'gale-scribe-acceleration', icon: { portraitIcon: 'mage' }, specials: [{ id: 'gale-script', name: 'Gale Script', damage: [{ type: 'air', coefficient: 1.3 }] }, { id: 'acceleration-rune', name: 'Acceleration Rune', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'stormvault-gallery', id: 'charged-seeker', name: 'Charged Seeker', subtitle: 'A hunting current searching for a grounded target', hp: 2813, damage: 100, defense: 30, trait: 'charged-seeker-twin-arc', specials: [{ id: 'twin-arc', name: 'Twin Arc', damage: [{ type: 'air', coefficient: .65 }, { type: 'air', coefficient: .65 }], status: { id: 'shock', stacks: 1 } }, { id: 'seek', name: 'Seek', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'stormvault-gallery', id: 'storm-archivist', name: 'Storm Archivist', subtitle: 'The gallery’s keeper, cataloguing every lightning strike', hp: 25000, damage: 115, defense: 70, resistances: { air: .25, earth: -.1 }, trait: 'static-armor-ward', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'archive-spark', name: 'Archive Spark', damage: [{ type: 'air', coefficient: 1.2 }], status: { id: 'shock', stacks: 1 } }, { id: 'rapid-annotation', name: 'Rapid Annotation', status: { id: 'haste', target: 'self' } }, { id: 'forked-bolt', name: 'Forked Bolt', damage: [{ type: 'air', coefficient: .75 }, { type: 'air', coefficient: .75 }] }, { id: 'static-barrier', name: 'Static Barrier', barrier: .06 }, { id: 'final-discharge', name: 'Final Discharge', damage: [{ type: 'air', coefficient: 2.15 }] }] },

  { dungeonId: 'starfallen-observatory', id: 'starbound-eye', name: 'Starbound Eye', subtitle: 'A watching star that never learned mercy', hp: 2625, damage: 100, defense: 38, resistances: { arcane: .2 }, trait: 'starbound-eye-gaze', icon: { portraitIcon: 'wisp' }, specials: [{ id: 'star-gaze', name: 'Star Gaze', damage: [{ type: 'arcane', coefficient: 1.35 }], status: { id: 'arcane-disruption' } }, { id: 'orbit', name: 'Orbit', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'starfallen-observatory', id: 'astral-husk', name: 'Astral Husk', subtitle: 'A shell left behind when an astronomer vanished', hp: 2250, damage: 98, defense: 50, resistances: { arcane: .25 }, trait: 'astral-husk-weight', specials: [{ id: 'astral-hammer', name: 'Astral Hammer', damage: [{ type: 'arcane', coefficient: 1.55 }] }, { id: 'dead-orbit', name: 'Dead Orbit', status: { id: 'fragile' } }] },
  { dungeonId: 'starfallen-observatory', id: 'orbiting-fragment', name: 'Orbiting Fragment', subtitle: 'A piece of the fallen star that refuses to land', hp: 2250, damage: 105, defense: 46, trait: 'orbiting-fragment-ward', specials: [{ id: 'orbital-ward', name: 'Orbital Ward', barrier: .07 }, { id: 'falling-fragment', name: 'Falling Fragment', damage: [{ type: 'physical', coefficient: 1.5 }] }] },
  { dungeonId: 'starfallen-observatory', id: 'lenskeeper-remnant', name: 'Lenskeeper Remnant', subtitle: 'A ruined curator still aligning the observatory lens', hp: 2563, damage: 96, defense: 44, trait: 'lenskeeper-disruption', specials: [{ id: 'broken-lens', name: 'Broken Lens', damage: [{ type: 'arcane', coefficient: 1.2 }], status: { id: 'arcane-disruption' } }, { id: 'focus-shift', name: 'Focus Shift', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'starfallen-observatory', id: 'fallen-astromancer', name: 'Fallen Astromancer', subtitle: 'A scholar who mapped the sky until the sky answered', hp: 26000, damage: 120, defense: 72, resistances: { arcane: .25 }, trait: 'lenskeeper-disruption', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'astral-ray', name: 'Astral Ray', damage: [{ type: 'arcane', coefficient: 1.4 }] }, { id: 'collapsed-orbit', name: 'Collapsed Orbit', damage: [{ type: 'physical', coefficient: 1.2 }, { type: 'arcane', coefficient: .6 }] }, { id: 'arcane-distortion', name: 'Arcane Distortion', status: { id: 'arcane-disruption' } }, { id: 'star-ward', name: 'Star Ward', barrier: .07 }, { id: 'falling-star', name: 'Falling Star', damage: [{ type: 'arcane', coefficient: 2.2 }] }] },

  { dungeonId: 'broken-meridian', id: 'meridian-warden', name: 'Meridian Warden', subtitle: 'A guardian holding four broken currents apart', hp: 3625, damage: 112, defense: 70, trait: 'meridian-warden-ward', specials: [{ id: 'meridian-ward', name: 'Meridian Ward', barrier: .09 }, { id: 'current-strike', name: 'Current Strike', damage: [{ type: 'arcane', coefficient: 1.5 }] }] },
  { dungeonId: 'broken-meridian', id: 'fractured-channeler', name: 'Fractured Channeler', subtitle: 'A caster split across incompatible elements', hp: 3250, damage: 118, defense: 48, trait: 'fractured-channeler-split', specials: [{ id: 'split-channel', name: 'Split Channel', damage: [{ type: 'fire', coefficient: .7 }, { type: 'water', coefficient: .7 }] }, { id: 'unstable-channel', name: 'Unstable Channel', status: { id: 'arcane-disruption' } }] },
  { dungeonId: 'broken-meridian', id: 'arc-surge-horror', name: 'Arc Surge Horror', subtitle: 'A current given teeth by a failed meridian', hp: 5000, damage: 120, defense: 58, resistances: { arcane: .2 }, trait: 'arc-surge-vulnerability', specials: [{ id: 'arc-surge', name: 'Arc Surge', damage: [{ type: 'arcane', coefficient: 1.5 }], status: { id: 'vulnerable' } }, { id: 'surge', name: 'Surge', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'broken-meridian', id: 'linebreaker-shade', name: 'Linebreaker Shade', subtitle: 'A shadow that cuts the leyline wherever it passes', hp: 2500, damage: 115, defense: 46, resistances: { physical: .2 }, trait: 'linebreaker-disruption', icon: { portraitIcon: 'ghost' }, specials: [{ id: 'linebreak', name: 'Linebreak', damage: [{ type: 'arcane', coefficient: 1.25 }], status: { id: 'arcane-disruption' } }, { id: 'shade-step', name: 'Shade Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'broken-meridian', id: 'meridian-splitter', name: 'Meridian Splitter', subtitle: 'The intelligence that made the frontier’s fracture permanent', hp: 34000, damage: 135, defense: 85, resistances: { fire: .1, water: .1, earth: .1, air: .1, arcane: .15 }, trait: 'meridian-warden-ward', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'flame-line', name: 'Flame Line', damage: [{ type: 'fire', coefficient: 1.2 }] }, { id: 'flood-line', name: 'Flood Line', damage: [{ type: 'water', coefficient: 1.2 }] }, { id: 'stone-line', name: 'Stone Line', damage: [{ type: 'earth', coefficient: 1.2 }] }, { id: 'gale-line', name: 'Gale Line', damage: [{ type: 'air', coefficient: 1.2 }] }, { id: 'meridian-barrier', name: 'Meridian Barrier', barrier: .08 }, { id: 'severed-meridian', name: 'Severed Meridian', damage: [{ type: 'arcane', coefficient: 2.3 }] }] },

  { dungeonId: 'hall-of-unbound-names', id: 'name-eater', name: 'Name-Eater', subtitle: 'A mouth in the archive that consumes identity', hp: 4000, damage: 122, defense: 52, trait: 'name-eater-silence', specials: [{ id: 'consume-name', name: 'Consume Name', damage: [{ type: 'arcane', coefficient: 1.25 }], status: { id: 'silenced' } }, { id: 'hunger', name: 'Hunger', status: { id: 'cursed' } }] },
  { dungeonId: 'hall-of-unbound-names', id: 'bound-echo', name: 'Bound Echo', subtitle: 'A voice caught in the hall and forced to repeat', hp: 3000, damage: 118, defense: 58, resistances: { physical: .15 }, trait: 'bound-echo-repetition', specials: [{ id: 'echo-strike', name: 'Echo Strike', damage: [{ type: 'arcane', coefficient: .65 }, { type: 'arcane', coefficient: .65 }] }, { id: 'repeat', name: 'Repeat', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'hall-of-unbound-names', id: 'hollow-liturgist', name: 'Hollow Liturgist', subtitle: 'A priest conducting a rite with no congregation', hp: 4250, damage: 120, defense: 60, trait: 'hollow-liturgist-curse', icon: { portraitIcon: 'mage' }, specials: [{ id: 'nameless-litany', name: 'Nameless Litany', status: { id: 'cursed' } }, { id: 'litany-flare', name: 'Litany Flare', damage: [{ type: 'arcane', coefficient: 1.45 }] }] },
  { dungeonId: 'hall-of-unbound-names', id: 'whisper-archivist', name: 'Whisper Archivist', subtitle: 'A keeper erasing formulas faster than they can be read', hp: 4375, damage: 125, defense: 48, trait: 'whisper-archivist-erasure', specials: [{ id: 'erased-formula', name: 'Erased Formula', damage: [{ type: 'arcane', coefficient: 1.2 }], status: { id: 'arcane-disruption' } }, { id: 'catalogue', name: 'Catalogue', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'hall-of-unbound-names', id: 'unspoken-prelate', name: 'Unspoken Prelate', subtitle: 'The hall’s highest voice, made terrifying by silence', hp: 42000, damage: 145, defense: 88, resistances: { arcane: .2 }, trait: 'name-eater-silence', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'unspoken-word', name: 'Unspoken Word', status: { id: 'silenced' } }, { id: 'litany-loss', name: 'Litany Loss', status: { id: 'cursed' } }, { id: 'erasure', name: 'Erasure', damage: [{ type: 'arcane', coefficient: 1.55 }] }, { id: 'binding-silence', name: 'Binding Silence', damage: [{ type: 'arcane', coefficient: 1.1 }], status: { id: 'silenced' } }, { id: 'nameless-judgment', name: 'Nameless Judgment', damage: [{ type: 'arcane', coefficient: 2.35 }] }] },

  { dungeonId: 'vault-of-the-black-sigil', id: 'sigil-guardian', name: 'Sigil Guardian', subtitle: 'A vault sentinel covered in self-renewing wards', hp: 3500, damage: 120, defense: 78, trait: 'sigil-guardian-ward', specials: [{ id: 'sigil-ward', name: 'Sigil Ward', barrier: .1 }, { id: 'guardian-crush', name: 'Guardian Crush', damage: [{ type: 'physical', coefficient: 1.5 }] }] },
  { dungeonId: 'vault-of-the-black-sigil', id: 'black-seal-parasite', name: 'Black Seal Parasite', subtitle: 'A crawling mark that feeds on every protective seal', hp: 3375, damage: 130, defense: 44, trait: 'black-seal-parasite-corruption', specials: [{ id: 'corrupting-bite', name: 'Corrupting Bite', damage: [{ type: 'physical', coefficient: 1.2 }], status: { id: 'corruption' } }, { id: 'black-pulse', name: 'Black Pulse', status: { id: 'cursed' } }] },
  { dungeonId: 'vault-of-the-black-sigil', id: 'vault-devourer', name: 'Vault Devourer', subtitle: 'A keeper-beast that consumes stored magic', hp: 4000, damage: 128, defense: 65, trait: 'vault-devourer-regrowth', specials: [{ id: 'devour-ward', name: 'Devour Ward', damage: [{ type: 'arcane', coefficient: 1.45 }] }, { id: 'dark-regrowth', name: 'Dark Regrowth', status: { id: 'regeneration', target: 'self' } }] },
  { dungeonId: 'vault-of-the-black-sigil', id: 'inkbound-specter', name: 'Inkbound Specter', subtitle: 'A ghost trapped inside an unfinished black contract', hp: 3875, damage: 124, defense: 50, resistances: { physical: .25 }, trait: 'inkbound-specter-curse', icon: { portraitIcon: 'ghost' }, specials: [{ id: 'black-ink', name: 'Black Ink', damage: [{ type: 'arcane', coefficient: 1.2 }], status: { id: 'cursed' } }, { id: 'ink-slip', name: 'Ink Slip', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'vault-of-the-black-sigil', id: 'sigil-warden', name: 'Sigil Warden', subtitle: 'The vault’s lock given a body and a hunger', hp: 44000, damage: 150, defense: 95, resistances: { arcane: .2 }, trait: 'sigil-guardian-ward', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'black-sigil', name: 'Black Sigil', status: { id: 'corruption' } }, { id: 'containment-ward', name: 'Containment Ward', barrier: .1 }, { id: 'vault-crush', name: 'Vault Crush', damage: [{ type: 'physical', coefficient: 1.65 }] }, { id: 'forbidden-seal', name: 'Forbidden Seal', status: { id: 'cursed' } }, { id: 'sigil-rupture', name: 'Sigil Rupture', damage: [{ type: 'arcane', coefficient: 2.3 }] }] },

  { dungeonId: 'black-gate', id: 'gatebound-remnant', name: 'Gatebound Remnant', subtitle: 'A fragment of a guardian still defending the threshold', hp: 6000, damage: 140, defense: 78, trait: 'gatebound-remnant-cleave', specials: [{ id: 'gate-cleave', name: 'Gate Cleave', damage: [{ type: 'physical', coefficient: 1.6 }] }, { id: 'threshold-stance', name: 'Threshold Stance', status: { id: 'fortified', target: 'self' } }] },
  { dungeonId: 'black-gate', id: 'black-rift-stalker', name: 'Black Rift Stalker', subtitle: 'A hunter that lives in the gap behind the portal', hp: 5375, damage: 148, defense: 55, resistances: { arcane: .15 }, trait: 'black-rift-stalker-corruption', icon: { portraitIcon: 'claw' }, specials: [{ id: 'rift-claw', name: 'Rift Claw', damage: [{ type: 'physical', coefficient: 1.1 }, { type: 'arcane', coefficient: .6 }], status: { id: 'corruption' } }, { id: 'void-step', name: 'Void Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'black-gate', id: 'portalbound-acolyte', name: 'Portalbound Acolyte', subtitle: 'A final supplicant waiting for the gate to answer', hp: 5625, damage: 145, defense: 60, trait: 'portalbound-acolyte-mute', icon: { portraitIcon: 'mage' }, specials: [{ id: 'portal-hex', name: 'Portal Hex', status: { id: 'cursed' } }, { id: 'mute-sigil', name: 'Mute Sigil', status: { id: 'silenced' } }] },
  { dungeonId: 'black-gate', id: 'sealbreaker-construct', name: 'Sealbreaker Construct', subtitle: 'A machine built to break every seal except its own', hp: 6500, damage: 138, defense: 95, resistances: { physical: .1 }, trait: 'sealbreaker-construct-ward', specials: [{ id: 'blackgate-ward', name: 'Blackgate Ward', barrier: .1 }, { id: 'sealbreaker-crush', name: 'Sealbreaker Crush', damage: [{ type: 'physical', coefficient: 1.7 }] }] },
  { dungeonId: 'black-gate', id: 'black-gatekeeper', name: 'Black Gatekeeper', subtitle: 'The final sentinel before the darkness beyond', hp: 65000, damage: 170, defense: 110, time: 2400, resistances: { physical: .1, arcane: .2, fire: .1, water: .1, earth: .1, air: .1 }, trait: 'sealbreaker-construct-ward', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'gatefire', name: 'Gatefire', damage: [{ type: 'fire', coefficient: 1.25 }] }, { id: 'abyssal-tide', name: 'Abyssal Tide', damage: [{ type: 'water', coefficient: 1.25 }] }, { id: 'broken-earth', name: 'Broken Earth', damage: [{ type: 'earth', coefficient: 1.25 }] }, { id: 'black-gale', name: 'Black Gale', damage: [{ type: 'air', coefficient: 1.25 }] }, { id: 'portal-corruption', name: 'Portal Corruption', status: { id: 'corruption' } }, { id: 'gate-seal', name: 'Gate Seal', barrier: .1 }, { id: 'unspoken-lock', name: 'Unspoken Lock', status: { id: 'silenced' } }, { id: 'black-rupture', name: 'Black Rupture', damage: [{ type: 'arcane', coefficient: 2.5 }] }] },
]

export const ACT1_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeMonster(spec)])) as Record<MonsterId, MonsterDefinition>
