import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { dungeonId: 'ashen-watch', id: 'cinder-hound', name: 'Cinder Hound', subtitle: 'A hunting beast with a furnace under its ribs', hp: 1438, damage: 78, defense: 28, resistances: { fire: .2, water: -.15 }, trait: 'cinder-hound-flameblood', icon: { portraitIcon: 'wolf' }, specials: [{ id: 'cinder-bite', name: 'Cinder Bite', damage: [{ type: 'physical', coefficient: .8 }, { type: 'fire', coefficient: .7 }], status: { id: 'burning' } }, { id: 'ember-trail', name: 'Ember Trail', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'ashen-watch', id: 'ash-cultist', name: 'Ash Cultist', subtitle: 'A zealot who feeds old watchfires with forbidden rites', hp: 1563, damage: 74, defense: 30, resistances: { fire: .15 }, trait: 'ash-cultist-fan', icon: { portraitIcon: 'mage' }, specials: [{ id: 'ember-bolt', name: 'Ember Bolt', damage: [{ type: 'fire', coefficient: 1.45 }] }, { id: 'fan-flames', name: 'Fan Flames', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'ashen-watch', id: 'fire-elemental', name: 'Fire Elemental', subtitle: 'A watchfire given a shape and a violent will', hp: 1688, damage: 80, defense: 34, resistances: { fire: .35, water: -.2 }, trait: 'fire-elemental-emberheart', icon: { portraitIcon: 'guardian' }, specials: [{ id: 'flame-lash', name: 'Flame Lash', damage: [{ type: 'fire', coefficient: 1.25 }], status: { id: 'burning' } }, { id: 'ember-heart', name: 'Ember Heart', status: { id: 'regeneration', target: 'self' } }] },
  { dungeonId: 'ashen-watch', id: 'lava-eel', name: 'Lava Eel', subtitle: 'A molten river predator coiled beneath the ash', hp: 1875, damage: 82, defense: 26, resistances: { fire: .25, water: -.15 }, trait: 'lava-eel-molten-hide', icon: { portraitIcon: 'plant' }, specials: [{ id: 'lava-surge', name: 'Lava Surge', damage: [{ type: 'fire', coefficient: 1.65 }] }, { id: 'molten-hide', name: 'Molten Hide', status: { id: 'fortified', target: 'self' } }] },
  { dungeonId: 'ashen-watch', id: 'flamebound-revenant', name: 'Flamebound Revenant', subtitle: 'A fallen commander still burning behind its armor', hp: 14500, damage: 95, defense: 52, resistances: { fire: .25, water: -.1 }, trait: 'fire-elemental-emberheart', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'flame-brand', name: 'Flame Brand', damage: [{ type: 'fire', coefficient: 1.25 }], status: { id: 'burning' } }, { id: 'ashen-burst', name: 'Ashen Burst', damage: [{ type: 'fire', coefficient: 1.6 }] }, { id: 'burning-guard', name: 'Burning Guard', barrier: .06 }, { id: 'cremation', name: 'Cremation', damage: [{ type: 'fire', coefficient: 2.1 }] }, { id: 'rekindle', name: 'Rekindle', status: { id: 'regeneration', target: 'self' } }] }
]

export const ASHEN_WATCH_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster(spec)])) as Record<MonsterId, MonsterDefinition>
