import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { dungeonId: 'ashen-watch', id: 'cinder-hound', combatV2: true, primaryAffinity: 'fire', basicAttackElement: 'fire', targetPower: 3050, name: 'Cinder Hound', subtitle: 'A hunting beast with a furnace under its ribs', hp: 1438, damage: 78, defense: 28, resistances: { fire: .2, water: -.15 }, resonanceYield: { fire: 24 }, trait: 'cinder-hound-flameblood', icon: { portraitIcon: 'wolf' }, specials: [{ id: 'cinder-bite', name: 'Cinder Bite', damage: [{ type: 'fire', coefficient: .8 }, { type: 'fire', coefficient: .7 }], dot: { statusId: 'burning', damageType: 'fire', coefficient: 0.9, durationMs: 5000 } }, { id: 'ember-trail', name: 'Ember Trail', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'ashen-watch', id: 'ash-cultist', combatV2: true, primaryAffinity: 'fire', basicAttackElement: 'fire', targetPower: 3250, name: 'Ash Cultist', subtitle: 'A zealot who feeds old watchfires with forbidden rites', hp: 1563, damage: 74, defense: 30, resistances: { fire: .15 }, resonanceYield: { fire: 28 }, trait: 'ash-cultist-fan', icon: { portraitIcon: 'mage' }, specials: [{ id: 'ember-bolt', name: 'Ember Bolt', damage: [{ type: 'fire', coefficient: 1.45 }] }, { id: 'fan-flames', name: 'Fan Flames', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'ashen-watch', id: 'fire-elemental', combatV2: true, primaryAffinity: 'fire', basicAttackElement: 'fire', targetPower: 3450, name: 'Fire Elemental', subtitle: 'A watchfire given a shape and a violent will', hp: 1688, damage: 80, defense: 34, resistances: { fire: .35, water: -.2 }, resonanceYield: { fire: 26 }, trait: 'fire-elemental-emberheart', icon: { portraitIcon: 'guardian' }, specials: [{ id: 'flame-lash', name: 'Flame Lash', damage: [{ type: 'fire', coefficient: 1.25 }], dot: { statusId: 'burning', damageType: 'fire', coefficient: 0.9, durationMs: 5000 } }, { id: 'ember-heart', name: 'Ember Heart', heal: .06 }] },
  { dungeonId: 'ashen-watch', id: 'lava-eel', combatV2: true, primaryAffinity: 'fire', basicAttackElement: 'fire', targetPower: 3650, name: 'Lava Eel', subtitle: 'A molten river predator coiled beneath the ash', hp: 1875, damage: 82, defense: 26, resistances: { fire: .25, water: -.15 }, resonanceYield: { fire: 30 }, trait: 'lava-eel-molten-hide', icon: { portraitIcon: 'plant' }, specials: [{ id: 'lava-surge', name: 'Lava Surge', damage: [{ type: 'fire', coefficient: 1.65 }] }, { id: 'molten-hide', name: 'Molten Hide', status: { id: 'fortified', target: 'self' } }] },
  { dungeonId: 'ashen-watch', id: 'flamebound-revenant', combatV2: true, primaryAffinity: 'fire', basicAttackElement: 'fire', targetPower: 5100, name: 'Flamebound Revenant', subtitle: 'A fallen commander still burning behind its armor', hp: 14500, damage: 95, defense: 52, resistances: { fire: .25, water: -.1 }, resonanceYield: { fire: 100 }, trait: 'fire-elemental-emberheart', combatV2Traits: ['flamebound-rekindle'], boss: true, specials: [{ id: 'flame-brand', name: 'Flame Brand', damage: [{ type: 'fire', coefficient: 1.25 }], dot: { statusId: 'burning', damageType: 'fire', coefficient: 1.4, durationMs: 5000 } }, { id: 'ashen-burst', name: 'Ashen Burst', damage: [{ type: 'fire', coefficient: 1.6 }] }, { id: 'burning-guard', name: 'Burning Guard', barrier: .06 }, { id: 'cremation', name: 'Cremation', damage: [{ type: 'fire', coefficient: 2.1 }] }] }
,  { dungeonId: 'ashen-watch', id: 'emberwing-harrier', combatV2: true, primaryAffinity: 'fire', basicAttackElement: 'fire', targetPower: 3850, name: 'Emberwing Harrier', subtitle: 'A hunting flame that dives through smoke and spellwork', hp: 1725, damage: 86, defense: 28, time: 2150, resonanceYield: { fire: 34 }, trait: 'cinder-hound-flameblood', icon: { portraitIcon: 'wisp' }, specials: [{ id: 'emberwing-dive', name: 'Emberwing Dive', damage: [{ type: 'fire', coefficient: 1.1 }, { type: 'fire', coefficient: .8 }], dot: { statusId: 'burning', damageType: 'fire', coefficient: 0.9, durationMs: 5000 } }, { id: 'smoke-rise', name: 'Smoke Rise', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'ashen-watch', id: 'charred-warden', combatV2: true, primaryAffinity: 'fire', basicAttackElement: 'fire', targetPower: 4100, name: 'Charred Warden', subtitle: 'A blackened guardian protecting a fire that should be dead', hp: 2250, damage: 88, defense: 58, time: 2800, resonanceYield: { fire: 38 }, trait: 'ash-cultist-fan', icon: { portraitIcon: 'guardian' }, specials: [{ id: 'charred-guard', name: 'Charred Guard', status: { id: 'fortified', target: 'self' } }, { id: 'brand-slam', name: 'Brand Slam', damage: [{ type: 'fire', coefficient: 1.35 }, { type: 'fire', coefficient: .65 }] }] },
  { dungeonId: 'ashen-watch', id: 'pyre-colossus', combatV2: true, primaryAffinity: 'fire', basicAttackElement: 'fire', targetPower: 4350, name: 'Pyre Colossus', subtitle: "A walking furnace assembled from the watch's fallen stones", hp: 2800, damage: 100, defense: 48, time: 2550, resonanceYield: { fire: 44 }, trait: 'fire-elemental-emberheart', icon: { portraitIcon: 'guardian' }, specials: [{ id: 'pyre-eruption', name: 'Pyre Eruption', damage: [{ type: 'fire', coefficient: 1.55 }], dot: { statusId: 'burning', damageType: 'fire', coefficient: 0.9, durationMs: 5000 } }, { id: 'falling-cinders', name: 'Falling Cinders', damage: [{ type: 'fire', coefficient: 1.1 }] }] },
]

export const ASHEN_WATCH_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster(spec)])) as Record<MonsterId, MonsterDefinition>
