import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { dungeonId: 'black-gate', id: 'gatebound-remnant', name: 'Gatebound Remnant', subtitle: 'A fragment of a guardian still defending the threshold', hp: 6000, damage: 140, defense: 78, trait: 'gatebound-remnant-cleave', specials: [{ id: 'gate-cleave', name: 'Gate Cleave', damage: [{ type: 'physical', coefficient: 1.6 }] }, { id: 'threshold-stance', name: 'Threshold Stance', status: { id: 'fortified', target: 'self' } }] },
  { dungeonId: 'black-gate', id: 'black-rift-stalker', name: 'Black Rift Stalker', subtitle: 'A hunter that lives in the gap behind the portal', hp: 5375, damage: 148, defense: 55, resistances: { arcane: .15 }, trait: 'black-rift-stalker-corruption', icon: { portraitIcon: 'claw' }, specials: [{ id: 'rift-claw', name: 'Rift Claw', damage: [{ type: 'physical', coefficient: 1.1 }, { type: 'arcane', coefficient: .6 }], status: { id: 'corruption' } }, { id: 'void-step', name: 'Void Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'black-gate', id: 'portalbound-acolyte', name: 'Portalbound Acolyte', subtitle: 'A final supplicant waiting for the gate to answer', hp: 5625, damage: 145, defense: 60, trait: 'portalbound-acolyte-mute', icon: { portraitIcon: 'mage' }, specials: [{ id: 'portal-hex', name: 'Portal Hex', status: { id: 'cursed' } }, { id: 'mute-sigil', name: 'Mute Sigil', status: { id: 'silenced' } }] },
  { dungeonId: 'black-gate', id: 'sealbreaker-construct', name: 'Sealbreaker Construct', subtitle: 'A machine built to break every seal except its own', hp: 6500, damage: 138, defense: 95, resistances: { physical: .1 }, trait: 'sealbreaker-construct-ward', specials: [{ id: 'blackgate-ward', name: 'Blackgate Ward', barrier: .1 }, { id: 'sealbreaker-crush', name: 'Sealbreaker Crush', damage: [{ type: 'physical', coefficient: 1.7 }] }] },
  { dungeonId: 'black-gate', id: 'black-gatekeeper', name: 'Black Gatekeeper', subtitle: 'The final sentinel before the darkness beyond', hp: 65000, damage: 170, defense: 110, time: 2400, resistances: { physical: .1, arcane: .2, fire: .1, water: .1, earth: .1, air: .1 }, trait: 'sealbreaker-construct-ward', resonanceYield: { fire: 150, water: 150, earth: 150, air: 150 }, boss: true, specials: [{ id: 'gatefire', name: 'Gatefire', damage: [{ type: 'fire', coefficient: 1.25 }] }, { id: 'abyssal-tide', name: 'Abyssal Tide', damage: [{ type: 'water', coefficient: 1.25 }] }, { id: 'broken-earth', name: 'Broken Earth', damage: [{ type: 'earth', coefficient: 1.25 }] }, { id: 'black-gale', name: 'Black Gale', damage: [{ type: 'air', coefficient: 1.25 }] }, { id: 'portal-corruption', name: 'Portal Corruption', status: { id: 'corruption' } }, { id: 'gate-seal', name: 'Gate Seal', barrier: .1 }, { id: 'unspoken-lock', name: 'Unspoken Lock', status: { id: 'silenced' } }, { id: 'black-rupture', name: 'Black Rupture', damage: [{ type: 'arcane', coefficient: 2.5 }] }] }
]

export const BLACK_GATE_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster(spec)])) as Record<MonsterId, MonsterDefinition>
