import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { dungeonId: 'broken-meridian', id: 'meridian-warden', name: 'Meridian Warden', subtitle: 'A guardian holding four broken currents apart', hp: 3625, damage: 112, defense: 70, trait: 'meridian-warden-ward', specials: [{ id: 'meridian-ward', name: 'Meridian Ward', barrier: .09 }, { id: 'current-strike', name: 'Current Strike', damage: [{ type: 'arcane', coefficient: 1.5 }] }] },
  { dungeonId: 'broken-meridian', id: 'fractured-channeler', name: 'Fractured Channeler', subtitle: 'A caster split across incompatible elements', hp: 3250, damage: 118, defense: 48, trait: 'fractured-channeler-split', specials: [{ id: 'split-channel', name: 'Split Channel', damage: [{ type: 'fire', coefficient: .7 }, { type: 'water', coefficient: .7 }] }, { id: 'unstable-channel', name: 'Unstable Channel', status: { id: 'arcane-disruption' } }] },
  { dungeonId: 'broken-meridian', id: 'arc-surge-horror', name: 'Arc Surge Horror', subtitle: 'A current given teeth by a failed meridian', hp: 5000, damage: 120, defense: 58, resistances: { arcane: .2 }, trait: 'arc-surge-vulnerability', specials: [{ id: 'arc-surge', name: 'Arc Surge', damage: [{ type: 'arcane', coefficient: 1.5 }], status: { id: 'vulnerable' } }, { id: 'surge', name: 'Surge', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'broken-meridian', id: 'linebreaker-shade', name: 'Linebreaker Shade', subtitle: 'A shadow that cuts the leyline wherever it passes', hp: 2500, damage: 115, defense: 46, resistances: { physical: .2 }, trait: 'linebreaker-disruption', icon: { portraitIcon: 'ghost' }, specials: [{ id: 'linebreak', name: 'Linebreak', damage: [{ type: 'arcane', coefficient: 1.25 }], status: { id: 'arcane-disruption' } }, { id: 'shade-step', name: 'Shade Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'broken-meridian', id: 'meridian-splitter', name: 'Meridian Splitter', subtitle: 'The intelligence that made the frontier’s fracture permanent', hp: 34000, damage: 135, defense: 85, resistances: { fire: .1, water: .1, earth: .1, air: .1, arcane: .15 }, trait: 'meridian-warden-ward', boss: true, specials: [{ id: 'flame-line', name: 'Flame Line', damage: [{ type: 'fire', coefficient: 1.2 }] }, { id: 'flood-line', name: 'Flood Line', damage: [{ type: 'water', coefficient: 1.2 }] }, { id: 'stone-line', name: 'Stone Line', damage: [{ type: 'earth', coefficient: 1.2 }] }, { id: 'gale-line', name: 'Gale Line', damage: [{ type: 'air', coefficient: 1.2 }] }, { id: 'meridian-barrier', name: 'Meridian Barrier', barrier: .08 }, { id: 'severed-meridian', name: 'Severed Meridian', damage: [{ type: 'arcane', coefficient: 2.3 }] }] }
]

export const BROKEN_MERIDIAN_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster(spec)])) as Record<MonsterId, MonsterDefinition>
