import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { dungeonId: 'crossroads-of-ruin', id: 'remnant-marauder', name: 'Remnant Marauder', subtitle: 'A road-warrior assembled from every failed expedition', hp: 2063, damage: 88, defense: 38, trait: 'remnant-marauder-pressure', specials: [{ id: 'ruin-cleave', name: 'Ruin Cleave', damage: [{ type: 'physical', coefficient: 1.55 }] }, { id: 'pressure', name: 'Pressure', status: { id: 'vulnerable' } }] },
  { dungeonId: 'crossroads-of-ruin', id: 'arcane-binder', name: 'Arcane Binder', subtitle: 'A warden tying broken roads together with hostile sigils', hp: 1500, damage: 86, defense: 32, trait: 'arcane-binder-binding', specials: [{ id: 'binding-hex', name: 'Binding Hex', damage: [{ type: 'arcane', coefficient: 1.15 }], status: { id: 'arcane-disruption' } }, { id: 'bind', name: 'Bind', status: { id: 'entangled' } }] },
  { dungeonId: 'crossroads-of-ruin', id: 'broken-construct', name: 'Broken Construct', subtitle: 'A road marker that learned to defend itself', hp: 2375, damage: 80, defense: 58, trait: 'broken-construct-ward', specials: [{ id: 'road-ward', name: 'Road Ward', barrier: .08 }, { id: 'construct-slam', name: 'Construct Slam', damage: [{ type: 'physical', coefficient: 1.5 }] }] },
  { dungeonId: 'crossroads-of-ruin', id: 'rift-archer', name: 'Rift Archer', subtitle: 'A scout firing arrows through the space between roads', hp: 1813, damage: 90, defense: 30, trait: 'rift-archer-precision', icon: { portraitIcon: 'claw' }, specials: [{ id: 'rift-shot', name: 'Rift Shot', damage: [{ type: 'air', coefficient: 1.55 }] }, { id: 'split-step', name: 'Split Step', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'crossroads-of-ruin', id: 'crossroads-keeper', name: 'Crossroads Keeper', subtitle: 'A many-faced custodian of the broken convergence', hp: 19500, damage: 105, defense: 70, trait: 'broken-construct-ward', resonanceYield: { fire: 75, water: 75, earth: 75, air: 75 }, boss: true, specials: [{ id: 'waystone-flame', name: 'Waystone Flame', damage: [{ type: 'fire', coefficient: 1.25 }] }, { id: 'flooded-path', name: 'Flooded Path', damage: [{ type: 'water', coefficient: 1.2 }], status: { id: 'chilled' } }, { id: 'rooted-road', name: 'Rooted Road', damage: [{ type: 'earth', coefficient: 1.15 }], status: { id: 'entangled' } }, { id: 'rift-lane', name: 'Rift Lane', damage: [{ type: 'air', coefficient: 1.25 }] }, { id: 'crossroads-ward', name: 'Crossroads Ward', barrier: .07 }, { id: 'convergence', name: 'Convergence', damage: [{ type: 'arcane', coefficient: 2.1 }] }] }
]

export const CROSSROADS_OF_RUIN_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster(spec)])) as Record<MonsterId, MonsterDefinition>
