import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { dungeonId: 'flooded-reliquary', id: 'drowned-acolyte', name: 'Drowned Acolyte', subtitle: 'A waterlogged priest still chanting beneath the tide', hp: 1875, damage: 72, defense: 34, time: 2500, resonanceYield: { water: 24 }, trait: 'drowned-acolyte-devotion', icon: { portraitIcon: 'mage' }, specials: [{ id: 'drowning-bolt', name: 'Drowning Bolt', damage: [{ type: 'water', coefficient: 1.4 }], status: { id: 'chilled' } }, { id: 'devotion', name: 'Drowned Devotion', status: { id: 'fortified', target: 'self' } }] },
  { dungeonId: 'flooded-reliquary', id: 'reliquary-slime', name: 'Reliquary Slime', subtitle: 'A living spill of preserved alchemical water', hp: 1813, damage: 68, defense: 40, time: 2700, resistances: { physical: .15, fire: -.1 }, resonanceYield: { water: 28 }, trait: 'reliquary-slime-engulf', specials: [{ id: 'engulf', name: 'Engulf', damage: [{ type: 'water', coefficient: 1.2 }], manaDrain: 8 }, { id: 'slick-form', name: 'Slick Form', status: { id: 'fortified', target: 'self' } }] },
  { dungeonId: 'flooded-reliquary', id: 'mist-wraith', name: 'Mist Wraith', subtitle: 'A cold memory refusing to condense', hp: 1375, damage: 76, defense: 26, time: 2200, resistances: { physical: .35, fire: -.1 }, resonanceYield: { water: 26 }, trait: 'mist-wraith-fade', icon: { portraitIcon: 'ghost' }, specials: [{ id: 'cold-veil', name: 'Cold Veil', damage: [{ type: 'water', coefficient: 1.15 }], status: { id: 'chilled' } }, { id: 'mist-fade', name: 'Mist Fade', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'flooded-reliquary', id: 'rune-leech', name: 'Rune Leech', subtitle: 'A parasite feeding on the reliquary’s arcane inscriptions', hp: 1563, damage: 70, defense: 28, time: 2150, resistances: { arcane: .15 }, trait: 'rune-leech-siphon', specials: [{ id: 'siphon-rune', name: 'Siphon Rune', damage: [{ type: 'arcane', coefficient: 1.1 }], manaDrain: 12 }, { id: 'rune-hunger', name: 'Rune Hunger', status: { id: 'arcane-disruption' } }] },
  { dungeonId: 'flooded-reliquary', id: 'drowned-keeper', name: 'Drowned Keeper', subtitle: 'The reliquary’s keeper, swollen with the weight of the deep', hp: 13500, damage: 88, defense: 58, time: 2450, resistances: { water: .2, fire: -.1 }, trait: 'drowned-acolyte-devotion', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'tidal-sweep', name: 'Tidal Sweep', damage: [{ type: 'water', coefficient: 1.35 }] }, { id: 'deep-chill', name: 'Deep Chill', damage: [{ type: 'water', coefficient: 1.1 }], status: { id: 'chilled' } }, { id: 'drowning-seal', name: 'Drowning Seal', damage: [{ type: 'arcane', coefficient: 1 }], manaDrain: 20 }, { id: 'reliquary-ward', name: 'Reliquary Ward', barrier: .07 }, { id: 'undertow', name: 'Undertow', damage: [{ type: 'water', coefficient: 2 }] }] }
,  { dungeonId: 'flooded-reliquary', id: 'tidefang-serpent', name: 'Tidefang Serpent', subtitle: 'A river predator sharpened by the Scar tides', hp: 1750, damage: 78, defense: 30, time: 2300, resonanceYield: { water: 34 }, trait: 'drowned-acolyte-devotion', icon: { portraitIcon: 'wolf' }, specials: [{ id: 'tidefang-lunge', name: 'Tidefang Lunge', damage: [{ type: 'physical', coefficient: 1.15 }, { type: 'water', coefficient: .65 }], status: { id: 'chilled' } }, { id: 'undertow-coil', name: 'Undertow Coil', status: { id: 'entangled' } }] },
  { dungeonId: 'flooded-reliquary', id: 'brinebound-sentinel', name: 'Brinebound Sentinel', subtitle: 'A warding shell still standing watch beneath the flood', hp: 2250, damage: 84, defense: 56, time: 2800, resonanceYield: { water: 38 }, trait: 'reliquary-slime-engulf', icon: { portraitIcon: 'guardian' }, specials: [{ id: 'brinewall', name: 'Brinewall', status: { id: 'fortified', target: 'self' } }, { id: 'salt-crush', name: 'Salt Crush', damage: [{ type: 'physical', coefficient: 1.35 }, { type: 'water', coefficient: .55 }] }] },
  { dungeonId: 'flooded-reliquary', id: 'abyssal-archivist', name: 'Abyssal Archivist', subtitle: 'A drowned keeper of names the water could not erase', hp: 2650, damage: 96, defense: 44, time: 2400, resonanceYield: { water: 44 }, trait: 'rune-leech-siphon', icon: { portraitIcon: 'mage' }, specials: [{ id: 'abyssal-index', name: 'Abyssal Index', damage: [{ type: 'arcane', coefficient: 1.5 }], manaDrain: 10 }, { id: 'drowned-footnote', name: 'Drowned Footnote', status: { id: 'arcane-disruption' } }] },
]

const resonanceOverrides: Partial<Record<MonsterId, MonsterDefinition['resonanceYield']>> = {
  'rune-leech': { water: 30 },
  'drowned-keeper': { water: 100 },
}

export const FLOODED_RELIQUARY_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster({ ...spec, resonanceYield: spec.resonanceYield ?? resonanceOverrides[spec.id] })])) as Record<MonsterId, MonsterDefinition>
