import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { dungeonId: 'graveglass-hollow', id: 'graveglass-shade', name: 'Graveglass Shade', subtitle: 'A reflection that learned how to curse the living', hp: 3125, damage: 98, defense: 34, resistances: { physical: .25 }, trait: 'graveglass-shade-cursed', icon: { portraitIcon: 'ghost' }, specials: [{ id: 'graveglass-touch', name: 'Graveglass Touch', damage: [{ type: 'arcane', coefficient: 1.35 }], status: { id: 'cursed' } }, { id: 'shard-step', name: 'Shard Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'graveglass-hollow', id: 'bone-shardling', name: 'Bone Shardling', subtitle: 'A splinter of a tomb animated by pressure', hp: 2313, damage: 100, defense: 45, trait: 'bone-shardling-brittle', specials: [{ id: 'shard-rend', name: 'Shard Rend', damage: [{ type: 'physical', coefficient: 1.45 }], status: { id: 'fragile' } }, { id: 'bone-wall', name: 'Bone Wall', barrier: .05 }] },
  { dungeonId: 'graveglass-hollow', id: 'silent-mourner', name: 'Silent Mourner', subtitle: 'A mourner whose grief has outlived its voice', hp: 2125, damage: 92, defense: 32, trait: 'silent-mourner-fade', icon: { portraitIcon: 'ghost' }, specials: [{ id: 'mourning-curse', name: 'Mourning Curse', status: { id: 'cursed' } }, { id: 'quiet-step', name: 'Quiet Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'graveglass-hollow', id: 'crypt-guardian', name: 'Crypt Guardian', subtitle: 'A sealed defender carrying a garden of grave moss', hp: 2875, damage: 90, defense: 62, trait: 'crypt-guardian-ward', specials: [{ id: 'crypt-ward', name: 'Crypt Ward', barrier: .08 }, { id: 'grave-regrowth', name: 'Grave Regrowth', status: { id: 'regeneration', target: 'self' } }] },
  { dungeonId: 'graveglass-hollow', id: 'graveglass-behemoth', name: 'Graveglass Behemoth', subtitle: 'A giant of tomb glass and accumulated sorrow', hp: 25000, damage: 116, defense: 78, resistances: { physical: .15, arcane: .15 }, trait: 'crypt-guardian-ward', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'shard-break', name: 'Shard Break', damage: [{ type: 'physical', coefficient: 1.6 }], status: { id: 'fragile' } }, { id: 'grave-curse', name: 'Grave Curse', status: { id: 'cursed' } }, { id: 'crystal-burst', name: 'Crystal Burst', damage: [{ type: 'arcane', coefficient: 1.7 }] }, { id: 'graveglass-regeneration', name: 'Graveglass Regeneration', status: { id: 'regeneration', target: 'self' } }, { id: 'behemoth-crush', name: 'Behemoth Crush', damage: [{ type: 'physical', coefficient: 2.2 }] }] }
]

export const GRAVEGLASS_HOLLOW_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster(spec)])) as Record<MonsterId, MonsterDefinition>
