import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { dungeonId: 'graveglass-hollow', id: 'graveglass-shade', name: 'Graveglass Shade', subtitle: 'A reflection that learned how to curse the living', hp: 3125, damage: 98, defense: 34, resistances: { physical: .25 }, resonanceYield: { water: 24, earth: 12 }, trait: 'graveglass-shade-cursed', icon: { portraitIcon: 'ghost' }, specials: [{ id: 'graveglass-touch', name: 'Graveglass Touch', damage: [{ type: 'arcane', coefficient: 1.35 }], status: { id: 'cursed' } }, { id: 'shard-step', name: 'Shard Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'graveglass-hollow', id: 'bone-shardling', name: 'Bone Shardling', subtitle: 'A splinter of a tomb animated by pressure', hp: 2313, damage: 100, defense: 45, resonanceYield: { earth: 34 }, trait: 'bone-shardling-brittle', specials: [{ id: 'shard-rend', name: 'Shard Rend', damage: [{ type: 'physical', coefficient: 1.45 }], status: { id: 'fragile' } }, { id: 'bone-wall', name: 'Bone Wall', barrier: .05 }] },
  { dungeonId: 'graveglass-hollow', id: 'silent-mourner', name: 'Silent Mourner', subtitle: 'A mourner whose grief has outlived its voice', hp: 2125, damage: 92, defense: 32, resonanceYield: { water: 32 }, trait: 'silent-mourner-fade', icon: { portraitIcon: 'ghost' }, specials: [{ id: 'mourning-curse', name: 'Mourning Curse', status: { id: 'cursed' } }, { id: 'quiet-step', name: 'Quiet Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'graveglass-hollow', id: 'crypt-guardian', name: 'Crypt Guardian', subtitle: 'A sealed defender carrying a garden of grave moss', hp: 2875, damage: 90, defense: 62, resonanceYield: { earth: 38 }, trait: 'crypt-guardian-ward', specials: [{ id: 'crypt-ward', name: 'Crypt Ward', barrier: .08 }, { id: 'grave-regrowth', name: 'Grave Regrowth', status: { id: 'regeneration', target: 'self' } }] },
  { dungeonId: 'graveglass-hollow', id: 'epitaph-weaver', name: 'Epitaph Weaver', subtitle: 'A curse-caster stitching warnings into grave glass', hp: 3000, damage: 108, defense: 42, time: 2400, resonanceYield: { water: 38, earth: 16 }, trait: 'graveglass-shade-cursed', icon: { portraitIcon: 'mage' }, specials: [{ id: 'epitaph-hex', name: 'Epitaph Hex', damage: [{ type: 'arcane', coefficient: 1.3 }], status: { id: 'cursed' } }, { id: 'funeral-glass', name: 'Funeral Glass', barrier: .07 }] },
  { dungeonId: 'graveglass-hollow', id: 'tombglass-reaver', name: 'Tombglass Reaver', subtitle: 'A shard-armored raider that breaks wards by force', hp: 3900, damage: 116, defense: 58, time: 2250, resonanceYield: { earth: 52, water: 20 }, trait: 'bone-shardling-brittle', icon: { portraitIcon: 'guardian' }, specials: [{ id: 'shard-cleave', name: 'Shard Cleave', damage: [{ type: 'physical', coefficient: 1.45 }], status: { id: 'fragile' } }, { id: 'refracted-step', name: 'Refracted Step', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'graveglass-hollow', id: 'ossuary-oracle', name: 'Ossuary Oracle', subtitle: 'A bone seer whose warnings arrive as curses', hp: 3500, damage: 122, defense: 50, time: 2500, resonanceYield: { water: 58, earth: 24 }, trait: 'silent-mourner-fade', icon: { portraitIcon: 'mage' }, specials: [{ id: 'ossuary-omen', name: 'Ossuary Omen', damage: [{ type: 'arcane', coefficient: 1.55 }], status: { id: 'cursed' } }, { id: 'bone-sentence', name: 'Bone Sentence', damage: [{ type: 'arcane', coefficient: 1.25 }], status: { id: 'arcane-disruption' } }] },
  { dungeonId: 'graveglass-hollow', id: 'graveglass-behemoth', name: 'Graveglass Behemoth', subtitle: 'A giant of tomb glass and accumulated sorrow', hp: 25000, damage: 116, defense: 78, resistances: { physical: .15, arcane: .15 }, resonanceYield: { earth: 90, water: 70 }, trait: 'crypt-guardian-ward', boss: true, specials: [{ id: 'shard-break', name: 'Shard Break', damage: [{ type: 'physical', coefficient: 1.6 }], status: { id: 'fragile' } }, { id: 'grave-curse', name: 'Grave Curse', status: { id: 'cursed' } }, { id: 'crystal-burst', name: 'Crystal Burst', damage: [{ type: 'arcane', coefficient: 1.7 }] }, { id: 'graveglass-regeneration', name: 'Graveglass Regeneration', status: { id: 'regeneration', target: 'self' } }, { id: 'behemoth-crush', name: 'Behemoth Crush', damage: [{ type: 'physical', coefficient: 2.2 }] }] },
]

export const GRAVEGLASS_HOLLOW_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster(spec)])) as Record<MonsterId, MonsterDefinition>
