import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { dungeonId: 'hall-of-unbound-names', id: 'name-eater', name: 'Name-Eater', subtitle: 'A mouth in the archive that consumes identity', hp: 4000, damage: 122, defense: 52, trait: 'name-eater-silence', resonanceYield: { air: 36, water: 24 }, specials: [{ id: 'consume-name', name: 'Consume Name', damage: [{ type: 'arcane', coefficient: 1.25 }], status: { id: 'silenced' } }, { id: 'hunger', name: 'Hunger', status: { id: 'cursed' } }] },
  { dungeonId: 'hall-of-unbound-names', id: 'bound-echo', name: 'Bound Echo', subtitle: 'A voice caught in the hall and forced to repeat', hp: 3000, damage: 118, defense: 58, resistances: { physical: .15 }, resonanceYield: { air: 40, water: 20 }, trait: 'bound-echo-repetition', specials: [{ id: 'echo-strike', name: 'Echo Strike', damage: [{ type: 'arcane', coefficient: .65 }, { type: 'arcane', coefficient: .65 }] }, { id: 'repeat', name: 'Repeat', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'hall-of-unbound-names', id: 'hollow-liturgist', name: 'Hollow Liturgist', subtitle: 'A priest conducting a rite with no congregation', hp: 4250, damage: 120, defense: 60, resonanceYield: { water: 42, air: 24 }, trait: 'hollow-liturgist-curse', icon: { portraitIcon: 'mage' }, specials: [{ id: 'nameless-litany', name: 'Nameless Litany', status: { id: 'cursed' } }, { id: 'litany-flare', name: 'Litany Flare', damage: [{ type: 'arcane', coefficient: 1.45 }] }] },
  { dungeonId: 'hall-of-unbound-names', id: 'whisper-archivist', name: 'Whisper Archivist', subtitle: 'A keeper erasing formulas faster than they can be read', hp: 4375, damage: 125, defense: 48, resonanceYield: { air: 46, water: 28 }, trait: 'whisper-archivist-erasure', specials: [{ id: 'erased-formula', name: 'Erased Formula', damage: [{ type: 'arcane', coefficient: 1.2 }], status: { id: 'arcane-disruption' } }, { id: 'catalogue', name: 'Catalogue', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'hall-of-unbound-names', id: 'nameless-cantor', name: 'Nameless Cantor', subtitle: 'A hard silence-caster whose stolen verses linger', hp: 4700, damage: 130, defense: 56, time: 2400, resonanceYield: { water: 50, air: 32 }, trait: 'hollow-liturgist-curse', icon: { portraitIcon: 'mage' }, specials: [{ id: 'stolen-verse', name: 'Stolen Verse', damage: [{ type: 'arcane', coefficient: 1.4 }], status: { id: 'cursed' } }, { id: 'quiet-refrain', name: 'Quiet Refrain', damage: [{ type: 'arcane', coefficient: 1.1 }], status: { id: 'silenced' } }] },
  { dungeonId: 'hall-of-unbound-names', id: 'oathless-confessor', name: 'Oathless Confessor', subtitle: 'A debuff-caster turning confession into pressure', hp: 5400, damage: 136, defense: 64, time: 2500, resonanceYield: { water: 58, air: 36 }, trait: 'name-eater-silence', icon: { portraitIcon: 'mage' }, specials: [{ id: 'broken-oath', name: 'Broken Oath', damage: [{ type: 'arcane', coefficient: 1.55 }], status: { id: 'silenced' } }, { id: 'confession-of-ruin', name: 'Confession of Ruin', damage: [{ type: 'arcane', coefficient: 1.35 }], status: { id: 'arcane-disruption' } }] },
  { dungeonId: 'hall-of-unbound-names', id: 'unwritten-hierophant', name: 'Unwritten Hierophant', subtitle: 'A heavy Arcane caster reciting laws that never existed', hp: 5100, damage: 142, defense: 60, time: 2350, resonanceYield: { air: 68, water: 42 }, trait: 'whisper-archivist-erasure', icon: { portraitIcon: 'mage' }, specials: [{ id: 'unwritten-law', name: 'Unwritten Law', damage: [{ type: 'arcane', coefficient: 1.75 }], status: { id: 'cursed' } }, { id: 'unbound-recital', name: 'Unbound Recital', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'hall-of-unbound-names', id: 'unspoken-prelate', name: 'Unspoken Prelate', subtitle: 'The hall’s highest voice, made terrifying by silence', hp: 42000, damage: 145, defense: 88, resistances: { arcane: .2 }, resonanceYield: { air: 100, water: 100 }, trait: 'name-eater-silence', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'unspoken-word', name: 'Unspoken Word', status: { id: 'silenced' } }, { id: 'litany-loss', name: 'Litany Loss', status: { id: 'cursed' } }, { id: 'erasure', name: 'Erasure', damage: [{ type: 'arcane', coefficient: 1.55 }] }, { id: 'binding-silence', name: 'Binding Silence', damage: [{ type: 'arcane', coefficient: 1.1 }], status: { id: 'silenced' } }, { id: 'nameless-judgment', name: 'Nameless Judgment', damage: [{ type: 'arcane', coefficient: 2.35 }] }] }
]

export const HALL_OF_UNBOUND_NAMES_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster(spec)])) as Record<MonsterId, MonsterDefinition>
