import { FRACTURED_APPROACH_MONSTERS } from './fracturedApproach'
import { FLOODED_RELIQUARY_MONSTERS } from './floodedReliquary'
import { ASHEN_WATCH_MONSTERS } from './ashenWatch'
import { ROOTSCAR_HOLLOW_MONSTERS } from './rootscarHollow'
import { CROSSROADS_OF_RUIN_MONSTERS } from './crossroadsOfRuin'
import { GRAVEGLASS_HOLLOW_MONSTERS } from './graveglassHollow'
import { STORMVAULT_GALLERY_MONSTERS } from './stormvaultGallery'
import { STARFALLEN_OBSERVATORY_MONSTERS } from './starfallenObservatory'
import { BROKEN_MERIDIAN_MONSTERS } from './brokenMeridian'
import { HALL_OF_UNBOUND_NAMES_MONSTERS } from './hallOfUnboundNames'
import { VAULT_OF_THE_BLACK_SIGIL_MONSTERS } from './vaultOfTheBlackSigil'
import { BLACK_GATE_MONSTERS } from './blackGate'

export {
  FRACTURED_APPROACH_MONSTERS,
  FLOODED_RELIQUARY_MONSTERS,
  ASHEN_WATCH_MONSTERS,
  ROOTSCAR_HOLLOW_MONSTERS,
  CROSSROADS_OF_RUIN_MONSTERS,
  GRAVEGLASS_HOLLOW_MONSTERS,
  STORMVAULT_GALLERY_MONSTERS,
  STARFALLEN_OBSERVATORY_MONSTERS,
  BROKEN_MERIDIAN_MONSTERS,
  HALL_OF_UNBOUND_NAMES_MONSTERS,
  VAULT_OF_THE_BLACK_SIGIL_MONSTERS,
  BLACK_GATE_MONSTERS,
}

export const ACT1_MONSTERS = Object.assign(
  {},
  FRACTURED_APPROACH_MONSTERS,
  FLOODED_RELIQUARY_MONSTERS,
  ASHEN_WATCH_MONSTERS,
  ROOTSCAR_HOLLOW_MONSTERS,
  CROSSROADS_OF_RUIN_MONSTERS,
  GRAVEGLASS_HOLLOW_MONSTERS,
  STORMVAULT_GALLERY_MONSTERS,
  STARFALLEN_OBSERVATORY_MONSTERS,
  BROKEN_MERIDIAN_MONSTERS,
  HALL_OF_UNBOUND_NAMES_MONSTERS,
  VAULT_OF_THE_BLACK_SIGIL_MONSTERS,
  BLACK_GATE_MONSTERS,
)
