import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { dungeonId: 'rootscar-hollow', id: 'thorn-maw', name: 'Thorn Maw', subtitle: 'A carnivorous bloom grown around a poisoned root', hp: 1875, damage: 78, defense: 42, resonanceYield: { earth: 24 }, trait: 'thorn-maw-venom', icon: { portraitIcon: 'plant' }, specials: [{ id: 'venomous-bite', name: 'Venomous Bite', damage: [{ type: 'physical', coefficient: 1.25 }], dot: { statusId: 'poisoned', damageType: 'physical', coefficient: 0.5, durationMs: 8000 } }, { id: 'thorn-bloom', name: 'Thorn Bloom', status: { id: 'thorn-wound', target: 'self' } }] },
  { dungeonId: 'rootscar-hollow', id: 'rootbound-stalker', name: 'Rootbound Stalker', subtitle: 'A patient hunter hiding beneath the scarred soil', hp: 1250, damage: 82, defense: 32, resonanceYield: { earth: 28 }, trait: 'rootbound-stalker-ambush', icon: { portraitIcon: 'plant' }, specials: [{ id: 'root-ambush', name: 'Root Ambush', damage: [{ type: 'physical', coefficient: 1.35 }], status: { id: 'entangled' } }, { id: 'burrow', name: 'Burrow', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'rootscar-hollow', id: 'briar-sprite', name: 'Briar Sprite', subtitle: 'A small spirit with a spiteful garden to tend', hp: 1375, damage: 74, defense: 24, resistances: { earth: .15, fire: -.15 }, resonanceYield: { earth: 26 }, trait: 'briar-sprite-bloom', icon: { portraitIcon: 'wisp' }, specials: [{ id: 'briar-hex', name: 'Briar Hex', damage: [{ type: 'earth', coefficient: 1.15 }], dot: { statusId: 'poisoned', damageType: 'physical', coefficient: 0.45, durationMs: 8000 } }, { id: 'bloom', name: 'Bloom', status: { id: 'regeneration', target: 'self' } }] },
  { dungeonId: 'rootscar-hollow', id: 'moss-carapace', name: 'Moss Carapace', subtitle: 'A slow shell carrying a whole forest on its back', hp: 2063, damage: 72, defense: 52, resistances: { physical: .1 }, resonanceYield: { earth: 30 }, trait: 'moss-carapace-regrowth', specials: [{ id: 'shell-up', name: 'Shell Up', status: { id: 'fortified', target: 'self' } }, { id: 'moss-regrowth', name: 'Moss Regrowth', status: { id: 'regeneration', target: 'self' } }] },
  { dungeonId: 'rootscar-hollow', id: 'rootscar-ancient', name: 'Rootscar Ancient', subtitle: 'The oldest root beneath the frontier, awake and starving', hp: 15500, damage: 92, defense: 68, resistances: { earth: .25, fire: -.1 }, resonanceYield: { earth: 100 }, trait: 'moss-carapace-regrowth', boss: true, specials: [{ id: 'entangling-roots', name: 'Entangling Roots', damage: [{ type: 'earth', coefficient: 1.1 }], status: { id: 'entangled' } }, { id: 'toxic-sap', name: 'Toxic Sap', dot: { statusId: 'poisoned', damageType: 'physical', coefficient: 0.7, durationMs: 8000 } }, { id: 'barkwall', name: 'Barkwall', barrier: .08 }, { id: 'ancient-regrowth', name: 'Ancient Regrowth', status: { id: 'regeneration', target: 'self' } }, { id: 'earthsplit', name: 'Earthsplit', damage: [{ type: 'earth', coefficient: 2 }] }] }
,  { dungeonId: 'rootscar-hollow', id: 'sporeback-brute', name: 'Sporeback Brute', subtitle: 'A hulking carrier of spores that root into every wound', hp: 1900, damage: 86, defense: 46, time: 2600, resonanceYield: { earth: 34 }, trait: 'thorn-maw-venom', icon: { portraitIcon: 'plant' }, specials: [{ id: 'sporeback-slam', name: 'Sporeback Slam', damage: [{ type: 'physical', coefficient: 1.35 }], status: { id: 'poisoned' } }, { id: 'spore-cloud', name: 'Spore Cloud', status: { id: 'entangled' } }] },
  { dungeonId: 'rootscar-hollow', id: 'vinebound-reaver', name: 'Vinebound Reaver', subtitle: 'A bladed creeper that pulls prey into the green dark', hp: 2200, damage: 90, defense: 38, time: 2450, resonanceYield: { earth: 38 }, trait: 'rootbound-stalker-ambush', icon: { portraitIcon: 'plant' }, specials: [{ id: 'vinebound-lash', name: 'Vinebound Lash', damage: [{ type: 'physical', coefficient: 1.4 }], status: { id: 'entangled' } }, { id: 'reaver-burrow', name: 'Reaver Burrow', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'rootscar-hollow', id: 'scarwood-behemoth', name: 'Scarwood Behemoth', subtitle: 'A walking trunk grown around the Elemental Scarâ€™s oldest wound', hp: 2850, damage: 102, defense: 64, time: 2900, resonanceYield: { earth: 44 }, trait: 'moss-carapace-regrowth', icon: { portraitIcon: 'guardian' }, specials: [{ id: 'scarwood-crush', name: 'Scarwood Crush', damage: [{ type: 'physical', coefficient: 1.55 }] }, { id: 'rooted-regrowth', name: 'Rooted Regrowth', status: { id: 'regeneration', target: 'self' } }] },
]

export const ROOTSCAR_HOLLOW_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster(spec)])) as Record<MonsterId, MonsterDefinition>
