import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { dungeonId: 'rootscar-hollow', id: 'thorn-maw', name: 'Thorn Maw', subtitle: 'A carnivorous bloom grown around a poisoned root', hp: 1875, damage: 78, defense: 42, trait: 'thorn-maw-venom', icon: { portraitIcon: 'plant' }, specials: [{ id: 'venomous-bite', name: 'Venomous Bite', damage: [{ type: 'physical', coefficient: 1.25 }], dot: { statusId: 'poisoned', damageType: 'physical', coefficient: 0.5, durationMs: 8000 } }, { id: 'thorn-bloom', name: 'Thorn Bloom', status: { id: 'thorn-wound', target: 'self' } }] },
  { dungeonId: 'rootscar-hollow', id: 'rootbound-stalker', name: 'Rootbound Stalker', subtitle: 'A patient hunter hiding beneath the scarred soil', hp: 1250, damage: 82, defense: 32, trait: 'rootbound-stalker-ambush', icon: { portraitIcon: 'plant' }, specials: [{ id: 'root-ambush', name: 'Root Ambush', damage: [{ type: 'physical', coefficient: 1.35 }], status: { id: 'entangled' } }, { id: 'burrow', name: 'Burrow', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'rootscar-hollow', id: 'briar-sprite', name: 'Briar Sprite', subtitle: 'A small spirit with a spiteful garden to tend', hp: 1375, damage: 74, defense: 24, resistances: { earth: .15, fire: -.15 }, trait: 'briar-sprite-bloom', icon: { portraitIcon: 'wisp' }, specials: [{ id: 'briar-hex', name: 'Briar Hex', damage: [{ type: 'earth', coefficient: 1.15 }], dot: { statusId: 'poisoned', damageType: 'physical', coefficient: 0.45, durationMs: 8000 } }, { id: 'bloom', name: 'Bloom', status: { id: 'regeneration', target: 'self' } }] },
  { dungeonId: 'rootscar-hollow', id: 'moss-carapace', name: 'Moss Carapace', subtitle: 'A slow shell carrying a whole forest on its back', hp: 2063, damage: 72, defense: 52, resistances: { physical: .1 }, trait: 'moss-carapace-regrowth', specials: [{ id: 'shell-up', name: 'Shell Up', status: { id: 'fortified', target: 'self' } }, { id: 'moss-regrowth', name: 'Moss Regrowth', status: { id: 'regeneration', target: 'self' } }] },
  { dungeonId: 'rootscar-hollow', id: 'rootscar-ancient', name: 'Rootscar Ancient', subtitle: 'The oldest root beneath the frontier, awake and starving', hp: 15500, damage: 92, defense: 68, resistances: { earth: .25, fire: -.1 }, trait: 'moss-carapace-regrowth', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'entangling-roots', name: 'Entangling Roots', damage: [{ type: 'earth', coefficient: 1.1 }], status: { id: 'entangled' } }, { id: 'toxic-sap', name: 'Toxic Sap', dot: { statusId: 'poisoned', damageType: 'physical', coefficient: 0.7, durationMs: 8000 } }, { id: 'barkwall', name: 'Barkwall', barrier: .08 }, { id: 'ancient-regrowth', name: 'Ancient Regrowth', status: { id: 'regeneration', target: 'self' } }, { id: 'earthsplit', name: 'Earthsplit', damage: [{ type: 'earth', coefficient: 2 }] }] }
]

export const ROOTSCAR_HOLLOW_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster(spec)])) as Record<MonsterId, MonsterDefinition>
