import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { dungeonId: 'starfallen-observatory', id: 'starbound-eye', name: 'Starbound Eye', subtitle: 'A watching star that never learned mercy', hp: 2625, damage: 100, defense: 38, resistances: { arcane: .2 }, trait: 'starbound-eye-gaze', icon: { portraitIcon: 'wisp' }, specials: [{ id: 'star-gaze', name: 'Star Gaze', damage: [{ type: 'arcane', coefficient: 1.35 }], status: { id: 'arcane-disruption' } }, { id: 'orbit', name: 'Orbit', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'starfallen-observatory', id: 'astral-husk', name: 'Astral Husk', subtitle: 'A shell left behind when an astronomer vanished', hp: 2250, damage: 98, defense: 50, resistances: { arcane: .25 }, trait: 'astral-husk-weight', specials: [{ id: 'astral-hammer', name: 'Astral Hammer', damage: [{ type: 'arcane', coefficient: 1.55 }] }, { id: 'dead-orbit', name: 'Dead Orbit', status: { id: 'fragile' } }] },
  { dungeonId: 'starfallen-observatory', id: 'orbiting-fragment', name: 'Orbiting Fragment', subtitle: 'A piece of the fallen star that refuses to land', hp: 2250, damage: 105, defense: 46, trait: 'orbiting-fragment-ward', specials: [{ id: 'orbital-ward', name: 'Orbital Ward', barrier: .07 }, { id: 'falling-fragment', name: 'Falling Fragment', damage: [{ type: 'physical', coefficient: 1.5 }] }] },
  { dungeonId: 'starfallen-observatory', id: 'lenskeeper-remnant', name: 'Lenskeeper Remnant', subtitle: 'A ruined curator still aligning the observatory lens', hp: 2563, damage: 96, defense: 44, trait: 'lenskeeper-disruption', specials: [{ id: 'broken-lens', name: 'Broken Lens', damage: [{ type: 'arcane', coefficient: 1.2 }], status: { id: 'arcane-disruption' } }, { id: 'focus-shift', name: 'Focus Shift', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'starfallen-observatory', id: 'fallen-astromancer', name: 'Fallen Astromancer', subtitle: 'A scholar who mapped the sky until the sky answered', hp: 26000, damage: 120, defense: 72, resistances: { arcane: .25 }, trait: 'lenskeeper-disruption', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'astral-ray', name: 'Astral Ray', damage: [{ type: 'arcane', coefficient: 1.4 }] }, { id: 'collapsed-orbit', name: 'Collapsed Orbit', damage: [{ type: 'physical', coefficient: 1.2 }, { type: 'arcane', coefficient: .6 }] }, { id: 'arcane-distortion', name: 'Arcane Distortion', status: { id: 'arcane-disruption' } }, { id: 'star-ward', name: 'Star Ward', barrier: .07 }, { id: 'falling-star', name: 'Falling Star', damage: [{ type: 'arcane', coefficient: 2.2 }] }] }
]

export const STARFALLEN_OBSERVATORY_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster(spec)])) as Record<MonsterId, MonsterDefinition>
