import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { dungeonId: 'starfallen-observatory', id: 'starbound-eye', name: 'Starbound Eye', subtitle: 'A watching star that never learned mercy', hp: 2625, damage: 100, defense: 38, resonanceYield: { air: 24, fire: 16 }, resistances: { arcane: .2 }, trait: 'starbound-eye-gaze', icon: { portraitIcon: 'wisp' }, specials: [{ id: 'star-gaze', name: 'Star Gaze', damage: [{ type: 'arcane', coefficient: 1.35 }], status: { id: 'arcane-disruption' } }, { id: 'orbit', name: 'Orbit', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'starfallen-observatory', id: 'astral-husk', name: 'Astral Husk', subtitle: 'A shell left behind when an astronomer vanished', hp: 2250, damage: 98, defense: 50, resonanceYield: { air: 20, fire: 12 }, resistances: { arcane: .25 }, trait: 'astral-husk-weight', specials: [{ id: 'astral-hammer', name: 'Astral Hammer', damage: [{ type: 'arcane', coefficient: 1.55 }] }, { id: 'dead-orbit', name: 'Dead Orbit', status: { id: 'fragile' } }] },
  { dungeonId: 'starfallen-observatory', id: 'orbiting-fragment', name: 'Orbiting Fragment', subtitle: 'A piece of the fallen star that refuses to land', hp: 2250, damage: 105, defense: 46, resonanceYield: { air: 28, fire: 18 }, trait: 'orbiting-fragment-ward', specials: [{ id: 'orbital-ward', name: 'Orbital Ward', barrier: .07 }, { id: 'falling-fragment', name: 'Falling Fragment', damage: [{ type: 'physical', coefficient: 1.5 }] }] },
  { dungeonId: 'starfallen-observatory', id: 'lenskeeper-remnant', name: 'Lenskeeper Remnant', subtitle: 'A ruined curator still aligning the observatory lens', hp: 2563, damage: 96, defense: 44, resonanceYield: { air: 36, fire: 16 }, trait: 'lenskeeper-disruption', specials: [{ id: 'broken-lens', name: 'Broken Lens', damage: [{ type: 'arcane', coefficient: 1.2 }], status: { id: 'arcane-disruption' } }, { id: 'focus-shift', name: 'Focus Shift', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'starfallen-observatory', id: 'comet-wraith', name: 'Comet Wraith', subtitle: 'A burning wraith that crosses the sky in a single breath', hp: 3100, damage: 116, defense: 36, time: 2200, resonanceYield: { fire: 42, air: 22 }, trait: 'starbound-eye-gaze', icon: { portraitIcon: 'ghost' }, specials: [{ id: 'comet-trail', name: 'Comet Trail', damage: [{ type: 'fire', coefficient: 1.4 }], status: { id: 'burning' } }, { id: 'stellar-drift', name: 'Stellar Drift', status: { id: 'spectral-fade', target: 'self' } }] },
  { dungeonId: 'starfallen-observatory', id: 'voidglass-custodian', name: 'Voidglass Custodian', subtitle: "A silent custodian guarding the observatory's last lens", hp: 4100, damage: 120, defense: 64, time: 2700, resonanceYield: { air: 48, fire: 24 }, trait: 'orbiting-fragment-ward', icon: { portraitIcon: 'guardian' }, specials: [{ id: 'voidglass-ward', name: 'Voidglass Ward', barrier: .09 }, { id: 'refraction-burst', name: 'Refraction Burst', damage: [{ type: 'arcane', coefficient: 1.6 }], status: { id: 'arcane-disruption' } }] },
  { dungeonId: 'starfallen-observatory', id: 'zenith-horror', name: 'Zenith Horror', subtitle: 'A thing at the highest point where fire and air become one', hp: 3700, damage: 130, defense: 50, time: 2300, resonanceYield: { fire: 60, air: 30 }, trait: 'lenskeeper-disruption', icon: { portraitIcon: 'wisp' }, specials: [{ id: 'zenith-ray', name: 'Zenith Ray', damage: [{ type: 'fire', coefficient: .8 }, { type: 'air', coefficient: .8 }] }, { id: 'gravity-shear', name: 'Gravity Shear', damage: [{ type: 'arcane', coefficient: 1.5 }], status: { id: 'fragile' } }] },
  { dungeonId: 'starfallen-observatory', id: 'fallen-astromancer', name: 'Fallen Astromancer', subtitle: 'A scholar who mapped the sky until the sky answered', hp: 26000, damage: 120, defense: 72, resistances: { arcane: .25 }, resonanceYield: { fire: 80, air: 80 }, trait: 'lenskeeper-disruption', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'astral-ray', name: 'Astral Ray', damage: [{ type: 'arcane', coefficient: 1.4 }] }, { id: 'collapsed-orbit', name: 'Collapsed Orbit', damage: [{ type: 'physical', coefficient: 1.2 }, { type: 'arcane', coefficient: .6 }] }, { id: 'arcane-distortion', name: 'Arcane Distortion', status: { id: 'arcane-disruption' } }, { id: 'star-ward', name: 'Star Ward', barrier: .07 }, { id: 'falling-star', name: 'Falling Star', damage: [{ type: 'arcane', coefficient: 2.2 }] }] },
]

export const STARFALLEN_OBSERVATORY_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster(spec)])) as Record<MonsterId, MonsterDefinition>
