import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { dungeonId: 'stormvault-gallery', id: 'volt-wisp', name: 'Volt Wisp', subtitle: 'A spark trapped between two storm records', hp: 2188, damage: 96, defense: 28, resonanceYield: { air: 30 }, resistances: { air: .2 }, trait: 'volt-wisp-static', icon: { portraitIcon: 'wisp' }, specials: [{ id: 'volt-spark', name: 'Volt Spark', damage: [{ type: 'air', coefficient: 1.1 }], status: { id: 'shock', stacks: 1 } }, { id: 'static-charge', name: 'Static Charge', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'stormvault-gallery', id: 'gale-scribe', name: 'Gale Scribe', subtitle: 'A storm historian writing faster than thought', hp: 2438, damage: 94, defense: 34, resonanceYield: { air: 34 }, trait: 'gale-scribe-acceleration', icon: { portraitIcon: 'mage' }, specials: [{ id: 'gale-script', name: 'Gale Script', damage: [{ type: 'air', coefficient: 1.3 }] }, { id: 'acceleration-rune', name: 'Acceleration Rune', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'stormvault-gallery', id: 'charged-seeker', name: 'Charged Seeker', subtitle: 'A hunting current searching for a grounded target', hp: 2813, damage: 100, defense: 30, resonanceYield: { air: 40 }, trait: 'charged-seeker-twin-arc', specials: [{ id: 'twin-arc', name: 'Twin Arc', damage: [{ type: 'air', coefficient: .65 }, { type: 'air', coefficient: .65 }], status: { id: 'shock', stacks: 1 } }, { id: 'seek', name: 'Seek', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'stormvault-gallery', id: 'thundercoil-serpent', name: 'Thundercoil Serpent', subtitle: 'A storm serpent that stores lightning in every coil', hp: 3000, damage: 110, defense: 34, time: 2100, resonanceYield: { air: 44 }, trait: 'charged-seeker-twin-arc', icon: { portraitIcon: 'wolf' }, specials: [{ id: 'coil-arc', name: 'Coil Arc', damage: [{ type: 'air', coefficient: .7 }, { type: 'air', coefficient: .7 }], status: { id: 'shock', stacks: 1 } }, { id: 'lightning-shed', name: 'Lightning Shed', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'stormvault-gallery', id: 'static-armor', name: 'Static Armor', subtitle: 'A walking shell charged by a vault gallery', hp: 3750, damage: 90, defense: 66, resonanceYield: { air: 38 }, resistances: { physical: .1 }, trait: 'static-armor-ward', specials: [{ id: 'static-ward', name: 'Static Ward', barrier: .08 }, { id: 'armor-crush', name: 'Armor Crush', damage: [{ type: 'physical', coefficient: 1.5 }] }] },
  { dungeonId: 'stormvault-gallery', id: 'stormbound-curator', name: 'Stormbound Curator', subtitle: 'A curator defending the vault with sealed gales', hp: 3600, damage: 116, defense: 52, time: 2450, resonanceYield: { air: 50 }, trait: 'gale-scribe-acceleration', icon: { portraitIcon: 'mage' }, specials: [{ id: 'archive-gale', name: 'Archive Gale', damage: [{ type: 'air', coefficient: 1.5 }] }, { id: 'storm-seal', name: 'Storm Seal', barrier: .06 }] },
  { dungeonId: 'stormvault-gallery', id: 'tempest-engine', name: 'Tempest Engine', subtitle: 'A high-pressure engine built from captured thunder', hp: 4600, damage: 126, defense: 72, time: 2700, resonanceYield: { air: 62 }, trait: 'static-armor-ward', icon: { portraitIcon: 'guardian' }, specials: [{ id: 'thunder-ram', name: 'Thunder Ram', damage: [{ type: 'physical', coefficient: .8 }, { type: 'air', coefficient: 1 }], status: { id: 'shock', stacks: 1 } }, { id: 'overcharge', name: 'Overcharge', status: { id: 'haste', target: 'self' } }] },
  { dungeonId: 'stormvault-gallery', id: 'storm-archivist', name: 'Storm Archivist', subtitle: 'The gallery keeper cataloguing every lightning strike', hp: 25000, damage: 115, defense: 70, resistances: { air: .25, earth: -.1 }, resonanceYield: { air: 150 }, trait: 'static-armor-ward', boss: true, lifeEssence: { min: 25, max: 55 }, specials: [{ id: 'archive-spark', name: 'Archive Spark', damage: [{ type: 'air', coefficient: 1.2 }], status: { id: 'shock', stacks: 1 } }, { id: 'rapid-annotation', name: 'Rapid Annotation', status: { id: 'haste', target: 'self' } }, { id: 'forked-bolt', name: 'Forked Bolt', damage: [{ type: 'air', coefficient: .75 }, { type: 'air', coefficient: .75 }] }, { id: 'static-barrier', name: 'Static Barrier', barrier: .06 }, { id: 'final-discharge', name: 'Final Discharge', damage: [{ type: 'air', coefficient: 2.15 }] }] },
]

export const STORMVAULT_GALLERY_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster(spec)])) as Record<MonsterId, MonsterDefinition>
