import type { MonsterId } from '../../../types'
import { makeAct1Monster, type Act1MonsterSpec } from './act1MonsterFactory'
import type { MonsterDefinition } from '../monsterTypes'

const specs: Act1MonsterSpec[] = [
  { combatV2: true, dungeonId: 'vault-of-the-black-sigil', id: 'sigil-guardian', name: 'Sigil Guardian', subtitle: 'A vault sentinel covered in self-renewing wards', hp: 3500, damage: 120, defense: 78, targetPower: 11100, primaryAffinity: 'earth', basicAttackElement: 'earth', resonanceYield: { earth: 44, fire: 20 }, specials: [{ id: 'sigil-ward', name: 'Sigil Ward', barrier: .1 }, { id: 'guardian-crush', name: 'Guardian Crush', damage: [{ type: 'earth', coefficient: 1.5 }] }] },
  { combatV2: true, dungeonId: 'vault-of-the-black-sigil', id: 'black-seal-parasite', name: 'Black Seal Parasite', subtitle: 'A crawling mark that feeds on every protective seal', hp: 3375, damage: 130, defense: 44, targetPower: 10000, primaryAffinity: 'fire', basicAttackElement: 'fire', resonanceYield: { fire: 46, earth: 24 }, specials: [{ id: 'corrupting-bite', name: 'Corrupting Bite', damage: [{ type: 'fire', coefficient: 1.2 }], status: { id: 'corruption' } }, { id: 'black-pulse', name: 'Black Pulse', damage: [{ type: 'arcane', coefficient: .75 }], status: { id: 'cursed' } }] },
  { combatV2: true, dungeonId: 'vault-of-the-black-sigil', id: 'vault-devourer', name: 'Vault Devourer', subtitle: 'A keeper-beast that consumes stored magic', hp: 4000, damage: 128, defense: 65, targetPower: 11700, primaryAffinity: 'earth', basicAttackElement: 'earth', resonanceYield: { earth: 50, fire: 28 }, specials: [{ id: 'devour-ward', name: 'Devour Ward', damage: [{ type: 'arcane', coefficient: 1.45 }] }, { id: 'stone-hunger', name: 'Stone Hunger', damage: [{ type: 'earth', coefficient: 1.25 }] }, { id: 'dark-regrowth', name: 'Dark Regrowth', status: { id: 'fortified', target: 'self' } }] },
  { combatV2: true, dungeonId: 'vault-of-the-black-sigil', id: 'inkbound-specter', name: 'Inkbound Specter', subtitle: 'A ghost trapped inside an unfinished black contract', hp: 3875, damage: 124, defense: 50, targetPower: 10500, primaryAffinity: 'arcane', basicAttackElement: 'arcane', resonanceYield: { fire: 48, earth: 30 }, icon: { portraitIcon: 'ghost' }, specials: [{ id: 'black-ink', name: 'Black Ink', damage: [{ type: 'arcane', coefficient: 1.2 }], status: { id: 'cursed' } }, { id: 'ink-slip', name: 'Ink Slip', status: { id: 'spectral-fade', target: 'self' } }] },
  { combatV2: true, dungeonId: 'vault-of-the-black-sigil', id: 'sealbound-custodian', name: 'Sealbound Custodian', subtitle: 'A ward-keeper whose seals crackle with corruption', hp: 5000, damage: 132, defense: 82, time: 2600, targetPower: 12300, primaryAffinity: 'earth', basicAttackElement: 'earth', resonanceYield: { earth: 58, fire: 32 }, icon: { portraitIcon: 'guardian' }, specials: [{ id: 'keeper-ward', name: 'Keeper Ward', barrier: .08 }, { id: 'seal-lash', name: 'Seal Lash', damage: [{ type: 'earth', coefficient: .7 }, { type: 'arcane', coefficient: .7 }], status: { id: 'corruption' } }] },
  { combatV2: true, dungeonId: 'vault-of-the-black-sigil', id: 'blackscript-colossus', name: 'Blackscript Colossus', subtitle: 'A massive construct inscribed with living prohibitions', hp: 6200, damage: 140, defense: 96, time: 2800, targetPower: 13000, primaryAffinity: 'earth', basicAttackElement: 'earth', resonanceYield: { earth: 70, fire: 38 }, icon: { portraitIcon: 'guardian' }, specials: [{ id: 'scripted-crush', name: 'Scripted Crush', damage: [{ type: 'earth', coefficient: 1.7 }] }, { id: 'blackscript-pulse', name: 'Blackscript Pulse', damage: [{ type: 'arcane', coefficient: 1.2 }], status: { id: 'cursed' } }] },
  { combatV2: true, dungeonId: 'vault-of-the-black-sigil', id: 'voidseal-arbiter', name: 'Voidseal Arbiter', subtitle: 'A seal-judge balancing corruption against forbidden renewal', hp: 5600, damage: 144, defense: 76, time: 2450, targetPower: 13800, primaryAffinity: 'fire', basicAttackElement: 'fire', resonanceYield: { fire: 72, earth: 42 }, icon: { portraitIcon: 'mage' }, specials: [{ id: 'void-verdict', name: 'Void Verdict', damage: [{ type: 'fire', coefficient: .825 }, { type: 'arcane', coefficient: .825 }], status: { id: 'corruption' } }, { id: 'seal-renewal', name: 'Seal Renewal', barrier: .08 }] },
  { combatV2: true, dungeonId: 'vault-of-the-black-sigil', id: 'sigil-warden', name: 'Sigil Warden', subtitle: 'The vault’s lock given a body and a hunger', hp: 44000, damage: 150, defense: 95, targetPower: 16000, primaryAffinity: 'earth', basicAttackElement: 'earth', resistances: { arcane: .2 }, resonanceYield: { earth: 110, fire: 110 }, boss: true, specials: [{ id: 'black-sigil', name: 'Black Sigil', damage: [{ type: 'arcane', coefficient: .55 }], status: { id: 'corruption', stacks: 2 } }, { id: 'containment-ward', name: 'Containment Ward', barrier: .1 }, { id: 'vault-crush', name: 'Vault Crush', damage: [{ type: 'earth', coefficient: 1.65 }] }, { id: 'forbidden-seal', name: 'Forbidden Seal', status: { id: 'cursed' } }, { id: 'ember-seal', name: 'Ember Seal', damage: [{ type: 'fire', coefficient: 1.4 }] }, { id: 'sigil-rupture', name: 'Sigil Rupture', actionTimeMs: 3200, damage: [{ type: 'arcane', coefficient: 2.3 }] }] },
]

export const VAULT_OF_THE_BLACK_SIGIL_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeAct1Monster(spec)])) as Record<MonsterId, MonsterDefinition>
