import { useMemo, useState } from 'react'
import { GameTooltip } from '../../components/ui'
import { SIGIL_QUALITIES, type SigilQuality } from '../../game/content/sigils/sigilQualities'
import { SIGIL_SETS, SIGIL_SET_IDS, type SigilSetId } from '../../game/content/sigils/sigilSets'
import { SIGIL_MAIN_STAT_POOLS, SIGIL_SECONDARY_STAT_IDS, SIGIL_STAT_DEFINITIONS, type SigilStatId } from '../../game/content/sigils/sigilStats'
import { getEligibleSigilTraits, SIGIL_TRAITS, type SigilTraitId } from '../../game/content/sigils/sigilTraits'
import { SIGIL_TIERS } from '../../game/content/sigils/sigilTiers'
import { getSigilEnhancementCap } from '../../game/systems/sigils/sigilRuntime'
import type { SigilSlot } from '../../game/types'
import { useGameStore } from '../../store/gameStore'

export function DeveloperSigils() {
  const state = useGameStore()
  const [tier, setTier] = useState(1)
  const [quality, setQuality] = useState<SigilQuality>('legendary')
  const [setId, setSetId] = useState<SigilSetId>('arcane')
  const [slot, setSlot] = useState<SigilSlot>(1)
  const [mainStat, setMainStat] = useState<SigilStatId>(SIGIL_MAIN_STAT_POOLS[1][0])
  const [dust, setDust] = useState(String(state.sigils.dust))
  const [ignoreGlobalCap, setIgnoreGlobalCap] = useState(true)
  const [rollQuality, setRollQuality] = useState(.5)
  const [manualTrait, setManualTrait] = useState<SigilTraitId>('arcane-surge')
  const options = useMemo(() => SIGIL_MAIN_STAT_POOLS[slot] ?? [], [slot])
  const stored = Object.values(state.sigils.storage)
  const selected = stored[stored.length - 1]
  const eligibleTraits = selected ? getEligibleSigilTraits(selected.setId) : getEligibleSigilTraits(setId)
  const secondaryOptions = SIGIL_SECONDARY_STAT_IDS.filter((id) => id !== selected?.mainStatId && id !== mainStat)

  const create = () => { const selectedMain = options.includes(mainStat) ? mainStat : options[0]; useGameStore.getState().debugCreateSigil(tier, quality, setId, slot, selectedMain) }
  const enhanceTo = (instanceId: string, target: number) => { const store = useGameStore.getState(); for (let rank = store.sigils.storage[instanceId]?.rank ?? 0; rank < target; rank += 1) if (!store.debugEnhanceSigil(instanceId, { ignoreGlobalCap })) break }
  const configureSelected = (changes: Parameters<ReturnType<typeof useGameStore.getState>['debugConfigureSigil']> extends [string, infer Config] ? Config : never) => { if (selected) useGameStore.getState().debugConfigureSigil(selected.instanceId, changes) }
  const toggleSecondary = (statId: SigilStatId) => { if (!selected) return; const ids = selected.secondaries.map((secondary) => secondary.statId); configureSelected({ secondaryStatIds: ids.includes(statId) ? ids.filter((id) => id !== statId) : [...ids, statId], rollQuality01: rollQuality }) }
  const addTrait = (traitId: SigilTraitId) => { if (selected) configureSelected({ traitIds: [...selected.traitIds, traitId] }) }
  const clearEquipped = () => { const store = useGameStore.getState(); ([1, 2, 3, 4, 5, 6] as const).forEach((slotId) => store.unequipSigil(slotId)) }
  const unequipSelected = () => { if (selected) useGameStore.getState().unequipSigil(selected.slot) }
  const equipPattern = (pattern: 'all' | '2+2+2' | '4+2') => { clearEquipped(); const grouped = SIGIL_SET_IDS.map((id) => stored.filter((sigil) => sigil.setId === id)).filter((group) => group.length); const ids = pattern === 'all' ? stored.slice(0, 6) : pattern === '2+2+2' ? grouped.slice(0, 3).flatMap((group) => group.slice(0, 2)) : [...(grouped[0]?.slice(0, 4) ?? []), ...(grouped[1]?.slice(0, 2) ?? [])]; ids.slice(0, 6).forEach((sigil) => useGameStore.getState().equipSigil(sigil.instanceId)) }
  const simulateDrops = (count: number) => { const store = useGameStore.getState(); for (let index = 0; index < count; index += 1) store.debugCreateSigil(tier, quality, setId, ((index % 6) + 1) as SigilSlot, undefined) }
  const forceTrait = (index: 0 | 1) => { if (!selected) return; const candidates = getEligibleSigilTraits(selected.setId, selected.traitIds); if (candidates[index]) addTrait(candidates[index]) }

  return <div className="developer-tab"><header className="developer-tab-header"><div><span className="eyebrow">SIGIL LAB</span><h2>Arcane Sigils</h2><p>Spawn controlled instances, exercise enhancement gates, and inspect the live loadout.</p></div><GameTooltip content="Set the tester-only Dust balance directly."><label>DUST<input type="number" min="0" value={dust} onChange={(event) => setDust(event.target.value)} onBlur={() => useGameStore.getState().debugSetSigilDust(Number(dust))} /></label></GameTooltip></header>
    <div className="developer-form-grid"><label>Force Tier<select value={tier} onChange={(event) => setTier(Number(event.target.value))}>{SIGIL_TIERS.map((entry) => <option key={entry.tier} value={entry.tier}>{entry.label}</option>)}</select></label><label>Force Quality<select value={quality} onChange={(event) => setQuality(event.target.value as SigilQuality)}>{SIGIL_QUALITIES.map((entry) => <option key={entry.id} value={entry.id}>{entry.label}</option>)}</select></label><label>Force Set<select value={setId} onChange={(event) => setSetId(event.target.value as SigilSetId)}>{SIGIL_SET_IDS.map((id) => <option key={id} value={id}>{SIGIL_SETS[id].name}</option>)}</select></label><label>Force Slot<select value={slot} onChange={(event) => { const next = Number(event.target.value) as SigilSlot; setSlot(next); setMainStat(SIGIL_MAIN_STAT_POOLS[next][0]) }}>{[1, 2, 3, 4, 5, 6].map((value) => <option key={value} value={value}>{value}</option>)}</select></label><label>Main Stat<select value={mainStat} onChange={(event) => setMainStat(event.target.value as SigilStatId)}>{options.map((id) => <option key={id} value={id}>{SIGIL_STAT_DEFINITIONS[id].label}</option>)}</select></label></div>
    <div className="developer-inline-actions"><button onClick={create}>FORCE NEXT SIGIL</button><button onClick={create}>SPAWN CONTROLLED SIGIL</button><button onClick={() => useGameStore.getState().debugCreateSigil(tier, quality, setId, slot, undefined)}>SPAWN RANDOM STATS</button><GameTooltip content="Free +1 can optionally bypass the current Global Cap."><label><input type="checkbox" checked={ignoreGlobalCap} onChange={(event) => setIgnoreGlobalCap(event.target.checked)} /> IGNORE GLOBAL CAP</label></GameTooltip><button onClick={() => useGameStore.getState().debugAddSigilDust(10000)}>+10,000 DUST</button></div>
    <div className="developer-inline-actions"><button onClick={() => useGameStore.getState().debugCraftSigil('basic', tier, setId)}>FREE BASIC CRAFT</button><button onClick={() => useGameStore.getState().debugCraftSigil('focused', tier, setId, slot)}>FREE FOCUSED CRAFT</button><button onClick={() => selected && enhanceTo(selected.instanceId, selected.rank + 3)}>+3 RANKS</button><button onClick={() => selected && enhanceTo(selected.instanceId, getSigilEnhancementCap(useGameStore.getState()))}>UPGRADE TO CURRENT CAP</button><button onClick={() => selected && enhanceTo(selected.instanceId, SIGIL_QUALITIES.find((entry) => entry.id === selected.quality)?.maxRank ?? 0)}>UPGRADE TO QUALITY MAX</button></div>
    <div className="developer-inline-actions"><button onClick={clearEquipped}>CLEAR EQUIPPED</button><button onClick={() => selected && useGameStore.getState().equipSigil(selected.instanceId)}>EQUIP SELECTED</button><button onClick={unequipSelected}>UNEQUIP SELECTED</button><button onClick={() => equipPattern('all')}>FILL ALL SIX</button><button onClick={() => equipPattern('2+2+2')}>FILL 2+2+2</button><button onClick={() => equipPattern('4+2')}>FILL 4+2</button></div>
    <div className="developer-inline-actions"><button onClick={() => simulateDrops(100)}>SIMULATE 100 DROPS</button><button onClick={() => simulateDrops(1000)}>SIMULATE 1,000 DROPS</button><button onClick={() => simulateDrops(10000)}>SIMULATE 10,000 DROPS</button></div>
    {selected && <section className="developer-subpanel"><div className="card-head"><div><span className="eyebrow">MANUAL ROLL EDITOR</span><h3>T{selected.tier} {selected.quality} · {SIGIL_SETS[selected.setId].name} {selected.slot}</h3></div><b>+{selected.rank}</b></div><label>Roll Quality<select value={rollQuality} onChange={(event) => { const next = Number(event.target.value); setRollQuality(next); configureSelected({ rollQuality01: next }) }}><option value="0">Low</option><option value="0.5">Mid</option><option value="1">High</option></select></label><div><span className="eyebrow">MANUAL SECONDARIES</span><div className="developer-inline-actions">{secondaryOptions.map((id) => <GameTooltip key={id} content={SIGIL_STAT_DEFINITIONS[id].label}><label><input type="checkbox" checked={selected.secondaries.some((secondary) => secondary.statId === id)} onChange={() => toggleSecondary(id)} /> {SIGIL_STAT_DEFINITIONS[id].label}</label></GameTooltip>)}</div></div><div className="developer-inline-actions"><select aria-label="Manual Trait" value={manualTrait} onChange={(event) => setManualTrait(event.target.value as SigilTraitId)}>{eligibleTraits.map((id) => <option key={id} value={id}>{SIGIL_TRAITS[id].name}</option>)}</select><button onClick={() => addTrait(manualTrait)}>ADD TRAIT</button><button onClick={() => forceTrait(0)}>RANDOM TRAIT I</button><button onClick={() => forceTrait(1)}>RANDOM TRAIT II</button><button onClick={() => configureSelected({ traitIds: [] })}>CLEAR TRAITS</button></div></section>}
    <div className="developer-sigil-list">{stored.slice(-12).reverse().map((sigil) => <div key={sigil.instanceId}><span>T{sigil.tier} {sigil.quality} · {SIGIL_SETS[sigil.setId].name} {sigil.slot}</span><b>+{sigil.rank}</b><button onClick={() => useGameStore.getState().debugEnhanceSigil(sigil.instanceId, { ignoreGlobalCap })}>FREE +1</button><button onClick={() => useGameStore.getState().equipSigil(sigil.instanceId)}>EQUIP</button></div>)}</div>
  </div>
}
