import { Card, Status } from '../../components/ui'
import { MONSTER_IDS, MONSTERS } from '../../game/content/monsters'
import { getLootUnlockTier, isLootUnlockedAtTier, UNIVERSAL_LOOT_BOSS_MULTIPLIERS, UNIVERSAL_LOOT_TIERS, UNIVERSAL_LOOT_UNLOCK_REGISTRY } from '../../game/content/loot/universalLootTiers'
import { resolveCombatCurrencyRewardRange } from '../../game/systems/loot/combatCurrencyRewards'
import { resolveAuthoredLootDropChance, resolveAuthoredLootDropQuantity, resolveCombatLootContext, resolveLootTierDistribution } from '../../game/systems/loot/universalLootRuntime'
import { resolveEnemyResonanceReward } from '../../game/systems/resonance/resonanceRuntime'
import { getMonsterLocationEntries } from '../../game/systems/bestiary/bestiarySelectors'

const pct = (value: number) => `${(value * 100).toFixed(2)}%`
const fmt = (value: number) => Number.isInteger(value) ? value.toLocaleString() : value.toFixed(2)

export function DeveloperUniversalLootTiers() {
  const tiers = resolveLootTierDistribution(MONSTER_IDS, (enemyId) => resolveCombatLootContext(enemyId))
  const rows = MONSTER_IDS.map((enemyId) => {
    const context = resolveCombatLootContext(enemyId)
    return { enemyId, context, life: resolveCombatCurrencyRewardRange(enemyId, 'life-essence'), artifact: resolveCombatCurrencyRewardRange(enemyId, 'artifact-essence'), resonance: resolveEnemyResonanceReward(enemyId), locations: getMonsterLocationEntries(enemyId).map((entry) => entry.name).join(', ') }
  })
  return <div className="developer-tab-stack">
    <Card title="Universal Loot Tier power curves" action={<Status tone="active">POWER DRIVEN</Status>}><p className="muted">Canonical enemy Power selects one shared Universal Loot Tier. Item tier, Sigil tier, and Combat Tier remain separate classifications.</p><div className="developer-balance-table-wrap"><table className="developer-balance-table"><thead><tr>{['TIER', 'MIN POWER', 'NEXT THRESHOLD', 'QUANTITY', 'CHANCE', 'RARITY', 'SIGIL CHANCE', 'CRYSTAL CHANCE', 'UNLOCKS', 'AUTHORED ENEMIES'].map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{UNIVERSAL_LOOT_TIERS.map((tier, index) => <tr key={tier.tier}><th scope="row">T{tier.tier}</th><td>{fmt(tier.minPower)}</td><td>{UNIVERSAL_LOOT_TIERS[index + 1] ? fmt(UNIVERSAL_LOOT_TIERS[index + 1].minPower) : 'Open ended'}</td><td>{tier.quantityMultiplier.toFixed(2)}?</td><td>{tier.chanceMultiplier.toFixed(2)}?</td><td>{tier.rarityMultiplier.toFixed(2)}?</td><td>{pct(tier.sigilDropChance)}</td><td>{pct(tier.crystalCacheDropChance)}</td><td>{tier.unlocks.map((id) => UNIVERSAL_LOOT_UNLOCK_REGISTRY[id].label).join(', ') || (isLootUnlockedAtTier('crystal-cache-t1', tier) ? `${UNIVERSAL_LOOT_UNLOCK_REGISTRY['crystal-cache-t1'].label} eligible` : '?')}</td><td>{tiers[tier.tier]?.length ?? 0}</td></tr>)}</tbody></table></div></Card>
    <Card title="Canonical enemy reward audit" action={<Status tone="neutral">{rows.length} ENCOUNTERS</Status>}><p className="muted">Rewards use each enemy?s authored Power and loot tier, then authored, boss, guild, and hunter rules.</p><div className="developer-balance-table-wrap"><table className="developer-balance-table"><thead><tr>{['MONSTER / BOSS', 'LOCATION', 'POWER', 'LOOT TIER', 'LIFE ESSENCE', 'ARTIFACT ESSENCE', 'RESONANCE ?', 'SIGIL CHANCE', 'CRYSTAL CHANCE', 'AUTHORED LOOT'].map((label) => <th key={label}>{label}</th>)}</tr></thead><tbody>{rows.map(({ enemyId, context, life, artifact, resonance, locations }) => { const bossChance = context.isBoss ? UNIVERSAL_LOOT_BOSS_MULTIPLIERS.chance : 1; const sigilChance = Math.min(1, context.lootTier.sigilDropChance * bossChance); const crystalChance = isLootUnlockedAtTier('crystal-cache-t1', context.lootTier) ? Math.min(1, context.lootTier.crystalCacheDropChance * bossChance) : 0; const authoredLoot = MONSTERS[enemyId].loot.map((drop) => `${drop.itemId} ${resolveAuthoredLootDropQuantity(drop, drop.quantity.min, context)}?${resolveAuthoredLootDropQuantity(drop, drop.quantity.max, context)} (${pct(resolveAuthoredLootDropChance(drop, context))})`).join('; ') || 'None authored'; return <tr key={enemyId}><th scope="row">{MONSTERS[enemyId].name}{context.isBoss ? ' ? BOSS' : ''}</th><td>{locations || 'Unassigned'}</td><td>{fmt(context.effectivePower)}</td><td>T{context.lootTier.tier}</td><td>{life.finalMin}?{life.finalMax}</td><td>{artifact.finalMin}?{artifact.finalMax}</td><td>{resonance.rewardMultiplier.toFixed(2)}?</td><td>{pct(sigilChance)}</td><td>{pct(crystalChance)}</td><td>{authoredLoot}</td></tr> })}</tbody></table></div></Card>
    <Card title="Scaling contract"><div className="developer-detail-grid"><span>STANDARD BOSS QUANTITY<strong>{UNIVERSAL_LOOT_BOSS_MULTIPLIERS.quantity}?</strong></span><span>STANDARD BOSS CHANCE<strong>{UNIVERSAL_LOOT_BOSS_MULTIPLIERS.chance}?</strong></span><span>STANDARD BOSS RARITY<strong>{UNIVERSAL_LOOT_BOSS_MULTIPLIERS.rarity}?</strong></span><span>CRYSTAL CACHE UNLOCK<strong>LOOT TIER {getLootUnlockTier('crystal-cache-t1') ?? 'UNSET'}</strong></span></div></Card>
  </div>
}
