import { useMemo, useState } from 'react'
import { Button, Card, GameTooltip, Status } from '../../components/ui'
import { ARCANE_CORE_BRANCHES } from '../../game/content/arcaneCore/arcaneCoreBranches'
import { ARCANE_CORE_FULL_RING_COST_BY_RING, ARCANE_CORE_MAJOR_COST_BY_RING, ARCANE_CORE_STANDARD_RANK_COST_BY_RING, ARCANE_CORE_TOTAL_TREE_COST } from '../../game/content/arcaneCore/arcaneCoreBalance'
import { ARCANE_CORE_MAJOR_GATES, ARCANE_CORE_RING_GATES, ARCANE_CORE_RING_INDICES } from '../../game/content/arcaneCore/arcaneCoreRings'
import { getArcaneCoreNodeEffectTexts } from '../../game/presentation/arcaneCore/arcaneCorePresentation'
import { getArcaneCoreHighestUnlockedRing, getArcaneCoreNodeRank, getArcaneCoreRingPointsSpent, getArcaneCoreRingStandardRanksInvested, getArcaneCoreWalletInfo, isArcaneCoreMajorUnlocked, isArcaneCoreRingUnlocked } from '../../game/systems/arcaneCore'
import { validateArcaneCoreCatalog } from '../../game/systems/arcaneCore/arcaneCoreValidation'
import type { ArcaneCoreBranchId, ArcaneCoreRingIndex } from '../../game/types'
import { useGameStore } from '../../store/gameStore'
import { NumberField, Summary } from './DeveloperTabPrimitives'

const ringCost = (ring: ArcaneCoreRingIndex) => ARCANE_CORE_FULL_RING_COST_BY_RING[ring]

export function DeveloperArcaneCore() {
  const state = useGameStore()
  const [selectedNodeId, setSelectedNodeId] = useState(ARCANE_CORE_BRANCHES[0]?.nodes[0]?.id ?? '')
  const [selectedBranchId, setSelectedBranchId] = useState<ArcaneCoreBranchId>('power')
  const [selectedRing, setSelectedRing] = useState<ArcaneCoreRingIndex>(1)
  const nodes = useMemo(() => ARCANE_CORE_BRANCHES.flatMap((branch) => branch.nodes.map((node) => ({ ...node, branchName: branch.name }))), [])
  const selectedNode = nodes.find((node) => node.id === selectedNodeId) ?? nodes[0]
  const selectedRank = selectedNode ? getArcaneCoreNodeRank(state.arcaneCore, selectedNode.id) : 0
  const wallet = getArcaneCoreWalletInfo(state.arcaneCore)
  const diagnostics = validateArcaneCoreCatalog()
  const selectedBranch = ARCANE_CORE_BRANCHES.find((branch) => branch.id === selectedBranchId) ?? ARCANE_CORE_BRANCHES[0]
  const selectedRingPoints = selectedBranch ? getArcaneCoreRingPointsSpent(state.arcaneCore, selectedBranch.id, selectedRing) : 0
  const selectedRingRanks = selectedBranch ? getArcaneCoreRingStandardRanksInvested(state.arcaneCore, selectedBranch.id, selectedRing) : 0

  return <div className="developer-tab-stack developer-arcane-core-tab">
    <Card title="Arcane Core · V6 tester controls" action={<Status tone="warning">DEV SESSION ONLY</Status>}>
      <div className="developer-summary-grid"><Summary label="Points earned" value={wallet.totalPointsEarned} /><Summary label="Points spent" value={wallet.pointsSpent} /><Summary label="Points available" value={wallet.pointsAvailable} /><Summary label="Tree cost" value={ARCANE_CORE_TOTAL_TREE_COST} /><Summary label="State entries" value={Object.keys(state.arcaneCore.nodes).length} /></div>
      <div className="developer-form-grid"><NumberField label="Set Total Arcane Points Earned" value={wallet.totalPointsEarned} onChange={state.setArcanePoints} min={0} max={ARCANE_CORE_TOTAL_TREE_COST} /></div>
      <div className="button-row"><Button onClick={() => state.grantArcanePoints(10)}>+10 POINTS</Button><Button onClick={() => state.grantArcanePoints(100)}>+100 POINTS</Button><Button onClick={() => state.grantArcanePoints(1000)}>+1,000 POINTS</Button><Button variant="secondary" onClick={() => state.setArcanePoints(ARCANE_CORE_TOTAL_TREE_COST)}>MAX POINTS</Button><Button variant="primary" onClick={state.maxArcanePointsAndPurchaseAll}>MAX POINTS + PURCHASE ALL</Button><Button variant="ghost" onClick={state.resetArcaneCore}>RESET POINTS + ALL</Button></div>
    </Card>
    <Card title="Progression flags" className="developer-debug-card"><p className="muted">Runtime-only flags make authored Ring gates and costs testable without changing the profile save format.</p><div className="developer-arcane-core-toggle-grid"><GameTooltip content="Remove Arcane Point costs for Arcane Core purchases during this session."><label className="developer-check-row"><input type="checkbox" checked={state.debug.arcaneCoreFreeCosts} onChange={(event) => state.setDebugArcaneCoreFreeCosts(event.target.checked)} /> Free Arcane costs</label></GameTooltip><GameTooltip content="Allow all Arcane Core Ring and Major gates during this session."><label className="developer-check-row"><input type="checkbox" checked={state.debug.arcaneCoreIgnorePrerequisites} onChange={(event) => state.setDebugArcaneCoreIgnorePrerequisites(event.target.checked)} /> Ignore Ring gates</label></GameTooltip></div></Card>
    <div className="developer-tab-grid">
      <Card title="Selected node rank controls"><label className="developer-select-field">SELECT NODE<select aria-label="Developer Arcane Core node" value={selectedNode?.id ?? ''} onChange={(event) => setSelectedNodeId(event.target.value)}>{nodes.map((node) => <option value={node.id} key={node.id}>{node.branchName} · Ring {node.ring} · {node.name}</option>)}</select></label>{selectedNode && <><div className="developer-summary-grid"><Summary label="Rank" value={`${selectedRank} / ${selectedNode.maxRank}`} /><Summary label="Type" value={selectedNode.nodeType} /><Summary label="Cost" value={`${selectedNode.rankCost} Arcane Points`} /><Summary label="Gate" value={selectedNode.nodeType === 'major' ? `${getArcaneCoreRingStandardRanksInvested(state.arcaneCore, selectedNode.branchId, selectedNode.ring)} / ${ARCANE_CORE_MAJOR_GATES[selectedNode.ring]} standard ranks` : selectedNode.ring === 1 ? 'Ring I open' : `${getArcaneCoreRingStandardRanksInvested(state.arcaneCore, selectedNode.branchId, (selectedNode.ring - 1) as ArcaneCoreRingIndex)} / ${ARCANE_CORE_RING_GATES[selectedNode.ring]} previous-ring ranks`} /><Summary label="Effect" value={getArcaneCoreNodeEffectTexts(selectedNode, Math.max(1, selectedRank)).join(' · ')} /></div><label className="developer-select-field">SET RANK<select aria-label="Set selected Arcane Core node rank" value={selectedRank} onChange={(event) => state.setArcaneCoreNodeRank(selectedNode.id, Number(event.target.value))}>{Array.from({ length: selectedNode.maxRank + 1 }, (_, rank) => <option key={rank} value={rank}>{rank}</option>)}</select></label></>}<div className="button-row"><Button disabled={!selectedNode || selectedRank >= (selectedNode?.maxRank ?? 0)} onClick={() => selectedNode && state.purchaseArcaneCoreNode(selectedNode.id)}>PURCHASE RANK</Button><Button variant="secondary" disabled={!selectedNode || selectedRank >= (selectedNode?.maxRank ?? 0)} onClick={() => selectedNode && state.maxArcaneCoreNode(selectedNode.id)}>MAX SELECTED NODE</Button><Button variant="ghost" disabled={!selectedNode || selectedRank === 0} onClick={() => selectedNode && state.resetArcaneCoreNode(selectedNode.id)}>RESET SELECTED NODE</Button><Button variant="ghost" disabled={!selectedNode || selectedRank === 0} onClick={() => selectedNode && state.refundArcaneCoreNode(selectedNode.id)}>REFUND RANK</Button></div></Card>
      <Card title="Core / Ring controls" className="developer-debug-card"><div className="developer-form-grid"><label className="developer-select-field">SELECT CORE<select aria-label="Developer Arcane Core branch" value={selectedBranch?.id ?? ''} onChange={(event) => setSelectedBranchId(event.target.value as ArcaneCoreBranchId)}>{ARCANE_CORE_BRANCHES.map((branch) => <option value={branch.id} key={branch.id}>{branch.name} Core</option>)}</select></label><label className="developer-select-field">SELECT RING<select aria-label="Developer Arcane Core ring" value={selectedRing} onChange={(event) => setSelectedRing(Number(event.target.value) as ArcaneCoreRingIndex)}>{ARCANE_CORE_RING_INDICES.map((ring) => <option value={ring} key={ring}>Ring {ring}</option>)}</select></label></div><div className="developer-diagnostics"><span>Selected ring <b>{selectedBranch?.name} · Ring {selectedRing}</b></span><span>Standard ranks <b>{selectedRingRanks} / 40</b></span><span>Cost invested <b>{selectedRingPoints} / {ringCost(selectedRing)}</b></span></div><div className="button-row"><Button variant="secondary" onClick={() => selectedBranch && state.maxArcaneCoreRing(selectedBranch.id, selectedRing)}>MAX RING {selectedRing}</Button><Button variant="ghost" onClick={() => selectedBranch && state.resetArcaneCoreRing(selectedBranch.id, selectedRing)}>RESET RING {selectedRing}</Button><Button variant="secondary" onClick={() => selectedBranch && state.maxArcaneCoreBranch(selectedBranch.id)}>MAX CORE</Button><Button variant="ghost" onClick={() => selectedBranch && state.resetArcaneCoreBranch(selectedBranch.id)}>RESET CORE</Button></div><div className="button-row"><Button onClick={state.purchaseAllArcaneCore}>MAX ALL</Button><Button variant="ghost" onClick={state.resetArcaneCore}>RESET ALL</Button></div></Card>
    </div>
    <Card title="Ring diagnostics" className="developer-debug-card"><div className="developer-arcane-ring-diagnostics">{ARCANE_CORE_BRANCHES.map((branch) => <section key={branch.id}><strong>{branch.name}</strong>{ARCANE_CORE_RING_INDICES.map((ring) => { const points = getArcaneCoreRingPointsSpent(state.arcaneCore, branch.id, ring); const ranks = getArcaneCoreRingStandardRanksInvested(state.arcaneCore, branch.id, ring); const unlocked = isArcaneCoreRingUnlocked(state.arcaneCore, branch.id, ring); const majorNode = branch.nodes.find((node) => node.ring === ring && node.nodeType === 'major'); return <div key={ring}><span>Ring {ring}</span><b>{unlocked ? `${ranks} / 40 ranks · ${points} points` : 'LOCKED'}</b><small>Major {ranks} / {ARCANE_CORE_MAJOR_GATES[ring]} standard ranks · {majorNode && isArcaneCoreMajorUnlocked(state.arcaneCore, majorNode) ? 'AVAILABLE' : 'LOCKED'}</small></div>})}<small>Highest unlocked: Ring {getArcaneCoreHighestUnlockedRing(state.arcaneCore, branch.id)}</small></section>)}</div></Card>
    <Card title="Catalog diagnostics" className="developer-debug-card"><div className="developer-summary-grid"><Summary label="Branches" value={ARCANE_CORE_BRANCHES.length} /><Summary label="Nodes" value={nodes.length} /><Summary label="Validation errors" value={diagnostics.length} /><Summary label="Tree cost" value={ARCANE_CORE_TOTAL_TREE_COST} /><Summary label="Ring I standard" value={ARCANE_CORE_STANDARD_RANK_COST_BY_RING[1]} /><Summary label="Ring VIII major" value={ARCANE_CORE_MAJOR_COST_BY_RING[8]} /></div><Status tone={diagnostics.length === 0 ? 'success' : 'warning'}>{diagnostics.length === 0 ? 'CATALOG VALID' : 'CATALOG NEEDS REVIEW'}</Status>{diagnostics.length > 0 && <pre className="developer-json">{diagnostics.join('\n')}</pre>}</Card>
  </div>
}
