import { RotateCcw, Save, Wrench } from 'lucide-react'
import { assessThemeContrast, hasReadableContrast } from '../../ui/theme/contrast'
import { customFromPreset, THEME_PRESETS, themeColors } from '../../ui/theme/themePresets'
import { resetAppearance, resetCustomTheme, setCustomThemeColor, setUiPreferences, useUiPreferences } from '../../ui/preferences/uiPreferencesStore'
import { defaultUiPreferences } from '../../ui/preferences/uiPreferencesStorage'
import type { CustomThemeColors, TextSize, UiTheme } from '../../ui/preferences/uiPreferencesTypes'
import { useGameStore } from '../../store/gameStore'
import { closeLayoutEditor, openLayoutEditor, resetAllScreenLayouts, resetScreenLayout, useLayoutEditorStore } from '../../ui/layout-editor/layoutEditorStore'
import { Button, Card, Status } from '../../components/ui'
import { EditableGrid } from '../../ui/layout-editor/EditableGrid'

const themeOptions: { id: UiTheme; label: string; description: string }[] = [{ id: 'default', label: 'Default', description: 'Current SSS Wizard arcane violet theme.' }, { id: 'dark', label: 'Dark', description: 'Neutral, deeper, higher-contrast dark theme.' }, { id: 'light', label: 'Light', description: 'Warm fantasy parchment / ivory theme.' }, { id: 'custom', label: 'Custom', description: 'Player-controlled UI colors.' }]
const colorFields: { key: keyof CustomThemeColors; label: string }[] = [{ key: 'background', label: 'Background' }, { key: 'panel', label: 'Panel' }, { key: 'text', label: 'Primary Text' }, { key: 'muted', label: 'Muted Text' }, { key: 'accent', label: 'Accent' }, { key: 'secondary', label: 'Secondary / Progress Accent' }, { key: 'border', label: 'Border' }]

export function SettingsScreenV2() {
  const preferences = useUiPreferences(); const save = useGameStore((state) => state.saveGame); const reset = useGameStore((state) => state.resetSave); const debug = useGameStore((state) => state.ui.showDebug); const setDebug = useGameStore((state) => state.setDebug); const screen = useGameStore((state) => state.ui.screen); const edit = useLayoutEditorStore().isEditing; const colors = themeColors(preferences.theme, preferences.customTheme); const contrast = assessThemeContrast(colors); const readable = hasReadableContrast(colors)
  const appearance = <Card title="Appearance" className="settings-card"><div className="setting-section"><strong>Theme</strong><small>Choose the UI chrome while Fire, Water, Earth, Air, Health, and status colors remain semantic.</small><div className="theme-presets">{themeOptions.map((option) => <button className={`theme-choice ${preferences.theme === option.id ? 'active' : ''}`} key={option.id} onClick={() => setUiPreferences({ theme: option.id })}><strong>{option.label}</strong><small>{option.description}</small></button>)}</div></div><div className="setting-section"><strong>Text Size</strong><small>Default is tuned for longer play sessions.</small><div className="preference-options">{(['default', 'large', 'extra-large'] as TextSize[]).map((size) => <button className={`preference-choice ${preferences.textSize === size ? 'active' : ''}`} key={size} onClick={() => setUiPreferences({ textSize: size })}>{size === 'extra-large' ? 'Extra Large' : size[0].toUpperCase() + size.slice(1)}</button>)}</div></div><div className="setting-row"><div><strong>Background Effects</strong><small>Three.js atmosphere particles. Gameplay is unaffected.</small></div><Button variant={preferences.backgroundEffects ? 'success' : 'secondary'} onClick={() => setUiPreferences({ backgroundEffects: !preferences.backgroundEffects })}>{preferences.backgroundEffects ? 'ON' : 'OFF'}</Button></div><div className="setting-row"><div><strong>Reduced Motion</strong><small>Reduces decorative animation without changing gameplay timers.</small></div><Button variant={preferences.reducedMotion ? 'success' : 'secondary'} onClick={() => setUiPreferences({ reducedMotion: !preferences.reducedMotion })}>{preferences.reducedMotion ? 'ON' : 'OFF'}</Button></div>{preferences.theme === 'custom' && <CustomThemeEditor preferences={preferences} readable={readable} contrast={contrast} />}</Card>
  const preview = <Card title="Theme preview" className="settings-card"><div className="theme-preview"><strong>Panel title</strong><p>Muted description remains readable in the selected theme.</p><div className="button-row"><Button>Primary button</Button><Button variant="secondary">Secondary</Button></div><div className="theme-preview-bars"><i /><i /></div><Status tone="success">Status pill</Status></div>{preferences.theme === 'custom' && <small className="muted">Text / background {contrast.primaryBackground.toFixed(1)}:1 · text / panel {contrast.primaryPanel.toFixed(1)}:1 · muted / panel {contrast.mutedPanel.toFixed(1)}:1</small>}</Card>
  const savePanel = <Card title="Save" className="settings-card"><div className="setting-row"><div><strong>Local save</strong><small>Autosaves every 15 seconds and when the tab is hidden.</small></div><Button variant="success" onClick={save}><Save size={15} /> Save now</Button></div><div className="setting-row"><div><strong>Reset gameplay state</strong><small>Resets progression only. Appearance stays unchanged.</small></div><Button variant="danger" onClick={() => { if (window.confirm('Reset the current save?')) reset() }}><RotateCcw size={15} /> Reset save</Button></div><div className="setting-row"><div><strong>Reset Appearance</strong><small>Default theme, readable text, effects on, custom colors reset.</small></div><Button className="appearance-reset" variant="secondary" onClick={resetAppearance}>Reset Appearance</Button></div></Card>
  const layoutPanel = <Card title="Interface Layout" className="settings-card"><div className="setting-row"><div><strong>UI Edit mode</strong><small>Desktop only. Edit individual panels with a 12-column grid.</small></div><Button variant={edit ? 'success' : 'secondary'} onClick={() => edit ? closeLayoutEditor() : openLayoutEditor(screen)}>{edit ? 'Exit UI editor' : 'Open UI editor'}</Button></div><div className="setting-row"><div><strong>Layout reset</strong><small>Reset saved layout geometry only. Gameplay and appearance are unchanged.</small></div><div className="button-row"><Button variant="ghost" onClick={() => { if (window.confirm('Reset the current screen layout?')) resetScreenLayout(screen) }}>Current</Button><Button variant="ghost" onClick={() => { if (window.confirm('Reset all screen layouts?')) resetAllScreenLayouts() }}>All</Button></div></div></Card>
  const developer = <Card title="Developer" className="settings-card"><div className="setting-row"><div><strong>Testing panel</strong><small>Changes here modify the current save.</small></div><Button variant={debug ? 'success' : 'secondary'} onClick={() => setDebug(!debug)}><Wrench size={14} /> {debug ? 'Hide tools' : 'Show tools'}</Button></div></Card>
  const info = <Card title="Info" className="settings-card"><div className="rules-list"><Rule text="Combat, Research, and Transmutation continue when you navigate." /><Rule text="Hidden time is banked once; the real-time simulation pauses while hidden." /><Rule text="Appearance uses the separate sss-wizard-ui-preferences-v1 browser key." /></div><div className="settings-status"><Status tone="active">Save schema v2</Status><span>Local browser storage · no cloud account</span></div></Card>
  return <div className="screen-content"><div className="screen-header"><div><div className="eyebrow">TOWER SYSTEMS</div><h1>Settings / Info</h1><p>Appearance preferences are stored separately from gameplay and update immediately.</p></div></div><EditableGrid screen="settings" panels={[{ id: 'settings-appearance', content: appearance }, { id: 'settings-theme-preview', content: preview }, { id: 'settings-save', content: savePanel }, { id: 'settings-layout', content: layoutPanel }, { id: 'settings-developer', content: developer }, { id: 'settings-info', content: info }]} /><div className="footer-note">SSS Wizard · Phase 2.1</div></div>
}
function CustomThemeEditor({ preferences, readable, contrast }: { preferences: ReturnType<typeof useUiPreferences>; readable: boolean; contrast: ReturnType<typeof assessThemeContrast> }) { return <div className="custom-theme-editor"><div className="setting-section"><strong>Custom Theme</strong><small>Start from a preset, then edit the player-facing UI colors.</small><div className="preference-options">{(['default', 'dark', 'light'] as const).map((preset) => <Button key={preset} variant="ghost" onClick={() => setUiPreferences({ customTheme: customFromPreset(THEME_PRESETS[preset]), theme: 'custom' })}>Start from {preset[0].toUpperCase() + preset.slice(1)}</Button>)}</div></div><div className="custom-theme-grid">{colorFields.map(({ key, label }) => <CustomColorField key={key} colorKey={key} label={label} value={preferences.customTheme[key]} />)}</div>{!readable && <p className="contrast-warning">Low contrast · this color combination may be difficult to read.</p>}<small className="muted">Contrast: {readable ? 'Good' : 'Low'} · primary/background {contrast.primaryBackground.toFixed(1)}:1</small><div className="button-row" style={{ marginTop: 12 }}><Button variant="ghost" onClick={resetCustomTheme}>Reset Custom Colors</Button></div></div> }
function CustomColorField({ colorKey, label, value }: { colorKey: keyof CustomThemeColors; label: string; value: string }) { return <div className="color-field"><label><input type="color" value={value} onChange={(event) => setCustomThemeColor(colorKey, event.target.value)} /><span>{label}<input type="text" value={value} onChange={(event) => setCustomThemeColor(colorKey, event.target.value)} /></span></label><button type="button" onClick={() => setCustomThemeColor(colorKey, defaultUiPreferences().customTheme[colorKey])}>Reset</button></div> }
function Rule({ text }: { text: string }) { return <div>✓ {text}</div> }
