import { useState } from 'react'
import { RotateCcw, Save, Wrench } from 'lucide-react'
import { assessThemeContrast, hasReadableContrast } from '../../ui/theme/contrast'
import { customFromPreset, THEME_PRESETS, themeColors } from '../../ui/theme/themePresets'
import { resetAppearance, resetCustomTheme, setCustomThemeColor, setUiPreferences, useUiPreferences } from '../../ui/preferences/uiPreferencesStore'
import { defaultUiPreferences } from '../../ui/preferences/uiPreferencesStorage'
import type { CustomThemeColors, TextSize, UiTheme } from '../../ui/preferences/uiPreferencesTypes'
import { useGameStore } from '../../store/gameStore'
import { closeLayoutEditor, openLayoutEditor, resetAllScreenLayouts, resetScreenLayout, useLayoutEditorStore } from '../../ui/layout-editor/layoutEditorStore'
import { Button, Card, Progress, Status } from '../../components/ui'
import { EditableGrid } from '../../ui/layout-editor/EditableGrid'
import { openDeveloperTools } from '../../devtools/developerToolsStore'
import { leaveToProfiles } from '../../profiles/profileController'
import { useProfileSession } from '../../profiles/profileSessionStore'
import { DIFFICULTIES, GAME_MODES } from '../../profiles/profileTypes'

const themeOptions: { id: UiTheme; label: string; description: string }[] = [{ id: 'default', label: 'Default', description: 'Current SSS Wizard arcane violet theme.' }, { id: 'dark', label: 'Dark', description: 'Neutral, deeper, higher-contrast dark theme.' }, { id: 'light', label: 'Light', description: 'Warm fantasy parchment / ivory theme.' }, { id: 'custom', label: 'Custom', description: 'Player-controlled UI colors.' }]
const colorFields: { key: keyof CustomThemeColors; label: string }[] = [{ key: 'background', label: 'Background' }, { key: 'panel', label: 'Panel' }, { key: 'text', label: 'Primary Text' }, { key: 'muted', label: 'Muted Text' }, { key: 'accent', label: 'Accent' }, { key: 'secondary', label: 'Secondary / Progress Accent' }, { key: 'border', label: 'Border' }]

export function SettingsScreenV2() {
  const preferences = useUiPreferences()
  const save = useGameStore((state) => state.saveGame)
  const reset = useGameStore((state) => state.resetSave)
  const screen = useGameStore((state) => state.ui.screen)
  const edit = useLayoutEditorStore().isEditing
  const colors = themeColors(preferences.theme, preferences.customTheme)
  const contrast = assessThemeContrast(colors)
  const readable = hasReadableContrast(colors)
  const profileSession = useProfileSession()
  const activeProfile = profileSession.activeProfileId ? profileSession.profiles.slots[profileSession.activeProfileId] : null
  const [profileError, setProfileError] = useState<string | null>(null)
  const profilePanel = <Card title="Profile" className="settings-card"><div className="profile-settings-summary">{activeProfile ? <><div><span className="profile-slot">SLOT {activeProfile.slotNumber}</span><strong>{activeProfile.name}</strong></div><div className="profile-badges"><Status tone="active">{GAME_MODES[activeProfile.gameMode].name}</Status><Status tone="neutral">{DIFFICULTIES[activeProfile.difficulty].name}</Status></div></> : <span className="muted">No active profile</span>}</div><p className="muted">Gameplay saves are isolated per profile. Appearance, navigation, and layout preferences are shared by this browser.</p>{profileError && <p className="profile-settings-error" role="alert">{profileError}</p>}<Button variant="secondary" onClick={() => { const result = leaveToProfiles(); if (!result.ok) setProfileError(result.error) }} disabled={!activeProfile}>Return to Profiles</Button></Card>
  const appearance = <Card title="Appearance" className="settings-card"><div className="setting-section"><strong>Theme</strong><small>Choose the UI chrome while Fire, Water, Earth, Air, Health, and status colors remain semantic.</small><div className="theme-presets">{themeOptions.map((option) => <button className={`theme-choice ${preferences.theme === option.id ? 'active' : ''}`} key={option.id} onClick={() => setUiPreferences({ theme: option.id })}><strong>{option.label}</strong><small>{option.description}</small></button>)}</div></div><div className="setting-section"><strong>Text Size</strong><small>Default is tuned for longer play sessions.</small><div className="preference-options">{(['default', 'large', 'extra-large'] as TextSize[]).map((size) => <button className={`preference-choice ${preferences.textSize === size ? 'active' : ''}`} key={size} onClick={() => setUiPreferences({ textSize: size })}>{size === 'extra-large' ? 'Extra Large' : size[0].toUpperCase() + size.slice(1)}</button>)}</div></div><div className="setting-row"><div><strong>Background Effects</strong><small>Three.js atmosphere particles. Gameplay is unaffected.</small></div><Button variant={preferences.backgroundEffects ? 'success' : 'secondary'} onClick={() => setUiPreferences({ backgroundEffects: !preferences.backgroundEffects })}>{preferences.backgroundEffects ? 'ON' : 'OFF'}</Button></div><div className="setting-row"><div><strong>Reduced Motion</strong><small>Reduces decorative animation without changing gameplay timers.</small></div><Button variant={preferences.reducedMotion ? 'success' : 'secondary'} onClick={() => setUiPreferences({ reducedMotion: !preferences.reducedMotion })}>{preferences.reducedMotion ? 'ON' : 'OFF'}</Button></div>{preferences.theme === 'custom' && <CustomThemeEditor preferences={preferences} readable={readable} contrast={contrast} />}</Card>
  const sandbox = <UiSandbox preferences={preferences} colors={colors} />
  const savePanel = <Card title="Save" className="settings-card"><div className="setting-row"><div><strong>Local save</strong><small>Autosaves every 30 seconds and when the tab is hidden.</small></div><Button variant="success" onClick={save}><Save size={15} /> Save now</Button></div><div className="setting-row"><div><strong>Reset Current Profile</strong><small>Resets gameplay progression but keeps this profile slot.</small></div><Button variant="danger" onClick={() => { if (window.confirm('Reset the current profile gameplay?')) reset() }}><RotateCcw size={15} /> Reset Profile</Button></div><div className="setting-row"><div><strong>Reset Appearance</strong><small>Default theme, readable text, effects on, custom colors reset.</small></div><Button className="appearance-reset" variant="secondary" onClick={resetAppearance}>Reset Appearance</Button></div></Card>
  const layoutPanel = <Card title="Interface Layout" className="settings-card"><div className="setting-row"><div><strong>UI Edit mode</strong><small>Desktop only. Edit individual panels with a 12-column grid.</small></div><Button variant={edit ? 'success' : 'secondary'} onClick={() => edit ? closeLayoutEditor() : openLayoutEditor(screen)}>{edit ? 'Exit UI editor' : 'Open UI editor'}</Button></div><div className="setting-row"><div><strong>Layout reset</strong><small>Reset saved layout geometry only. Gameplay and appearance are unchanged.</small></div><div className="button-row"><Button variant="ghost" onClick={() => { if (window.confirm('Reset the current screen layout?')) resetScreenLayout(screen) }}>Current</Button><Button variant="ghost" onClick={() => { if (window.confirm('Reset all screen layouts?')) resetAllScreenLayouts() }}>All</Button></div></div></Card>
  const developer = <Card title="Developer Tools" className="settings-card"><div className="setting-row"><div><strong>Open the full testing and state console.</strong><small>Player, schools, inventory, combat, progression, and save diagnostics.</small></div><Button variant="secondary" onClick={() => openDeveloperTools()}><Wrench size={14} /> Open Developer Tools</Button></div></Card>
  const info = <Card title="Info" className="settings-card"><div className="rules-list"><Rule text="Combat, Research, and Transmutation continue when you navigate." /><Rule text="Hidden time is banked once; the real-time simulation pauses while hidden." /><Rule text="Appearance and navigation preferences use a separate browser key." /></div><div className="settings-status"><Status tone="active">Save schema v4</Status><span>Local browser storage  -  no cloud account</span></div></Card>
  return <div className="screen-content"><div className="screen-header"><div><div className="eyebrow">SYSTEM  -  INTERFACE</div><h1>Settings / Info</h1><p>Appearance preferences are stored separately from gameplay and update immediately.</p></div></div><EditableGrid screen="settings" panels={[{ id: 'settings-profile', content: profilePanel }, { id: 'settings-appearance', content: appearance }, { id: 'settings-theme-preview', content: sandbox }, { id: 'settings-save', content: savePanel }, { id: 'settings-layout', content: layoutPanel }, { id: 'settings-developer', content: developer }, { id: 'settings-info', content: info }]} /><div className="footer-note">SSS Wizard  -  Phase 2.4</div></div>
}

function UiSandbox({ preferences, colors }: { preferences: ReturnType<typeof useUiPreferences>; colors: ReturnType<typeof themeColors> }) {
  const [mode, setMode] = useState<'general' | 'combat' | 'inventory'>('general')
  const allThemes = themeOptions.map((option) => ({ ...option, colors: themeColors(option.id, preferences.customTheme), contrast: assessThemeContrast(themeColors(option.id, preferences.customTheme)) }))
  return <Card title="UI Sandbox" className="settings-card settings-sandbox-card"><div className="sandbox-toolbar"><div className="button-row">{(['general', 'combat', 'inventory'] as const).map((item) => <Button key={item} variant={mode === item ? 'success' : 'secondary'} onClick={() => setMode(item)}>{item[0].toUpperCase() + item.slice(1)}</Button>)}</div><div className="sandbox-swatches">{allThemes.map((theme) => <span key={theme.id} className={`sandbox-swatch ${preferences.theme === theme.id ? 'active' : ''}`} title={`${theme.label}: ${theme.contrast.primaryPanel.toFixed(1)}:1`}><i style={{ background: theme.colors.background }} /><i style={{ background: theme.colors.panel }} /><i style={{ background: theme.colors.accent }} /><i style={{ background: theme.colors.secondary }} /></span>)}</div></div><div className="sandbox-contrast-grid">{allThemes.map((theme) => <span key={theme.id}><strong>{theme.label}</strong><small>{theme.contrast.primaryPanel.toFixed(1)}:1 panel  -  {hasReadableContrast(theme.colors) ? 'readable' : 'low contrast'}</small></span>)}</div>{mode === 'general' ? <GeneralPreview colors={colors} /> : mode === 'combat' ? <CombatPreview /> : <InventoryPreview />}</Card>
}

function GeneralPreview({ colors }: { colors: ReturnType<typeof themeColors> }) { return <div className="sandbox-general"><div className="sandbox-mini-sidebar"><strong>SSS</strong><span>Overview</span><span>Wizard Tower</span><span>Settings</span></div><div className="sandbox-mini-main"><div className="sandbox-mini-topbar"><strong>HP 100 / 100</strong><span>MANA 80 / 100</span><span>FOCUS 60 FREE</span></div><div className="sandbox-mini-panel"><div><strong>Readable panel title</strong><span className="muted">Muted body text and theme-aware border</span></div><div className="button-row"><Button>Primary</Button><Button variant="secondary">Secondary</Button><Button variant="success">Success</Button><Button variant="danger">Danger</Button></div><div className="sandbox-form-row"><input placeholder="Input sample" /><select defaultValue="sample"><option value="sample">Select sample</option><option>Another option</option></select></div><div className="sandbox-status-row"><Status tone="active">Active</Status><Status tone="success">Success</Status><Status tone="warning">Warning</Status><Status tone="locked">Locked</Status></div><Progress value={64} label="Progress bar" right="64%" /><div className="sandbox-scroll-sample"><span>Scrollbar sample</span>{['Item one', 'Item two', 'Item three', 'Item four', 'Item five', 'Item six'].map((item) => <small key={item}>{item}</small>)}</div><div className="sandbox-tooltip" style={{ borderColor: colors.accent }}>Tooltip sample  -  hover-friendly guidance</div></div></div></div> }
function CombatPreview() { return <div className="sandbox-combat"><div className="sandbox-chip-row"><span>HP HP <strong>85 / 100</strong></span><span>* MANA <strong>70 / 100</strong></span><span>FOCUS FOCUS <strong>40 FREE</strong></span></div><Card title="Grove Sentinel" action={<Status tone="warning">Telegraph</Status>}><Progress value={58} tone="red" label="Enemy HP" right="210 / 360" /><div className="sandbox-combat-actions"><Status tone="active">Normal attack</Status><Status tone="warning">Root Crush incoming</Status><Status tone="success">Barrier 60</Status><Status tone="locked">Stunned</Status></div></Card></div> }
function InventoryPreview() { return <div className="sandbox-inventory"><div className="sandbox-inventory-grid">{[['Fire Fragment', '12', 'normal'], ['Ember Staff', '1', 'selected'], ['Forest Heart', '0', 'locked'], ['Tide Focus', '1', 'equipped'], ['Empty slot', '-', 'empty']].map(([name, quantity, state]) => <div className={`sandbox-item ${state}`} key={name}><span>*</span><strong>{name}</strong><small>{state}</small><b>{quantity}</b></div>)}</div><div className="sandbox-item-detail"><strong>Ember Staff</strong><span className="muted">A crafted equipment item with a readable selected state.</span><Status tone="success">Equipped</Status><div className="sandbox-scroll-sample"><small>Basic Damage +4</small><small>Max Mana +10</small><small>Fire Spell Damage +20%</small><small>Source: Transmutation</small></div></div></div> }
function CustomThemeEditor({ preferences, readable, contrast }: { preferences: ReturnType<typeof useUiPreferences>; readable: boolean; contrast: ReturnType<typeof assessThemeContrast> }) { return <div className="custom-theme-editor"><div className="setting-section"><strong>Custom Theme</strong><small>Start from a preset, then edit the player-facing UI colors.</small><div className="preference-options">{(['default', 'dark', 'light'] as const).map((preset) => <Button key={preset} variant="ghost" onClick={() => setUiPreferences({ customTheme: customFromPreset(THEME_PRESETS[preset]), theme: 'custom' })}>Start from {preset[0].toUpperCase() + preset.slice(1)}</Button>)}</div></div><div className="custom-theme-grid">{colorFields.map(({ key, label }) => <CustomColorField key={key} colorKey={key} label={label} value={preferences.customTheme[key]} />)}</div>{!readable && <p className="contrast-warning">Low contrast  -  this color combination may be difficult to read.</p>}<small className="muted">Contrast: {readable ? 'Good' : 'Low'}  -  primary/background {contrast.primaryBackground.toFixed(1)}:1</small><div className="button-row" style={{ marginTop: 12 }}><Button variant="ghost" onClick={resetCustomTheme}>Reset Custom Colors</Button></div></div> }
function CustomColorField({ colorKey, label, value }: { colorKey: keyof CustomThemeColors; label: string; value: string }) { return <div className="color-field"><label><input type="color" value={value} onChange={(event) => setCustomThemeColor(colorKey, event.target.value)} /><span>{label}<input type="text" value={value} onChange={(event) => setCustomThemeColor(colorKey, event.target.value)} /></span></label><button type="button" onClick={() => setCustomThemeColor(colorKey, defaultUiPreferences().customTheme[colorKey])}>Reset</button></div> }
function Rule({ text }: { text: string }) { return <div>OK {text}</div> }
