import type { MonsterId } from "../../../types";
import {
  action,
  basic,
  scaledBarrier,
  scaledDirectDamage,
  scaledDot,
  scaledHeal,
  opponentStatusStackScaled,
  withDungeonLoot,
  applyStatus,
  type MonsterDefinition,
} from "../monsterTypes";

export const ABANDONED_CATACOMBS_MONSTERS = {
  "restless-skeleton": {
    id: "restless-skeleton",
    bestiaryCategory: "monster",
    name: "Restless Skeleton",
    subtitle: "Bones animated by the last command they heard",
    maxHealth: 680,
    basicAttackDamage: 45,
    basicAttackTimeMs: 2700,
    defense: 30,
    color: "#c9c3ae",
    ui: { portraitIcon: "skeleton" },
    traitIds: ["restless-skeleton-brittle-bones"],
    resistances: { physical: 0.25 },
    actions: {
      "bone-cleaver": {
        id: "bone-cleaver",
        name: "Bone Cleaver",
        actionTimeMs: 2200,
        description: "A heavy cleaver blow splits through the target.",
        effects: [scaledDirectDamage("physical", 1.85)],
        tags: ["special", "physical", "melee", "direct"],
      },
      "bone-rattle": {
        id: "bone-rattle",
        name: "Bone Rattle",
        actionTimeMs: 1900,
        description:
          "A violent clatter of cursed bones leaves the Wizard Fragile.",
        effects: [applyStatus("fragile", "opponent", 6000)],
        tags: ["special", "debuff", "physical"],
      },
    },
    actionPatterns: {
      default: {
        id: "default",
        steps: [
          basic("basic-1"),
          basic("basic-2"),
          action("bone-cleaver-step", "bone-cleaver"),
          basic("basic-3"),
          action("bone-rattle-step", "bone-rattle"),
          basic("basic-4"),
        ],
      },
    },
    defaultActionPatternId: "default",
    loot: withDungeonLoot("abandoned-catacombs", "normal", { min: 4, max: 8 }),
  },
  "grave-wraith": {
    id: "grave-wraith",
    bestiaryCategory: "monster",
    name: "Grave Wraith",
    subtitle: "A cold memory refusing to fade",
    maxHealth: 600,
    basicAttackDamage: 56,
    basicAttackTimeMs: 2400,
    defense: 20,
    color: "#8d9dc9",
    ui: { portraitIcon: "ghost" },
    traitIds: ["grave-wraith-ethereal-form"],
    resistances: {
      physical: 0.5,
      fire: -0.25,
      water: -0.25,
      earth: -0.25,
      air: -0.25,
    },
    actions: {
      "chilling-touch": {
        id: "chilling-touch",
        name: "Chilling Touch",
        actionTimeMs: 1800,
        description: "A cold touch damages the target and leaves it Chilled.",
        effects: [
          scaledDirectDamage("water", 1.3),
          applyStatus("chilled", "opponent", 10000),
        ],
        tags: ["special", "water", "magic", "debuff"],
      },
      "frost-reap": {
        id: "frost-reap",
        name: "Frost Reap",
        actionTimeMs: 2100,
        description:
          "Reaps the target with spectral frost. Deals 50% more damage while the target is Chilled.",
        effects: [
          {
            type: "deal-damage",
            target: "opponent",
            components: [{
              damageType: "water",
              magnitude: opponentStatusStackScaled("chilled", { type: "source-basic-damage-percent", value: 1.25 }, 0.5, 1),
            }],
            tags: ["direct"],
          },
        ],
        tags: ["special", "water", "magic", "direct"],
      },
      fade: {
        id: "fade",
        name: "Fade",
        actionTimeMs: 1700,
        description: "The Grave Wraith slips into Spectral Fade.",
        effects: [applyStatus("spectral-fade", "self", 5000)],
        tags: ["special", "buff"],
      },
    },
    actionPatterns: {
      default: {
        id: "default",
        steps: [
          basic("basic-1"),
          action("chilling-touch-step-1", "chilling-touch"),
          basic("basic-2"),
          action("fade-step", "fade"),
          basic("basic-3"),
          action("frost-reap-step", "frost-reap"),
          basic("basic-4"),
        ],
      },
    },
    defaultActionPatternId: "default",
    loot: withDungeonLoot("abandoned-catacombs", "normal", { min: 4, max: 8 }),
  },
  "fallen-acolyte": {
    id: "fallen-acolyte",
    bestiaryCategory: "monster",
    name: "Fallen Acolyte",
    subtitle: "A ritualist still serving a forgotten master",
    maxHealth: 550,
    basicAttackDamage: 50,
    basicAttackTimeMs: 2600,
    defense: 18,
    color: "#9b7eaa",
    ui: { portraitIcon: "mage" },
    traitIds: ["fallen-acolyte-grave-channeling"],
    actions: {
      "grave-bolt": {
        id: "grave-bolt",
        name: "Grave Bolt",
        actionTimeMs: 1500,
        description: "A focused Arcane bolt tears through the target.",
        effects: [scaledDirectDamage("arcane", 1.45)],
        tags: ["special", "arcane", "magic", "direct"],
      },
      "grave-curse": {
        id: "grave-curse",
        name: "Grave Curse",
        actionTimeMs: 1700,
        description:
          "A funerary curse weakens the Wizard's damage and recovery.",
        effects: [applyStatus("cursed", "opponent", 12000)],
        tags: ["special", "debuff"],
      },
      "soul-drain": {
        id: "soul-drain",
        name: "Soul Drain",
        actionTimeMs: 2200,
        description:
          "Drains Arcane energy and restores Health. Both effects are 40% stronger while the target is Cursed.",
        effects: [
          {
            type: "deal-damage",
            target: "opponent",
            components: [{
              damageType: "arcane",
              magnitude: opponentStatusStackScaled("cursed", { type: "source-basic-damage-percent", value: 1.1 }, 0.4, 1),
            }],
            tags: ["direct"],
          },
          {
            type: "heal",
            target: "self",
            magnitude: opponentStatusStackScaled("cursed", { type: "source-max-health-percent", value: 0.07 }, 0.4, 1),
            tags: ["heal", "direct"],
          },
        ],

        tags: ["special", "arcane", "magic", "heal", "direct"],
      },
      "death-ward": {
        id: "death-ward",
        name: "Death Ward",
        actionTimeMs: 2000,
        description:
          "A deathly ward gathers a protective Barrier around the caster.",
        effects: [scaledBarrier(0.18)],
        tags: ["special", "barrier"],
      },
    },
    actionPatterns: {
      default: {
        id: "default",
        steps: [
          action("grave-bolt-step", "grave-bolt"),
          basic("basic-1"),
          action("grave-curse-step", "grave-curse"),
          basic("basic-2"),
          basic("basic-3"),
          action("soul-drain-step", "soul-drain"),
          action("death-ward-step", "death-ward"),
          basic("basic-4"),
        ],
      },
    },
    defaultActionPatternId: "default",
    loot: withDungeonLoot("abandoned-catacombs", "normal", { min: 5, max: 10 }),
  },
  "archmage-edrin-shade": {
    id: "archmage-edrin-shade",
    bestiaryCategory: "boss",
    name: "Archmage Edrin's Shade",
    subtitle: "The last spell of a wizard who would not rest",
    maxHealth: 6000,
    basicAttackDamage: 60,
    basicAttackTimeMs: 2500,
    defense: 45,
    color: "#70619b",
    ui: { portraitIcon: "mage" },
    traitIds: [
      "archmage-edrin-arcane-remnant",
      "archmage-edrin-unbound-spirit",
    ],
    resistances: { fire: 0.15, water: 0.15, earth: 0.15, air: 0.15 },
    actions: {
      gravefire: {
        id: "gravefire",
        name: "Gravefire",
        actionTimeMs: 1800,
        description: "Flame erupts across the target and leaves it Burning.",
        effects: [
          scaledDirectDamage("fire", 1.1),
          scaledDot("burning", "fire", 1.0, 5000),
        ],
        tags: ["special", "fire", "magic", "debuff"],
      },
      frostbind: {
        id: "frostbind",
        name: "Frostbind",
        actionTimeMs: 2000,
        description:
          "A freezing surge damages the target and leaves it Chilled.",
        effects: [
          scaledDirectDamage("water", 1.05),
          applyStatus("chilled", "opponent"),
        ],
        tags: ["special", "water", "magic", "debuff"],
      },
      "arcane-ward": {
        id: "arcane-ward",
        name: "Arcane Ward",
        actionTimeMs: 2500,
        description: "Edrin shapes an Arcane ward into a protective Barrier.",
        effects: [scaledBarrier(0.08)],
        tags: ["special", "arcane", "barrier"],
      },
      "soul-drain": {
        id: "soul-drain",
        name: "Soul Drain",
        actionTimeMs: 2400,
        description:
          "Arcane force tears at the target and restores the caster's Health.",
        effects: [scaledDirectDamage("arcane", 1.2), scaledHeal(0.05)],
        tags: ["special", "arcane", "magic", "heal", "direct"],
      },
      "arcane-disruption": {
        id: "arcane-disruption",
        name: "Arcane Disruption",
        actionTimeMs: 2000,
        description: "Edrin fractures the Wizard's flow of Mana and recovery.",
        effects: [
          scaledDirectDamage("arcane", 0.8),
          applyStatus("arcane-disruption", "opponent", 6000),
        ],
        tags: ["special", "arcane", "magic", "debuff", "direct"],
      },
      "final-incantation": {
        id: "final-incantation",
        name: "Final Incantation",
        actionTimeMs: 3500,
        description: "Edrin unleashes a devastating Arcane incantation.",
        effects: [scaledDirectDamage("arcane", 2.0)],
        tags: ["special", "arcane", "magic", "direct"],
      },
    },
    actionPatterns: {
      default: {
        id: "default",
        steps: [
          action("gravefire-step", "gravefire"),
          basic("basic-1"),
          action("frostbind-step", "frostbind"),
          basic("basic-2"),
          action("arcane-ward-step", "arcane-ward"),
          action("soul-drain-step", "soul-drain"),
          basic("basic-3"),
        ],
      },
      unbound: {
        id: "unbound",
        steps: [
          action("arcane-disruption-step", "arcane-disruption"),
          action("gravefire-step", "gravefire"),
          action("frostbind-step", "frostbind"),
          basic("basic-1"),
          action("soul-drain-step", "soul-drain"),
          action("final-incantation-step", "final-incantation"),
          basic("basic-2"),
        ],
      },
    },
    defaultActionPatternId: "default",
    loot: withDungeonLoot("abandoned-catacombs", "boss", { min: 21, max: 48 }),
  },
} satisfies Partial<Record<MonsterId, MonsterDefinition>>;
