import type { MonsterId } from "../../../types";
import {
  action,
  applyStatus,
  basic,
  delayCurrentAction,
  opponentStatusStackScaled,
  scaledDirectDamage,
  scaledDot,
  scaledMultiDamage,
  withDungeonLoot,
  type MonsterDefinition,
} from "../monsterTypes";

export const HOWLING_DEN_MONSTERS = {
  "cavefang-wolf": {
    id: "cavefang-wolf",
    bestiaryCategory: "monster",
    name: "Cavefang Wolf",
    subtitle: "A patient predator that waits for weakness",
    maxHealth: 350,
    basicAttackDamage: 20,
    basicAttackTimeMs: 2200,
    defense: 16,
    color: "#b8a0a0",
    ui: { portraitIcon: "wolf" },
    traitIds: ["cavefang-wolf-predator-instinct"],
    resonanceYield: { air: 28 },
    actions: {
      pounce: {
        id: "pounce",
        name: "Pounce",
        actionTimeMs: 1400,
        description:
          "The Wolf lunges through the Wizard's concentration and disrupts the current Spell cast.",
        effects: [scaledDirectDamage("physical", 1.5), delayCurrentAction(400)],
        tags: ["special", "physical", "melee", "control"],
      },
      "predator-howl": {
        id: "predator-howl",
        name: "Predator's Howl",
        actionTimeMs: 1600,
        description: "A hunting howl accelerates the Wolf's assault.",
        effects: [applyStatus("haste", "self", 16000)],
        tags: ["special", "buff"],
      },
    },
    actionPatterns: {
      default: {
        id: "default",
        steps: [
          basic("basic-1"),
          basic("basic-2"),
          action("pounce-step", "pounce"),
          basic("basic-3"),
          action("predator-howl-step", "predator-howl"),
          basic("basic-4"),
        ],
      },
    },
    defaultActionPatternId: "default",
    loot: withDungeonLoot("howling-den", "normal", { min: 3, max: 5 }),
  },
  "razorclaw-lynx": {
    id: "razorclaw-lynx",
    bestiaryCategory: "monster",
    name: "Razorclaw Lynx",
    subtitle: "A blur of claws and hungry momentum",
    maxHealth: 360,
    basicAttackDamage: 21,
    basicAttackTimeMs: 1900,
    defense: 16,
    color: "#c18b73",
    ui: { portraitIcon: "claw" },
    traitIds: ["razorclaw-lynx-relentless-hunter"],
    resonanceYield: { air: 32 },
    actions: {
      "rending-claws": {
        id: "rending-claws",
        name: "Rending Claws",
        actionTimeMs: 1300,
        description:
          "Raking claws cut the target and leave a lingering Bleeding wound.",
        effects: [
          scaledDirectDamage("physical", 1.25),
          scaledDot("bleeding", "physical", 1.45, 8000),
        ],
        tags: ["special", "physical", "melee", "debuff"],
      },
      "blood-scent": {
        id: "blood-scent",
        name: "Blood Scent",
        actionTimeMs: 1200,
        description:
          "The Lynx catches the scent of blood and quickens its assault.",
        effects: [applyStatus("haste", "self", 5000)],
        tags: ["special", "buff"],
      },
    },
    actionPatterns: {
      default: {
        id: "default",
        steps: [
          basic("basic-1"),
          action("rending-claws-step-1", "rending-claws"),
          basic("basic-2"),
          basic("basic-3"),
          action("blood-scent-step", "blood-scent"),
          basic("basic-4"),
          action("rending-claws-step-2", "rending-claws"),
        ],
      },
    },
    defaultActionPatternId: "default",
    loot: withDungeonLoot("howling-den", "normal", { min: 3, max: 5 }),
  },
  "corrupted-dire-wolf": {
    id: "corrupted-dire-wolf",
    bestiaryCategory: "monster",
    name: "Corrupted Dire Wolf",
    subtitle: "A beast split between fang and sorcery",
    maxHealth: 420,
    basicAttackDamage: 26,
    basicAttackTimeMs: 2300,
    defense: 13,
    color: "#7e6c9f",
    ui: { portraitIcon: "wolf" },
    traitIds: ["corrupted-dire-wolf-arcane-corruption"],
    resonanceYield: { air: 25, earth: 20 },
    resistances: { fire: 0.1, water: 0.1, earth: 0.1, air: 0.1 },
    actions: {
      "arcane-bite": {
        id: "arcane-bite",
        name: "Arcane Bite",
        actionTimeMs: 1600,
        description: "A corrupted bite tears through both body and warding.",
        effects: [
          {
            type: "deal-damage",
            target: "opponent",
            components: [
              {
                damageType: "physical",
                magnitude: { type: "source-basic-damage-percent", value: 0.65 },
              },
              {
                damageType: "arcane",
                magnitude: { type: "source-basic-damage-percent", value: 0.65 },
              },
            ],
            tags: ["direct"],
          },
        ],
        tags: ["special", "physical", "arcane", "melee", "direct"],
      },
      "corrupted-howl": {
        id: "corrupted-howl",
        name: "Corrupted Howl",
        actionTimeMs: 1800,
        description: "The howl fills the Corrupted Dire Wolf with Haste.",
        effects: [applyStatus("haste", "self", 6000)],
        tags: ["special", "buff"],
      },
      "corrupting-fang": {
        id: "corrupting-fang",
        name: "Corrupting Fang",
        actionTimeMs: 1900,
        description:
          "A corrupted bite leaves unstable Arcane residue in the wound.",
        effects: [
          scaledMultiDamage(
            [
              { damageType: "physical", coefficient: 0.9 },
              { damageType: "arcane", coefficient: 0.6 },
            ],
            ["direct"],
          ),
          applyStatus("corruption", "opponent", undefined, 1),
        ],
        tags: ["special", "physical", "arcane", "melee", "debuff", "direct"],
      },
    },
    actionPatterns: {
      default: {
        id: "default",
        steps: [
          basic("basic-1"),
          action("arcane-bite-step-1", "arcane-bite"),
          basic("basic-2"),
          action("corrupted-howl-step", "corrupted-howl"),
          basic("basic-3"),
          action("corrupting-fang-step", "corrupting-fang"),
          basic("basic-4"),
          action("arcane-bite-step-2", "arcane-bite"),
        ],
      },
    },
    defaultActionPatternId: "default",
    loot: withDungeonLoot("howling-den", "normal", { min: 3, max: 5 }),
  },
  "bonehide-boar": {
    id: "bonehide-boar",
    bestiaryCategory: "monster",
    name: "Bonehide Boar",
    subtitle: "A slow armored bruiser that turns every charge into a wall of force",
    maxHealth: 470,
    basicAttackDamage: 24,
    basicAttackTimeMs: 2900,
    defense: 28,
    color: "#9a8066",
    ui: { portraitIcon: "bear" },
    traitIds: [],
    actions: {
      "tusk-charge": {
        id: "tusk-charge",
        name: "Tusk Charge",
        actionTimeMs: 2300,
        description: "A brutal charge deals Physical damage and delays the Wizard's current action.",
        effects: [scaledDirectDamage("physical", 1.45), delayCurrentAction(500)],
        tags: ["special", "physical", "melee", "control", "direct"],
      },
      "bristle-guard": {
        id: "bristle-guard",
        name: "Bristle Guard",
        actionTimeMs: 2000,
        description: "The Boar hardens its hide and becomes Fortified.",
        effects: [applyStatus("fortified", "self", 8000)],
        tags: ["special", "buff"],
      },
    },
    actionPatterns: {
      default: {
        id: "default",
        steps: [basic("basic-1"), action("tusk-charge-step-1", "tusk-charge"), basic("basic-2"), action("bristle-guard-step", "bristle-guard"), basic("basic-3"), basic("basic-4"), action("tusk-charge-step-2", "tusk-charge")],
      },
    },
    defaultActionPatternId: "default",
    resonanceYield: { earth: 36 },
    loot: withDungeonLoot("howling-den", "normal", { min: 3, max: 5 }),
  },
  "moonblind-jackal": {
    id: "moonblind-jackal",
    bestiaryCategory: "monster",
    name: "Moonblind Jackal",
    subtitle: "A fast debuff predator that hunts by scent and curse",
    maxHealth: 340,
    basicAttackDamage: 23,
    basicAttackTimeMs: 1900,
    defense: 15,
    color: "#8c829d",
    ui: { portraitIcon: "wolf" },
    traitIds: [],
    actions: {
      moonbite: {
        id: "moonbite",
        name: "Moonbite",
        actionTimeMs: 1700,
        description: "Arcane damage leaves the Wizard Cursed.",
        effects: [scaledDirectDamage("arcane", 1.1), applyStatus("cursed", "opponent", 7000)],
        tags: ["special", "arcane", "melee", "debuff", "direct"],
      },
      "blood-trail": {
        id: "blood-trail",
        name: "Blood Trail",
        actionTimeMs: 1800,
        description: "Physical damage opens a Bleeding wound.",
        effects: [scaledDirectDamage("physical", 0.9), scaledDot("bleeding", "physical", 1.2, 8000)],
        tags: ["special", "physical", "melee", "debuff", "direct"],
      },
    },
    actionPatterns: {
      default: {
        id: "default",
        steps: [basic("basic-1"), action("moonbite-step-1", "moonbite"), basic("basic-2"), action("blood-trail-step", "blood-trail"), basic("basic-3"), action("moonbite-step-2", "moonbite"), basic("basic-4")],
      },
    },
    defaultActionPatternId: "default",
    resonanceYield: { air: 38 },
    loot: withDungeonLoot("howling-den", "normal", { min: 3, max: 5 }),
  },
  "den-stalker": {
    id: "den-stalker",
    bestiaryCategory: "monster",
    name: "Den Stalker",
    subtitle: "An ambush predator that sets up a fragile target for the killing bite",
    maxHealth: 400,
    basicAttackDamage: 28,
    basicAttackTimeMs: 2200,
    defense: 18,
    color: "#5e526e",
    ui: { portraitIcon: "claw" },
    traitIds: [],
    actions: {
      "shadow-pounce": {
        id: "shadow-pounce",
        name: "Shadow Pounce",
        actionTimeMs: 1800,
        description: "Physical damage leaves the Wizard Fragile.",
        effects: [scaledDirectDamage("physical", 1.2), applyStatus("fragile", "opponent", 6000)],
        tags: ["special", "physical", "melee", "debuff", "direct"],
      },
      vanish: {
        id: "vanish",
        name: "Vanish",
        actionTimeMs: 1500,
        description: "The Stalker slips into Spectral Fade.",
        effects: [applyStatus("spectral-fade", "self", 5000)],
        tags: ["special", "buff"],
      },
      "execution-bite": {
        id: "execution-bite",
        name: "Execution Bite",
        actionTimeMs: 2100,
        description: "A devastating bite that deals extra damage to Fragile targets.",
        effects: [{ type: "deal-damage", target: "opponent", components: [{ damageType: "physical", magnitude: opponentStatusStackScaled("fragile", { type: "source-basic-damage-percent", value: 1.3 }, 0.5, 1) }], tags: ["special", "physical", "melee", "direct"] }],
      },
    },
    actionPatterns: {
      default: {
        id: "default",
        steps: [action("vanish-step", "vanish"), basic("basic-1"), action("shadow-pounce-step-1", "shadow-pounce"), basic("basic-2"), action("execution-bite-step", "execution-bite"), basic("basic-3"), action("shadow-pounce-step-2", "shadow-pounce")],
      },
    },
    defaultActionPatternId: "default",
    resonanceYield: { air: 32, earth: 18 },
    loot: withDungeonLoot("howling-den", "normal", { min: 3, max: 5 }),
  },
  "corrupted-greatbear": {
    id: "corrupted-greatbear",
    bestiaryCategory: "boss",
    name: "Corrupted Greatbear",
    subtitle: "A mountain of fur warped by hungry magic",
    maxHealth: 2400,
    basicAttackDamage: 50,
    basicAttackTimeMs: 2800,
    defense: 30,
    color: "#554240",
    ui: {
      portraitIcon: "bear",
      bestiary: {
        roleTags: ["Physical", "Stacking Debuff", "Ramping Damage", "Control", "2 Phases"],
        phaseLabels: { default: "Thick Hide", corrupted: "Corrupted" },
        phaseOrder: ["default", "corrupted"],
      },
    },
    traitIds: [
      "corrupted-greatbear-thick-hide",
      "corrupted-greatbear-unstable-corruption",
    ],
    resonanceYield: { earth: 110, air: 30 },
    actions: {
      "crushing-maul": {
        id: "crushing-maul",
        name: "Crushing Maul",
        actionTimeMs: 2200,
        description: "A brutal maul strike crashes into the target.",
        effects: [scaledDirectDamage("physical", 1.55)],
        tags: ["special", "physical", "melee", "direct"],
      },
      groundbreaker: {
        id: "groundbreaker",
        name: "Groundbreaker",
        actionTimeMs: 2500,
        description:
          "The Greatbear shatters the ground, disrupting the Wizard's current Spell cast.",
        effects: [scaledDirectDamage("physical", 1.2), delayCurrentAction(1000)],
        tags: ["special", "physical", "control"],
      },
      "corrupted-roar": {
        id: "corrupted-roar",
        name: "Corrupted Roar",
        actionTimeMs: 2200,
        description: "Makes the target Vulnerable and adds 1 Corruption.",
        effects: [
          applyStatus("vulnerable", "opponent", 10000),
          applyStatus("corruption", "opponent", 30000, 1),
        ],
        tags: ["special", "debuff"],
      },
      "savage-rampage": {
        id: "savage-rampage",
        name: "Savage Rampage",
        actionTimeMs: 3000,
        description: "A heavy Physical strike empowered by Corruption.",
        effects: [
          {
            type: "deal-damage",
            target: "opponent",
            components: [{
              damageType: "physical",
              magnitude: opponentStatusStackScaled("corruption", { type: "source-basic-damage-percent", value: 2 }, 0.12, 5),
            }],
            tags: ["direct"],
          },
          applyStatus("corruption", "opponent", 30000, 1),
        ],
        tags: ["special", "physical", "melee", "debuff", "direct"],
      },
    },
    actionPatterns: {
      default: {
        id: "default",
        steps: [
          basic("basic-1"),
          basic("basic-2"),
          action("crushing-maul-step", "crushing-maul"),
          basic("basic-3"),
          action("groundbreaker-step", "groundbreaker"),
          basic("basic-4"),
        ],
      },
      corrupted: {
        id: "corrupted",
        steps: [
          action("corrupted-roar-step", "corrupted-roar"),
          action("crushing-maul-step-1", "crushing-maul"),
          basic("basic-1"),
          action("savage-rampage-step-1", "savage-rampage"),
          basic("basic-2"),
          action("crushing-maul-step-2", "crushing-maul"),
          action("savage-rampage-step-2", "savage-rampage"),
          basic("basic-3"),
        ],
      },
    },
    defaultActionPatternId: "default",
    loot: withDungeonLoot("howling-den", "boss", { min: 12, max: 30 }),
  },
} satisfies Partial<Record<MonsterId, MonsterDefinition>>;
