import { Copy, RotateCcw, ShieldCheck, SlidersHorizontal } from 'lucide-react'
import { getRegisteredUiElement } from './uiEditorRegistry'
import { getUiPropertyDefinitions } from './uiEditorProperties'
import { resolveUiStyle } from './uiEditorResolver'
import { copyUiStyle, pasteUiStyle, resetUiElement, resetUiSection, resetUiStyleProperty, setUiEditorScope, setUiStyleProperty, useUiEditorStore } from './uiEditorStore'
import { getActiveUiPreset } from './uiEditorStore'
import type { UiLength, UiLengthUnit, UiPropertyCategory, UiStyleKey, UiStyleValue } from './uiEditorTypes'

const categories: readonly { id: UiPropertyCategory; label: string }[] = [{ id: 'layout', label: 'Layout' }, { id: 'position', label: 'Position / Transform' }, { id: 'typography', label: 'Typography' }, { id: 'image', label: 'Image / Icon' }, { id: 'appearance', label: 'Appearance' }, { id: 'effects', label: 'Effects' }]

export function UiEditorInspector() {
  const selectedUiId = useUiEditorStore((state) => state.selectedUiId); const scope = useUiEditorStore((state) => state.scope); const entry = selectedUiId ? getRegisteredUiElement(selectedUiId) : null
  if (!entry) return <section className="ui-editor-inspector ui-editor-empty"><SlidersHorizontal size={26} /><strong>Select an element</strong><span>Click a registered surface in the game or choose one from the hierarchy.</span></section>
  const preset = getActiveUiPreset(); const resolved = resolveUiStyle({ element: entry, preset }); const own = scope === 'component' && entry.componentType ? preset.componentStyles?.[entry.componentType] ?? {} : scope === 'screen' ? preset.screens?.[entry.screen as never]?.[entry.id] ?? {} : preset.elements?.[entry.id] ?? {}; const computed = getComputedStyle(entry.element); const rect = entry.element.getBoundingClientRect(); const definitions = getUiPropertyDefinitions(entry.type)
  const grouped = categories.map((category) => ({ ...category, properties: definitions.filter((property) => property.category === category.id) })).filter((category) => category.properties.length)
  return <section className="ui-editor-inspector" data-ui-editor-ignore="true">
    <div className="ui-editor-inspector-head"><div className="ui-editor-inspector-symbol">{entry.type === 'panel' ? '◇' : entry.type === 'image' ? '▧' : '✦'}</div><div><span className="ui-editor-kicker">INSPECTOR</span><h2>{entry.label}</h2><code>{entry.id}</code></div></div>
    <div className="ui-editor-inspector-summary"><span><small>TYPE</small><strong>{entry.type}</strong></span><span><small>SIZE</small><strong>{Math.round(rect.width)} × {Math.round(rect.height)}</strong></span><span><small>SOURCE</small><strong>{Object.keys(resolved.sources).length ? `${new Set(Object.values(resolved.sources)).size} layers` : 'base CSS'}</strong></span></div>
    <section className="ui-editor-inspector-section"><div className="ui-editor-section-heading"><h3>General</h3><ShieldCheck size={13} /></div><dl className="ui-editor-meta-list"><div><dt>Component</dt><dd>{entry.componentType ?? '—'}</dd></div><div><dt>Screen</dt><dd>{entry.screen}</dd></div><div><dt>Parent</dt><dd>{entry.parentId ?? '—'}</dd></div><div><dt>Computed position</dt><dd>{Math.round(rect.left)} / {Math.round(rect.top)}</dd></div></dl><div className="ui-editor-scope"><span>Editing scope</span><div><button type="button" className={scope === 'element' ? 'active' : ''} onClick={() => setUiEditorScope('element')}>This instance</button><button type="button" className={scope === 'screen' ? 'active' : ''} onClick={() => setUiEditorScope('screen')}>This screen</button><button type="button" className={scope === 'component' ? 'active' : ''} disabled={!entry.componentType} onClick={() => setUiEditorScope('component')}>All {entry.componentType ?? 'instances'}</button></div></div><div className="ui-editor-control-row"><button type="button" onClick={() => copyUiStyle(entry.id, scope)}><Copy size={12} /> Copy style</button><button type="button" onClick={() => pasteUiStyle(entry.id, scope)}><Copy size={12} /> Paste style</button><button type="button" onClick={() => { if (window.confirm(`Reset overrides for ${entry.label}?`)) resetUiElement(entry.id, scope) }}><RotateCcw size={12} /> Reset element</button></div></section>
    {grouped.map((group) => <details className="ui-editor-inspector-section ui-editor-property-group" key={group.id} open><summary><h3>{group.label}</h3><span>{group.properties.length}</span></summary><div className="ui-editor-property-list">{group.properties.map((definition) => <PropertyControl key={definition.key} entry={entry} definition={definition} value={own[definition.key] ?? resolved.style[definition.key]} inherited={own[definition.key] === undefined} computed={computed} onChange={(value) => setUiStyleProperty(entry.id, definition.key, value, scope)} onReset={() => resetUiStyleProperty(entry.id, definition.key, scope)} />)}</div><button type="button" className="ui-editor-section-reset" onClick={() => resetUiSection(entry.id, group.id, scope)}>Reset section</button></details>)}
    <details className="ui-editor-inspector-section"><summary><h3>Resolved style sources</h3><span>ADVANCED</span></summary><div className="ui-editor-source-trace">{Object.entries(resolved.sources).map(([key, source]) => <div key={key}><code>{key}</code><span>{source}</span></div>)}{!Object.keys(resolved.sources).length && <span>All values are inherited from base CSS.</span>}</div></details>
  </section>
}

function PropertyControl({ entry, definition, value, inherited, computed, onChange, onReset }: { entry: NonNullable<ReturnType<typeof getRegisteredUiElement>>; definition: ReturnType<typeof getUiPropertyDefinitions>[number]; value: unknown; inherited: boolean; computed: CSSStyleDeclaration; onChange: (value: UiStyleValue) => void; onReset: () => void }) {
  const property = definition.key; const displayValue = value ?? computedValue(property, computed); const label = <span className="ui-editor-property-label">{definition.label}{inherited ? <small>inherited</small> : <small className="override">override</small>}</span>
  if (definition.valueType === 'length') return <label className="ui-editor-property-row">{label}<LengthInput value={toLength(displayValue)} min={definition.min} max={definition.max} onChange={onChange} onReset={inherited ? undefined : onReset} /></label>
  if (definition.valueType === 'number') return <label className="ui-editor-property-row">{label}<span className="ui-editor-input-wrap"><input type="number" min={definition.min} max={definition.max} step={definition.step} value={typeof displayValue === 'number' ? displayValue : toNumber(displayValue)} onChange={(event) => onChange(Number(event.target.value))} />{!inherited && <button type="button" aria-label={`Reset ${definition.label}`} onClick={onReset}>×</button>}</span></label>
  if (definition.valueType === 'enum') return <label className="ui-editor-property-row">{label}<span className="ui-editor-input-wrap"><select value={String(displayValue ?? definition.allowedValues?.[0] ?? '')} onChange={(event) => onChange(event.target.value)}>{definition.allowedValues?.map((option) => <option key={option}>{option}</option>)}</select>{!inherited && <button type="button" aria-label={`Reset ${definition.label}`} onClick={onReset}>×</button>}</span></label>
  if (definition.valueType === 'color') return <label className="ui-editor-property-row">{label}<span className="ui-editor-input-wrap"><input type="text" value={colorInput(displayValue)} placeholder="token or #hex" onChange={(event) => onChange({ custom: event.target.value })} />{!inherited && <button type="button" aria-label={`Reset ${definition.label}`} onClick={onReset}>×</button>}</span></label>
  return <label className="ui-editor-property-row">{label}<span className="ui-editor-input-wrap"><input type="text" value={String(displayValue ?? '')} onChange={(event) => onChange(event.target.value)} />{!inherited && <button type="button" aria-label={`Reset ${definition.label}`} onClick={onReset}>×</button>}</span></label>
}

function LengthInput({ value, min, max, onChange, onReset }: { value: UiLength; min?: number; max?: number; onChange: (value: UiLength) => void; onReset?: () => void }) { const auto = isAutoLength(value); const numericValue = auto ? null : value as { value: number; unit: UiLengthUnit }; const numeric = numericValue?.value ?? ''; const unit: UiLengthUnit = numericValue?.unit ?? 'px'; return <span className="ui-editor-length-control"><input type="number" min={min} max={max} value={numeric} placeholder="auto" onChange={(event) => onChange(event.target.value === '' ? { keyword: 'auto' } : { value: Number(event.target.value), unit })} /><select value={unit} onChange={(event) => onChange(auto ? { value: 0, unit: event.target.value as UiLengthUnit } : { value: numericValue?.value ?? 0, unit: event.target.value as UiLengthUnit })}><option value="px">px</option><option value="%">%</option><option value="rem">rem</option><option value="fr">fr</option></select>{onReset && <button type="button" aria-label="Reset property" onClick={onReset}>×</button>}</span> }
function isAutoLength(value: UiLength): value is { keyword: 'auto' } { return 'keyword' in value }
function toLength(value: unknown): UiLength { if (value && typeof value === 'object' && ('keyword' in value || 'value' in value)) return value as UiLength; if (typeof value === 'number') return { value, unit: 'px' }; if (typeof value === 'string' && value === 'auto') return { keyword: 'auto' }; const match = typeof value === 'string' ? value.match(/^(-?[\d.]+)(px|%|rem|fr)$/) : null; return match ? { value: Number(match[1]), unit: match[2] as UiLengthUnit } : { value: 0, unit: 'px' } }
function toNumber(value: unknown) { const number = Number.parseFloat(String(value ?? '0')); return Number.isFinite(number) ? number : 0 }
function colorInput(value: unknown) { if (!value || typeof value !== 'object') return String(value ?? ''); if ('custom' in value) return String(value.custom); if ('token' in value) return String(value.token); return '' }
function computedValue(key: UiStyleKey, computed: CSSStyleDeclaration): unknown { const property = { minWidth: 'min-width', minHeight: 'min-height', maxWidth: 'max-width', maxHeight: 'max-height', marginTop: 'margin-top', marginRight: 'margin-right', marginBottom: 'margin-bottom', marginLeft: 'margin-left', paddingTop: 'padding-top', paddingRight: 'padding-right', paddingBottom: 'padding-bottom', paddingLeft: 'padding-left', rowGap: 'row-gap', columnGap: 'column-gap', flexDirection: 'flex-direction', flexWrap: 'flex-wrap', justifyContent: 'justify-content', alignItems: 'align-items', alignSelf: 'align-self', gridTemplateColumns: 'grid-template-columns', gridTemplateRows: 'grid-template-rows', overflowX: 'overflow-x', overflowY: 'overflow-y', fontFamily: 'font-family', fontSize: 'font-size', fontWeight: 'font-weight', fontStyle: 'font-style', lineHeight: 'line-height', letterSpacing: 'letter-spacing', textAlign: 'text-align', textTransform: 'text-transform', textDecoration: 'text-decoration', whiteSpace: 'white-space', textOverflow: 'text-overflow', objectFit: 'object-fit', objectPosition: 'object-position', borderColor: 'border-color', borderWidth: 'border-width', borderStyle: 'border-style', borderRadius: 'border-radius', background: 'background-color', color: 'color', boxShadow: 'box-shadow', backdropFilter: 'backdrop-filter', zIndex: 'z-index', opacity: 'opacity', display: 'display', width: 'width', height: 'height', gap: 'gap' } as Partial<Record<UiStyleKey, string>>; return property[key] ? computed.getPropertyValue(property[key]!) : key === 'scale' ? 1 : key === 'rotation' || key === 'xOffset' || key === 'yOffset' ? 0 : '' }
