import { RotateCcw } from 'lucide-react'
import { setUiToken, useUiEditorStore } from './uiEditorStore'
import type { UiLength, UiLengthUnit } from './uiEditorTypes'

export function UiEditorDesignSystem() {
  const preset = useUiEditorStore((state) => state.presets[state.activePresetId]); const tokens = preset.tokens ?? {}; const token = (path: string): unknown => { const [group, key] = path.split('.'); return (tokens as Record<string, Record<string, unknown>>)[group]?.[key] }; const lineHeight = token('typography.lineHeightBase')
  return <section className="ui-editor-design-system" data-ui-editor-ignore="true"><div className="ui-editor-pane-heading"><div><span className="ui-editor-kicker">DESIGN SYSTEM</span><strong>Global tokens</strong></div><span>LIVE</span></div><p className="ui-editor-help">Token-linked surfaces update together. Instance overrides remain independent.</p><TokenLength label="Body font size" value={token('typography.fontSizeBase')} fallback={{ value: 14, unit: 'px' }} onChange={(value) => setUiToken('typography.fontSizeBase', value)} /><TokenNumber label="Base line height" value={typeof lineHeight === 'number' ? lineHeight : 1.4} min={0.5} max={4} step={0.05} onChange={(value) => setUiToken('typography.lineHeightBase', value)} /><TokenLength label="Panel radius" value={token('panel.borderRadius')} fallback={{ value: 8, unit: 'px' }} onChange={(value) => setUiToken('panel.borderRadius', value)} /><TokenLength label="Panel padding" value={token('panel.padding')} fallback={{ value: 16, unit: 'px' }} onChange={(value) => setUiToken('panel.padding', value)} /><TokenLength label="Card gap" value={token('card.gap')} fallback={{ value: 8, unit: 'px' }} onChange={(value) => setUiToken('card.gap', value)} /><TokenLength label="Button height" value={token('button.height')} fallback={{ value: 35, unit: 'px' }} onChange={(value) => setUiToken('button.height', value)} /><button type="button" className="ui-editor-secondary-action" onClick={() => { ['typography.fontSizeBase', 'typography.lineHeightBase', 'panel.borderRadius', 'panel.padding', 'card.gap', 'button.height'].forEach((path) => setUiToken(path, undefined)) }}><RotateCcw size={12} /> Reset token overrides</button></section>
}
function TokenLength({ label, value, fallback, onChange }: { label: string; value: unknown; fallback: UiLength; onChange: (value: UiLength) => void }) { const current = value && typeof value === 'object' && ('value' in value || 'keyword' in value) ? value as UiLength : fallback; const numericValue = 'keyword' in current ? null : current as { value: number; unit: UiLengthUnit }; const number = numericValue?.value ?? ''; const unit: UiLengthUnit = numericValue?.unit ?? 'px'; return <label className="ui-editor-token-row"><span>{label}</span><span><input type="number" value={number} onChange={(event) => onChange({ value: Number(event.target.value), unit })} /><select value={unit} onChange={(event) => onChange({ value: Number(number || 0), unit: event.target.value as UiLengthUnit })}><option>px</option><option>%</option><option>rem</option></select></span></label> }
function TokenNumber({ label, value, min, max, step, onChange }: { label: string; value: number; min: number; max: number; step: number; onChange: (value: number) => void }) { return <label className="ui-editor-token-row"><span>{label}</span><input type="number" min={min} max={max} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} /></label> }
