import { useState } from 'react'
import { BALANCE } from '../../game/data/balance'
import { ITEMS } from '../../game/data/items'
import { FRAGMENT_ORDER, RESEARCH_ITEMS, SCHOOLS } from '../../game/data/schools'
import type { ItemId, SchoolId } from '../../game/types'
import { useGameStore } from '../../store/gameStore'
import { Button, Card, Progress, Status } from '../../components/ui'
import { formatTime } from '../../game/utils'

export function ResearchPanel() { const [itemId, setItemId] = useState<ItemId>('fire-fragment'); const [schoolId, setSchoolId] = useState<SchoolId>('fire'); const [quantity, setQuantity] = useState(1); const inventory = useGameStore((state) => state.inventory); const job = useGameStore((state) => state.activities.research); const setConfig = useGameStore((state) => state.setResearchConfig); const toggle = useGameStore((state) => state.toggleResearch); const definition = ITEMS[itemId]; const max = Math.max(1, Math.min(10, inventory[itemId] ?? 0)); const xp = definition.researchSchool === schoolId ? BALANCE.research.matchingXp : BALANCE.research.nonMatchingXp; return <Card title="Arcane Crucible" action={<Status tone={job.running ? 'active' : job.status === 'level-cap' ? 'warning' : 'neutral'}>{job.running ? 'Running' : job.status === 'level-cap' ? 'Level Cap Reached' : 'Paused'}</Status>}><p className="muted">Choose an item, target school, and quantity. Matching affinity gives stronger XP.</p><div className="research-config"><label>Item<select value={itemId} onChange={(event) => { setItemId(event.target.value as ItemId); setQuantity(1) }}>{RESEARCH_ITEMS.map((item) => <option key={item.itemId} value={item.itemId}>{item.label} · {inventory[item.itemId] ?? 0} available</option>)}</select></label><label>Target School<select value={schoolId} onChange={(event) => setSchoolId(event.target.value as SchoolId)}>{FRAGMENT_ORDER.map((id) => <option key={id} value={id}>{SCHOOLS[id].name}</option>)}</select></label><div className="quantity-control"><span>Quantity</span><div><button onClick={() => setQuantity(Math.max(1, quantity - 1))}>−</button><strong>{quantity}</strong><button onClick={() => setQuantity(Math.min(max, quantity + 1))}>+</button></div></div></div><div className="research-preview"><span>Selected <strong>{quantity} × {definition.name} → {SCHOOLS[schoolId].name}</strong></span><span>XP <strong>{xp} / item · {xp * quantity} total</strong></span><span>Time <strong>{formatTime(BALANCE.research.durationPerItemMs * quantity)}</strong></span></div>{job.itemId && <Progress value={job.progressMs / job.durationPerItemMs * 100} tone="violet" label={`${job.remainingQuantity} items remaining`} right={job.status} />}<div className="card-foot"><span>Reserve {job.focusCost} Focus</span><Button variant={job.running ? 'ghost' : 'secondary'} onClick={() => { if (job.running) toggle(); else { setConfig(itemId, schoolId, quantity); toggle(itemId, schoolId, quantity) } }}>{job.running ? 'Pause Research' : 'Start Research'}</Button></div></Card> }
