import { useMemo, useState } from 'react'
import { Pause, Play, ShieldCheck, Zap } from 'lucide-react'
import { BALANCE } from '../../game/data/balance'
import { ITEMS } from '../../game/data/items'
import { FRAGMENT_ORDER, RESEARCH_ITEMS, SCHOOLS } from '../../game/data/schools'
import { RECIPES } from '../../game/data/recipes'
import { selectFreeFocus, selectManaRegen, selectUsedFocus } from '../../store/selectors'
import { deriveFocusReservations } from '../../game/engine'
import { useGameStore } from '../../store/gameStore'
import type { ItemId, SchoolId } from '../../game/types'
import { formatNumber, formatTime } from '../../game/utils'
import { Button, Card, Progress, Status } from '../../components/ui'

export function TowerScreenV2() {
  const [selectedItem, setSelectedItem] = useState<ItemId>('fire-fragment')
  const [selectedSchool, setSelectedSchool] = useState<SchoolId>('fire')
  const [quantity, setQuantity] = useState(1)
  const [recipeId, setRecipeId] = useState('ember-staff')
  const player = useGameStore((state) => state.player)
  const activities = useGameStore((state) => state.activities)
  const inventory = useGameStore((state) => state.inventory)
  const progress = useGameStore((state) => state.progress)
  const channelMana = useGameStore((state) => state.channelMana)
  const toggleAutoChannel = useGameStore((state) => state.toggleAutoChannel)
  const toggleCondense = useGameStore((state) => state.toggleCondense)
  const toggleResearch = useGameStore((state) => state.toggleResearch)
  const toggleTransmutation = useGameStore((state) => state.toggleTransmutation)
  const focusUsed = useGameStore(selectUsedFocus)
  const focusFree = useGameStore(selectFreeFocus)
  const reservations = useMemo(() => deriveFocusReservations({ activities, progress }), [activities, progress])
  const manaRegen = useGameStore(selectManaRegen)
  const job = activities.research
  const selectedDefinition = ITEMS[selectedItem]
  const available = inventory[selectedItem] ?? 0
  const maxQuantity = Math.max(1, Math.min(10, available))
  const xpPerItem = selectedDefinition.researchSchool === selectedSchool ? BALANCE.research.matchingXp : BALANCE.research.nonMatchingXp
  const activeRecipe = RECIPES[recipeId]

  return <div className="screen-content">
    <div className="screen-header"><div><div className="eyebrow">ROOM 01 · WIZARD TOWER</div><h1>The tower is awake.</h1><p>Keep the tower working while the wizard fights below. Every automated room reserves Focus.</p></div><div className="focus-summary"><span>FOCUS RESERVATION</span><strong>{focusUsed} <small>/ {player.maxFocus}</small></strong><em>{focusFree} free</em></div></div>
    <div className="tower-grid">
      <Card title="Channeling Chamber" action={<Status tone="active">Passive +{manaRegen}/s</Status>}><div className="channel-visual"><div className="mana-core"><span>✦</span><i /></div><div><div className="eyebrow">CURRENT MANA</div><strong className="big-number">{formatNumber(player.mana)} <small>/ {player.maxMana}</small></strong><p className="muted">Manual channeling costs no Focus. Automation does.</p></div></div><div className="button-row"><Button onClick={channelMana} disabled={player.mana >= player.maxMana}><Zap size={16} /> Channel Mana <small>+{BALANCE.mana.manualChannelAmount}</small></Button><Button variant={activities.autoChannel ? 'success' : 'secondary'} onClick={toggleAutoChannel}>{activities.autoChannel ? <Pause size={15} /> : <Play size={15} />} {activities.autoChannel ? 'Pause Auto Channeling' : 'Enable Auto Channeling'} <small>−{BALANCE.mana.autoChannelFocus} Focus</small></Button></div><div className="info-strip"><span>Mana regeneration</span><strong>{manaRegen}/s</strong><span>Net with active drains</span><strong className="positive">{manaRegen}/s baseline</strong></div></Card>
      <Card title="Focus Allocation" action={<span className="focus-ring"><strong>{focusUsed}</strong><small>/ {player.maxFocus}</small></span>}><p className="muted">Reservations are derived from the engine. Pause an activity to release Focus immediately.</p><div className="focus-total"><span>Used</span><Progress value={focusUsed / player.maxFocus * 100} tone="violet" /><strong>{focusFree} free</strong></div><div className="reservation-list">{reservations.length ? reservations.map((reservation) => <div className="reservation" key={reservation.id}><span className="reservation-dot" /><span>{reservation.label}</span><strong>{reservation.amount}</strong></div>) : <div className="empty-state small">No automated activities are reserving Focus.</div>}</div><div className="focus-rule"><ShieldCheck size={15} /><span>Basic Attack requires <strong>0 Focus</strong>. Spell Auto-Cast costs come from each spell definition.</span></div></Card>
    </div>
    <div className="section-label">Parallel activities</div>
    <div className="tower-grid lower">
      <Card title="Elemental Condensation" action={<Status tone={activities.condense.running ? 'active' : 'neutral'}>{activities.condense.running ? 'Running' : 'Paused'}</Status>}><p className="muted">Turn Mana into fragments. One batch every {formatTime(BALANCE.condense.durationMs)}.</p><div className="element-pills">{FRAGMENT_ORDER.map((element) => <button key={element} className={`element-pill ${activities.condense.element === element ? 'selected' : ''}`} style={{ '--element-color': SCHOOLS[element].color } as React.CSSProperties} onClick={() => activities.condense.running ? toggleCondense() : toggleCondense(element)}><span>{SCHOOLS[element].glyph}</span>{SCHOOLS[element].name}<small>{inventory[SCHOOLS[element].fragment] ?? 0}</small></button>)}</div>{activities.condense.running && <Progress value={activities.condense.progressMs / BALANCE.condense.durationMs * 100} tone="orange" label={`Condensing ${SCHOOLS[activities.condense.element].name}`} right={activities.condense.progressMs >= BALANCE.condense.durationMs && player.mana < BALANCE.condense.manaCost ? 'Waiting for Mana' : formatTime(BALANCE.condense.durationMs - activities.condense.progressMs)} />}<div className="card-foot"><span>Reserve {BALANCE.condense.focusCost} Focus · spend {BALANCE.condense.manaCost} Mana / batch</span><Button variant={activities.condense.running ? 'ghost' : 'secondary'} onClick={() => toggleCondense()}>{activities.condense.running ? 'Pause' : 'Start Condensing'}</Button></div></Card>
      <Card title="Arcane Crucible" action={<Status tone={job.running ? 'active' : job.status === 'level-cap' ? 'warning' : 'neutral'}>{job.running ? job.status === 'waiting-mana' ? 'Waiting for Mana' : 'Running' : job.status === 'level-cap' ? 'Level Cap Reached' : job.status === 'completed' ? 'Completed' : 'Paused'}</Status>}><p className="muted">Choose the item, the target school, and how many fragments to process. Matching affinity gives 12 XP; other schools give 8 XP.</p><div className="research-config"><label>Item<select value={selectedItem} onChange={(event) => { const value = event.target.value as ItemId; setSelectedItem(value); setQuantity(1) }}>{RESEARCH_ITEMS.map((item) => <option key={item.itemId} value={item.itemId}>{item.label} · {inventory[item.itemId] ?? 0} available</option>)}</select></label><label>Target School<select value={selectedSchool} onChange={(event) => setSelectedSchool(event.target.value as SchoolId)}>{FRAGMENT_ORDER.map((school) => <option key={school} value={school}>{SCHOOLS[school].name}</option>)}</select></label><div className="quantity-control"><span>Quantity</span><div><button onClick={() => setQuantity(Math.max(1, quantity - 1))}>−</button><strong>{quantity}</strong><button onClick={() => setQuantity(Math.min(maxQuantity, quantity + 1))}>+</button></div><div className="quantity-presets"><button onClick={() => setQuantity(1)}>1</button><button onClick={() => setQuantity(Math.min(5, maxQuantity))}>5</button><button onClick={() => setQuantity(Math.min(10, maxQuantity))}>10</button><button onClick={() => setQuantity(maxQuantity)}>MAX</button></div></div></div><div className="research-preview"><span>Selected <strong>{quantity} × {selectedDefinition.name} → {SCHOOLS[selectedSchool].name}</strong></span><span>XP <strong>{xpPerItem} / item · {xpPerItem * quantity} total</strong></span><span>Mana <strong>{BALANCE.research.manaCostPerItem} / item · {BALANCE.research.manaCostPerItem * quantity} total over time</strong></span><span>Time <strong>{formatTime(BALANCE.research.durationPerItemMs * quantity)}</strong></span></div>{job.itemId && <Progress value={job.progressMs / job.durationPerItemMs * 100} tone="violet" label={`${job.remainingQuantity} items remaining`} right={job.status === 'level-cap' ? 'Queue preserved' : job.running ? formatTime(job.durationPerItemMs - job.progressMs) : job.status} />}<div className="card-foot"><span>Reserve {job.focusCost} Focus · item consumption is cap-safe</span><Button variant={job.running ? 'ghost' : 'secondary'} onClick={() => job.running ? toggleResearch() : toggleResearch(selectedItem, selectedSchool, quantity)}>{job.running ? 'Pause Research' : job.status === 'level-cap' ? 'Resume after cap' : 'Start Research'}</Button></div></Card>
      <Card title="Transmutation" action={<Status tone={activities.transmutation.running ? 'active' : progress.emberStaffUnlocked ? 'neutral' : 'locked'}>{activities.transmutation.running ? 'Running' : progress.emberStaffUnlocked ? 'Ready' : 'Locked'}</Status>}><label className="recipe-select">Recipe<select value={recipeId} onChange={(event) => setRecipeId(event.target.value)}>{Object.values(RECIPES).map((recipe) => <option key={recipe.id} value={recipe.id}>{recipe.name}</option>)}</select></label><div className="recipe-visual"><div className="recipe-item">{ITEMS[activeRecipe.output].icon}</div><div className="recipe-arrow">→</div><div className="recipe-item muted-item">✦</div></div><h3>{activeRecipe.name}</h3><p className="muted">One queue, four build-changing first-chapter recipes.</p><div className="cost-line">{activeRecipe.ingredients.map((ingredient) => <span key={ingredient.itemId}>{ITEMS[ingredient.itemId].name} <strong>{inventory[ingredient.itemId] ?? 0} / {ingredient.quantity}</strong></span>)}</div><Progress value={activities.transmutation.recipeId === recipeId ? activities.transmutation.progressMs / activeRecipe.durationMs * 100 : 0} tone="gold" label={activities.transmutation.running ? 'Transmuting' : `${formatTime(activeRecipe.durationMs)} recipe`} /><Button className="wide" variant={activities.transmutation.running ? 'ghost' : 'secondary'} disabled={!progress.emberStaffUnlocked} onClick={() => toggleTransmutation(recipeId)}>{activities.transmutation.running ? 'Pause Transmutation' : 'Begin Transmutation'}</Button></Card>
    </div>
  </div>
}
