import { Button, GameTooltip } from '../ui'
import { getArtifactMinorRank, getArtifactTotalInvestedRanks } from '../../game/systems/artifacts/artifactProgression'
import { ARTIFACTS } from '../../game/content/artifacts/artifacts'
import type { ArtifactId, GameState } from '../../game/types'
import { useGameStore } from '../../store/gameStore'
import { setArtifactDevPanelVisible, useDeveloperToolsStore } from '../../devtools/developerToolsStore'

export function ArtifactPathDevMiniPanel({ state, artifactId, selectedNodeId }: { state: GameState; artifactId: ArtifactId; selectedNodeId: string | null }) {
  const session = useDeveloperToolsStore(); const actions = useGameStore(); const definition = ARTIFACTS[artifactId]
  if (!session.showArtifactDevPanel || !definition) return null
  const selected = selectedNodeId ? definition.minorNodes.find((node) => node.id === selectedNodeId) : null
  const total = getArtifactTotalInvestedRanks(state, artifactId)
  return <aside className="artifact-path-dev-mini" aria-label="Artifact rank developer panel"><div className="artifact-path-dev-mini-header"><div><span className="eyebrow">DEV ONLY</span><strong>RANK CONTROL</strong></div><GameTooltip content="Hide the compact developer panel"><button type="button" className="icon-button" aria-label="Hide Artifact rank developer panel" onClick={() => setArtifactDevPanelVisible(false)}>×</button></GameTooltip></div><div className="artifact-path-dev-mini-summary"><span>RANKS {total} / {definition.minorNodes.length * 10}</span><span>{definition.majorMilestones.filter((major) => total >= major.unlockAtTotalRanks).length} MILESTONES ACTIVE</span></div>{selected && <div className="artifact-path-dev-mini-actions"><Button className="artifact-dev-mini-button" tooltip="Raise the selected Minor node by one rank." onClick={() => actions.debugAdjustArtifactMinorRank(artifactId, selected.id, 1)}>+1 RANK</Button><Button className="artifact-dev-mini-button" tooltip="Lower the selected Minor node by one rank." disabled={getArtifactMinorRank(state, artifactId, selected.id) <= 0} onClick={() => actions.debugAdjustArtifactMinorRank(artifactId, selected.id, -1)}>-1 RANK</Button><Button className="artifact-dev-mini-button" variant="secondary" tooltip="Purchase the selected rank with normal costs." onClick={() => actions.debugPurchaseArtifactRank(artifactId, selected.id, false)}>NORMAL BUY</Button><Button className="artifact-dev-mini-button" variant="primary" tooltip="Purchase the selected rank without material costs." onClick={() => actions.debugPurchaseArtifactRank(artifactId, selected.id, true)}>FREE BUY</Button><Button className="artifact-dev-mini-button" variant="secondary" tooltip="Set the selected Minor node to rank 10." onClick={() => actions.debugMaxArtifactMinorNode(artifactId, selected.id)}>MAX NODE</Button><Button className="artifact-dev-mini-button" variant="ghost" tooltip="Reset the selected Minor node to rank 0." onClick={() => actions.debugResetArtifactMinorNode(artifactId, selected.id)}>RESET NODE</Button></div>}<div className="artifact-path-dev-mini-actions"><Button className="artifact-dev-mini-button" variant="secondary" tooltip="Max every Minor node on this Artifact." onClick={() => actions.debugMaxArtifact(artifactId)}>MAX ARTIFACT</Button><Button className="artifact-dev-mini-button" variant="danger" tooltip="Reset every Minor node on this Artifact." onClick={() => actions.debugResetArtifact(artifactId)}>RESET ARTIFACT</Button></div></aside>
}
