import type { MonsterId } from '../../../types'
import { makeCombatMonster, type CombatMonsterSpec } from '../combatMonsterAuthoring'
import type { MonsterDefinition } from '../monsterTypes'

const specs: CombatMonsterSpec[] = [
  { combatV2: true, locationId: 'hall-of-unbound-names', id: 'name-eater', name: 'Name-Eater', subtitle: 'A mouth in the archive that consumes identity', hp: 4000, damage: 122, defense: 52, targetPower: 9800, primaryAffinity: 'arcane', basicAttackElement: 'arcane', resonanceYield: { air: 36, water: 24 }, specials: [{ id: 'consume-name', name: 'Consume Name', damage: [{ type: 'arcane', coefficient: 1.25 }], status: { id: 'silenced' } }, { id: 'hunger', name: 'Hunger', status: { id: 'cursed' } }] },
  { combatV2: true, locationId: 'hall-of-unbound-names', id: 'bound-echo', name: 'Bound Echo', subtitle: 'A voice caught in the hall and forced to repeat', hp: 3000, damage: 118, defense: 58, targetPower: 10300, primaryAffinity: 'air', basicAttackElement: 'air', resonanceYield: { air: 40, water: 20 }, specials: [{ id: 'echo-strike', name: 'Echo Strike', damage: [{ type: 'air', coefficient: .65 }, { type: 'arcane', coefficient: .65 }] }, { id: 'repeat', name: 'Repeat', status: { id: 'haste', target: 'self' } }] },
  { combatV2: true, locationId: 'hall-of-unbound-names', id: 'hollow-liturgist', name: 'Hollow Liturgist', subtitle: 'A priest conducting a rite with no congregation', hp: 4250, damage: 120, defense: 60, targetPower: 10800, primaryAffinity: 'water', basicAttackElement: 'water', resonanceYield: { water: 42, air: 24 }, icon: { portraitIcon: 'mage' }, specials: [{ id: 'nameless-litany', name: 'Nameless Litany', status: { id: 'cursed' } }, { id: 'litany-flare', name: 'Litany Flare', damage: [{ type: 'water', coefficient: .725 }, { type: 'arcane', coefficient: .725 }] }] },
  { combatV2: true, locationId: 'hall-of-unbound-names', id: 'whisper-archivist', name: 'Whisper Archivist', subtitle: 'A keeper erasing formulas faster than they can be read', hp: 4375, damage: 125, defense: 48, targetPower: 11300, primaryAffinity: 'air', basicAttackElement: 'air', resonanceYield: { air: 46, water: 28 }, specials: [{ id: 'erased-formula', name: 'Erased Formula', damage: [{ type: 'air', coefficient: .6 }, { type: 'arcane', coefficient: .6 }], status: { id: 'arcane-disruption' } }, { id: 'catalogue', name: 'Catalogue', status: { id: 'haste', target: 'self' } }] },
  { combatV2: true, locationId: 'hall-of-unbound-names', id: 'nameless-cantor', name: 'Nameless Cantor', subtitle: 'A hard silence-caster whose stolen verses linger', hp: 4700, damage: 130, defense: 56, time: 2400, targetPower: 11900, primaryAffinity: 'water', basicAttackElement: 'water', resonanceYield: { water: 50, air: 32 }, icon: { portraitIcon: 'mage' }, specials: [{ id: 'stolen-verse', name: 'Stolen Verse', damage: [{ type: 'water', coefficient: .7 }, { type: 'arcane', coefficient: .7 }], status: { id: 'cursed' } }, { id: 'quiet-refrain', name: 'Quiet Refrain', damage: [{ type: 'arcane', coefficient: 1.1 }], status: { id: 'silenced' } }] },
  { combatV2: true, locationId: 'hall-of-unbound-names', id: 'oathless-confessor', name: 'Oathless Confessor', subtitle: 'A debuff-caster turning confession into pressure', hp: 5400, damage: 136, defense: 64, time: 2500, targetPower: 12600, primaryAffinity: 'water', basicAttackElement: 'water', resonanceYield: { water: 58, air: 36 }, icon: { portraitIcon: 'mage' }, specials: [{ id: 'broken-oath', name: 'Broken Oath', damage: [{ type: 'water', coefficient: .7 }, { type: 'arcane', coefficient: .7 }], status: { id: 'silenced' } }, { id: 'confession-of-ruin', name: 'Confession of Ruin', damage: [{ type: 'arcane', coefficient: 1.35 }], status: { id: 'arcane-disruption' } }] },
  { combatV2: true, locationId: 'hall-of-unbound-names', id: 'unwritten-hierophant', name: 'Unwritten Hierophant', subtitle: 'A heavy Arcane caster reciting laws that never existed', hp: 5100, damage: 142, defense: 60, time: 2350, targetPower: 13300, primaryAffinity: 'arcane', basicAttackElement: 'arcane', resonanceYield: { air: 68, water: 42 }, specials: [{ id: 'unwritten-law', name: 'Unwritten Law', damage: [{ type: 'arcane', coefficient: 1.75 }], status: { id: 'cursed' } }, { id: 'unbound-recital', name: 'Unbound Recital', status: { id: 'haste', target: 'self' } }] },
  { combatV2: true, locationId: 'hall-of-unbound-names', id: 'unspoken-prelate', name: 'Unspoken Prelate', subtitle: 'The hall’s highest voice, made terrifying by silence', hp: 42000, damage: 145, defense: 88, targetPower: 15500, primaryAffinity: 'arcane', basicAttackElement: 'arcane', resistances: { arcane: .2 }, resonanceYield: { air: 100, water: 100 }, boss: true, specials: [{ id: 'unspoken-word', name: 'Unspoken Word', status: { id: 'silenced' } }, { id: 'litany-loss', name: 'Litany Loss', status: { id: 'cursed' } }, { id: 'erasure', name: 'Erasure', damage: [{ type: 'arcane', coefficient: 1.55 }] }, { id: 'whispering-flood', name: 'Whispering Flood', damage: [{ type: 'water', coefficient: 1.35 }], status: { id: 'arcane-disruption' } }, { id: 'voiceless-gale', name: 'Voiceless Gale', damage: [{ type: 'air', coefficient: 1.35 }] }, { id: 'nameless-judgment', name: 'Nameless Judgment', actionTimeMs: 3200, damage: [{ type: 'arcane', coefficient: 2.35 }] }, { id: 'binding-silence', name: 'Binding Silence', damage: [{ type: 'arcane', coefficient: .8 }], status: { id: 'silenced' } }], patternSteps: [{ id: 'prelate-word', type: 'action', actionId: 'unspoken-word' }, { id: 'prelate-basic-1', type: 'basic' }, { id: 'prelate-erasure', type: 'action', actionId: 'erasure' }, { id: 'prelate-basic-2', type: 'basic' }, { id: 'prelate-litany', type: 'action', actionId: 'litany-loss' }, { id: 'prelate-basic-3', type: 'basic' }, { id: 'prelate-flood', type: 'action', actionId: 'whispering-flood' }, { id: 'prelate-basic-4', type: 'basic' }, { id: 'prelate-gale', type: 'action', actionId: 'voiceless-gale' }, { id: 'prelate-basic-5', type: 'basic' }, { id: 'prelate-judgment', type: 'action', actionId: 'nameless-judgment' }, { id: 'prelate-basic-6', type: 'basic' }, { id: 'prelate-binding', type: 'action', actionId: 'binding-silence' }] },
]

export const HALL_OF_UNBOUND_NAMES_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeCombatMonster(spec)])) as Record<MonsterId, MonsterDefinition>
