import type { ArtifactId, EquipmentStats, ItemDefinition, ItemId } from '../../types'
import type { CombatModifier, CombatTriggerRule, DamageType } from '../../systems/combat/combatTypes'
import type { ResonanceType } from '../resonance/resonance'
import { createCombatValidationContext, validateCombatProvider } from '../../systems/combat/combatEffectValidation'
import { STATUS_DEFINITIONS } from '../statuses/statuses'

export interface ArtifactForgeDefinition { ingredients: { itemId: ItemId; quantity: number }[] }
export interface ArtifactRankCost {
  artifactEssence: number
  fragment?: { itemId: ItemId; quantity: number }
  prismaticFragment?: number
  resonance: Partial<Record<ResonanceType, number>>
}
export type ArtifactSpecialEffect =
  | { type: 'heal-on-hp-threshold'; threshold: number; maxHealthPercent: number }
  | { type: 'damage-taken-while-barrier'; reduction: number }
  | { type: 'critical-next-cooldown'; school: DamageType; reduction: number }
  | { type: 'lethal-barrier'; barrierMaxHealthPercent: number }
  | { type: 'barrier-break'; barrierMaxHealthPercent: number; cooldownMs: number }
  | { type: 'barrier-gain-mana'; maxHealthPercent: number; cooldownMs: number }
  | { type: 'hp-threshold-barrier-status-immunity'; threshold: number; barrierMaxHealthPercent: number; durationMs: number }
  | { type: 'nth-spell-mana-refund'; every: number; manaPercent: number }
  | { type: 'mana-band-shift'; manaReduction: number; cooldownMs: number }
  | { type: 'first-spell-after-idle'; damageIncrease: number; idleMs: number }
  | { type: 'air-spell-repeat'; every: number; effectiveness: number }
  | { type: 'burn-refresh-detonation'; damagePercent: number }
  | { type: 'after-heal-water-damage'; damageIncrease: number }
  | { type: 'critical-air-damage'; damagePercent: number }
export interface ArtifactResolvedEffects { stats?: EquipmentStats; combat?: { modifiers?: CombatModifier[]; rules?: CombatTriggerRule[] }; special?: ArtifactSpecialEffect[] }
export interface ArtifactMinorNodeDefinition { id: string; name: string; description: string; maxRank: 10; rankCosts: readonly ArtifactRankCost[]; rankEffects: readonly ArtifactResolvedEffects[] }
export interface ArtifactMajorMilestoneDefinition { id: string; name: string; unlockAtTotalRanks: number; effects: ArtifactResolvedEffects }
export interface ArtifactDefinition { id: ArtifactId; itemId: ArtifactId; tier: number; forge: ArtifactForgeDefinition; baseline: ArtifactResolvedEffects; minorNodes: readonly ArtifactMinorNodeDefinition[]; majorMilestones: readonly ArtifactMajorMilestoneDefinition[] }

const material = (itemId: ItemId, quantity: number) => ({ itemId, quantity })
const act0WeaponCosts = [[15, 50, 50], [25, 80, 100], [40, 120, 150], [60, 170, 225], [90, 240, 350], [130, 330, 500], [185, 450, 685], [260, 600, 885], [360, 800, 1125], [500, 1050, 1500]] as const
const act0PrismaticCosts = [[15, 5, 35], [25, 8, 70], [40, 12, 105], [60, 17, 160], [90, 24, 250], [130, 33, 360], [185, 45, 500], [260, 60, 650], [360, 80, 825], [500, 105, 1100]] as const
const act1WeaponCosts = [[25, 100, 100], [40, 160, 200], [65, 240, 300], [100, 350, 450], [150, 500, 700], [225, 700, 1000], [320, 950, 1370], [450, 1250, 1770], [650, 1650, 2250], [900, 2200, 3000]] as const
const act1PrismaticCosts = [[25, 8, 30], [40, 12, 60], [65, 18, 90], [100, 26, 140], [150, 36, 220], [225, 50, 320], [320, 68, 440], [450, 90, 570], [650, 120, 725], [900, 160, 950]] as const
const resonanceBundle = (types: readonly ResonanceType[], amount: number) => Object.fromEntries(types.map((type) => [type, amount])) as Partial<Record<ResonanceType, number>>
const weaponCost = (table: readonly (readonly [number, number, number])[], fragment: ItemId, resonance: ResonanceType) => table.map(([artifactEssence, fragmentQuantity, resonanceAmount]) => ({ artifactEssence, fragment: material(fragment, fragmentQuantity), resonance: { [resonance]: resonanceAmount } }))
const prismaticCost = (table: readonly (readonly [number, number, number])[], resonanceTypes: readonly ResonanceType[]) => table.map(([artifactEssence, fragment, resonance]) => ({ artifactEssence, prismaticFragment: fragment, resonance: resonanceBundle(resonanceTypes, resonance) }))
const effect = (stats?: EquipmentStats, modifiers?: CombatModifier[], special?: ArtifactSpecialEffect[], rules?: CombatTriggerRule[]): ArtifactResolvedEffects => ({ ...(stats ? { stats } : {}), ...(modifiers?.length || rules?.length ? { combat: { ...(modifiers?.length ? { modifiers } : {}), ...(rules?.length ? { rules } : {}) } } : {}), ...(special?.length ? { special } : {}) })
const pct = (values: readonly number[]) => values.map((value) => value / 100)
const act0Spell = [0.75, 0.75, 1, 1.25, 1.5, 1.75, 2, 2.5, 3, 3.75]
const act1Spell = [1.25, 1.5, 1.75, 2, 2.5, 3, 3.75, 4.5, 5.5, 7]
const act0Damage = pct([0.25, 0.5, 0.5, 0.75, 0.75, 1, 1.25, 1.5, 1.75, 2])
const act1Damage = pct([0.5, 0.75, 0.75, 1, 1.25, 1.5, 1.75, 2.25, 2.75, 3.5])
const act0Duration = pct([0.5, 0.5, 0.5, 0.75, 0.75, 0.75, 1, 1, 1.25, 1.5])
const act1Duration = pct([0.5, 0.75, 0.75, 1, 1, 1.25, 1.5, 1.75, 2, 2.5])
const act0Mana = [0.5, 0.75, 1, 1.25, 1.5, 2, 2.5, 3, 3.75, 5]
const act1Mana = [1.25, 1.5, 2, 2.5, 3, 3.75, 5, 6.25, 7.5, 10]
const act0Defense = [0.25, 0.25, 0.25, 0.5, 0.5, 0.75, 0.75, 1, 1.25, 1.5]
const act1Defense = [0.5, 0.5, 0.75, 0.75, 1, 1.25, 1.5, 2, 2.5, 3]
const act0Health = [1.25, 1.25, 2, 2.5, 3, 3.75, 5, 6.25, 7.5, 10]
const act1Health = [2.5, 3, 3.75, 5, 6.25, 8.75, 11.25, 15, 20, 27.5]
const act0Crit = pct([0.0625, 0.0625, 0.125, 0.125, 0.1875, 0.1875, 0.25, 0.3125, 0.375, 0.5])
const act1Crit = pct([0.125, 0.125, 0.1875, 0.1875, 0.25, 0.3125, 0.375, 0.4375, 0.5625, 0.75])
const act0CritDamage = pct([0.25, 0.25, 0.5, 0.5, 0.75, 0.75, 1, 1.25, 1.5, 2])
const act1CritDamage = pct([0.5, 0.5, 0.75, 0.75, 1, 1.25, 1.5, 1.75, 2, 2.5])
const act0Cooldown = pct([0.0625, 0.125, 0.1875, 0.25, 0.3125, 0.375, 0.4375, 0.5, 0.625, 0.75])
const act1Cooldown = pct([0.125, 0.1875, 0.25, 0.3125, 0.375, 0.4375, 0.5, 0.625, 0.75, 1])
const act0Resistance = pct([0.0625, 0.0625, 0.125, 0.125, 0.1875, 0.1875, 0.25, 0.25, 0.3125, 0.375])
const act1Resistance = pct([0.125, 0.125, 0.1875, 0.1875, 0.25, 0.3125, 0.375, 0.5, 0.625, 0.75])
const act1Reduction = pct([0.0625, 0.0625, 0.125, 0.125, 0.1875, 0.1875, 0.25, 0.3125, 0.375, 0.5])
const act1ManaEfficiency = pct([0.0625, 0.125, 0.125, 0.1875, 0.25, 0.3125, 0.375, 0.5, 0.625, 0.875])
const direct = (school: DamageType, values: readonly number[]) => values.map((value) => effect(undefined, [{ key: 'spell-damage-percent', value, originSourceKinds: ['spell'], damageTypes: [school], sourceTags: ['direct'] }]))
const statRanks = (key: keyof EquipmentStats, values: readonly number[]) => values.map((value) => effect({ [key]: value } as EquipmentStats))
const resistanceRanks = (school: DamageType, values: readonly number[]) => values.map((value) => effect(undefined, [{ key: 'resistance-percent', value: -value, originSourceKinds: ['spell'], damageTypes: [school] }]))
const allResistanceRanks = (values: readonly number[]) => values.map((value) => effect({ resistances: { fire: value, water: value, earth: value, air: value } }))
const castTimeRanks = (school: ResonanceType, values: readonly number[]) => values.map((value) => effect(undefined, [{ key: 'spell-cast-time-percent', value: -value, originSourceKinds: ['spell'], sourceTags: ['spell', school] }]))
const minor = (id: string, name: string, description: string, costs: readonly ArtifactRankCost[], rankEffects: readonly ArtifactResolvedEffects[]): ArtifactMinorNodeDefinition => ({ id, name, description, maxRank: 10, rankCosts: costs, rankEffects })
const majors = (entries: readonly [string, string, number, ArtifactResolvedEffects][]): ArtifactMajorMilestoneDefinition[] => entries.map(([id, name, unlockAtTotalRanks, effects]) => ({ id, name, unlockAtTotalRanks, effects }))
const weaponRanks = (table: readonly (readonly [number, number, number])[], fragment: ItemId, resonance: ResonanceType) => weaponCost(table, fragment, resonance)
const armorRanks = (table: readonly (readonly [number, number, number])[], types: readonly ResonanceType[]) => prismaticCost(table, types)
const forge = (fragment: ItemId, quantity = 20, essence = 20): ArtifactForgeDefinition => ({ ingredients: [material(fragment, quantity), material('artifact-essence', essence)] })
const two = (a: ResonanceType, b: ResonanceType) => [a, b] as const
const four = ['fire', 'water', 'earth', 'air'] as const
const fire = 'fire' as const
const water = 'water' as const
const earth = 'earth' as const
const air = 'air' as const
const act0Elemental = (id: ArtifactId, baseline: EquipmentStats, fragment: ItemId, nodes: ArtifactMinorNodeDefinition[], majorMilestones: ArtifactMajorMilestoneDefinition[]) => ({ id, itemId: id, tier: 1, forge: forge(fragment), baseline: effect(baseline), minorNodes: nodes, majorMilestones }) satisfies ArtifactDefinition
const act1Elemental = (id: ArtifactId, baseline: EquipmentStats, fragment: ItemId, nodes: ArtifactMinorNodeDefinition[], majorMilestones: ArtifactMajorMilestoneDefinition[]) => ({ id, itemId: id, tier: 2, forge: forge(fragment, 40, 80), baseline: effect(baseline), minorNodes: nodes, majorMilestones }) satisfies ArtifactDefinition
const prismatic = (id: ArtifactId, tier: number, baseline: EquipmentStats, nodes: ArtifactMinorNodeDefinition[], majorMilestones: ArtifactMajorMilestoneDefinition[]) => ({ id, itemId: id, tier, forge: forge('prismatic-fragment', tier === 1 ? 5 : 40, tier === 1 ? 20 : 80), baseline: effect(baseline), minorNodes: nodes, majorMilestones }) satisfies ArtifactDefinition

const emberCosts = weaponRanks(act0WeaponCosts, 'fire-fragment', fire)
const emberNodes = [minor('arcane-embers', 'Arcane Embers', 'Spell Power', emberCosts, statRanks('spellPower', act0Spell)), minor('lingering-flame', 'Lingering Flame', 'Burn Duration', emberCosts, statRanks('statusDurationPct', act0Duration)), minor('feeding-fire', 'Feeding Fire', 'Burn Damage', emberCosts, statRanks('damageOverTimePct', pct([0.5, 0.5, 0.75, 0.75, 1, 1, 1.25, 1.25, 1.5, 1.75]))), minor('flame-impact', 'Flame Impact', 'Direct Fire Spell Damage', emberCosts, direct(fire, act0Damage)), minor('quickkindle', 'Cinder Precision', 'Spell Critical Chance', emberCosts, statRanks('critChance', pct([0.25, 0.25, 0.50, 0.50, 0.75, 0.75, 1.00, 1.00, 1.25, 1.25])))]
const emberMajors = majors([['kindle-sigil', 'Kindle Sigil', 10, effect({ spellPower: 3.75, statusDurationPct: 0.0125 })], ['heartfire-seal', 'Heartfire Seal', 20, effect({ spellPower: 5, damageOverTimePct: 0.025 })], ['furnace-core', 'Furnace Core', 30, effect({ spellPower: 6.25, statusDurationPct: 0.025 })], ['blackflame-crest', 'Blackflame Crest', 40, effect({ spellPower: 7.5, cooldownRecoveryPct: 0.0125 }, [{ key: 'spell-damage-percent', value: 0.025, originSourceKinds: ['spell'], damageTypes: [fire], sourceTags: ['direct'] }])], ['edrins-inferno', "Edrin's Inferno", 50, effect({ spellPower: 11.25, damageOverTimePct: 0.0375 }, [{ key: 'spell-damage-percent', value: 0.025, originSourceKinds: ['spell'], damageTypes: [fire], sourceTags: ['direct'] }])]])
const tideCosts = weaponRanks(act0WeaponCosts, 'water-fragment', water)
const tideNodes = [minor('arcane-current', 'Arcane Current', 'Spell Power', tideCosts, statRanks('spellPower', act0Spell)), minor('deep-reservoir', 'Deep Reservoir', 'Maximum Mana', tideCosts, statRanks('maxMana', act0Mana)), minor('mending-current', 'Mending Current', 'Healing Done', tideCosts, statRanks('healingDonePct', pct([0.25, 0.5, 0.5, 0.75, 0.75, 1, 1.25, 1.5, 1.75, 2]))), minor('frosted-surge', 'Frosted Surge', 'Direct Water Spell Damage', tideCosts, direct(water, act0Damage)), minor('lingering-chill', 'Lingering Chill', 'Chilled Duration', tideCosts, statRanks('statusDurationPct', act0Duration))]
const tideMajors = majors([['tideglass-sigil', 'Tideglass Sigil', 10, effect({ spellPower: 3.75, maxMana: 2.5 })], ['deepwater-seal', 'Deepwater Seal', 20, effect({ spellPower: 5, healingDonePct: 0.025 })], ['frozen-grace', 'Frozen Grace', 30, effect({ spellPower: 6.25, statusDurationPct: 0.025 })], ['abyssal-current', 'Abyssal Current', 40, effect({ spellPower: 7.5, maxMana: 3.75 }, [{ key: 'spell-damage-percent', value: 0.025, originSourceKinds: ['spell'], damageTypes: [water], sourceTags: ['direct'] }])], ['edrins-tidal-grace', "Edrin's Tidal Grace", 50, effect({ spellPower: 11.25, healingDonePct: 0.0375 }, undefined, undefined, [{ id: 'artifact-tidal-grace', event: 'on-hp-threshold', condition: { type: 'self-hp-below-percent', percent: 35 }, effects: [{ type: 'heal', target: 'self', magnitude: { type: 'source-max-health-percent', value: 0.05 } }], oncePerEncounter: true }])]])
const stoneCosts = weaponRanks(act0WeaponCosts, 'earth-fragment', earth)
const stoneNodes = [minor('stonebound-arcana', 'Stonebound Arcana', 'Spell Power', stoneCosts, statRanks('spellPower', act0Spell)), minor('earthen-force', 'Earthen Force', 'Direct Earth Spell Damage', stoneCosts, direct(earth, act0Damage)), minor('granite-skin', 'Granite Skin', 'Defense', stoneCosts, statRanks('defense', act0Defense)), minor('living-bulwark', 'Living Bulwark', 'Barrier Power', stoneCosts, statRanks('barrierPowerPct', act0Damage)), minor('rooted-vitality', 'Rooted Vitality', 'Maximum Health', stoneCosts, statRanks('maxHealth', act0Health))]
const stoneMajors = majors([['stone-sigil', 'Stone Sigil', 10, effect({ spellPower: 3.75, defense: 0.75 })], ['deepcore-seal', 'Deepcore Seal', 20, effect({ spellPower: 5, maxHealth: 7.5 })], ['mountain-heart', 'Mountain Heart', 30, effect({ spellPower: 6.25, barrierPowerPct: 0.025 })], ['colossus-ward', 'Colossus Ward', 40, effect({ spellPower: 7.5, defense: 1.25 }, [{ key: 'spell-damage-percent', value: 0.025, originSourceKinds: ['spell'], damageTypes: [earth], sourceTags: ['direct'] }])], ['edrins-worldstone', "Edrin's Worldstone", 50, effect({ spellPower: 11.25, maxHealth: 15, barrierPowerPct: 0.0375 }, [{ key: 'damage-taken-percent', value: -0.02, condition: { type: 'self-has-barrier' } }])]])
const windCosts = weaponRanks(act0WeaponCosts, 'air-fragment', air)
const windNodes = [minor('arcane-draft', 'Arcane Draft', 'Spell Power', windCosts, statRanks('spellPower', act0Spell)), minor('razorwind', 'Razorwind', 'Direct Air Spell Damage', windCosts, direct(air, act0Damage)), minor('eye-of-the-gale', 'Eye of the Gale', 'Spell Critical Chance', windCosts, statRanks('critChance', act0Crit)), minor('storm-edge', 'Storm Edge', 'Spell Critical Damage', windCosts, statRanks('critDamage', act0CritDamage)), minor('windstep', 'Windstep', 'Air Spell Cooldown Time', windCosts, statRanks('cooldownRecoveryPct', act0Cooldown))]
const windMajors = majors([['gale-sigil', 'Gale Sigil', 10, effect({ spellPower: 3.75, critChance: 0.00375 })], ['storm-focus', 'Storm Precision', 20, effect({ spellPower: 5, critDamage: 0.02 })], ['tempest-rhythm', 'Tempest Rhythm', 30, effect({ spellPower: 6.25, cooldownRecoveryPct: 0.0075 })], ['skybreaker-crest', 'Skybreaker Crest', 40, effect({ spellPower: 7.5, critChance: 0.005 }, [{ key: 'spell-damage-percent', value: 0.025, originSourceKinds: ['spell'], damageTypes: [air], sourceTags: ['direct'] }])], ['edrins-tempest', "Edrin's Tempest", 50, effect({ spellPower: 11.25, critDamage: 0.03 }, [{ key: 'spell-damage-percent', value: 0.0375, originSourceKinds: ['spell'], damageTypes: [air], sourceTags: ['direct'] }, { key: 'cooldown-recovery-percent', value: 0.025, originSourceKinds: ['spell'], damageTypes: [air] }], [{ type: 'critical-next-cooldown', school: air, reduction: 0.025 }])]])

const wispweaveCosts = armorRanks(act0PrismaticCosts, two(earth, water))
const wispweaveNodes = [minor('spiritwoven-vitality', 'Spiritwoven Vitality', 'Maximum Health', wispweaveCosts, statRanks('maxHealth', act0Health)), minor('wispguard-weave', 'Wispguard Weave', 'Defense', armorRanks(act0PrismaticCosts, two(earth, fire)), statRanks('defense', act0Defense)), minor('arcane-mesh', 'Arcane Mesh', 'Barrier Power', armorRanks(act0PrismaticCosts, two(water, earth)), statRanks('barrierPowerPct', act0Damage)), minor('deep-thread', 'Deep Thread', 'Maximum Mana', armorRanks(act0PrismaticCosts, two(water, air)), statRanks('maxMana', act0Mana)), minor('elemental-weave', 'Elemental Weave', 'All Element Resistance', armorRanks(act0PrismaticCosts, two(fire, air)), allResistanceRanks(act0Resistance))]
const wispweaveMajors = majors([['wisp-knot', 'Wisp Knot', 10, effect({ maxHealth: 10, defense: 0.75 })], ['spirit-mantle', 'Spirit Mantle', 20, effect({ maxHealth: 15, barrierPowerPct: 0.025 })], ['arcane-loom', 'Arcane Loom', 30, effect({ maxHealth: 20, maxMana: 5 })], ['deathless-weave', 'Deathless Weave', 40, effect({ maxHealth: 25, defense: 1.25, resistances: { fire: 0.0075, water: 0.0075, earth: 0.0075, air: 0.0075 } })], ['edrins-ghostweave', "Edrin's Ghostweave", 50, effect({ maxHealth: 37.5, defense: 2, barrierPowerPct: 0.0375 }, undefined, [{ type: 'lethal-barrier', barrierMaxHealthPercent: 0.05 }])]])
const wispveilCosts = armorRanks(act0PrismaticCosts, two(fire, air))
const wispveilNodes = [minor('veiled-intellect', 'Veiled Intellect', 'Spell Power', wispveilCosts, statRanks('spellPower', act0Spell)), minor('spirit-reservoir', 'Spirit Reservoir', 'Maximum Mana', armorRanks(act0PrismaticCosts, two(water, air)), statRanks('maxMana', act0Mana)), minor('arcane-precision', 'Arcane Precision', 'Spell Critical Chance', wispveilCosts, statRanks('critChance', act0Crit)), minor('veil-tempo', 'Veil Tempo', 'Spell Cooldown Time', armorRanks(act0PrismaticCosts, two(air, water)), statRanks('cooldownRecoveryPct', act0Cooldown)), minor('wisp-clarity', 'Wisp Clarity', 'Spell Status Duration', armorRanks(act0PrismaticCosts, two(water, earth)), statRanks('statusDurationPct', pct([0.25, 0.25, 0.5, 0.5, 0.75, 0.75, 1, 1, 1.25, 1.5])))]
const wispveilMajors = majors([['wispmark', 'Wispmark', 10, effect({ spellPower: 3.75, maxMana: 2.5 })], ['thought-veil', 'Thought Veil', 20, effect({ spellPower: 5, critChance: 0.00375 })], ['arcane-sight', 'Arcane Sight', 30, effect({ spellPower: 6.25, statusDurationPct: 0.0125 })], ['phantom-tempo', 'Phantom Tempo', 40, effect({ spellPower: 7.5, cooldownRecoveryPct: 0.0075, maxMana: 3.75 })], ['edrins-veil', "Edrin's Veil", 50, effect({ spellPower: 11.25, critChance: 0.005, statusDurationPct: 0.02 }, undefined, [{ type: 'first-spell-after-idle', damageIncrease: 0.05, idleMs: 5000 }])]])

const act1Weapon = (id: ArtifactId, baseline: EquipmentStats, fragment: ItemId, school: ResonanceType, nodes: ArtifactMinorNodeDefinition[], milestoneData: readonly [string, string, number, ArtifactResolvedEffects][]) => act1Elemental(id, baseline, fragment, nodes, majors(milestoneData))
const galeshardCosts = weaponRanks(act1WeaponCosts, 'air-fragment', air)
const galeshard = act1Weapon('galeshard-staff', { spellPower: 245, critChance: 0.04 }, 'air-fragment', air, [minor('fractured-arcana', 'Fractured Arcana', 'Spell Power', galeshardCosts, statRanks('spellPower', act1Spell)), minor('razorstorm', 'Razorstorm', 'Direct Air Spell Damage', galeshardCosts, direct(air, act1Damage)), minor('storm-eye', 'Storm Eye', 'Spell Critical Chance', galeshardCosts, statRanks('critChance', act1Crit)), minor('shatter-edge', 'Shatter Edge', 'Spell Critical Damage', galeshardCosts, statRanks('critDamage', act1CritDamage)), minor('gale-tempo', 'Gale Tempo', 'Air Spell Cooldown Time', galeshardCosts, statRanks('cooldownRecoveryPct', act1Cooldown)), minor('pressure-break', 'Pressure Break', 'Air Resistance Ignored', galeshardCosts, resistanceRanks(air, act1Resistance))], [['gatewind-sigil', 'Gatewind Sigil', 10, effect({ spellPower: 7.5, critChance: 0.005 })], ['shardstorm-seal', 'Shardstorm Seal', 20, effect({ spellPower: 10, critDamage: 0.025 })], ['tempest-core', 'Tempest Core', 30, effect({ spellPower: 13.75, cooldownRecoveryPct: 0.0125 })], ['meridian-break', 'Meridian Break', 40, effect({ spellPower: 17.5 }, [{ key: 'spell-damage-percent', value: 0.0375, originSourceKinds: ['spell'], damageTypes: [air], sourceTags: ['direct'] }])], ['skyfracture-crown', 'Skyfracture Crown', 50, effect({ spellPower: 22.5, critChance: 0.01, critDamage: 0.0375 }, undefined, [{ type: 'critical-air-damage', damagePercent: 0.0375 }])], ['eye-of-the-gale-major', 'Eye of the Gale', 60, effect({ spellPower: 30, cooldownRecoveryPct: 0.01875 }, [{ key: 'spell-damage-percent', value: 0.05, originSourceKinds: ['spell'], damageTypes: [air], sourceTags: ['direct'] }], [{ type: 'air-spell-repeat', every: 5, effectiveness: 0.1 }])]])
const reliquaryCosts = weaponRanks(act1WeaponCosts, 'water-fragment', water)
const reliquary = act1Weapon('reliquary-scepter', { spellPower: 235, maxMana: 60, healingDonePct: 0.1 }, 'water-fragment', water, [minor('drowned-arcana', 'Drowned Arcana', 'Spell Power', reliquaryCosts, statRanks('spellPower', act1Spell)), minor('reliquary-current', 'Reliquary Current', 'Direct Water Spell Damage', reliquaryCosts, direct(water, act1Damage)), minor('drowned-grace', 'Drowned Grace', 'Healing Done', reliquaryCosts, statRanks('healingDonePct', act1Damage)), minor('deep-reservoir-act1', 'Deep Reservoir', 'Maximum Mana', reliquaryCosts, statRanks('maxMana', act1Mana)), minor('frozen-memory', 'Frozen Memory', 'Chilled Duration', reliquaryCosts, statRanks('statusDurationPct', act1Duration)), minor('cold-tempo', 'Cold Tempo', 'Water Spell Cast Time', reliquaryCosts, castTimeRanks(water, act1Cooldown))], [['drowned-sigil', 'Drowned Sigil', 10, effect({ spellPower: 7.5, maxMana: 5 })], ['reliquary-seal', 'Reliquary Seal', 20, effect({ spellPower: 10, healingDonePct: 0.03 })], ['undertow-grace', 'Undertow Grace', 30, effect({ spellPower: 13.75, statusDurationPct: 0.03 })], ['abyssal-reliquary', 'Abyssal Reliquary', 40, effect({ spellPower: 17.5, maxMana: 7.5 }, [{ key: 'spell-damage-percent', value: 0.0375, originSourceKinds: ['spell'], damageTypes: [water], sourceTags: ['direct'] }])], ['frozen-benediction', 'Frozen Benediction', 50, effect({ spellPower: 22.5, healingDonePct: 0.045, cooldownRecoveryPct: 0.0125 }, undefined, [{ type: 'after-heal-water-damage', damageIncrease: 0.05 }])], ['crown-of-the-deep', 'Crown of the Deep', 60, effect({ spellPower: 30, maxMana: 15, healingDonePct: 0.0625 }, [{ key: 'spell-damage-percent', value: 0.05, originSourceKinds: ['spell'], damageTypes: [water], sourceTags: ['direct'] }], undefined, [{ id: 'artifact-crown-deep', event: 'on-hp-threshold', condition: { type: 'self-hp-below-percent', percent: 35 }, effects: [{ type: 'heal', target: 'self', magnitude: { type: 'source-max-health-percent', value: 0.075 } }, { type: 'restore-resource', target: 'self', resource: 'mana', magnitude: { type: 'source-max-mana-percent', value: 0.0375 } }], oncePerEncounter: true }])]])
const pyreCosts = weaponRanks(act1WeaponCosts, 'fire-fragment', fire)
const pyrebound = act1Weapon('pyrebound-staff', { spellPower: 240, damageOverTimePct: 0.1 }, 'fire-fragment', fire, [minor('pyre-arcana', 'Pyre Arcana', 'Spell Power', pyreCosts, statRanks('spellPower', act1Spell)), minor('bound-flame', 'Bound Flame', 'Burn Damage', pyreCosts, statRanks('damageOverTimePct', pct([0.75, 0.75, 1, 1, 1.25, 1.5, 1.75, 2, 2.5, 3.25]))), minor('ashen-memory', 'Ashen Memory', 'Burn Duration', pyreCosts, statRanks('statusDurationPct', act1Duration)), minor('watchfire-impact', 'Watchfire Impact', 'Direct Fire Spell Damage', pyreCosts, direct(fire, act1Damage)), minor('cinder-tempo', 'Pyre Precision', 'Spell Critical Chance', pyreCosts, statRanks('critChance', pct([0.25, 0.50, 0.50, 0.75, 0.75, 1.00, 1.25, 1.50, 1.50, 2.00]))), minor('scorching-depth', 'Scorching Depth', 'Fire Resistance Ignored', pyreCosts, resistanceRanks(fire, act1Resistance))], [['watchfire-sigil', 'Watchfire Sigil', 10, effect({ spellPower: 7.5, damageOverTimePct: 0.03 })], ['pyre-seal', 'Pyre Seal', 20, effect({ spellPower: 10, statusDurationPct: 0.03 })], ['ashen-furnace', 'Ashen Furnace', 30, effect({ spellPower: 13.75, damageOverTimePct: 0.045 })], ['revenant-flame', 'Revenant Flame', 40, effect({ spellPower: 17.5 }, [{ key: 'spell-damage-percent', value: 0.0375, originSourceKinds: ['spell'], damageTypes: [fire], sourceTags: ['direct'] }])], ['black-pyre', 'Black Pyre', 50, effect({ spellPower: 22.5, damageOverTimePct: 0.055, cooldownRecoveryPct: 0.0125 }, undefined, [{ type: 'burn-refresh-detonation', damagePercent: 0.0375 }])], ['pyrebound-inferno', 'Pyrebound Inferno', 60, effect({ spellPower: 30, damageOverTimePct: 0.075 }, [{ key: 'spell-damage-percent', value: 0.05, originSourceKinds: ['spell'], damageTypes: [fire], sourceTags: ['direct'] }], [{ type: 'burn-refresh-detonation', damagePercent: 0.0625 }])]])
const rootCosts = weaponRanks(act1WeaponCosts, 'earth-fragment', earth)
const rootheart = act1Weapon('rootheart-scepter', { spellPower: 230, defense: 50, maxHealth: 150, barrierPowerPct: 0.1 }, 'earth-fragment', earth, [minor('rooted-arcana', 'Rooted Arcana', 'Spell Power', rootCosts, statRanks('spellPower', act1Spell)), minor('earthen-pulse', 'Earthen Pulse', 'Direct Earth Spell Damage', rootCosts, direct(earth, act1Damage)), minor('barkbound-guard', 'Barkbound Guard', 'Defense', rootCosts, statRanks('defense', act1Defense)), minor('root-ward', 'Root Ward', 'Barrier Power', rootCosts, statRanks('barrierPowerPct', act1Damage)), minor('ancient-vitality', 'Ancient Vitality', 'Maximum Health', rootCosts, statRanks('maxHealth', act1Health)), minor('stonebound-endurance', 'Stonebound Endurance', 'Damage Reduction', rootCosts, statRanks('damageReductionPct', act1Reduction))], [['root-sigil', 'Root Sigil', 10, effect({ spellPower: 7.5, defense: 2 })], ['deepwood-seal', 'Deepwood Seal', 20, effect({ spellPower: 10, maxHealth: 18.75 })], ['ancient-core', 'Ancient Core', 30, effect({ spellPower: 13.75, barrierPowerPct: 0.03 })], ['hollow-guardian', 'Hollow Guardian', 40, effect({ spellPower: 17.5, defense: 3 }, [{ key: 'spell-damage-percent', value: 0.0375, originSourceKinds: ['spell'], damageTypes: [earth], sourceTags: ['direct'] }])], ['living-bastion', 'Living Bastion', 50, effect({ spellPower: 22.5, maxHealth: 31.25, damageReductionPct: 0.0125 }, [{ key: 'damage-taken-percent', value: -0.05, condition: { type: 'self-has-barrier' } }])], ['rootheart-colossus', 'Rootheart Colossus', 60, effect({ spellPower: 30, maxHealth: 50, barrierPowerPct: 0.0625, damageReductionPct: 0.02 }, undefined, [{ type: 'barrier-break', barrierMaxHealthPercent: 0.0375, cooldownMs: 12000 }])]])
const convergenceCosts = armorRanks(act1PrismaticCosts, four)
const convergence = prismatic('convergence-robe', 2, { maxHealth: 700, defense: 60, resistances: { fire: 0.05, water: 0.05, earth: 0.05, air: 0.05 } }, [minor('convergent-vitality', 'Convergent Vitality', 'Maximum Health', convergenceCosts, statRanks('maxHealth', act1Health)), minor('crossroad-weave', 'Crossroad Weave', 'Defense', convergenceCosts, statRanks('defense', act1Defense)), minor('meridian-barrier', 'Meridian Barrier', 'Barrier Power', convergenceCosts, statRanks('barrierPowerPct', act1Damage)), minor('convergence-reserve', 'Convergence Reserve', 'Maximum Mana', convergenceCosts, statRanks('maxMana', act1Mana)), minor('fourfold-ward', 'Fourfold Ward', 'All Element Resistance', convergenceCosts, allResistanceRanks(act1Resistance)), minor('perfect-weave', 'Perfect Weave', 'Damage Reduction', convergenceCosts, statRanks('damageReductionPct', act1Reduction))], majors([['first-convergence', 'First Convergence', 10, effect({ maxHealth: 25, defense: 2 })], ['crossroads-mantle', 'Crossroads Mantle', 20, effect({ maxHealth: 37.5, barrierPowerPct: 0.03 })], ['meridian-loom', 'Meridian Loom', 30, effect({ maxHealth: 50, maxMana: 10 })], ['fourfold-aegis', 'Fourfold Aegis', 40, effect({ maxHealth: 62.5, defense: 3.75, resistances: { fire: 0.0125, water: 0.0125, earth: 0.0125, air: 0.0125 } })], ['stable-convergence', 'Stable Convergence', 50, effect({ maxHealth: 87.5, barrierPowerPct: 0.05, damageReductionPct: 0.015 }, undefined, [{ type: 'barrier-gain-mana', maxHealthPercent: 0.0125, cooldownMs: 5000 }])], ['perfect-convergence', 'Perfect Convergence', 60, effect({ maxHealth: 125, defense: 6.25, damageReductionPct: 0.025, resistances: { fire: 0.02, water: 0.02, earth: 0.02, air: 0.02 } }, undefined, [{ type: 'hp-threshold-barrier-status-immunity', threshold: 0.3, barrierMaxHealthPercent: 0.0875, durationMs: 3000 }])]]))
const waystone = prismatic('waystone-circlet', 2, { spellPower: 240, maxMana: 120, critChance: 0.03 }, [minor('waystone-intellect', 'Waystone Intellect', 'Spell Power', convergenceCosts, statRanks('spellPower', act1Spell)), minor('meridian-reservoir', 'Meridian Reservoir', 'Maximum Mana', convergenceCosts, statRanks('maxMana', act1Mana)), minor('mana-anchor', 'Mana Anchor', 'Spell Mana Cost', convergenceCosts, statRanks('manaCostReductionPct', act1ManaEfficiency)), minor('waystep-tempo', 'Waystep Tempo', 'Spell Cooldown Time', convergenceCosts, statRanks('cooldownRecoveryPct', act1Cooldown)), minor('stabilized-incantation', 'Stabilized Incantation', 'Spell Status Duration', convergenceCosts, statRanks('statusDurationPct', act1Duration)), minor('waystone-precision', 'Waystone Precision', 'Spell Critical Chance', convergenceCosts, statRanks('critChance', act1Crit))], majors([['waymark', 'Waymark', 10, effect({ spellPower: 7.5, maxMana: 5 })], ['mana-seal', 'Mana Seal', 20, effect({ spellPower: 10, manaCostReductionPct: 0.0075 })], ['meridian-crown', 'Meridian Crown', 30, effect({ spellPower: 13.75, statusDurationPct: 0.025 })], ['stable-path', 'Stable Path', 40, effect({ spellPower: 17.5, cooldownRecoveryPct: 0.0125, maxMana: 7.5 })], ['convergent-sight', 'Convergent Sight', 50, effect({ spellPower: 22.5, critChance: 0.01, manaCostReductionPct: 0.01 }, undefined, [{ type: 'mana-band-shift', manaReduction: 0.0625, cooldownMs: 3000 }])], ['perfect-waystone', 'Perfect Waystone', 60, effect({ spellPower: 30, maxMana: 15, cooldownRecoveryPct: 0.01875, manaCostReductionPct: 0.015 }, undefined, [{ type: 'nth-spell-mana-refund', every: 10, manaPercent: 0.15 }])]]))

export const ACT1_ARTIFACT_IDS: readonly ArtifactId[] = ['galeshard-staff', 'reliquary-scepter', 'pyrebound-staff', 'rootheart-scepter', 'convergence-robe', 'waystone-circlet']
export const ARTIFACTS: Record<ArtifactId, ArtifactDefinition> = { 'ember-staff': act0Elemental('ember-staff', { spellPower: 15 }, 'fire-fragment', emberNodes, emberMajors), 'tideglass-wand': act0Elemental('tideglass-wand', { spellPower: 15, maxMana: 10 }, 'water-fragment', tideNodes, tideMajors), 'stoneheart-scepter': act0Elemental('stoneheart-scepter', { spellPower: 15, defense: 3 }, 'earth-fragment', stoneNodes, stoneMajors), 'windthread-wand': act0Elemental('windthread-wand', { spellPower: 15, critChance: 0.01 }, 'air-fragment', windNodes, windMajors), 'wispweave-robe': prismatic('wispweave-robe', 1, { maxHealth: 40, defense: 4 }, wispweaveNodes, wispweaveMajors), 'wispveil-hood': prismatic('wispveil-hood', 1, { spellPower: 15, maxMana: 10 }, wispveilNodes, wispveilMajors), 'galeshard-staff': galeshard, 'reliquary-scepter': reliquary, 'pyrebound-staff': pyrebound, 'rootheart-scepter': rootheart, 'convergence-robe': convergence, 'waystone-circlet': waystone }
export const isArtifactId = (itemId: ItemId): itemId is ArtifactId => Object.prototype.hasOwnProperty.call(ARTIFACTS, itemId)
export const getArtifactDefinition = (itemId: ItemId) => isArtifactId(itemId) ? ARTIFACTS[itemId] : undefined

export const validateArtifactDefinitions = (items: Record<string, ItemDefinition>) => {
  const errors: string[] = []; const context = createCombatValidationContext(STATUS_DEFINITIONS)
  Object.entries(ARTIFACTS).forEach(([key, definition]) => {
    if (key !== definition.id || definition.itemId !== definition.id) errors.push(`${key}: Artifact key/id mismatch`)
    const item = items[definition.itemId]
    if (!item) errors.push(`${definition.id}: Artifact item is missing`)
    else { if (item.kind !== 'equipment') errors.push(`${definition.id}: Artifact item must be Equipment`); if (item.source !== 'Artificing') errors.push(`${definition.id}: Artifact item source must be Artificing`); if (item.stats !== undefined) errors.push(`${definition.id}: Artifact item must not define static stats`); if (item.combat !== undefined) errors.push(`${definition.id}: Artifact item must not define static combat effects`); if (item.sellValue !== null) errors.push(`${definition.id}: Artifact item must not be sellable`); if (item.canDestroy) errors.push(`${definition.id}: Artifact item must not be destroyable`) }
    if (!definition.baseline) errors.push(`${definition.id}: missing Rank 0 baseline object`)
    const expectedCount = ACT1_ARTIFACT_IDS.includes(definition.id) ? 6 : 5; const expectedMax = expectedCount * 10
    if (definition.minorNodes.length !== expectedCount) errors.push(`${definition.id}: wrong Minor count`)
    if (definition.majorMilestones.length !== expectedCount || definition.majorMilestones[definition.majorMilestones.length - 1]?.unlockAtTotalRanks !== expectedMax) errors.push(`${definition.id}: wrong Major thresholds`)
    const nodeIds = new Set<string>(); definition.minorNodes.forEach((node) => { if (nodeIds.has(node.id)) errors.push(`${definition.id}: duplicate node id ${node.id}`); nodeIds.add(node.id); if (node.maxRank !== 10) errors.push(`${definition.id}/${node.id}: maxRank must be 10`); if (node.rankCosts.length !== 10) errors.push(`${definition.id}/${node.id}: rankCosts must contain 10 entries`); if (node.rankEffects.length !== 10) errors.push(`${definition.id}/${node.id}: rankEffects must contain 10 entries`); node.rankCosts.forEach((cost) => { if (cost.artifactEssence < 0 || cost.prismaticFragment !== undefined && cost.prismaticFragment < 0 || cost.fragment?.quantity !== undefined && cost.fragment.quantity < 0 || Object.values(cost.resonance).some((value) => (value ?? 0) < 0)) errors.push(`${definition.id}/${node.id}: negative rank cost`) }); node.rankEffects.forEach((resolved) => { errors.push(...validateCombatProvider(resolved.combat, `${definition.id}.${node.id}.combat`, context)) }) })
    const majorIds = new Set<string>(); let previous = 0; definition.majorMilestones.forEach((major) => { if (majorIds.has(major.id)) errors.push(`${definition.id}: duplicate Major ID ${major.id}`); majorIds.add(major.id); if (major.unlockAtTotalRanks <= previous || major.unlockAtTotalRanks > expectedMax) errors.push(`${definition.id}: unordered Major thresholds`); previous = major.unlockAtTotalRanks })
  }); return errors
}
