import type { MonsterId } from '../../../../types'
import { makeCombatMonster, type CombatMonsterSpec } from '../../combatMonsterAuthoring'
import type { MonsterDefinition } from '../../monsterTypes'

const specs: CombatMonsterSpec[] = [
  { locationId: 'rootscar-hollow', id: 'thorn-maw', combatV2: true, primaryAffinity: 'earth', basicAttackElement: 'earth', targetPower: 3100, name: 'Thorn Maw', subtitle: 'A carnivorous bloom grown around a poisoned root', hp: 1875, damage: 78, defense: 42, resonanceYield: { earth: 24 }, icon: { portraitIcon: 'plant' }, specials: [{ id: 'venomous-bite', name: 'Venomous Bite', damage: [{ type: 'earth', coefficient: 1.25 }], dot: { statusId: 'root-rot', damageType: 'earth', coefficient: 1, durationMs: 8000 } }, { id: 'thorn-bloom', name: 'Thorn Bloom', status: { id: 'fortified', target: 'self' } }] },
  { locationId: 'rootscar-hollow', id: 'rootbound-stalker', combatV2: true, primaryAffinity: 'earth', basicAttackElement: 'earth', targetPower: 3300, name: 'Rootbound Stalker', subtitle: 'A patient hunter hiding beneath the scarred soil', hp: 1250, damage: 82, defense: 32, resonanceYield: { earth: 28 }, icon: { portraitIcon: 'plant' }, specials: [{ id: 'root-ambush', name: 'Root Ambush', damage: [{ type: 'earth', coefficient: 1.35 }], status: { id: 'entangled' } }, { id: 'burrow', name: 'Burrow', status: { id: 'spectral-fade', target: 'self' } }] },
  { locationId: 'rootscar-hollow', id: 'briar-sprite', combatV2: true, primaryAffinity: 'earth', basicAttackElement: 'earth', targetPower: 3500, name: 'Briar Sprite', subtitle: 'A small spirit with a spiteful garden to tend', hp: 1375, damage: 74, defense: 24, resistances: { earth: .15, fire: -.15 }, resonanceYield: { earth: 26 }, icon: { portraitIcon: 'wisp' }, specials: [{ id: 'briar-hex', name: 'Briar Hex', damage: [{ type: 'earth', coefficient: 1.15 }], dot: { statusId: 'root-rot', damageType: 'earth', coefficient: 0.45, durationMs: 8000 } }, { id: 'bloom', name: 'Bloom', heal: .06 }] },
  { locationId: 'rootscar-hollow', id: 'moss-carapace', combatV2: true, primaryAffinity: 'earth', basicAttackElement: 'earth', targetPower: 3700, name: 'Moss Carapace', subtitle: 'A slow shell carrying a whole forest on its back', hp: 2063, damage: 72, defense: 52, resonanceYield: { earth: 30 }, specials: [{ id: 'shell-up', name: 'Shell Up', status: { id: 'fortified', target: 'self' } }, { id: 'moss-regrowth', name: 'Moss Regrowth', heal: .06 }] },
  { locationId: 'rootscar-hollow', id: 'rootscar-ancient', combatV2: true, primaryAffinity: 'earth', basicAttackElement: 'earth', targetPower: 5200, name: 'Rootscar Ancient', subtitle: 'The oldest root beneath the frontier, awake and starving', hp: 15500, damage: 92, defense: 68, resistances: { earth: .25, fire: -.1 }, resonanceYield: { earth: 100 }, combatV2Traits: ['rootscar-ancient-regrowth'], boss: true, specials: [{ id: 'entangling-roots', name: 'Entangling Roots', damage: [{ type: 'earth', coefficient: 1.1 }], status: { id: 'entangled' } }, { id: 'toxic-sap', name: 'Toxic Sap', dot: { statusId: 'root-rot', damageType: 'earth', coefficient: 0.7, durationMs: 8000 } }, { id: 'barkwall', name: 'Barkwall', barrier: .1 }, { id: 'earthsplit', name: 'Earthsplit', damage: [{ type: 'earth', coefficient: 2 }] }] }
,  { locationId: 'rootscar-hollow', id: 'sporeback-brute', combatV2: true, primaryAffinity: 'earth', basicAttackElement: 'earth', targetPower: 3950, name: 'Sporeback Brute', subtitle: 'A hulking carrier of spores that root into every wound', hp: 1900, damage: 86, defense: 46, time: 2600, resonanceYield: { earth: 34 }, icon: { portraitIcon: 'plant' }, specials: [{ id: 'sporeback-slam', name: 'Sporeback Slam', damage: [{ type: 'earth', coefficient: 1.35 }], dot: { statusId: 'root-rot', damageType: 'earth', coefficient: 0.6, durationMs: 8000 } }, { id: 'spore-cloud', name: 'Spore Cloud', status: { id: 'entangled' } }] },
  { locationId: 'rootscar-hollow', id: 'vinebound-reaver', combatV2: true, primaryAffinity: 'earth', basicAttackElement: 'earth', targetPower: 4200, name: 'Vinebound Reaver', subtitle: 'A bladed creeper that pulls prey into the green dark', hp: 2200, damage: 90, defense: 38, time: 2450, resonanceYield: { earth: 38 }, icon: { portraitIcon: 'plant' }, specials: [{ id: 'vinebound-lash', name: 'Vinebound Lash', damage: [{ type: 'earth', coefficient: 1.4 }], status: { id: 'entangled' } }, { id: 'reaver-burrow', name: 'Reaver Burrow', status: { id: 'spectral-fade', target: 'self' } }] },
  { locationId: 'rootscar-hollow', id: 'scarwood-behemoth', combatV2: true, primaryAffinity: 'earth', basicAttackElement: 'earth', targetPower: 4450, name: 'Scarwood Behemoth', subtitle: "A walking trunk grown around the Elemental Scar's oldest wound", hp: 2850, damage: 102, defense: 64, time: 2900, resonanceYield: { earth: 44 }, icon: { portraitIcon: 'guardian' }, specials: [{ id: 'scarwood-crush', name: 'Scarwood Crush', damage: [{ type: 'earth', coefficient: 1.55 }] }, { id: 'rooted-regrowth', name: 'Rooted Regrowth', heal: .06 }] },
]

export const ROOTSCAR_HOLLOW_MONSTERS = Object.fromEntries(specs.map((spec) => [spec.id, makeCombatMonster(spec)])) as Record<MonsterId, MonsterDefinition>
