import { useEffect, type ReactNode } from 'react'
import { Check, PackageOpen, X } from 'lucide-react'
import { ItemIcon, ItemTooltip } from '../../components/ui/item'
import { Button } from '../../components/ui'
import { CHANNELING_DISCOVERIES } from '../../game/content/channeling/channelingDiscoveries'
import { ITEMS } from '../../game/content/items/items'
import { MONSTERS } from '../../game/content/monsters'
import { SCHOOLS } from '../../game/content/schools/schools'
import { SPELLS } from '../../game/content/spells/spells'
import type { ItemId, MonsterId, SchoolId } from '../../game/types'
import type { OfflineBankReport } from '../../game/systems/offline-bank/offlineBankReport'
import { formatOfflineBank, formatNumber } from '../../game/utils'

export function OfflineBankResultsDialog({ report, open, onClose, onOpenInventory }: { report: OfflineBankReport | null; open: boolean; onClose: () => void; onOpenInventory: () => void }) {
  useEffect(() => {
    if (!open) return
    const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') { event.preventDefault(); onClose() } }
    window.addEventListener('keydown', onKeyDown)
    return () => window.removeEventListener('keydown', onKeyDown)
  }, [open, onClose])
  if (!open || !report) return null
  const produced = report.production.transmutation
  const hasItemGains = Object.entries(report.netInventory).some(([, amount]) => amount > 0)
  const summary = [{ value: report.combat.killsTotal, label: 'ENEMIES', show: report.combat.killsTotal > 0 }, { value: sumValues(produced), label: 'PRODUCED', show: sumValues(produced) > 0 }, { value: sumValues(report.research.xpBySchool), label: 'RESEARCH XP', show: sumValues(report.research.xpBySchool) > 0 }, { value: sumValues(report.production.craftsByRecipe), label: 'CRAFTS', show: sumValues(report.production.craftsByRecipe) > 0 }].filter((tile) => tile.show)
  return <div className="offline-results-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose() }}><section className="offline-results-dialog" role="dialog" aria-modal="true" aria-label="Offline Bank Results"><header className="offline-results-header"><div><span className="offline-bank-eyebrow"><Check size={14} /> OFFLINE BANK RESULTS</span><h2>{formatOfflineBank(report.durationMs)} advanced</h2><p>Bank Remaining: {formatOfflineBank(report.bankAfterMs)}</p></div><button type="button" className="icon-button" onClick={onClose} aria-label="Close Offline Bank Results"><X size={16} /></button></header>{summary.length > 0 && <div className="offline-results-summary">{summary.map((tile) => <div key={tile.label}><strong>{formatNumber(tile.value)}</strong><span>{tile.label}</span></div>)}</div>}<div className="offline-results-scroll">
    {hasProgression(report) && <ResultSection title="PROGRESSION / UNLOCKS"><div className="offline-result-events">{report.progression.spellsUnlocked.map((id) => <span key={id}><strong>Spell Unlocked</strong>{SPELLS[id]?.name ?? id}</span>)}{report.progression.discoveriesUnlocked.map((id) => <span key={id}><strong>Arcane Discovery</strong>{CHANNELING_DISCOVERIES.find((entry) => entry.id === id)?.name ?? id}</span>)}{report.progression.guildUnlocked && <span><strong>Guild</strong>Guild unlocked</span>}{report.progression.levelCapAfter && <span><strong>Magic School Cap</strong>{report.progression.levelCapBefore} → {report.progression.levelCapAfter}</span>}{report.progression.guildRankAfter && <span><strong>Guild Rank</strong>{report.progression.guildRankBefore} → {report.progression.guildRankAfter}</span>}{report.progression.notableEvents.map((event) => <span key={event}><strong>Notable Event</strong>{event}</span>)}</div></ResultSection>}
    {(report.combat.killsTotal > 0 || report.combat.playerDeaths > 0 || Object.keys(report.combat.loot).length > 0) && <ResultSection title="COMBAT"><div className="offline-result-metrics"><span>Enemies Defeated<strong>{report.combat.killsTotal}</strong></span><span>Player Deaths<strong>{report.combat.playerDeaths}</strong></span></div><div className="offline-result-list">{Object.entries(report.combat.killsByMonster).map(([id, quantity]) => <span key={id}><span>{MONSTERS[id as MonsterId]?.name ?? id}</span><strong>{quantity}</strong></span>)}</div>{Object.keys(report.combat.loot).length > 0 && <div className="offline-result-subsection"><span className="offline-result-label">LOOT</span>{Object.entries(report.combat.loot).map(([id, quantity]) => <ReportItemRow key={id} itemId={id as ItemId} amount={quantity ?? 0} />)}</div>}</ResultSection>}
    {(Object.keys(report.research.researchedItems).length > 0 || sumValues(report.research.xpBySchool) > 0) && <ResultSection title="RESEARCH"><div className="offline-result-list">{Object.entries(report.research.xpBySchool).map(([id, xp]) => <span key={id}><span>{SCHOOLS[id as SchoolId]?.name ?? id} School XP</span><strong>+{formatNumber(xp ?? 0)}</strong></span>)}</div>{Object.entries(report.research.researchedItems).map(([id, quantity]) => <ReportItemRow key={id} itemId={id as ItemId} amount={quantity ?? 0} label="Researched" />)}{report.research.stoppedAtCap && <div className="offline-result-note">Research stopped at the current level cap.</div>}{Object.entries(report.research.levelAfter).filter(([id, level]) => level !== report.research.levelBefore[id as SchoolId]).map(([id, level]) => <div className="offline-result-level" key={id}>{SCHOOLS[id as SchoolId]?.name ?? id} Level <strong>{report.research.levelBefore[id as SchoolId]} → {level}</strong></div>)}</ResultSection>}
    {(Object.keys(report.production.craftsByRecipe).length > 0 || Object.keys(report.production.transmutation).length > 0) && <ResultSection title="TRANSMUTATION"><div className="offline-result-list">{Object.entries(report.production.transmutation).map(([id, quantity]) => <ReportItemRow key={id} itemId={id as ItemId} amount={quantity ?? 0} />)}</div>{Object.entries(report.consumption.transmutation).map(([id, quantity]) => <ReportItemRow key={id} itemId={id as ItemId} amount={-(quantity ?? 0)} label="Materials Used" />)}</ResultSection>}
    {Object.keys(report.netInventory).length > 0 && <ResultSection title="NET INVENTORY"><div className="offline-result-list">{Object.entries(report.netInventory).map(([id, amount]) => <ReportItemRow key={id} itemId={id as ItemId} amount={amount ?? 0} />)}</div></ResultSection>}
    <ResultSection title="ENDING STATE"><div className="offline-result-metrics"><span>Health<strong>{formatNumber(report.endingState.health)} / {formatNumber(report.endingState.maxHealth)}</strong></span><span>Mana<strong>{formatNumber(report.endingState.mana)} / {formatNumber(report.endingState.maxMana)}</strong></span></div></ResultSection>
  </div><footer className="offline-results-footer"><Button variant="ghost" onClick={onClose}>Done</Button>{hasItemGains && <Button variant="secondary" onClick={onOpenInventory}><PackageOpen size={14} /> Open Inventory</Button>}</footer></section></div>
}

function ResultSection({ title, children }: { title: string; children: ReactNode }) { return <section className="offline-result-section"><h3>{title}</h3>{children}</section> }
function ReportItemRow({ itemId, amount, label }: { itemId: ItemId; amount: number; label?: string }) { const item = ITEMS[itemId]; return <ItemTooltip itemId={itemId} owned={Math.max(0, amount)}><span className="offline-result-item-row"><ItemIcon itemId={itemId} size="tiny" /><span>{label ?? item.name}</span><strong className={amount >= 0 ? 'positive' : 'negative'}>{amount >= 0 ? '+' : ''}{amount}</strong></span></ItemTooltip> }
function hasProgression(report: OfflineBankReport) { return report.progression.spellsUnlocked.length > 0 || report.progression.discoveriesUnlocked.length > 0 || report.progression.guildUnlocked || Boolean(report.progression.levelCapAfter) || Boolean(report.progression.guildRankAfter) || report.progression.notableEvents.length > 0 }
function sumValues(record: Partial<Record<string, number>> | Record<string, number>): number { return Object.values(record).reduce<number>((sum, value) => sum + (value ?? 0), 0) }
