import type { MonsterId } from '../../../types'
import { authorExpansionNormalAt, hit, normalAction, status } from '../expansion/authoring'

const zone = 'brineveil-marsh'
export const BRINEVEIL_MARSH_NORMALS = [
  authorExpansionNormalAt(zone, 0, 0, { id: 'mirefin-lurker', name: 'Mirefin Lurker', subtitle: 'A reed-stalking predator that vanishes beneath the black water.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Bog Lunge', { damage: [hit('water', 1.4)] }), normalAction('second-special', 'Submerge', { barrier: .08 })], pattern: ['basic', 'first', 'basic', 'second'] }),
  authorExpansionNormalAt(zone, 0, 1, { id: 'brinefang-eel', name: 'Brinefang Eel', subtitle: 'A salt-scaled ambusher crackling through flooded reeds.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Shock Current', { damage: [hit('water', .9), hit('air', .5)] }), normalAction('second-special', 'Coil Snap', { damage: [hit('water', 1.6)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 0, 2, { id: 'tidebloom-warden', name: 'Tidebloom Warden', subtitle: 'A rooted marsh guardian crowned with pale water flowers.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Reed Lash', { damage: [hit('water', 1.2)], status: status('entangled') }), normalAction('second-special', 'Blooming Tide', { heal: .06 })], pattern: ['basic', 'first', 'basic', 'second'] }),
  authorExpansionNormalAt(zone, 0, 3, { id: 'fenwater-hexer', name: 'Fenwater Hexer', subtitle: 'A marsh witch whose curses ripple across the flooded ground.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Bog Hex', { damage: [hit('water', .85)], status: status('cursed') }), normalAction('second-special', 'Flood Pulse', { damage: [hit('water', 1.5)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 0, 4, { id: 'saltglass-crab', name: 'Saltglass Crab', subtitle: 'A heavy clawed sentinel armored in translucent salt crystal.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Glassclaw', { damage: [hit('water', 1.35)] }), normalAction('second-special', 'Carapace Lock', { status: status('fortified', 'self') })], pattern: ['basic', 'second', 'first', 'basic'] }),
  authorExpansionNormalAt(zone, 0, 5, { id: 'runesunk-oracle', name: 'Runesunk Oracle', subtitle: 'A drowned seer reading unstable glyphs beneath the tide.', affinity: 'arcane', resonance: 8, specials: [normalAction('first-special', 'Sunken Rune', { damage: [hit('arcane', 1.15)], status: status('arcane-disruption') }), normalAction('second-special', 'Tidal Reading', { damage: [hit('water', .7), hit('arcane', .7)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 0, 6, { id: 'mistwing-skimmer', name: 'Mistwing Skimmer', subtitle: 'A swift marsh bird that cuts through fog and crosswinds.', affinity: 'air', resonance: 8, specials: [normalAction('first-special', 'Mist Dive', { damage: [hit('air', 1.5)] }), normalAction('second-special', 'Crosswind', { damage: [hit('air', .9)], delayOpponentMs: 400 })], pattern: ['basic', 'first', 'second', 'basic'] }),
] satisfies readonly ReturnType<typeof authorExpansionNormalAt>[]
export const BRINEVEIL_MARSH_ROSTER = BRINEVEIL_MARSH_NORMALS.map(({ id }) => id as MonsterId)
