import type { MonsterId } from '../../../types'
import { authorExpansionNormalAt, hit, normalAction, status } from '../expansion/authoring'

const zone = 'cinderwild-expanse'
export const CINDERWILD_EXPANSE_NORMALS = [
  authorExpansionNormalAt(zone, 1, 0, { id: 'ashclaw-jackal', name: 'Ashclaw Jackal', subtitle: 'A lean pack hunter with ember-lit teeth and paws.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Searing Bite', { damage: [hit('fire', 1.2)], status: status('burning') }), normalAction('second-special', 'Pack Rush', { damage: [hit('fire', 1.5)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 1, 1, { id: 'emberhide-ram', name: 'Emberhide Ram', subtitle: 'A broad-shouldered grazer whose hide glows through cracked ash.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Cinder Charge', { damage: [hit('fire', 1.65)] }), normalAction('second-special', 'Ember Hide', { status: status('fortified', 'self') })], pattern: ['basic', 'second', 'first', 'basic'] }),
  authorExpansionNormalAt(zone, 1, 2, { id: 'cinderwing-hawk', name: 'Cinderwing Hawk', subtitle: 'A volcanic raptor diving from smoke-darkened skies.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Flare Dive', { damage: [hit('fire', 1.45)] }), normalAction('second-special', 'Ash Veil', { status: status('spectral-fade', 'self') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 1, 3, { id: 'magma-tick', name: 'Magma Tick', subtitle: 'A heat-swollen parasite clinging to the edges of lava vents.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Magma Bite', { damage: [hit('fire', .95)], status: status('burning') }), normalAction('second-special', 'Heat Swell', { status: status('haste', 'self') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 1, 4, { id: 'pyrebark-treant', name: 'Pyrebark Treant', subtitle: 'A charred woodland giant sheltering a heart of living embers.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Cinder Branch', { damage: [hit('fire', 1.35)] }), normalAction('second-special', 'Smoldering Bark', { barrier: .08 })], pattern: ['basic', 'second', 'first', 'basic'] }),
  authorExpansionNormalAt(zone, 1, 5, { id: 'stormsmoke-imp', name: 'Stormsmoke Imp', subtitle: 'A soot-winged trickster trailing sparks through the ash clouds.', affinity: 'air', resonance: 8, specials: [normalAction('first-special', 'Smoke Gust', { damage: [hit('air', 1.2)], status: status('vulnerable') }), normalAction('second-special', 'Static Cinder', { damage: [hit('air', .8), hit('fire', .55)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 1, 6, { id: 'sootbound-augur', name: 'Sootbound Augur', subtitle: 'A wandering oracle carrying a furnace-lit rune tablet.', affinity: 'arcane', resonance: 8, specials: [normalAction('first-special', 'Ash Rune', { damage: [hit('arcane', 1.1)], status: status('cursed') }), normalAction('second-special', 'Furnace Omen', { damage: [hit('fire', .75), hit('arcane', .75)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
] satisfies readonly ReturnType<typeof authorExpansionNormalAt>[]
export const CINDERWILD_EXPANSE_ROSTER = CINDERWILD_EXPANSE_NORMALS.map(({ id }) => id as MonsterId)
