import type { MonsterId } from '../../../types'
import { authorExpansionNormalAt, hit, normalAction, status } from '../expansion/authoring'

const zone = 'runeblight-expanse'
export const RUNEBLIGHT_EXPANSE_NORMALS = [
  authorExpansionNormalAt(zone, 3, 0, { id: 'leybound-husk', name: 'Leybound Husk', subtitle: 'An empty shell animated by a fractured line of Arcane force.', affinity: 'arcane', resonance: 8, specials: [normalAction('first-special', 'Ley Strike', { damage: [hit('arcane', 1.3)] }), normalAction('second-special', 'Overload Shell', { barrier: .07 })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 3, 1, { id: 'prism-stalker', name: 'Prism Stalker', subtitle: 'A refracting predator whose body splits into shifting colors.', affinity: 'arcane', resonance: 8, specials: [normalAction('first-special', 'Prism Fang', { damage: [hit('arcane', .6), hit('fire', .4), hit('water', .4)] }), normalAction('second-special', 'Refraction', { status: status('spectral-fade', 'self') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 3, 2, { id: 'runic-parasite', name: 'Runic Parasite', subtitle: 'A glyph-eating leech that feeds on the magic in its prey.', affinity: 'arcane', resonance: 8, specials: [normalAction('first-special', 'Mana Gnaw', { damage: [hit('arcane', .9)], manaDrain: 6 }), normalAction('second-special', 'Glyph Leech', { damage: [hit('arcane', 1.1)], heal: .04 })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 3, 3, { id: 'echo-knight', name: 'Echo Knight', subtitle: 'A rune-plated sentinel repeating motions from a broken spell.', affinity: 'arcane', resonance: 8, specials: [normalAction('first-special', 'Echo Slash', { damage: [hit('arcane', 1.45)] }), normalAction('second-special', 'Repeated Form', { status: status('haste', 'self') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 3, 4, { id: 'aether-maw', name: 'Aether Maw', subtitle: 'A void-fed beast that distorts the air around its open jaws.', affinity: 'arcane', resonance: 8, specials: [normalAction('first-special', 'Void Bite', { damage: [hit('arcane', 1.5)] }), normalAction('second-special', 'Aether Collapse', { damage: [hit('arcane', 1.1)], status: status('vulnerable') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 3, 5, { id: 'frostscript-adept', name: 'Frostscript Adept', subtitle: 'A spellcaster inscribing cold runes into the torn ley field.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Frostscript Bolt', { damage: [hit('water', 1.25)], status: status('chilled') }), normalAction('second-special', 'Null Script', { damage: [hit('arcane', .8), hit('water', .6)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 3, 6, { id: 'emberglyph-adept', name: 'Emberglyph Adept', subtitle: 'A scorched scholar channeling fire through unstable runes.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Glyph Flame', { damage: [hit('fire', 1.2)], status: status('burning') }), normalAction('second-special', 'Rune Burst', { damage: [hit('arcane', .8), hit('fire', .65)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
] satisfies readonly ReturnType<typeof authorExpansionNormalAt>[]
export const RUNEBLIGHT_EXPANSE_ROSTER = RUNEBLIGHT_EXPANSE_NORMALS.map(({ id }) => id as MonsterId)
