import type { MonsterId } from '../../../types'
import { authorExpansionNormalAt, hit, normalAction, status } from '../expansion/authoring'

const zone = 'skybreak-cliffs'
export const SKYBREAK_CLIFFS_NORMALS = [
  authorExpansionNormalAt(zone, 2, 0, { id: 'razorwind-raptor', name: 'Razorwind Raptor', subtitle: 'An aerial hunter slicing across the cliff-face thermals.', affinity: 'air', resonance: 8, specials: [normalAction('first-special', 'Razor Dive', { damage: [hit('air', 1.5)] }), normalAction('second-special', 'Wing Shear', { damage: [hit('air', 1)], status: status('bleeding') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 2, 1, { id: 'galehorn-ibex', name: 'Galehorn Ibex', subtitle: 'A sure-footed ram braced against the relentless mountain winds.', affinity: 'air', resonance: 8, specials: [normalAction('first-special', 'Wind Charge', { damage: [hit('air', 1.6)] }), normalAction('second-special', 'Horn Brace', { status: status('fortified', 'self') })], pattern: ['second', 'basic', 'first', 'basic'] }),
  authorExpansionNormalAt(zone, 2, 2, { id: 'cloudmaw-drake', name: 'Cloudmaw Drake', subtitle: 'A storm-breathing drake circling above the broken ledges.', affinity: 'air', resonance: 8, specials: [normalAction('first-special', 'Gale Breath', { damage: [hit('air', 1.4)] }), normalAction('second-special', 'Stormbite', { damage: [hit('air', 1), hit('water', .45)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 2, 3, { id: 'stormfeather-harrier', name: 'Stormfeather Harrier', subtitle: 'A hunting bird that rides its own spiraling storm.', affinity: 'air', resonance: 8, specials: [normalAction('first-special', 'Featherstorm', { damage: [hit('air', .55)], hitCount: 3 }), normalAction('second-special', 'Slipstream', { status: status('haste', 'self') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 2, 4, { id: 'whistling-wraith', name: 'Whistling Wraith', subtitle: 'A pale cliff spirit whose cry carries through the stone arches.', affinity: 'air', resonance: 8, specials: [normalAction('first-special', 'Sonic Lash', { damage: [hit('air', 1.2)], status: status('staggered') }), normalAction('second-special', 'Dissipate', { status: status('spectral-fade', 'self') })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 2, 5, { id: 'raincoil-serpent', name: 'Raincoil Serpent', subtitle: 'A cloud-fed serpent coiling through the rain-cut ravines.', affinity: 'water', resonance: 8, specials: [normalAction('first-special', 'Raincoil Bite', { damage: [hit('water', 1.2)], status: status('chilled') }), normalAction('second-special', 'Stormcoil', { damage: [hit('water', .8), hit('air', .5)] })], pattern: ['first', 'basic', 'second', 'basic'] }),
  authorExpansionNormalAt(zone, 2, 6, { id: 'cindercrest-roc', name: 'Cindercrest Roc', subtitle: 'A fire-feathered giant nesting among the highest spires.', affinity: 'fire', resonance: 8, specials: [normalAction('first-special', 'Cinder Dive', { damage: [hit('fire', 1.4)] }), normalAction('second-special', 'Burning Updraft', { damage: [hit('air', .9)], status: status('haste', 'self') })], pattern: ['first', 'basic', 'second', 'basic'] }),
] satisfies readonly ReturnType<typeof authorExpansionNormalAt>[]
export const SKYBREAK_CLIFFS_ROSTER = SKYBREAK_CLIFFS_NORMALS.map(({ id }) => id as MonsterId)
